const fs = require('fs');
const path = 'C:/Users/shawn/Downloads/Green Bay Explorer.html';
let html = fs.readFileSync(path, 'utf8');

const entries = [
// === MORE FOOD TRUCKS ===
{id:4500,name:"Kickin Ash BBQ (Food Truck!)",cat:"Restaurant",sub:"Food Truck",date:"",dateLabel:"Events & rallies (see social media)",venue:"Kickin Ash BBQ",loc:"Green Bay area (mobile)",addr:"Green Bay area (mobile)",desc:"Smoked BBQ from a food truck! Find at Pamperin Park Monday nights, brewery events, and summer rallies across Green Bay.",url:"",setting:"outdoor",walking:"lowWalking",goodFor:["seniors","family"],highlight:false,free:false,recurring:true,cuisine:"BBQ"},
{id:4501,name:"Mai's Eggrolls (Hmong-Style Food Truck!)",cat:"Restaurant",sub:"Food Truck",date:"",dateLabel:"Events statewide (see Facebook)",venue:"Mai's Eggrolls",loc:"Green Bay area (mobile)",addr:"Green Bay area (mobile)",desc:"Hmong-style egg rolls, wings, noodles, rice! A local favorite at food truck rallies and events. Check Facebook for schedule.",url:"",setting:"outdoor",walking:"lowWalking",goodFor:["seniors","family"],highlight:false,free:false,recurring:true,cuisine:"Asian"},
{id:4502,name:"Dough Shoppe (Cookie Dough Food Truck!)",cat:"Restaurant",sub:"Food Truck",date:"",dateLabel:"Events & bookings (3 mobile units!)",venue:"Dough Shoppe",loc:"Green Bay area (mobile)",addr:"Green Bay area (mobile)",desc:"Edible cookie dough dessert truck with 3 mobile units! Sweet treat at food truck rallies, farmers markets, and events.",url:"https://www.thedoughshoppe.com/",setting:"outdoor",walking:"lowWalking",goodFor:["seniors","family"],highlight:false,free:false,recurring:true,cuisine:"Dessert"},
{id:4503,name:"Caribbean Cruiser (Island Food Truck!)",cat:"Restaurant",sub:"Food Truck",date:"",dateLabel:"Events & rallies",venue:"Caribbean Cruiser",loc:"Green Bay area (mobile)",addr:"Green Bay area (mobile)",desc:"Caribbean island flavors from a food truck! Jerk chicken, plantains, island rice. Find at Green Bay food truck events and rallies.",url:"https://caribbeancruiser.net/",setting:"outdoor",walking:"lowWalking",goodFor:["seniors","family"],highlight:false,free:false,recurring:true,cuisine:"Caribbean"},
{id:4504,name:"Philly's & York (Cheesesteaks Food Truck!)",cat:"Restaurant",sub:"Food Truck",date:"",dateLabel:"Events & rallies",venue:"Philly's & York",loc:"Green Bay area (mobile)",addr:"Green Bay area (mobile)",desc:"Philly cheesesteaks on fresh-baked bread from a food truck! Find at rallies, breweries, and events across NE Wisconsin.",url:"https://phillysandyork.com/",setting:"outdoor",walking:"lowWalking",goodFor:["seniors","family"],highlight:false,free:false,recurring:true,cuisine:"American"},
// === MORE MEXICAN ===
{id:4506,name:"Las Brisas (University Ave Mexican!)",cat:"Restaurant",sub:"Mexican",date:"",dateLabel:"Daily 10am-9pm",venue:"Las Brisas",loc:"Green Bay",addr:"1906 University Ave, Green Bay, WI",desc:"University Ave Mexican staple! Classic plates plus seafood options. Long-running family restaurant. Daily 10-9.",url:"https://www.lasbrisaswi.com/",setting:"indoor",walking:"lowWalking",goodFor:["seniors","family"],highlight:false,free:false,recurring:true,cuisine:"Mexican"},
{id:4507,name:"La Chata (Buffet + Tortas Ahogadas!)",cat:"Restaurant",sub:"Mexican",date:"",dateLabel:"Mon-Sat 7am-9pm, Sun 7am-6pm",venue:"La Chata Restaurant",loc:"Green Bay",addr:"800 Cedar St, Green Bay, WI",desc:"Mexican buffet + menu! Tortas ahogadas, amazing breakfast spread. In the beautifully converted old Greyhound bus station. Opens at 7am for Mexican breakfast.",url:"",setting:"indoor",walking:"lowWalking",goodFor:["seniors","family"],highlight:true,free:false,recurring:true,cuisine:"Mexican"},
{id:4508,name:"El Tapatio (Authentic, Cash-Only!)",cat:"Restaurant",sub:"Mexican",date:"",dateLabel:"Daily ~8am-9pm",venue:"El Tapatio Restaurant",loc:"Green Bay",addr:"1638 University Ave, Green Bay, WI",desc:"Authentic Mexican on University Ave! Tacos, carne asada, great margaritas. Many locals call it their favorite. CASH ONLY — plan ahead!",url:"",setting:"indoor",walking:"lowWalking",goodFor:["seniors","family"],highlight:true,free:false,recurring:true,cuisine:"Mexican"},
{id:4509,name:"El Nuevo 7 Mares (Mexican Seafood!)",cat:"Restaurant",sub:"Mexican",date:"",dateLabel:"Sun/Fri 10am-midnight, Mon-Thu 10-10, Sat 10-9",venue:"El Nuevo 7 Mares",loc:"East Green Bay",addr:"Green Bay, WI 54302",desc:"Mexican seafood restaurant (marisqueria)! Ceviche, seafood cocktails, caldos, fish tacos. Authentic niche — if you love Mexican-style seafood, this is the spot.",url:"http://www.el7mares.com/",setting:"indoor",walking:"lowWalking",goodFor:["seniors","couples"],highlight:true,free:false,recurring:true,cuisine:"Mexican Seafood"},
{id:4510,name:"Panaderia La Rosa (Mexican Bakery!)",cat:"Restaurant",sub:"Bakery",date:"",dateLabel:"Daily ~8:30am-8pm",venue:"Panaderia La Rosa",loc:"Green Bay",addr:"1742 University Ave, Green Bay, WI",desc:"Authentic Mexican bakery! Conchas, pan dulce, pastries. Fresh-baked daily. Affordable prices. A sweet taste of Mexico on University Ave.",url:"",setting:"indoor",walking:"lowWalking",goodFor:["seniors","family"],highlight:false,free:false,recurring:true,cuisine:"Mexican Bakery"},
// === MORE BREAKFAST ===
{id:4512,name:"Cafe Con Crema (Mexican-American Brunch!)",cat:"Restaurant",sub:"Breakfast",date:"",dateLabel:"Daily 7am-3pm",venue:"Cafe Con Crema",loc:"West Green Bay",addr:"2581 Packerland Dr, Green Bay, WI 54313",desc:"Modern Mexican-American breakfast/brunch! Chilaquiles, skillets, La Crema omelet. A trendy brunch spot with great coffee.",url:"",setting:"indoor",walking:"lowWalking",goodFor:["seniors","couples"],highlight:false,free:false,recurring:true,cuisine:"Mexican Breakfast"},
{id:4513,name:"Graystone Ale House (Sunday Breakfast!)",cat:"Restaurant",sub:"Breakfast",date:"",dateLabel:"Sunday opens 9am (weekdays from 11am)",venue:"Graystone Ale House",loc:"De Pere",addr:"3711 Monroe Rd, De Pere, WI 54115",desc:"Sunday breakfast from 9am! Downloadable breakfast menu, full bar with Bloody Marys. Great beer selection and atmosphere. Weekdays open at 11am for lunch/dinner.",url:"https://www.graystonealehouse.com/",setting:"indoor",walking:"lowWalking",goodFor:["seniors","couples"],highlight:false,free:false,recurring:true,cuisine:"Breakfast"},
{id:4514,name:"Bay Motel & Family Restaurant (Since 1958!)",cat:"Restaurant",sub:"Breakfast",date:"",dateLabel:"Mon-Sat 6am-8pm, Sun 6am-2pm",venue:"Bay Motel & Family Restaurant",loc:"Green Bay",addr:"1301 S Military Ave, Green Bay, WI 54303",desc:"Homestyle breakfast since 1958! Family-owned diner that's been serving Green Bay for decades. Opens at 6am. Good old-fashioned comfort food.",url:"",setting:"indoor",walking:"lowWalking",goodFor:["seniors","family"],highlight:false,free:false,recurring:true,cuisine:"Breakfast"},
// === MORE FINE DINING ===
{id:4516,name:"Angelina's (Intimate Italian Romance!)",cat:"Restaurant",sub:"Fine Dining",date:"",dateLabel:"Mon-Sat 5-10pm",venue:"Angelina's",loc:"Downtown Green Bay",addr:"117 N Adams St, Green Bay, WI 54301",desc:"Intimate upscale Italian dining! Retractable-roof patio, classic romantic ambiance. Perfect for anniversaries. Reservations via Tock.",url:"https://www.angelinagb.com/",setting:"indoor",walking:"lowWalking",goodFor:["seniors","couples"],highlight:true,free:false,recurring:true,cuisine:"Italian"},
{id:4517,name:"Plae Bistro (Chef's Table Available!)",cat:"Restaurant",sub:"Fine Dining",date:"",dateLabel:"Mon-Thu 11-9, Fri-Sat 11-10",venue:"Plae Bistro",loc:"Green Bay",addr:"1671 Hoffman Rd Ste 10, Green Bay, WI",desc:"Contemporary American fine dining with wine/martini program! Ask about the Chef's Table for a special occasion. Smart casual to dressy.",url:"https://plaebistro.com/",setting:"indoor",walking:"lowWalking",goodFor:["seniors","couples"],highlight:true,free:false,recurring:true,cuisine:"American"},
{id:4518,name:"Chives (Historic Building, Special Dinner!)",cat:"Restaurant",sub:"Fine Dining",date:"",dateLabel:"Tue-Sat lunch & dinner (closed Sun-Mon)",venue:"Chives",loc:"Suamico",addr:"1749 Riverside Dr, Suamico, WI",desc:"Fine dining in a beautiful historic building! Strong special dinner reputation. Smart casual. Reservations recommended by phone.",url:"",setting:"indoor",walking:"lowWalking",goodFor:["seniors","couples"],highlight:true,free:false,recurring:true,cuisine:"American"},
{id:4519,name:"George's Steak House (Appleton — Piano Bar!)",cat:"Restaurant",sub:"Fine Dining",date:"",dateLabel:"Mon-Sat 4:30-8:30pm (closed Sun)",venue:"George's Steak House",loc:"Appleton (30 min)",addr:"2208 S Memorial Dr, Appleton, WI 54915",desc:"Legacy steakhouse with PIANO BAR! Phone-only reservations strongly recommended. Worth the 30-min drive for a true classic supper club steak experience.",url:"https://www.georgessteakhouseappleton.com/",setting:"indoor",walking:"lowWalking",goodFor:["seniors","couples"],highlight:true,free:false,recurring:true,cuisine:"Steakhouse"},
// === MORE BUFFETS ===
{id:4521,name:"Sushi Lover — AYCE Sushi! ($12.99 Lunch!)",cat:"Restaurant",sub:"Buffet",date:"",dateLabel:"Lunch ~$12.99, dinner ~$18.99 (AYCE order-to-table)",venue:"Sushi Lover",loc:"Downtown Green Bay",addr:"313 N Broadway, Green Bay, WI",desc:"All-you-can-eat sushi! Order-to-table (not a steam table). Lunch ~$12.99, dinner ~$18.99. Sashimi +$1/order. Great value for sushi lovers!",url:"",setting:"indoor",walking:"lowWalking",goodFor:["seniors","couples"],highlight:true,free:false,recurring:true,cuisine:"Japanese"},
{id:4522,name:"Four Way Bar — Sunday Brunch + Dinner Buffet!",cat:"Restaurant",sub:"Buffet",date:"",dateLabel:"Sunday brunch + dinner buffets",venue:"Four Way Bar & Restaurant",loc:"Suamico",addr:"1801 Riverside Dr, Suamico, WI",desc:"Sunday brunch buffet AND Sunday dinner buffet! Plus salad bar with weekday meals. Classic Suamico gathering spot. (920) 434-3704.",url:"https://fourwaybar.com/",setting:"indoor",walking:"lowWalking",goodFor:["seniors","family"],highlight:true,free:false,recurring:true,cuisine:"American"},
{id:4523,name:"Golden Corral (Appleton — AYCE Everything!)",cat:"Restaurant",sub:"Buffet",date:"",dateLabel:"Mon-Fri 11-9, Sat-Sun 8-9 (30 min drive)",venue:"Golden Corral",loc:"Appleton (30 min)",addr:"1169 N Westhill Blvd, Appleton, WI 54914",desc:"All-you-can-eat buffet with everything! Breakfast buffet Sat-Sun from 8am. Often has senior/early-bird pricing — ask. 30-min drive from Green Bay.",url:"https://www.goldencorral.com/",setting:"indoor",walking:"lowWalking",goodFor:["seniors","family"],highlight:false,free:false,recurring:true,cuisine:"Buffet"},
// === URGENT CARE ===
{id:4525,name:"Bellin Health Urgent Care (2 Locations!)",cat:"Service",sub:"Medical",date:"",dateLabel:"Daily 8am-8pm (holidays 8am-4pm)",venue:"Bellin Health Urgent Care",loc:"Bellevue & Ashwaubenon",addr:"3263 Eaton Rd, Green Bay, WI 54311",desc:"Two locations! Bellevue (3263 Eaton Rd) and Ashwaubenon (1630 Commanche Ave). Daily 8am-8pm, holidays 8-4. (920) 433-6000.",url:"https://www.bellin.org/",setting:"indoor",walking:"lowWalking",goodFor:["seniors"],highlight:false,free:false,recurring:true},
{id:4526,name:"Prevea Urgent Care (6 Brown County Locations!)",cat:"Service",sub:"Medical",date:"",dateLabel:"Most Mon-Fri 8am-8pm (weekend hours vary)",venue:"Prevea Health Urgent Care",loc:"Multiple Locations",addr:"2502 S Ashland Ave, Green Bay, WI 54304",desc:"SIX locations! Ashwaubenon, E Mason/Voyager, Washington St, Howard, East De Pere, West De Pere. All (920) 496-4700. Most open Mon-Fri 8am-8pm.",url:"https://www.prevea.com/",setting:"indoor",walking:"lowWalking",goodFor:["seniors"],highlight:false,free:false,recurring:true},
{id:4527,name:"Bellin FastCare Walk-In (2 Locations!)",cat:"Service",sub:"Medical",date:"",dateLabel:"Mon-Fri 8-8, Sat 10-6, Sun 11-3",venue:"Bellin Health FastCare",loc:"East GB & West GB (Meijer)",addr:"1976 Lime Kiln Rd, Green Bay, WI 54311",desc:"Walk-in clinic! Also at 2015 Shawano Ave (inside Meijer). Mon-Fri 8-8, Sat 10-6, Sun 11-3. (920) 445-7377. Last patients ~15 min before close.",url:"https://www.bellin.org/",setting:"indoor",walking:"lowWalking",goodFor:["seniors"],highlight:false,free:false,recurring:true},
// === SPLASH PADS ===
{id:4529,name:"CityDeck Splash Pad (FREE, Downtown!)",cat:"Park",sub:"Splash Pad",date:"",dateLabel:"Seasonal daily (~6:30am-10pm, FREE)",venue:"CityDeck",loc:"Downtown Green Bay",addr:"301 N Washington St, Green Bay, WI 54301",desc:"FREE splash pad right on the CityDeck riverfront! Perfect for grandkids while you sit on benches nearby. Restrooms, water filling station, green space all around.",url:"https://greenbaywi.gov/",setting:"outdoor",walking:"lowWalking",goodFor:["family"],highlight:true,free:true,recurring:true},
{id:4530,name:"Red Smith Park Splash Pad (FREE!)",cat:"Park",sub:"Splash Pad",date:"",dateLabel:"Seasonal (FREE)",venue:"Red Smith Park",loc:"East Green Bay",addr:"2765 Sussex Rd, Green Bay, WI",desc:"FREE splash pad at Red Smith Park! Great park for families with playground equipment too. Bring towels and sunscreen.",url:"https://greenbaywi.gov/",setting:"outdoor",walking:"lowWalking",goodFor:["family"],highlight:false,free:true,recurring:true},
// === MORE COFFEE ===
{id:4532,name:"Glas Coffeehouse (Local Roasting!)",cat:"Restaurant",sub:"Coffee",date:"",dateLabel:"Mon-Sat 7am-2pm, closed Sun",venue:"Glas Coffeehouse",loc:"Downtown Green Bay",addr:"228 N Adams St, Green Bay, WI 54301",desc:"Local roasting with an Irish identity! WiFi, gluten-free options. Mon-Sat 7am-2pm. A cozy downtown spot for a quiet morning coffee.",url:"",setting:"indoor",walking:"lowWalking",goodFor:["seniors","couples"],highlight:false,free:false,recurring:true,cuisine:"Coffee"},
{id:4533,name:"Grounded Cafe (Mission-Driven, Senior-Friendly!)",cat:"Restaurant",sub:"Coffee",date:"",dateLabel:"Mon-Fri 7am-2pm (closed weekends)",venue:"Grounded Cafe",loc:"Downtown Green Bay",addr:"300 S Adams St, Green Bay, WI 54301",desc:"Mission-driven cafe that employs seniors! Great community story, good coffee, comfortable atmosphere. Weekdays only 7am-2pm.",url:"https://groundedcafegb.org/",setting:"indoor",walking:"lowWalking",goodFor:["seniors"],highlight:true,free:false,recurring:true,cuisine:"Coffee"},
{id:4534,name:"4th & Strong (Titletown Coffee Near Lambeau!)",cat:"Restaurant",sub:"Coffee",date:"",dateLabel:"Mon-Fri 6-2, Sat-Sun 8-12",venue:"4th & Strong",loc:"Ashwaubenon (Titletown)",addr:"Titletown, Green Bay, WI 54304",desc:"Craft coffee, smoothies, grab-and-go right in Titletown! Walking distance to Lambeau. Perfect morning meetup spot before crowds. Mon-Fri 6-2, weekends 8-12.",url:"https://www.titletown.com/",setting:"indoor",walking:"lowWalking",goodFor:["seniors","couples"],highlight:false,free:false,recurring:true,cuisine:"Coffee"},
{id:4535,name:"Luna Coffee Roastery (De Pere Specialty!)",cat:"Restaurant",sub:"Coffee",date:"",dateLabel:"Mon-Sat 6:30am-2pm, Sun 8:30am-2pm",venue:"Luna Coffee Roastery",loc:"De Pere",addr:"330 Main Ave, De Pere, WI 54115",desc:"Small-batch specialty coffee roasting! A De Pere metro favorite. Mon-Sat from 6:30am, Sun from 8:30am.",url:"",setting:"indoor",walking:"lowWalking",goodFor:["seniors","couples"],highlight:false,free:false,recurring:true,cuisine:"Coffee"},
// === MORE CHURCHES ===
{id:4537,name:"Pilgrim Lutheran (Many Service Times!)",cat:"Activity",sub:"Church / Worship",date:"",dateLabel:"Sun 7:45, 9, 10:30am & 2pm; Sat 5pm; Wed 6am & 6pm",venue:"Pilgrim Lutheran Church (LCMS)",loc:"West Green Bay",addr:"1731 St Agnes Dr, Green Bay, WI 54304",desc:"MANY service time options! Sunday at 7:45, 9, 10:30am & 2pm. Saturday 5 & 5:30pm. Wednesday 6am & 6pm Bible studies. (920) 965-2233.",url:"",setting:"indoor",walking:"lowWalking",goodFor:["seniors"],highlight:false,free:true,recurring:true},
{id:4538,name:"First United Methodist (Side Chapel for Mobility!)",cat:"Activity",sub:"Church / Worship",date:"",dateLabel:"Sundays 8:45am",venue:"First United Methodist Church",loc:"Downtown Green Bay",addr:"501 Howe St, Green Bay, WI 54301",desc:"Sunday 8:45am with Sermon Cafe ~10:10am (Sep-May). SIDE CHAPEL available for those with mobility needs! Live worship. (920) 437-9252.",url:"",setting:"indoor",walking:"lowWalking",goodFor:["seniors"],highlight:false,free:true,recurring:true},
{id:4539,name:"Islamic Society of Green Bay (Mosque)",cat:"Activity",sub:"Church / Worship",date:"",dateLabel:"5 daily prayers + Jumu'ah (Friday)",venue:"Islamic Society of Wisconsin - Green Bay",loc:"Green Bay",addr:"1512 Velp Ave, Green Bay, WI 54303",desc:"Five daily prayers plus Friday Jumu'ah. Wheelchair-accessible parking and entrance. (920) 234-5511.",url:"https://www.greenbaymasjid.com/",setting:"indoor",walking:"lowWalking",goodFor:["seniors"],highlight:false,free:true,recurring:true},
// === HEARING / EYE CARE ===
{id:4541,name:"HearingLife Green Bay (Hearing Aids!)",cat:"Service",sub:"Medical",date:"",dateLabel:"~9am-5pm (call for schedule)",venue:"HearingLife",loc:"Green Bay",addr:"550 N Military Ave, Ste 4A, Green Bay, WI 54303",desc:"Hearing aid center. Free hearing evaluations often available. (920) 593-9093. Important for seniors — don't ignore hearing changes!",url:"",setting:"indoor",walking:"lowWalking",goodFor:["seniors"],highlight:false,free:false,recurring:true},
{id:4542,name:"BayCare Clinic Eye Specialists (Cataracts!)",cat:"Service",sub:"Medical",date:"",dateLabel:"Mon-Fri 8am-5pm",venue:"BayCare Clinic Eye Specialists",loc:"West Green Bay",addr:"2253 W Mason St, Green Bay, WI 54303",desc:"Specialty ophthalmology — cataracts, glaucoma, retina, macular degeneration. Part of Aurora BayCare system. (920) 327-7000.",url:"https://www.aurorabaycare.com/",setting:"indoor",walking:"lowWalking",goodFor:["seniors"],highlight:false,free:false,recurring:true},
// === POST OFFICE / DMV ===
{id:4544,name:"Green Bay Downtown Post Office",cat:"Service",sub:"Government",date:"",dateLabel:"Mon-Fri ~8-5:30, Sat 9-12",venue:"USPS Downtown Green Bay",loc:"Downtown Green Bay",addr:"118 N Monroe Ave, Green Bay, WI 54301",desc:"Main downtown post office. (920) 432-0229. Retail window, PO boxes, passport acceptance. Sat morning hours 9-12.",url:"https://tools.usps.com/",setting:"indoor",walking:"lowWalking",goodFor:["seniors"],highlight:false,free:false,recurring:true},
// === EMERGENCY VET ===
{id:4546,name:"Animal Referral Center (24/7 Pet ER!)",cat:"Service",sub:"Veterinary",date:"",dateLabel:"24/7 emergency + specialty",venue:"Animal Referral Center of Green Bay",loc:"East Green Bay",addr:"2141 Lime Kiln Rd, Green Bay, WI 54311",desc:"24/7 pet emergency and specialty veterinary care! (920) 494-9400. Regional ER for dogs and cats. Important to know if you travel with pets.",url:"https://arcgb.com/",setting:"indoor",walking:"lowWalking",goodFor:["seniors"],highlight:false,free:false,recurring:true},
// === GARDEN ===
{id:4548,name:"Schroeder's Flowers & Garden Center",cat:"Shop",sub:"Garden Center",date:"",dateLabel:"Mon-Fri 8-6, Sat 8-5:30, Sun 10-3",venue:"Schroeder's Flowers & Garden Center",loc:"Green Bay",addr:"1530 S Webster Ave, Green Bay, WI 54301",desc:"Long-established florist + garden center! Annuals, perennials, hanging baskets, shrubs, roses, vegetables, herbs, cut flowers, floral design. (920) 436-6363.",url:"",setting:"indoor",walking:"someWalking",goodFor:["seniors"],highlight:false,free:false,recurring:true},
{id:4549,name:"Lindsley's Greenhouse (Family Seasonal!)",cat:"Shop",sub:"Garden Center",date:"",dateLabel:"~Mon-Sat 8-5, Sun 10-3 (seasonal)",venue:"Lindsley's Greenhouse",loc:"East Green Bay",addr:"733 Lime Kiln Rd, Green Bay, WI 54302",desc:"Seasonal family greenhouse! Hanging baskets, planters, annuals, perennials, vegetable starts. A local favorite each spring. (920) 468-6898.",url:"https://www.lindsleysgreenhouse.com/",setting:"outdoor",walking:"someWalking",goodFor:["seniors"],highlight:false,free:false,recurring:true},
];

let newStr = '';
for (const e of entries) {
  const descEsc = e.desc.replace(/"/g, '\\"');
  const nameEsc = e.name.replace(/"/g, '\\"');
  let s = ',\n{id:' + e.id + ',name:"' + nameEsc + '",cat:"' + e.cat + '",sub:"' + e.sub + '"';
  s += ',price:"' + (e.free ? 'free' : '$$') + '",priceNum:' + (e.free ? 0 : 2);
  s += ',date:"' + (e.date||'') + '"';
  if (e.dateTo) s += ',dateTo:"' + e.dateTo + '"';
  s += ',dateLabel:"' + (e.dateLabel || '') + '"';
  s += ',venue:"' + e.venue + '"';
  s += ',desc:"' + descEsc + '"';
  s += ',url:"' + (e.url || '') + '"';
  s += ',setting:"' + e.setting + '",walking:"' + e.walking + '"';
  s += ',goodFor:' + JSON.stringify(e.goodFor);
  s += ',highlight:' + e.highlight;
  s += ',cuisine:"' + (e.cuisine || '') + '",established:""';
  s += ',free:' + e.free + ',recurring:' + (e.recurring || false) + '}';
  newStr += s;
}

const lastEntry = 'free:false,recurring:true}';
const idx = html.lastIndexOf(lastEntry);
if (idx === -1) { console.log('ERROR: insertion point not found'); process.exit(1); }
html = html.substring(0, idx + lastEntry.length) + newStr + html.substring(idx + lastEntry.length);

fs.writeFileSync(path, html, 'utf8');
console.log('Added ' + entries.length + ' entries (IDs ' + Math.min(...entries.map(e=>e.id)) + '-' + Math.max(...entries.map(e=>e.id)) + ')');
console.log('File size: ' + Buffer.byteLength(html, 'utf8'));
