const fs = require('fs');
const path = 'C:/Users/shawn/Downloads/Green Bay Explorer.html';
let html = fs.readFileSync(path, 'utf8');

const entries = [
// === DAY TRIPS: OSHKOSH ===
{id:3500,name:"EAA AirVenture Oshkosh 2026",cat:"Event",sub:"Day Trip",date:"2026-07-20",dateTo:"2026-07-26",dateLabel:"Mon-Sun Jul 20-26",venue:"Wittman Regional Airport, Oshkosh",loc:"Oshkosh (Day Trip)",addr:"3000 Poberezny Rd, Oshkosh, WI 54902",desc:"World's LARGEST fly-in and air show! Daily aerial demonstrations, warbirds, homebuilt aircraft, forums, exhibits, night airshow. Youth 18 & under FREE. Weekly pass $159 (members). ~1 hr from Green Bay. A bucket-list experience!",url:"https://www.eaa.org/airventure",setting:"outdoor",walking:"longWalking",goodFor:["seniors","family","couples"],highlight:true,free:false,recurring:false},
// === DAY TRIPS: APPLETON/FOX CITIES ===
{id:3501,name:"Fox Cities PAC — Kimberly Akimbo (Broadway)",cat:"Event",sub:"Theater",date:"2026-03-03",dateTo:"2026-03-08",dateLabel:"Mar 3-8 (various times)",venue:"Fox Cities PAC, Thrivent Hall",loc:"Appleton (Day Trip)",addr:"400 W College Ave, Appleton, WI 54911",desc:"Tony-winning Broadway musical at the Fox Cities Performing Arts Center. Funny and heartfelt. ~30 min from Green Bay. Multiple matinee and evening performances.",url:"https://foxcitiespac.com/",setting:"indoor",walking:"lowWalking",goodFor:["seniors","couples"],highlight:true,free:false,recurring:false},
{id:3502,name:"Fox Cities PAC — The Great Gatsby (Musical)",cat:"Event",sub:"Theater",date:"2026-04-14",dateTo:"2026-04-19",dateLabel:"Apr 14-19 (various times)",venue:"Fox Cities PAC, Thrivent Hall",loc:"Appleton (Day Trip)",addr:"400 W College Ave, Appleton, WI 54911",desc:"The Great Gatsby as a Broadway musical! ~30 min from Green Bay. Matinee and evening performances available.",url:"https://foxcitiespac.com/",setting:"indoor",walking:"lowWalking",goodFor:["seniors","couples"],highlight:true,free:false,recurring:false},
// === DADDY D DINNER THEATER ===
{id:3505,name:"Daddy D Fifties Show (Dinner Theater)",cat:"Event",sub:"Dinner Show",date:"2026-04-15",dateTo:"2026-04-17",dateLabel:"Apr 15-17 (dinner 6pm, show 7pm)",venue:"Riverside Ballroom, 1560 Main St",loc:"Downtown Green Bay",addr:"1560 Main St, Green Bay, WI 54302",desc:"Classic 1950s rock 'n' roll dinner theater! Elvis, Buddy Holly, Patsy Cline hits. Dinner 6pm, show 7pm. Matinee Apr 16 (lunch noon, show 1pm). Seniors 65+ $55 dinner+show, $35 show-only.",url:"https://daddydproductions.com/",setting:"indoor",walking:"lowWalking",goodFor:["seniors","couples"],highlight:true,free:false,recurring:false},
{id:3506,name:"Daddy D Golden Oldies Show (60s & 70s)",cat:"Event",sub:"Dinner Show",date:"2026-06-03",dateTo:"2026-06-12",dateLabel:"Jun 3, 10, 11, 12 (dinner 6pm, show 7pm)",venue:"Riverside Ballroom, 1560 Main St",loc:"Downtown Green Bay",addr:"1560 Main St, Green Bay, WI 54302",desc:"1960s & 70s golden oldies dinner theater! Four great dates in June. Dinner 6pm, show 7pm. Matinee Jun 11 (sold out — check for returns). Seniors 65+ $55/$35.",url:"https://daddydproductions.com/",setting:"indoor",walking:"lowWalking",goodFor:["seniors","couples"],highlight:true,free:false,recurring:false},
// === EPIC EVENT CENTER HIGHLIGHTS ===
{id:3510,name:"Marshall Tucker Band at EPIC",cat:"Event",sub:"Concert",date:"2026-03-13",dateLabel:"Fri Mar 13, 7:30pm",venue:"EPIC Event Center",loc:"Ashwaubenon",addr:"2351 Holmgren Way, Ashwaubenon, WI 54304",desc:"Southern rock legends! Can't You See, Heard It in a Love Song, Fire on the Mountain. Doors 6:30pm, show 7:30pm.",url:"https://epicgreenbay.com/",setting:"indoor",walking:"lowWalking",goodFor:["seniors","couples"],highlight:true,free:false,recurring:false},
{id:3511,name:"Blood, Sweat & Tears at EPIC",cat:"Event",sub:"Concert",date:"2026-05-03",dateLabel:"Sat May 3, 7:30pm",venue:"EPIC Event Center",loc:"Ashwaubenon",addr:"2351 Holmgren Way, Ashwaubenon, WI 54304",desc:"Jazz-rock legends! Spinning Wheel, You've Made Me So Very Happy, And When I Die. Doors 6:30pm, show 7:30pm.",url:"https://epicgreenbay.com/",setting:"indoor",walking:"lowWalking",goodFor:["seniors","couples"],highlight:true,free:false,recurring:false},
{id:3512,name:"Tom Keifer Band (Cinderella) at EPIC",cat:"Event",sub:"Concert",date:"2026-05-14",dateLabel:"Thu May 14, 7:30pm",venue:"EPIC Event Center",loc:"Ashwaubenon",addr:"2351 Holmgren Way, Ashwaubenon, WI 54304",desc:"Cinderella frontman Tom Keifer with John Corabi. Nobody's Fool, Don't Know What You Got, Gypsy Road. Doors 6:30pm.",url:"https://epicgreenbay.com/",setting:"indoor",walking:"lowWalking",goodFor:["couples"],highlight:false,free:false,recurring:false},
{id:3513,name:"Edwin McCain & Five for Fighting at EPIC",cat:"Event",sub:"Concert",date:"2026-06-19",dateLabel:"Fri Jun 19, 7:30pm",venue:"EPIC Event Center",loc:"Ashwaubenon",addr:"2351 Holmgren Way, Ashwaubenon, WI 54304",desc:"I'll Be (Edwin McCain) meets Superman (Five for Fighting). Two acoustic soft-rock favorites on one stage. Doors 6:30pm.",url:"https://epicgreenbay.com/",setting:"indoor",walking:"lowWalking",goodFor:["seniors","couples"],highlight:true,free:false,recurring:false},
{id:3514,name:"Uncle Kracker at EPIC",cat:"Event",sub:"Concert",date:"2026-07-09",dateLabel:"Thu Jul 9, 7:30pm",venue:"EPIC Event Center",loc:"Ashwaubenon",addr:"2351 Holmgren Way, Ashwaubenon, WI 54304",desc:"Follow Me, Drift Away, Smile. Country/rock/pop crossover. With The Wannabes. Doors 6:30pm.",url:"https://epicgreenbay.com/",setting:"indoor",walking:"lowWalking",goodFor:["couples"],highlight:false,free:false,recurring:false},
{id:3515,name:"Pop 2000 Tour (*NSYNC, O-Town, LFO) at EPIC",cat:"Event",sub:"Concert",date:"2026-08-28",dateLabel:"Fri Aug 28, 7:15pm",venue:"EPIC Event Center",loc:"Ashwaubenon",addr:"2351 Holmgren Way, Ashwaubenon, WI 54304",desc:"Nostalgia tour! Chris Kirkpatrick (*NSYNC), O-Town, Ryan Cabrera, LFO. Fun for the whole family. Doors 6:30pm.",url:"https://epicgreenbay.com/",setting:"indoor",walking:"lowWalking",goodFor:["family","couples"],highlight:false,free:false,recurring:false},
// === DE PERE EVENTS ===
{id:3520,name:"De Pere City Band — Free Summer Concerts",cat:"Event",sub:"Free Concert Series",date:"2026-06-11",dateTo:"2026-08-06",dateLabel:"Thursdays 7pm: Jun 11, 25, Jul 9, 23, 30, Aug 6",venue:"Voyageur Park, De Pere",loc:"De Pere",addr:"100 William St, De Pere, WI 54115",desc:"FREE Thursday evening concerts by the De Pere City Band! Six summer dates with fun themes: Celebrate America, Music of the 70s, Christmas in July, and more. Bring a lawn chair. Cancelled if raining at 6pm.",url:"https://www.deperewi.gov/",setting:"outdoor",walking:"lowWalking",goodFor:["seniors","family","couples"],highlight:true,free:true,recurring:true},
{id:3521,name:"De Pere Beer Gardens (Tuesdays)",cat:"Event",sub:"Festival",date:"2026-06-09",dateTo:"2026-08-18",dateLabel:"Tuesdays 4:30-8:30pm, Jun 9 - Aug 18",venue:"Voyageur Park, De Pere",loc:"De Pere",addr:"100 William St, De Pere, WI 54115",desc:"Tuesday evening beer gardens at Voyageur Park! Craft beer and seltzer, live music, food trucks, lawn games. Proceeds support De Pere parks. 11 summer Tuesdays.",url:"https://www.deperewi.gov/",setting:"outdoor",walking:"lowWalking",goodFor:["couples","seniors"],highlight:true,free:false,recurring:true},
{id:3522,name:"Knights on the Fox — Free Concerts (SNC)",cat:"Event",sub:"Free Concert Series",date:"2026-07-07",dateTo:"2026-08-04",dateLabel:"Tuesdays 6:30-8pm, Jul 7 - Aug 4",venue:"St. Norbert College (Fox River)",loc:"De Pere",addr:"100 Grant St, De Pere, WI 54115",desc:"FREE outdoor summer concerts on the Fox River at St. Norbert College! Five Tuesday evenings. Bring a picnic or grab food from Phil's (opens 5pm). Beautiful riverside setting.",url:"https://www.snc.edu/community/communityprograms/kotf.html",setting:"outdoor",walking:"lowWalking",goodFor:["seniors","couples","family"],highlight:true,free:true,recurring:true},
{id:3523,name:"De Pere Summer Carnival",cat:"Event",sub:"Family",date:"2026-08-06",dateLabel:"Thu Aug 6, 5-7:30pm",venue:"Optimist Park, De Pere",loc:"De Pere",addr:"Optimist Park, De Pere, WI",desc:"Games, prizes, music, treats, Kiwanis hot dog dinner. Game tickets just 25 cents! Fun family evening in De Pere.",url:"https://www.deperewi.gov/",setting:"outdoor",walking:"someWalking",goodFor:["family","seniors"],highlight:false,free:false,recurring:false},
{id:3524,name:"Tour De Pere — Bike Racing Weekend",cat:"Event",sub:"Sports",date:"2026-06-22",dateTo:"2026-06-23",dateLabel:"Mon-Tue Jun 22-23",venue:"Downtown De Pere",loc:"De Pere",addr:"Downtown De Pere, WI",desc:"Pro/amateur bike racing on closed downtown streets! Marketplace, entertainment, food. Kids' Bike Rodeo at SNC (Jun 23). Part of the Tour of America's Dairyland cycling series.",url:"https://definitelydepere.org/events2/tour-de-pere/",setting:"outdoor",walking:"someWalking",goodFor:["family","seniors"],highlight:true,free:true,recurring:false},
// === BINGO ===
{id:3530,name:"Oneida Casino Bingo — Daily Sessions",cat:"Activity",sub:"Bingo",date:"2026-03-22",dateTo:"2026-08-31",dateLabel:"Daily — AM, PM, Evening, & Sat Nite Owls",venue:"Irene Moore Activity Center (IMAC), Oneida Casino",loc:"Ashwaubenon / Oneida",addr:"2100 Airport Dr, Green Bay, WI 54313",desc:"Daily bingo sessions at Oneida Casino! AM Express (10:30am daily), PM Quest (6:30pm Mon-Wed), Evening (6:30pm Thu-Fri, 5:30pm Sat-Sun), Nite Owls (9:30pm Sat). 692 seats. 18+. Packs from $13.",url:"https://oneidacasinohotel.com/bingo",setting:"indoor",walking:"lowWalking",goodFor:["seniors"],highlight:true,free:false,recurring:true},
{id:3531,name:"St. Philip the Apostle — Tuesday Bingo",cat:"Activity",sub:"Bingo",date:"2026-03-22",dateTo:"2026-04-28",dateLabel:"Tuesdays, doors 5pm, bingo 6:30pm (Sep-Apr)",venue:"St. Philip the Apostle Parish",loc:"West Green Bay",addr:"312 Victoria St, Green Bay, WI 54302",desc:"Parish bingo fundraiser every Tuesday! Doors 5pm, kitchen 5-6:30pm, bingo starts 6:30pm. All 22 games from $16. Cash only. 18+ to play. Season runs Sep through late April.",url:"https://www.stphilipgb.org/bingo",setting:"indoor",walking:"lowWalking",goodFor:["seniors"],highlight:true,free:false,recurring:true},
// === BREWERY WEEKLY EVENTS ===
{id:3535,name:"Stillmank Brewing — Jazz Wednesday",cat:"Activity",sub:"Live Music",date:"2026-03-22",dateTo:"2026-08-31",dateLabel:"Wednesdays 6:30-8:30pm",venue:"Stillmank Brewing Co.",loc:"Downtown Green Bay",addr:"215 N Henry St, Green Bay, WI 54302",desc:"Live jazz every Wednesday evening at Stillmank Brewery! Local jazz musicians, sit-in jams welcome. Taproom open. A sophisticated midweek outing.",url:"https://stillmankbrewing.com/",setting:"indoor",walking:"lowWalking",goodFor:["seniors","couples"],highlight:true,free:true,recurring:true},
{id:3536,name:"Copper State Brewing — Tuesday Jazz Night",cat:"Activity",sub:"Live Music",date:"2026-03-22",dateTo:"2026-08-31",dateLabel:"Tuesdays 6-9pm",venue:"Copper State Brewing Co.",loc:"Downtown Green Bay",addr:"313 Dousman St, Green Bay, WI 54303",desc:"Live jazz every Tuesday evening at Copper State! Plus live bands on Monday nights. Great downtown brewery atmosphere.",url:"https://www.copperstate.beer/",setting:"indoor",walking:"lowWalking",goodFor:["seniors","couples"],highlight:false,free:true,recurring:true},
{id:3537,name:"Titletown Brewing — Wednesday Trivia (Geeks Who Drink)",cat:"Activity",sub:"Trivia Night",date:"2026-03-22",dateTo:"2026-08-31",dateLabel:"Wednesdays 6:30-8:30pm",venue:"Titletown Brewing Co.",loc:"Downtown Green Bay",addr:"320 N Broadway, Green Bay, WI 54303",desc:"Free pub trivia every Wednesday at Titletown Brewing! Geeks Who Drink hosted. Teams up to 6. Fun midweek brain workout.",url:"https://www.titletownbrewing.com/",setting:"indoor",walking:"lowWalking",goodFor:["couples","seniors"],highlight:false,free:true,recurring:true},
{id:3538,name:"Stadium View — SINGO, Trivia, & Karaoke (Weekly)",cat:"Activity",sub:"Entertainment",date:"2026-03-22",dateTo:"2026-08-31",dateLabel:"Wed SINGO 6pm, Thu Trivia 5:15pm, Fri Karaoke 9pm",venue:"Stadium View Bar & Event Halls",loc:"Ashwaubenon",addr:"1963 Holmgren Way, Green Bay, WI 54304",desc:"Three weekly entertainment nights! Wednesday: SINGO (music bingo) 6pm. Thursday: DJ Trivia 5:15pm. Friday: Sky Bar Karaoke 9pm. Fun casual nights out near Lambeau.",url:"https://www.thestadiumview.com/",setting:"indoor",walking:"lowWalking",goodFor:["couples","seniors"],highlight:false,free:true,recurring:true},
// === SCENIC BOAT TOURS ===
{id:3540,name:"Sister Bay Scenic Boat Tours (Door County)",cat:"Activity",sub:"Boat Tour",date:"2026-05-15",dateTo:"2026-10-15",dateLabel:"Daily May-Oct (multiple tours)",venue:"Sister Bay Marina",loc:"Door County (Day Trip)",addr:"10707 N Bay Shore Dr, Sister Bay, WI 54234",desc:"Scenic cruises on Lake Michigan! Eagle Bluff ($32/$29 senior), Peninsula Park Caves ($42/$39), Death's Door ($45/$42), Sunset Music Cruise ($45/$42). FREE Sunday church service cruises (book 2 weeks ahead). ~1¼ hr from Green Bay.",url:"https://www.doorcountyboats.com/",setting:"outdoor",walking:"lowWalking",goodFor:["seniors","couples","family"],highlight:true,free:false,recurring:true},
{id:3541,name:"Washington Island Ferry",cat:"Activity",sub:"Boat Tour",date:"2026-03-22",dateTo:"2026-10-31",dateLabel:"Daily year-round (reduced winter schedule)",venue:"Northport Pier",loc:"Door County (Day Trip)",addr:"215 WI-42, Ellison Bay, WI 54210",desc:"30-minute car ferry to Washington Island! Round trip: adults $15, car $30, kids 6-11 $8, 5 & under free. Bikes $6. Beautiful day trip from Green Bay (~2 hrs). Island has Stavkirke, lavender farm, beaches.",url:"https://wisferry.com/",setting:"outdoor",walking:"lowWalking",goodFor:["seniors","couples","family"],highlight:true,free:false,recurring:true},
// === MANITOWOC DAY TRIPS ===
{id:3545,name:"SS Badger Car Ferry (Cross Lake Michigan!)",cat:"Activity",sub:"Day Trip",date:"2026-05-15",dateTo:"2026-10-11",dateLabel:"Daily May 15 - Oct 11",venue:"Manitowoc Ferry Dock",loc:"Manitowoc (Day Trip)",addr:"900 S Lakeview Dr, Manitowoc, WI 54220",desc:"Cross Lake Michigan on the last coal-fired steamship! 4-hour cruise to Ludington, MI. Day crossings + summer overnights. Onboard entertainment, food, lounge. ~45 min from Green Bay to the dock.",url:"https://www.ssbadger.com/",setting:"outdoor",walking:"lowWalking",goodFor:["seniors","couples","family"],highlight:true,free:false,recurring:true},
{id:3546,name:"Wisconsin Maritime Museum & USS Cobia Submarine",cat:"Attraction",sub:"Museum",date:"",dateLabel:"Open year-round (summer daily 9-5)",venue:"Wisconsin Maritime Museum",loc:"Manitowoc (Day Trip)",addr:"75 Maritime Dr, Manitowoc, WI 54220",desc:"Tour a REAL WWII submarine! USS Cobia is a national historic landmark. Plus maritime exhibits, model ships, shipwreck coast history. Special events: Cobia birthday (Mar 28), SubFest (Jul 3-5), submarine sleepovers. ~45 min from Green Bay.",url:"https://www.wisconsinmaritime.org/",setting:"indoor",walking:"someWalking",goodFor:["seniors","family","couples"],highlight:true,free:false,recurring:true},
{id:3547,name:"SubFest & Fourth on the Shore (Manitowoc)",cat:"Event",sub:"Festival",date:"2026-07-03",dateTo:"2026-07-05",dateLabel:"Fri-Sun Jul 3-5",venue:"Wisconsin Maritime Museum & riverfront",loc:"Manitowoc (Day Trip)",addr:"75 Maritime Dr, Manitowoc, WI 54220",desc:"Huge July 4th weekend festival at the Maritime Museum! Sub Pub, food vendors, live bands, parade (Jul 4 ~10am), fireworks at dusk. Military FREE all weekend. Museum admission $10. Tolling of the Boats ceremony Jul 5.",url:"https://www.wisconsinmaritime.org/explore/subfest/",setting:"outdoor",walking:"someWalking",goodFor:["seniors","family","couples"],highlight:true,free:false,recurring:false},
{id:3548,name:"Berners Ice Cream Parlor — Birthplace of the Sundae",cat:"Attraction",sub:"Day Trip",date:"2026-05-25",dateTo:"2026-09-30",dateLabel:"Late May - Sep (Thu-Mon noon-6pm)",venue:"Washington House, Two Rivers",loc:"Two Rivers (Day Trip)",addr:"1622 Jefferson St, Two Rivers, WI 54241",desc:"Visit the birthplace of the ice cream sundae! Replica of Ed Berners' 1881 parlor where the sundae was invented. Order a classic sundae. Charming historic setting. ~50 min from Green Bay.",url:"https://tworivers-history.org/",setting:"indoor",walking:"lowWalking",goodFor:["seniors","family","couples"],highlight:true,free:false,recurring:true},
{id:3549,name:"Lakeshore Balloon Glow (Manitowoc)",cat:"Event",sub:"Festival",date:"2026-08-14",dateLabel:"Fri Aug 14, 5-9pm",venue:"Downtown Manitowoc Riverfront",loc:"Manitowoc (Day Trip)",addr:"720 Quay St, Manitowoc, WI 54220",desc:"Hot-air balloons light up the evening sky! Kids' zone, food trucks, live entertainment, fireworks. FREE. A magical summer evening. ~45 min from Green Bay.",url:"",setting:"outdoor",walking:"someWalking",goodFor:["seniors","family","couples"],highlight:true,free:true,recurring:false},
{id:3550,name:"Metro Jam — Free Music Festival (Manitowoc)",cat:"Event",sub:"Festival",date:"2026-06-19",dateTo:"2026-06-20",dateLabel:"Fri-Sat Jun 19-20",venue:"Washington Park, Manitowoc",loc:"Manitowoc (Day Trip)",addr:"Washington Park, Manitowoc, WI 54220",desc:"FREE two-day music festival in downtown Manitowoc! National and regional acts. Friday 5:30-9:30pm, Saturday noon-10pm. ~45 min from Green Bay.",url:"https://www.metrojam.org/",setting:"outdoor",walking:"someWalking",goodFor:["seniors","couples","family"],highlight:true,free:true,recurring:false},
// === GOLF SENIOR RATES ===
{id:3555,name:"Brown County Golf Course (Senior Rates!)",cat:"Activity",sub:"Golf",date:"2026-04-15",dateTo:"2026-10-31",dateLabel:"Season ~Apr-Oct",venue:"Brown County Golf Course",loc:"Hobart",addr:"897 Riverdale Dr, Hobart, WI 54155",desc:"Beautiful 18-hole public course with SENIOR RATES (62+): weekday walking 18 holes $37, 9 holes $25. Mon & Wed special: 18 riding $48! Great condition, reasonable prices. Men's club Thursday league.",url:"https://www.browncountygc.com/",setting:"outdoor",walking:"someWalking",goodFor:["seniors"],highlight:true,free:false,recurring:true},
{id:3556,name:"Wander Springs Golf Course (Senior Rates!)",cat:"Activity",sub:"Golf",date:"2026-04-15",dateTo:"2026-10-31",dateLabel:"Season ~Apr-Oct",venue:"Wander Springs Golf Course",loc:"Greenleaf",addr:"4342 Wayside Rd, Greenleaf, WI 54126",desc:"Affordable senior golf! Age 60+: weekday 9 holes $17, 18 holes $27 (tax included). Beautiful countryside course ~20 min from Green Bay.",url:"https://wandersprings.com/",setting:"outdoor",walking:"someWalking",goodFor:["seniors"],highlight:true,free:false,recurring:true},
{id:3557,name:"Hilly Haven Golf Course (Senior Rates!)",cat:"Activity",sub:"Golf",date:"2026-04-15",dateTo:"2026-10-31",dateLabel:"Season ~Apr-Oct",venue:"Hilly Haven Golf Course",loc:"De Pere",addr:"5911 County Rd PP, De Pere, WI 54115",desc:"Senior rates (60+): Mon-Thu before 3pm — 9 holes $21, 18 holes $34. Scenic De Pere course with rolling hills. Great for a relaxed round.",url:"https://www.hillyhaven.com/",setting:"outdoor",walking:"someWalking",goodFor:["seniors"],highlight:false,free:false,recurring:true},
// === MOVIE THEATERS ===
{id:3560,name:"Marcus Bay Park Cinema (Senior Matinees)",cat:"Activity",sub:"Movie Theater",date:"",dateLabel:"Open daily — senior matinees before 4pm",venue:"Marcus Bay Park Cinema",loc:"Ashwaubenon",addr:"755 Willard Dr, Ashwaubenon, WI 54304",desc:"Modern multiplex with senior pricing (60+, ~$7.50 before 4pm). Fathom Big Screen Classics in 2026: Ben-Hur (Mar 29), Silence of the Lambs (Apr 26), Fried Green Tomatoes (May 10), Willy Wonka (Aug 2). Value Tuesdays and Young at Heart Friday deals.",url:"https://www.marcustheatres.com/",setting:"indoor",walking:"lowWalking",goodFor:["seniors","couples"],highlight:true,free:false,recurring:true},
{id:3561,name:"De Pere Cinema — $5 Senior Tickets!",cat:"Activity",sub:"Movie Theater",date:"",dateLabel:"Open daily — seniors 62+ always $5",venue:"De Pere Cinema (Get Reel)",loc:"De Pere",addr:"417 George St, De Pere, WI 54115",desc:"Small-town cinema with the BEST senior pricing! Seniors 62+ just $5 anytime. All matinees (before 5:30pm) $5 for everyone. Tuesday $5 admission day. Cozy 3-screen theater in downtown De Pere.",url:"https://www.getreelcinemas.com/de-pere-cinema",setting:"indoor",walking:"lowWalking",goodFor:["seniors","couples"],highlight:true,free:false,recurring:true},
{id:3562,name:"Field of Scenes Drive-In Theater",cat:"Activity",sub:"Movie Theater",date:"2026-05-01",dateTo:"2026-09-30",dateLabel:"Seasonal (May-Sep) — double features!",venue:"Field of Scenes Drive-In",loc:"Freedom (Day Trip)",addr:"N3712 Hwy 55, Freedom, WI 54130",desc:"Classic drive-in theater experience! Double features for $8/adult ($4 kids). Twin screens. Bring blankets and lawn chairs. ~25 min from Green Bay. A nostalgic summer treat!",url:"https://www.fieldofscenes.biz/",setting:"outdoor",walking:"noWalking",goodFor:["seniors","couples","family"],highlight:true,free:false,recurring:true},
// === FISH FRY ===
{id:3565,name:"Village Green Golf Course — Friday Fish Fry",cat:"Activity",sub:"Fish Fry",date:"2026-02-06",dateTo:"2026-10-31",dateLabel:"Fridays 3-8pm (Feb-Oct)",venue:"Village Green Golf Course",loc:"Howard",addr:"302 Riverdale Dr, Howard, WI 54313",desc:"Great Friday fish fry! Walleye/cod/haddock $19.50, perch $22.75, combo $23.50. Includes coleslaw, rye bread, choice of potato. ~10 min from Zak Lane.",url:"",setting:"indoor",walking:"lowWalking",goodFor:["seniors","couples","family"],highlight:true,free:false,recurring:true},
{id:3566,name:"Maricque's — Wed & Fri Fish Fry (Green Bay Institution)",cat:"Restaurant",sub:"Fish Fry",date:"",dateLabel:"Wed dinner & Fri lunch+dinner",venue:"Maricque's",loc:"West Green Bay",addr:"1517 University Ave, Green Bay, WI 54302",desc:"Green Bay's fish fry destination! Perch, cod, pike, bluegill, catfish — supper-club style with rye bread and onion. Friday lunch 11am-1:30pm, dinner 4:30-10pm. Wednesday dinner 4:30-10pm. A local legend.",url:"https://www.greenbayfishfry.com/",setting:"indoor",walking:"lowWalking",goodFor:["seniors","couples","family"],highlight:true,free:false,recurring:true},
// === BARKHAUSEN NATURE ===
{id:3570,name:"Barkhausen — Bluebird House Workshop",cat:"Event",sub:"Nature",date:"2026-03-14",dateLabel:"Sat Mar 14, 9-11am",venue:"Barkhausen Waterfowl Preserve",loc:"Suamico",addr:"2024 Lakeview Dr, Suamico, WI 54173",desc:"Learn about bluebirds and build a nest box! Pre-registration required. Great hands-on nature experience at the preserve.",url:"https://www.browncountywi.gov/community/parks-department/",setting:"indoor",walking:"lowWalking",goodFor:["seniors","family"],highlight:false,free:false,recurring:false},
{id:3571,name:"Barkhausen — Maple Syrupin' Public Day",cat:"Event",sub:"Nature",date:"2026-03-21",dateLabel:"Sat Mar 21, 9am-2pm",venue:"Barkhausen Waterfowl Preserve",loc:"Suamico",addr:"2024 Lakeview Dr, Suamico, WI 54173",desc:"Maple syrup open day! Learn the sugaring process, taste fresh syrup. $5/person, pre-registration. Rain or shine. Arrive any time within the window.",url:"https://www.browncountywi.gov/community/parks-department/",setting:"outdoor",walking:"someWalking",goodFor:["seniors","family"],highlight:true,free:false,recurring:false},
{id:3572,name:"Maple Syrup 5K & Pancake Breakfast",cat:"Event",sub:"Sports",date:"2026-03-28",dateLabel:"Sat Mar 28, 5K 9am + breakfast 9-11am",venue:"Brown County Reforestation Camp",loc:"Suamico",addr:"4418 Reforestation Rd, Suamico, WI 54313",desc:"Trail 5K run/walk through the pines plus all-you-can-eat pancake breakfast with real maple syrup! Kids' Mini Maple Fun Run at 10am. Benefits Brown County Parks.",url:"https://www.browncountywi.gov/community/parks-department/",setting:"outdoor",walking:"someWalking",goodFor:["family","seniors"],highlight:true,free:false,recurring:false},
// === SENIOR PICNIC ===
{id:3575,name:"De Pere Senior Picnic (55+)",cat:"Event",sub:"Senior Social",date:"2026-08-22",dateLabel:"Fri Aug 22, doors 10:30am, lunch noon",venue:"De Pere Community Center",loc:"De Pere",addr:"De Pere Community Center, De Pere, WI",desc:"Senior picnic for ages 55+! Bingo, prizes, lunch, and socializing. Just $6. A fun and affordable afternoon out. Register with De Pere Parks & Rec.",url:"https://www.deperewi.gov/",setting:"indoor",walking:"lowWalking",goodFor:["seniors"],highlight:true,free:false,recurring:false},
// === SALVATION ARMY SENIOR PROGRAMS ===
{id:3576,name:"Salvation Army — Wednesday Senior Social & Bingo",cat:"Activity",sub:"Senior Social",date:"2026-03-22",dateTo:"2026-08-31",dateLabel:"Wednesdays: lunch noon, activities 1:15-3pm",venue:"Salvation Army, 626 Union Ct",loc:"Green Bay",addr:"626 Union Ct, Green Bay, WI 54303",desc:"Weekly senior program (50+)! Lunch at noon ($4), then cards, bingo, and activities 1:15-3pm. Optional $2 round-trip transportation. Annual enrollment required. Call (920) 593-2362.",url:"https://www.salvationarmyusa.org/wi/green-bay/",setting:"indoor",walking:"lowWalking",goodFor:["seniors"],highlight:true,free:false,recurring:true},
{id:3577,name:"Salvation Army — Bridge Club (Mon & Tue)",cat:"Activity",sub:"Card Games",date:"2026-03-22",dateTo:"2026-08-31",dateLabel:"Mondays & Tuesdays 12:30-4pm",venue:"Salvation Army, 626 Union Ct",loc:"Green Bay",addr:"626 Union Ct, Green Bay, WI 54303",desc:"Free bridge club for seniors! Mondays and Tuesdays 12:30-4pm. $1 donation for coffee/snacks. Annual enrollment, register (920) 593-2362.",url:"https://www.salvationarmyusa.org/wi/green-bay/",setting:"indoor",walking:"lowWalking",goodFor:["seniors"],highlight:false,free:true,recurring:true},
// === DOWNTOWN BLOCK PARTY ===
{id:3580,name:"Washington Street Block Party",cat:"Event",sub:"Festival",date:"2026-04-25",dateLabel:"Sat Apr 25, noon-7pm",venue:"100 block S. Washington St, Downtown Green Bay",loc:"Downtown Green Bay",addr:"100 S Washington St, Green Bay, WI 54301",desc:"Spring block party with Booyah Battle, Kringle Combine, Bike Bash, live bands! Benefits Salvation Army. Fun downtown afternoon.",url:"https://downtowngreenbay.com/block-party",setting:"outdoor",walking:"someWalking",goodFor:["family","seniors","couples"],highlight:true,free:true,recurring:false},
// === ST WILLY'S JAM ===
{id:3581,name:"St. Willy's Jam — Parish Multicultural Picnic",cat:"Event",sub:"Festival",date:"2026-06-14",dateLabel:"Sun Jun 14, 10:30am-5pm",venue:"St. Willebrord Parish, 209 S Adams St",loc:"Downtown Green Bay",addr:"209 S Adams St, Green Bay, WI 54301",desc:"Annual multicultural parish picnic! Outdoor bilingual Mass 10:45am, then live music, tacos, brats, burgers, raffles, games, bounce house. All are welcome! A beloved Green Bay tradition.",url:"https://stwillys.org/",setting:"outdoor",walking:"someWalking",goodFor:["seniors","family","couples"],highlight:true,free:true,recurring:false},
// === GNOME GAMES ===
{id:3582,name:"Gnome Games — Board Game Nights",cat:"Activity",sub:"Game / Gift",date:"2026-03-22",dateTo:"2026-08-31",dateLabel:"Wed 2-9pm (West) & Sat 11am-4pm (East)",venue:"Gnome Games",loc:"Multiple",addr:"2160 Ridge Rd, Green Bay, WI 54304 (West) / 1683 E Mason St (East)",desc:"Free open board game play! Huge library of games to try. Wednesday afternoons at the West store, Saturday at East. Staff can recommend by age and interest. Great for grandkid visits or couples!",url:"https://gnomegames.com/",setting:"indoor",walking:"lowWalking",goodFor:["seniors","family","couples"],highlight:false,free:true,recurring:true},
// === OSHKOSH ADDITIONAL ===
{id:3585,name:"Winnebago County Fair",cat:"Event",sub:"Festival",date:"2026-07-29",dateTo:"2026-08-02",dateLabel:"Tue-Sat Jul 29 - Aug 2",venue:"Sunnyview Expo Center, Oshkosh",loc:"Oshkosh (Day Trip)",addr:"500 E County Rd Y, Oshkosh, WI 54901",desc:"Five-day county fair! Carnival, livestock, grandstand shows, demolition derby, food, 4-H exhibits. ~1 hr from Green Bay.",url:"https://winnebagofairoshkosh.com/",setting:"outdoor",walking:"someWalking",goodFor:["family","seniors"],highlight:false,free:false,recurring:false},
// === TWO RIVERS SNOWFEST ===
{id:3586,name:"Two Rivers SnowFest — Cool City Vibes",cat:"Event",sub:"Festival",date:"2026-07-24",dateTo:"2026-07-26",dateLabel:"Fri-Sun Jul 24-26",venue:"Neshotah Park, Two Rivers",loc:"Two Rivers (Day Trip)",addr:"2111 Pierce St, Two Rivers, WI 54241",desc:"Free 3-day summer festival on Lake Michigan! Bands, parade (Sat 11am), carnival, food. Saturday is the big day. Beautiful beachside setting. ~50 min from Green Bay.",url:"https://www.trsnowfest.org/",setting:"outdoor",walking:"someWalking",goodFor:["seniors","family","couples"],highlight:true,free:true,recurring:false},
// === NEVILLE MUSEUM DETAIL ===
{id:3590,name:"Neville Museum — Art and the Ice Age Exhibit",cat:"Event",sub:"Art",date:"2026-06-06",dateTo:"2026-09-06",dateLabel:"Jun 6 - Sep 6 (during museum hours)",venue:"Neville Public Museum",loc:"Downtown Green Bay",addr:"210 Museum Pl, Green Bay, WI 54303",desc:"New summer exhibit exploring art inspired by the Ice Age in Northeast Wisconsin. Guided Curiosity Unveiled tour Aug 18 at 6pm. Free on Explorer Wednesdays for Brown County residents.",url:"https://www.nevillepublicmuseum.org/",setting:"indoor",walking:"lowWalking",goodFor:["seniors","couples"],highlight:true,free:false,recurring:false},
{id:3591,name:"Art Garage — Open House (20th Anniversary)",cat:"Event",sub:"Art",date:"2026-03-21",dateLabel:"Sat Mar 21, 4-6pm",venue:"The Art Garage",loc:"Downtown Green Bay",addr:"1400 Cedar St, Green Bay, WI 54302",desc:"Celebrate 20 years of The Art Garage! Free community open house with local artists, demos, and refreshments. Great way to discover Green Bay's art scene.",url:"https://theartgarage.org/",setting:"indoor",walking:"lowWalking",goodFor:["seniors","couples"],highlight:false,free:true,recurring:false},
// === RIVERSIDE BALLROOM ===
{id:3595,name:"Riverside Ballroom — Easter Brunch Buffet",cat:"Event",sub:"Food",date:"2026-04-05",dateLabel:"Sun Apr 5, 9:30am",venue:"Riverside Ballroom",loc:"Downtown Green Bay",addr:"1560 Main St, Green Bay, WI 54302",desc:"Easter brunch buffet at the historic Riverside Ballroom! Adults $29.99, children 4-11 $14.99, 3 & under free. Reservations: (920) 432-5518.",url:"https://riversideballroom.com/",setting:"indoor",walking:"lowWalking",goodFor:["seniors","family","couples"],highlight:true,free:false,recurring:false},
// === SENIOR FITNESS ===
{id:3596,name:"YMCA — SilverSneakers & Active Older Adults",cat:"Activity",sub:"Senior Fitness",date:"",dateLabel:"Year-round (6 branches)",venue:"Greater Green Bay YMCA (all branches)",loc:"Multiple",addr:"380 Broadview Dr, Green Bay, WI (Broadview) + 5 other branches",desc:"SilverSneakers, Renew Active, and Silver&Fit accepted for FREE gym membership! Pool, group classes, chair exercises, social coffee time. 65+ memberships from $46/mo if not insurance-covered. Branches: Broadview, East Side, Ferguson, West Side, Suamico, The Ridge (De Pere).",url:"https://www.greenbayymca.org/",setting:"indoor",walking:"someWalking",goodFor:["seniors"],highlight:true,free:false,recurring:true},
{id:3597,name:"Bellin Health Fitness — Senior Classes & SilverSneakers",cat:"Activity",sub:"Senior Fitness",date:"",dateLabel:"Year-round (classes change monthly)",venue:"Bellin Health Fitness Center",loc:"Downtown Green Bay",addr:"744 S Webster Ave, Green Bay, WI 54301",desc:"Full fitness center accepting SilverSneakers, Renew Active, Silver&Fit! Senior rate (62+): $44/mo. Pool, group classes, yoga, strength training. Monthly class schedule at bellin.clubautomation.com.",url:"https://bellin.org/wellness-education/bellin-health-fitness-center/",setting:"indoor",walking:"someWalking",goodFor:["seniors"],highlight:true,free:false,recurring:true},
];

let newStr = '';
for (const e of entries) {
  const descEsc = e.desc.replace(/"/g, '\\"');
  const nameEsc = e.name.replace(/"/g, '\\"');
  let s = ',\n{id:' + e.id + ',name:"' + nameEsc + '",cat:"' + e.cat + '",sub:"' + e.sub + '"';
  s += ',price:"' + (e.free ? 'free' : '$$') + '",priceNum:' + (e.free ? 0 : 2);
  s += ',date:"' + (e.date||'') + '"';
  if (e.dateTo) s += ',dateTo:"' + e.dateTo + '"';
  s += ',dateLabel:"' + e.dateLabel + '"';
  s += ',venue:"' + e.venue + '"';
  s += ',desc:"' + descEsc + '"';
  s += ',url:"' + (e.url || '') + '"';
  s += ',setting:"' + e.setting + '",walking:"' + e.walking + '"';
  s += ',goodFor:' + JSON.stringify(e.goodFor);
  s += ',highlight:' + e.highlight;
  s += ',cuisine:"' + (e.cuisine || '') + '",established:"' + (e.established || '') + '"';
  s += ',free:' + e.free + ',recurring:' + e.recurring + '}';
  newStr += s;
}

const lastEntry = 'free:true,recurring:true}';
const idx = html.lastIndexOf(lastEntry);
if (idx === -1) { console.log('ERROR: insertion point not found'); process.exit(1); }
html = html.substring(0, idx + lastEntry.length) + newStr + html.substring(idx + lastEntry.length);

fs.writeFileSync(path, html, 'utf8');
console.log('Added ' + entries.length + ' entries (IDs ' + Math.min(...entries.map(e=>e.id)) + '-' + Math.max(...entries.map(e=>e.id)) + ')');
console.log('File size: ' + Buffer.byteLength(html, 'utf8'));
