const fs = require('fs');
const path = 'C:/Users/shawn/Downloads/Green Bay Explorer.html';
let html = fs.readFileSync(path, 'utf8');

const entries = [
// === LAMBEAU FIELD ===
{id:3700,name:"Lambeau Field Stadium Tours",cat:"Attraction",sub:"Tours",date:"",dateLabel:"Daily (Mon-Sat 9-6, Sun 10-5)",venue:"Lambeau Field",loc:"Ashwaubenon",addr:"1265 Lombardi Ave, Green Bay, WI 54304",desc:"Tour Lambeau Field! Classic (1hr, field via tunnel $20 senior), Champions (1.5hr +club levels $28 senior), Legendary (2hr +press box $36 senior). Walk the same tunnel as the Packers! Combos with HOF available. Book 30 days ahead at packershofandtours.com.",url:"https://www.packershofandtours.com/",setting:"indoor",walking:"someWalking",goodFor:["seniors","family","couples"],highlight:true,free:false,recurring:true},
{id:3701,name:"Green Bay Packers Hall of Fame",cat:"Attraction",sub:"Museum",date:"",dateLabel:"Daily (Mon-Sat 9-6, Sun 10-5)",venue:"Lambeau Field",loc:"Ashwaubenon",addr:"1265 Lombardi Ave, Green Bay, WI 54304",desc:"15,000 sq ft of Packers history! Vince Lombardi's desk, 13 Below Ice Bowl Theater, championship trophies, free audio tour. Senior (62+) admission $17. Brown County residents get a discount (in-person with ID).",url:"https://www.packershofandtours.com/",setting:"indoor",walking:"someWalking",goodFor:["seniors","family","couples"],highlight:true,free:false,recurring:true},
{id:3702,name:"Luke Combs at Lambeau Field!",cat:"Event",sub:"Concert",date:"2026-05-15",dateTo:"2026-05-16",dateLabel:"Fri-Sat May 15-16",venue:"Lambeau Field",loc:"Ashwaubenon",addr:"1265 Lombardi Ave, Green Bay, WI 54304",desc:"MEGA concert event! Luke Combs plays TWO NIGHTS at Lambeau Field with Dierks Bentley, Ty Myers, Jake Worthington, Thelma & James. The biggest concert event of the summer!",url:"https://www.packers.com/lambeau-field/luke-combs",setting:"outdoor",walking:"someWalking",goodFor:["couples","family"],highlight:true,free:false,recurring:false},
{id:3703,name:"Titletown Night Market (Thursdays)",cat:"Event",sub:"Farmers Market",date:"2026-06-11",dateTo:"2026-08-27",dateLabel:"Thursdays 4:30-8:30pm, Jun 11 - Aug 27",venue:"Hy-Vee Plaza, Titletown",loc:"Ashwaubenon",addr:"1065 Lombardi Ave, Green Bay, WI 54304",desc:"FREE weekly summer night market at Titletown! Live bands every Thursday, local vendors, food trucks, drinks. 12 weeks of summer fun right next to Lambeau. Different band each week!",url:"https://www.titletown.com/events/titletown-night-market",setting:"outdoor",walking:"someWalking",goodFor:["seniors","couples","family"],highlight:true,free:true,recurring:true},
{id:3704,name:"Titletown Acoustic Lunch (Fridays)",cat:"Event",sub:"Free Concert Series",date:"2026-05-29",dateTo:"2026-09-25",dateLabel:"Fridays 11:30am-1:30pm, May 29 - Sep 25",venue:"46 Below outdoor patio, Titletown",loc:"Ashwaubenon",addr:"1065 Lombardi Ave, Green Bay, WI 54304",desc:"FREE acoustic music every Friday at lunchtime on the 46 Below patio at Titletown! Great midday outing. Food available from on-site restaurants.",url:"https://www.titletown.com/events/acoustic-lunch",setting:"outdoor",walking:"lowWalking",goodFor:["seniors","couples"],highlight:true,free:true,recurring:true},
// === BAY BEACH ===
{id:3710,name:"Bay Beach Amusement Park ($0.25 rides!)",cat:"Attraction",sub:"Amusement Park",date:"2026-05-02",dateTo:"2026-09-27",dateLabel:"May 2 - Sep 27 (hours vary by month)",venue:"Bay Beach Amusement Park",loc:"East Green Bay",addr:"1313 Bay Beach Rd, Green Bay, WI 54302",desc:"America's most affordable amusement park! Rides just $0.25 each (1-4 tickets per ride). Zippin Pippin roller coaster only $1.50! FREE parking, FREE admission. Free concerts, late nights, movies at dusk. Perfect for grandkid visits!",url:"https://greenbaywi.gov/baybeach",setting:"outdoor",walking:"someWalking",goodFor:["family","seniors"],highlight:true,free:true,recurring:true},
{id:3711,name:"Bay Beach Free Summer Concerts",cat:"Event",sub:"Free Concert Series",date:"2026-06-30",dateTo:"2026-08-11",dateLabel:"Tuesdays 6-8pm: Jun 30, Jul 14, Jul 28, Aug 11",venue:"Bay Beach Amusement Park",loc:"East Green Bay",addr:"1313 Bay Beach Rd, Green Bay, WI 54302",desc:"FREE concerts at Bay Beach on Tuesday evenings! Four summer dates with live music at the park. Combine with cheap rides for a great summer evening out.",url:"https://greenbaywi.gov/baybeach",setting:"outdoor",walking:"lowWalking",goodFor:["seniors","family","couples"],highlight:true,free:true,recurring:true},
// === HERITAGE HILL ===
{id:3715,name:"Heritage Hill State Historical Park",cat:"Attraction",sub:"History",date:"2026-05-01",dateTo:"2026-10-31",dateLabel:"May-Oct: Tue-Sat 9-4, Sun noon-4",venue:"Heritage Hill State Historical Park",loc:"Allouez",addr:"2640 S Webster Ave, Green Bay, WI 54301",desc:"Step back in time! 56-acre open-air museum with 25+ historic buildings spanning 300 years. Fort Howard, fur trade village, farm, chapel. Senior (65+) $12. ADA tram tours for groups of 10+ ($20/person, call ahead). Second Saturdays year-round with special themes.",url:"https://heritagehillgb.org/",setting:"outdoor",walking:"longWalking",goodFor:["seniors","family"],highlight:true,free:false,recurring:true},
{id:3716,name:"Heritage Hill — Paranormal Investigation Night",cat:"Event",sub:"History",date:"2026-04-24",dateLabel:"Fri Apr 24, 6:30-10:30pm",venue:"Heritage Hill State Historical Park",loc:"Allouez",addr:"2640 S Webster Ave, Green Bay, WI 54301",desc:"Investigate 5 haunted historic buildings with Windigo Paranormal! Check-in 6:30pm, investigation 7-10:30pm. $45 ($40.50 members). Ages 12+. Outdoor walking on hilly terrain.",url:"https://heritagehillgb.org/",setting:"outdoor",walking:"someWalking",goodFor:["couples"],highlight:false,free:false,recurring:false},
{id:3717,name:"Heritage Hill — Bourbon Experience Fundraiser",cat:"Event",sub:"Food & Drink",date:"2026-03-20",dateLabel:"Fri Mar 20, VIP 6pm, GA 7-9pm",venue:"Heritage Hill State Historical Park",loc:"Allouez",addr:"2640 S Webster Ave, Green Bay, WI 54301",desc:"Barrels, Boards & Bootleggers bourbon tasting! VIP speakeasy experience $100, General $70, Non-tasting $20. 21+. The Wine Cellar partnership. 10% member discount.",url:"https://heritagehillgb.org/",setting:"indoor",walking:"someWalking",goodFor:["couples","seniors"],highlight:true,free:false,recurring:false},
// === BOTANICAL GARDEN ===
{id:3720,name:"Green Bay Botanical Garden",cat:"Attraction",sub:"Garden",date:"",dateLabel:"Daily (summer 9am-8pm, winter 9-5)",venue:"Green Bay Botanical Garden",loc:"East Green Bay",addr:"2600 Larsen Rd, Green Bay, WI 54303",desc:"Beautiful 47-acre gardens! Senior (62+) $13 ($1 off online). BMO BOGO Wednesdays Jun-Aug. Grand Concert Series Fridays (Jun 6, Jul 11, Aug 8, Sep 5). Yoga, cooking classes, T.I.L.L. talks, kids camps. Dog Days in April!",url:"https://www.gbbg.org/",setting:"outdoor",walking:"someWalking",goodFor:["seniors","couples","family"],highlight:true,free:false,recurring:true},
// === NATIONAL RAILROAD MUSEUM ===
{id:3725,name:"National Railroad Museum (Senior $12!)",cat:"Attraction",sub:"Museum",date:"",dateLabel:"Tue-Sun (train rides May-Sep)",venue:"National Railroad Museum",loc:"Ashwaubenon",addr:"2285 S Broadway, Green Bay, WI 54304",desc:"See Big Boy, ride a real train! Senior (62+) $12. Train rides $6 May-Sep. FREE Tuesdays until 8pm! 2026 is the 70th anniversary: Kids FREE May 2, FREE trains Jul 11, $10 day Aug 22, Seniors FREE Sep 15! Mystery Express dinner theater, Tales on the Rails, PAW Patrol Jun 12-14.",url:"https://nationalrrmuseum.org/",setting:"indoor",walking:"someWalking",goodFor:["seniors","family"],highlight:true,free:false,recurring:true},
{id:3726,name:"Railroad Museum — Seniors FREE Day (70th Anniversary)",cat:"Event",sub:"Senior Social",date:"2026-09-15",dateLabel:"Tue Sep 15, 9am-8pm",venue:"National Railroad Museum",loc:"Ashwaubenon",addr:"2285 S Broadway, Green Bay, WI 54304",desc:"Seniors 62+ get FREE admission for the museum's 70th anniversary! Behind-the-scenes tours at 5pm and 6:30pm (extra). A wonderful day to explore!",url:"https://nationalrrmuseum.org/70th/",setting:"indoor",walking:"someWalking",goodFor:["seniors"],highlight:true,free:true,recurring:false},
{id:3727,name:"Railroad Museum — PAW Patrol Paw-Palooza",cat:"Event",sub:"Family",date:"2026-06-12",dateTo:"2026-06-14",dateLabel:"Fri-Sun Jun 12-14, 9am-5pm",venue:"National Railroad Museum",loc:"Ashwaubenon",addr:"2285 S Broadway, Green Bay, WI 54304",desc:"PAW Patrol characters, train rides, crafts, bounce houses! $22 ages 2+. Perfect for grandkids!",url:"https://nationalrrmuseum.org/",setting:"outdoor",walking:"someWalking",goodFor:["family"],highlight:true,free:false,recurring:false},
// === CHILDREN'S MUSEUM ===
{id:3730,name:"Children's Museum of Green Bay (Senior $7)",cat:"Attraction",sub:"Museum",date:"",dateLabel:"Tue-Sat 10-5, Sun noon-5",venue:"Children's Museum of Green Bay",loc:"East Green Bay",addr:"1230 Bay Beach Rd, Green Bay, WI 54302",desc:"Next to Bay Beach! Senior (62+) $7. Grandparent Membership $90/yr (2 grandparents + 6 grandkids unlimited). Free Sensory Friendly Night 4th Thursday 3-5pm. Outdoor Discovery Center with butterfly house and gardens.",url:"https://gbchildrensmuseum.org/",setting:"indoor",walking:"someWalking",goodFor:["family","seniors"],highlight:true,free:false,recurring:true},
// === WEIDNER CENTER ===
{id:3735,name:"Weidner Center — Mrs. Doubtfire (Broadway)",cat:"Event",sub:"Theater",date:"2026-03-23",dateLabel:"Mon Mar 23, 7:30pm",venue:"Weidner Center for the Performing Arts",loc:"Allouez / UWGB",addr:"2420 Nicolet Dr, Green Bay, WI 54311",desc:"Broadway touring production of Mrs. Doubtfire at the Weidner! The beloved Robin Williams movie comes to life on stage.",url:"https://www.weidnercenter.com/",setting:"indoor",walking:"lowWalking",goodFor:["seniors","family","couples"],highlight:true,free:false,recurring:false},
{id:3736,name:"Weidner — Harry Potter in Concert (with orchestra!)",cat:"Event",sub:"Concert",date:"2026-04-18",dateLabel:"Sat Apr 18, 7:30pm",venue:"Weidner Center",loc:"Allouez / UWGB",addr:"2420 Nicolet Dr, Green Bay, WI 54311",desc:"Watch Prisoner of Azkaban on the big screen while the Weidner Philharmonic plays John Williams' score LIVE! With Dudley Birder Chorale. A magical experience.",url:"https://www.weidnercenter.com/",setting:"indoor",walking:"lowWalking",goodFor:["seniors","family","couples"],highlight:true,free:false,recurring:false},
{id:3737,name:"Green Bay Jazz Fest — Pay What You May!",cat:"Event",sub:"Concert",date:"2026-04-11",dateLabel:"Sat Apr 11, 7:30pm",venue:"Weidner Center",loc:"Allouez / UWGB",addr:"2420 Nicolet Dr, Green Bay, WI 54311",desc:"PAY WHAT YOU MAY jazz concert! Green Bay Jazz Orchestra with nationally acclaimed guests. Choose your own price ($5-$200). One of the best musical values in town.",url:"https://www.weidnercenter.com/events-and-tickets/green-bay-jazz-fest/",setting:"indoor",walking:"lowWalking",goodFor:["seniors","couples"],highlight:true,free:false,recurring:false},
{id:3738,name:"Weidner — PAW Patrol Live! A Mighty Adventure",cat:"Event",sub:"Family",date:"2026-04-21",dateTo:"2026-04-22",dateLabel:"Tue-Wed Apr 21-22, 6pm",venue:"Weidner Center",loc:"Allouez / UWGB",addr:"2420 Nicolet Dr, Green Bay, WI 54311",desc:"PAW Patrol Live on stage! Perfect for young grandkids. Two evenings of adventure with Chase, Marshall, Skye and the whole crew.",url:"https://www.weidnercenter.com/",setting:"indoor",walking:"lowWalking",goodFor:["family"],highlight:true,free:false,recurring:false},
{id:3739,name:"Beethoven's 9th — Weidner Philharmonic + Chorus",cat:"Event",sub:"Concert",date:"2026-05-02",dateLabel:"Sat May 2, 7pm",venue:"Weidner Center",loc:"Allouez / UWGB",addr:"2420 Nicolet Dr, Green Bay, WI 54311",desc:"The mighty Ode to Joy! Weidner Philharmonic with Dudley Birder Chorale and UW-Green Bay Choirs perform Beethoven's 9th Symphony. A thrilling season finale.",url:"https://www.weidnercenter.com/",setting:"indoor",walking:"lowWalking",goodFor:["seniors","couples"],highlight:true,free:false,recurring:false},
// === LET ME BE FRANK ===
{id:3740,name:"Let Me Be Frank: ShopKo, Say Hello to a Goodbye",cat:"Event",sub:"Comedy / Theater",date:"2026-04-09",dateTo:"2026-04-26",dateLabel:"Apr 9-26 (Thu-Sat 7:30pm, matinees available)",venue:"Meyer Theatre",loc:"Downtown Green Bay",addr:"117 S Washington St, Green Bay, WI 54301",desc:"Green Bay's beloved comedy troupe! A hilarious musical about the rise and fall of ShopKo. $43 all-in. 14 performances over 3 weeks. Matinees on select Thursdays and Sundays. Flex packs: 5 shows $185.",url:"https://letmebefranks.com/",setting:"indoor",walking:"lowWalking",goodFor:["seniors","couples"],highlight:true,free:false,recurring:false},
{id:3741,name:"Let Me Be Frank: The Dingaling Brothers Circus",cat:"Event",sub:"Comedy / Theater",date:"2026-07-23",dateTo:"2026-08-09",dateLabel:"Jul 23 - Aug 9 (Thu-Sat 7:30pm, matinees)",venue:"Meyer Theatre",loc:"Downtown Green Bay",addr:"117 S Washington St, Green Bay, WI 54301",desc:"A circus-themed comedy musical from Green Bay's funniest troupe! 12 performances with 60s music. $43 all-in. A perfect summer show.",url:"https://letmebefranks.com/",setting:"indoor",walking:"lowWalking",goodFor:["seniors","couples","family"],highlight:true,free:false,recurring:false},
// === MEYER THEATRE ===
{id:3745,name:"Meyer Theatre — Glenn Miller Orchestra",cat:"Event",sub:"Concert",date:"2026-04-29",dateLabel:"Wed Apr 29, 7:30pm",venue:"Meyer Theatre",loc:"Downtown Green Bay",addr:"117 S Washington St, Green Bay, WI 54301",desc:"Big band swing at the Meyer! The legendary Glenn Miller Orchestra. Moonlight Serenade, In the Mood, A String of Pearls. From $44.50.",url:"https://meyertheatre.org/",setting:"indoor",walking:"lowWalking",goodFor:["seniors","couples"],highlight:true,free:false,recurring:false},
{id:3746,name:"Meyer Theatre — Beatles Celebration (Revolver at 60)",cat:"Event",sub:"Concert",date:"2026-05-15",dateLabel:"Fri May 15, 7pm",venue:"Meyer Theatre",loc:"Downtown Green Bay",addr:"117 S Washington St, Green Bay, WI 54301",desc:"A Beatles Celebration with Fox Valley Symphony string quartet! Celebrating 60 years of the Revolver album. From $24.50. Presented by 91.1 The Avenue.",url:"https://meyertheatre.org/",setting:"indoor",walking:"lowWalking",goodFor:["seniors","couples"],highlight:true,free:false,recurring:false},
{id:3747,name:"Meyer Theatre — The Lovin' Spoonful",cat:"Event",sub:"Concert",date:"2026-05-28",dateLabel:"Thu May 28, 7pm",venue:"Meyer Theatre",loc:"Downtown Green Bay",addr:"117 S Washington St, Green Bay, WI 54301",desc:"Do You Believe in Magic? Summer in the City! The Lovin' Spoonful bring 1960s pop-rock to the Meyer. From $53.25.",url:"https://meyertheatre.org/",setting:"indoor",walking:"lowWalking",goodFor:["seniors","couples"],highlight:true,free:false,recurring:false},
{id:3748,name:"Meyer Theatre — BoDeans (SOLD OUT)",cat:"Event",sub:"Concert",date:"2026-06-05",dateLabel:"Fri Jun 5, 7:30pm",venue:"Meyer Theatre",loc:"Downtown Green Bay",addr:"117 S Washington St, Green Bay, WI 54301",desc:"Wisconsin's own BoDeans celebrate 40 years! Fadeaway, Good Things, Closer to Free. SOLD OUT but check for returns.",url:"https://meyertheatre.org/",setting:"indoor",walking:"lowWalking",goodFor:["seniors","couples"],highlight:true,free:false,recurring:false},
{id:3749,name:"Meyer Theatre — Jay and The Americans",cat:"Event",sub:"Concert",date:"2026-07-08",dateLabel:"Wed Jul 8, 7pm",venue:"Meyer Theatre",loc:"Downtown Green Bay",addr:"117 S Washington St, Green Bay, WI 54301",desc:"Come A Little Bit Closer, This Magic Moment, Cara Mia! Classic 60s pop at the Meyer. From $58.",url:"https://meyertheatre.org/",setting:"indoor",walking:"lowWalking",goodFor:["seniors","couples"],highlight:true,free:false,recurring:false},
{id:3750,name:"Meyer Theatre — Get The Led Out (Zeppelin Tribute)",cat:"Event",sub:"Concert",date:"2026-07-15",dateLabel:"Wed Jul 15, 7:30pm",venue:"Meyer Theatre",loc:"Downtown Green Bay",addr:"117 S Washington St, Green Bay, WI 54301",desc:"The ultimate Led Zeppelin experience! Full live renditions of classic albums. From $47.",url:"https://meyertheatre.org/",setting:"indoor",walking:"lowWalking",goodFor:["couples"],highlight:false,free:false,recurring:false},
// === RESCH CENTER ===
{id:3755,name:"Journey at the Resch Center!",cat:"Event",sub:"Concert",date:"2026-06-21",dateLabel:"Sat Jun 21, 7:30pm",venue:"Resch Center",loc:"Ashwaubenon",addr:"820 Armed Forces Dr, Green Bay, WI 54304",desc:"Don't Stop Believin'! Journey's Final Frontier Tour comes to Green Bay. From $63. Doors 6pm.",url:"https://www.reschcomplex.com/",setting:"indoor",walking:"lowWalking",goodFor:["seniors","couples"],highlight:true,free:false,recurring:false},
{id:3756,name:"Shinedown at the Resch Center",cat:"Event",sub:"Concert",date:"2026-05-13",dateLabel:"Wed May 13, 7pm",venue:"Resch Center",loc:"Ashwaubenon",addr:"820 Armed Forces Dr, Green Bay, WI 54304",desc:"Dance, Kid, Dance Act II tour! With Coheed & Cambria and Black Stone Cherry. From $61. Doors 5:30pm.",url:"https://www.reschcomplex.com/",setting:"indoor",walking:"lowWalking",goodFor:["couples"],highlight:false,free:false,recurring:false},
{id:3757,name:"Monster Jam at the Resch Center",cat:"Event",sub:"Family",date:"2026-03-27",dateTo:"2026-03-29",dateLabel:"Fri-Sun Mar 27-29 (4 shows)",venue:"Resch Center",loc:"Ashwaubenon",addr:"820 Armed Forces Dr, Green Bay, WI 54304",desc:"MONSTER JAM Freestyle Mania! Huge monster trucks doing flips and crushes. Fri 7pm, Sat noon & 6pm, Sun noon. Pit Party available. Great for grandkids!",url:"https://www.reschcomplex.com/",setting:"indoor",walking:"lowWalking",goodFor:["family"],highlight:true,free:false,recurring:false},
{id:3758,name:"Beja Shrine Circus at the Resch",cat:"Event",sub:"Family",date:"2026-05-02",dateTo:"2026-05-03",dateLabel:"Sat May 2 (11am/3pm/7pm), Sun May 3 (1pm/5pm)",venue:"Resch Center",loc:"Ashwaubenon",addr:"820 Armed Forces Dr, Green Bay, WI 54304",desc:"Glow 2.0 Circus Spectacular! Acrobats, clowns, animals, dazzling lights. Five performances over two days. Great for grandkids!",url:"https://www.reschcomplex.com/",setting:"indoor",walking:"lowWalking",goodFor:["family","seniors"],highlight:true,free:false,recurring:false},
// === DOOR COUNTY THEATER ===
{id:3760,name:"Northern Sky Theater — Outdoor Musicals (Door County)",cat:"Attraction",sub:"Day Trip",date:"2026-06-24",dateTo:"2026-08-29",dateLabel:"Nightly 7:30pm (3 shows in rotation), Jun-Aug",venue:"Peninsula State Park Amphitheater",loc:"Door County (Day Trip)",addr:"10169 Shore Rd, Fish Creek, WI 54212",desc:"World-class outdoor theater under the stars! Three original musicals in rotation all summer. Standard $29, Premium $37. Bring a blanket, buy popcorn. Wisconsin's most beloved summer tradition. ~1.25 hrs from GB.",url:"https://www.northernskytheater.com/",setting:"outdoor",walking:"lowWalking",goodFor:["seniors","couples","family"],highlight:true,free:false,recurring:true},
{id:3761,name:"Peninsula Players Theatre (Door County)",cat:"Attraction",sub:"Day Trip",date:"2026-06-16",dateTo:"2026-10-18",dateLabel:"Tue-Sun evenings, Jun-Oct (5 plays in rotation)",venue:"Peninsula Players Theatre",loc:"Door County (Day Trip)",addr:"4351 Peninsula Players Rd, Fish Creek, WI 54212",desc:"America's oldest professional resident summer theater! Five shows: Baggage, The Mousetrap, Ring of Fire (Johnny Cash music!), Moon Over Buffalo, plus more. $54-$59. Beautiful garden-party atmosphere. ~1.25 hrs from GB.",url:"https://www.peninsulaplayers.com/",setting:"outdoor",walking:"lowWalking",goodFor:["seniors","couples"],highlight:true,free:false,recurring:true},
// === DOOR COUNTY FESTIVALS ===
{id:3763,name:"Ephraim Fyr Bal Festival (Door County)",cat:"Event",sub:"Festival",date:"2026-06-20",dateLabel:"Sat Jun 20 (bonfire at dusk)",venue:"Eagle Harbor waterfront, Ephraim",loc:"Door County (Day Trip)",addr:"Ephraim, WI 54211",desc:"Scandinavian midsummer celebration! Crafts, music, food all day, then a huge harbor bonfire and fireworks at dusk. FREE admission. One of Door County's most magical events. 61st annual!",url:"https://ephraim-doorcounty.com/events/fyr-bal-festival/",setting:"outdoor",walking:"someWalking",goodFor:["seniors","couples","family"],highlight:true,free:true,recurring:false},
{id:3764,name:"Door County Beer Festival",cat:"Event",sub:"Festival",date:"2026-06-20",dateLabel:"Sat Jun 20, noon-4pm",venue:"About Thyme Farm, Baileys Harbor",loc:"Door County (Day Trip)",addr:"Baileys Harbor, WI 54202",desc:"Craft beer festival in beautiful Door County! GA $50-55, Early Access $70-75, DD $15. 21+. Shuttle from county lots. Tasting glass + samples included.",url:"https://doorcountybeerfestival.com/",setting:"outdoor",walking:"someWalking",goodFor:["couples"],highlight:false,free:false,recurring:false},
{id:3765,name:"Door County Wine Fest (10th Anniversary!)",cat:"Event",sub:"Festival",date:"2026-06-27",dateLabel:"Sat Jun 27, noon-4pm",venue:"About Thyme Farm, Baileys Harbor",loc:"Door County (Day Trip)",addr:"Baileys Harbor, WI 54202",desc:"10th anniversary wine festival! GA $65-75, VIP $85-95. Door County wines, food, beautiful farm setting. Shuttle from lots. 21+.",url:"https://www.doorcountywinefest.com/",setting:"outdoor",walking:"someWalking",goodFor:["seniors","couples"],highlight:true,free:false,recurring:false},
{id:3766,name:"Jacksonport Cherry Fest (Door County)",cat:"Event",sub:"Festival",date:"2026-08-01",dateLabel:"Sat Aug 1, 9am-4pm",venue:"Lakeside Park, Jacksonport",loc:"Door County (Day Trip)",addr:"Jacksonport, WI 54235",desc:"Annual cherry festival at the beach! Car show, cherry treats, crafts, music. A sweet Door County tradition on Lake Michigan.",url:"https://jacksonporthistoricalsociety.org/cherry-fest/",setting:"outdoor",walking:"someWalking",goodFor:["seniors","family","couples"],highlight:true,free:true,recurring:false},
// === FREE CONCERTS ===
{id:3770,name:"Levitt AMP Free Sunday Concerts (Leicht Park)",cat:"Event",sub:"Free Concert Series",date:"2026-05-31",dateTo:"2026-08-09",dateLabel:"Sundays 4-6:30pm, May 31 - Aug 9",venue:"Leicht Memorial Park (Fox River)",loc:"Downtown Green Bay",addr:"128 Dousman St, Green Bay, WI 54303",desc:"FREE national and regional music every Sunday at the Fox River waterfront! 11 weeks of diverse live music. Bring a lawn chair. One of downtown Green Bay's best summer traditions.",url:"https://downtowngreenbay.com/",setting:"outdoor",walking:"lowWalking",goodFor:["seniors","couples","family"],highlight:true,free:true,recurring:true},
{id:3771,name:"Fridays on the Fox (CityDeck)",cat:"Event",sub:"Free Concert Series",date:"2026-06-12",dateTo:"2026-07-31",dateLabel:"Fridays 6-9pm: Jun 12-26, Jul 10-31",venue:"CityDeck (Fox River)",loc:"Downtown Green Bay",addr:"CityDeck, Green Bay, WI 54301",desc:"FREE Friday evening music on the CityDeck! Beautiful river setting, Hagemeister Park serves food and drinks from 5pm. A wonderful summer evening stroll along the Fox.",url:"https://downtowngreenbay.com/",setting:"outdoor",walking:"lowWalking",goodFor:["seniors","couples"],highlight:true,free:true,recurring:true},
{id:3772,name:"Fire Over the Fox — July 4th Celebration",cat:"Event",sub:"Festival",date:"2026-07-04",dateLabel:"Sat Jul 4, 3-10:30pm (fireworks at dusk)",venue:"Downtown Green Bay waterfront",loc:"Downtown Green Bay",addr:"128 Dousman St, Green Bay, WI 54303",desc:"Green Bay's BIG July 4th celebration! Multiple stages, live music, food, kids activities. FIREWORKS at dusk over the Fox River. Free admission. One of the best 4th of July events in Wisconsin!",url:"https://downtowngreenbay.com/do/fire-over-the-fox",setting:"outdoor",walking:"someWalking",goodFor:["seniors","family","couples"],highlight:true,free:true,recurring:false},
// === CIVIC SYMPHONY ===
{id:3775,name:"Civic Symphony — Orchestra at the Airport (FREE!)",cat:"Event",sub:"Concert",date:"2026-06-27",dateLabel:"Sat Jun 27, 2pm (doors noon)",venue:"Jet Air Group hangar, Austin Straubel",loc:"Ashwaubenon",addr:"1911 Airport Dr, Green Bay, WI 54313",desc:"FREE patriotic pops concert in an airplane hangar! Civic Symphony of Green Bay performs Wings of Freedom: America250. Optional $5 donation for reserved chair. A unique musical experience!",url:"https://gbcivic.org/",setting:"indoor",walking:"lowWalking",goodFor:["seniors","couples","family"],highlight:true,free:true,recurring:false},
{id:3776,name:"Civic Symphony — Harmonies for Hope",cat:"Event",sub:"Concert",date:"2026-05-17",dateLabel:"Sat May 17, 2pm",venue:"Weidner Center",loc:"Allouez / UWGB",addr:"2420 Nicolet Dr, Green Bay, WI 54311",desc:"Copland, Shostakovich, Williams! Fanfare for the Common Man, Schindler's List, and more. Senior $33, Adult $39. With Dudley Birder Chorale.",url:"https://gbcivic.org/",setting:"indoor",walking:"lowWalking",goodFor:["seniors","couples"],highlight:true,free:false,recurring:false},
// === GREEN BAY JAZZ ORCHESTRA ===
{id:3778,name:"Green Bay Jazz Orchestra — Free Monthly Shows",cat:"Event",sub:"Concert",date:"2026-03-22",dateTo:"2026-06-11",dateLabel:"2nd Thursdays 6pm: Apr 9, May 14, Jun 11",venue:"The Tarlton Theatre",loc:"Green Bay",addr:"The Tarlton Theatre, Green Bay, WI",desc:"FREE jazz concerts! Green Bay Jazz Orchestra plays the second Thursday monthly at the Tarlton Theatre. Doors 5pm, music 6-8pm. A sophisticated evening out at no cost.",url:"https://greenbayjazzorchestra.org/",setting:"indoor",walking:"lowWalking",goodFor:["seniors","couples"],highlight:true,free:true,recurring:true},
// === CHEESE FEST ===
{id:3780,name:"Great Wisconsin Cheese Festival (Little Chute!)",cat:"Event",sub:"Festival",date:"2026-06-05",dateTo:"2026-06-07",dateLabel:"Fri-Sun Jun 5-7",venue:"Doyle Park, Little Chute",loc:"Little Chute (Day Trip)",addr:"100 Van Buren St, Little Chute, WI 54140",desc:"Wisconsin's BIGGEST cheese festival! Free cheese samples, live bands, carnival rides, Cheddar Chase fun run, Big Cheese Parade (Sat 10:30am). Sunday is FREE admission. Shuttles from LC High School. ~25 min from Green Bay.",url:"https://cheesefest.org/",setting:"outdoor",walking:"someWalking",goodFor:["seniors","family","couples"],highlight:true,free:false,recurring:false},
// === COMMUNITY FESTIVALS ===
{id:3785,name:"Ashwaubenon Blast (Village Festival)",cat:"Event",sub:"Festival",date:"2026-08-08",dateLabel:"Sat Aug 8",venue:"Ashwaubomay Park",loc:"Ashwaubenon",addr:"2881 S Broadway, Ashwaubenon, WI 54304",desc:"Ashwaubenon's big summer festival! Carnival, live music, car show, vendors, free swim at Ashwaubomay Lake. Always the 2nd Saturday of August.",url:"https://www.ashwaubenonalumni.org/ashwaubenon-blast.html",setting:"outdoor",walking:"someWalking",goodFor:["family","seniors"],highlight:true,free:false,recurring:false},
{id:3786,name:"Howard Flannel Fest",cat:"Event",sub:"Festival",date:"2026-07-10",dateTo:"2026-07-11",dateLabel:"Fri 4-8pm, Sat 10am-5pm",venue:"Duck Creek Quarry, Howard",loc:"Howard",addr:"2183 Glendale Ave, Green Bay, WI 54303",desc:"Log rolling, chainsaw carving, live music, food trucks! A unique lumberjack-themed festival at the quarry. Fun for all ages.",url:"https://www.villageofhoward.com/",setting:"outdoor",walking:"someWalking",goodFor:["family","seniors","couples"],highlight:true,free:false,recurring:false},
{id:3787,name:"Howard Rock the Commons Concerts (Summer)",cat:"Event",sub:"Free Concert Series",date:"2026-06-13",dateTo:"2026-08-29",dateLabel:"Select Saturdays 5-6pm, Jun-Aug",venue:"Howard Commons, 550 Commons Pl",loc:"Howard",addr:"550 Commons Pl, Howard, WI 54313",desc:"Free summer concerts at Howard Commons! Six dates: Jun 13, 20, Jul 18, Aug 8, 15, 29. Different bands each date. Plus weekly Market & Music on Mondays!",url:"https://www.villageofhoward.com/",setting:"outdoor",walking:"lowWalking",goodFor:["seniors","couples","family"],highlight:true,free:true,recurring:true},
// === GREEN BAY BLIZZARD ===
{id:3790,name:"Green Bay Blizzard Indoor Football (Home Games)",cat:"Event",sub:"Sports",date:"2026-03-21",dateTo:"2026-06-27",dateLabel:"Select Sat/Fri Mar-Jun (see schedule)",venue:"Resch Center",loc:"Ashwaubenon",addr:"820 Armed Forces Dr, Green Bay, WI 54304",desc:"Indoor football action! Green Bay Blizzard play at the Resch Center. Fun theme nights: Youth Jersey, Star Wars, Kids Night, Dairy Night, Military Appreciation. Fast-paced indoor game, easy to follow!",url:"https://greenbayblizzard.com/",setting:"indoor",walking:"lowWalking",goodFor:["family","seniors","couples"],highlight:false,free:false,recurring:true},
// === AUTOMOBILE GALLERY ===
{id:3792,name:"Automobile Gallery — Festa Italiana",cat:"Event",sub:"Festival",date:"2026-05-16",dateLabel:"Sat May 16, 2-6pm",venue:"The Automobile Gallery",loc:"Downtown Green Bay",addr:"400 S Adams St, Green Bay, WI 54301",desc:"Italian car collection, BelGioioso cheese, wood-fired pizza, gelato, Italian music! $15. One afternoon celebrating Italian automotive art and food.",url:"https://theautomobilegallery.org/",setting:"indoor",walking:"lowWalking",goodFor:["seniors","couples"],highlight:true,free:false,recurring:false},
// === SATURDAY FARMERS MARKET ===
{id:3795,name:"Downtown Green Bay Saturday Farmers Market",cat:"Event",sub:"Farmers Market",date:"2026-05-23",dateTo:"2026-10-31",dateLabel:"Saturdays 7am-noon, May 23 - Oct 31",venue:"S Washington & Doty Streets",loc:"Downtown Green Bay",addr:"S Washington St & Doty St, Green Bay, WI 54301",desc:"100+ vendors! Fresh produce, baked goods, cheese, meat, flowers, crafts. Live music 9-11:30am. Family Days Jun 13, Jul 11, Aug 8. Yoga 7:30am biweekly. Green Bay's biggest and best market!",url:"https://downtowngreenbay.com/",setting:"outdoor",walking:"someWalking",goodFor:["seniors","family","couples"],highlight:true,free:true,recurring:true},
// === igNIGHT MARKET ===
{id:3796,name:"igNight Market — Downtown Night Festival",cat:"Event",sub:"Festival",date:"2026-08-15",dateLabel:"Sat Aug 15, 5-10pm",venue:"Broadway District, Downtown Green Bay",loc:"Downtown Green Bay",addr:"Broadway District, Green Bay, WI 54303",desc:"FREE evening night market with live original music, artisan vendors, demonstrations, games, food and drink! A fun, lively summer Saturday evening in the Broadway District.",url:"https://downtowngreenbay.com/",setting:"outdoor",walking:"someWalking",goodFor:["seniors","couples"],highlight:true,free:true,recurring:false},
// === WINERIES ===
{id:3798,name:"Captain's Walk Winery (Downtown!)",cat:"Activity",sub:"Winery",date:"",dateLabel:"Wed-Sat open (check hours)",venue:"Captain's Walk Winery",loc:"Downtown Green Bay",addr:"345 S Adams St, Green Bay, WI 54301",desc:"Urban winery in a charming historic house! Wine flights, hard cider, cocktails. Multiple cozy rooms and a porch. Live music events (check Facebook). Great midweek or Sunday afternoon outing.",url:"https://captainswalkwinery.com/",setting:"indoor",walking:"lowWalking",goodFor:["seniors","couples"],highlight:true,free:false,recurring:true},
{id:3799,name:"von Stiehl Winery (Algoma Day Trip)",cat:"Activity",sub:"Winery",date:"",dateLabel:"Daily year-round (10-4 winter, 10-5 summer)",venue:"von Stiehl Winery",loc:"Algoma (Day Trip)",addr:"115 Navarino St, Algoma, WI 54201",desc:"Wisconsin's oldest licensed winery! Wine tasting, cellar tours ($10, Fri-Sun 11am & 1pm), plus a Cider & Spirits Bar next door. Summer Concert Series Saturdays Jul 4 - Sep 5. Beautiful harbor views. ~40 min from GB.",url:"https://www.vonstiehl.com/",setting:"indoor",walking:"lowWalking",goodFor:["seniors","couples"],highlight:true,free:false,recurring:true},
];

let newStr = '';
for (const e of entries) {
  const descEsc = e.desc.replace(/"/g, '\\"');
  const nameEsc = e.name.replace(/"/g, '\\"');
  let s = ',\n{id:' + e.id + ',name:"' + nameEsc + '",cat:"' + e.cat + '",sub:"' + e.sub + '"';
  s += ',price:"' + (e.free ? 'free' : '$$') + '",priceNum:' + (e.free ? 0 : 2);
  s += ',date:"' + (e.date||'') + '"';
  if (e.dateTo) s += ',dateTo:"' + e.dateTo + '"';
  s += ',dateLabel:"' + e.dateLabel + '"';
  s += ',venue:"' + e.venue + '"';
  s += ',desc:"' + descEsc + '"';
  s += ',url:"' + (e.url || '') + '"';
  s += ',setting:"' + e.setting + '",walking:"' + e.walking + '"';
  s += ',goodFor:' + JSON.stringify(e.goodFor);
  s += ',highlight:' + e.highlight;
  s += ',cuisine:"",established:""';
  s += ',free:' + e.free + ',recurring:' + (e.recurring || false) + '}';
  newStr += s;
}

const lastEntry = 'free:false,recurring:true}';
const idx = html.lastIndexOf(lastEntry);
if (idx === -1) { console.log('ERROR: insertion point not found'); process.exit(1); }
html = html.substring(0, idx + lastEntry.length) + newStr + html.substring(idx + lastEntry.length);

fs.writeFileSync(path, html, 'utf8');
console.log('Added ' + entries.length + ' entries (IDs ' + Math.min(...entries.map(e=>e.id)) + '-' + Math.max(...entries.map(e=>e.id)) + ')');
console.log('File size: ' + Buffer.byteLength(html, 'utf8'));
