const fs = require('fs');
const path = 'C:/Users/shawn/Downloads/Green Bay Explorer.html';
let html = fs.readFileSync(path, 'utf8');

const entries = [
// === GAMBLERS HOCKEY ===
{id:4600,name:"Green Bay Gamblers Hockey (USHL!) at Resch Center",cat:"Event",sub:"Sports",date:"2026-01-24",dateTo:"2026-04-04",dateLabel:"Home games Jan-Apr 2026 (6:05pm, from $10)",venue:"Resch Center",loc:"Ashwaubenon",addr:"820 Armed Forces Dr, Green Bay, WI 54304",desc:"USHL junior hockey! Home games at Resch Center, faceoff 6:05pm. Season tix from $10/game. Theme nights: Teddy Bear Toss (Jan 31), Family Night (Apr 4). Groups 15+ save $3/ticket!",url:"https://gamblershockey.com/",setting:"indoor",walking:"lowWalking",goodFor:["seniors","family"],highlight:true,free:false,recurring:false},
// === BLIZZARD INDOOR FOOTBALL ===
{id:4601,name:"Green Bay Blizzard Indoor Football (IFL!) 2026",cat:"Event",sub:"Sports",date:"2026-03-16",dateTo:"2026-06-27",dateLabel:"Home: Mar 16,21; Apr 18,24; May 8,29; Jun 12,27",venue:"Resch Center",loc:"Ashwaubenon",addr:"820 Armed Forces Dr, Green Bay, WI 54304",desc:"IFL indoor football at Resch Center! 8 home games: Faith & Family (Mar 16), Youth Jersey (Mar 21), Frozen Phoenix (Apr 18), Kids Night (Apr 24), Star Wars (May 8), Dairy Night (May 29), Backyard (Jun 12), Military Appreciation (Jun 27).",url:"https://www.greenbayblizzard.com/",setting:"indoor",walking:"lowWalking",goodFor:["seniors","family"],highlight:true,free:false,recurring:false},
// === PACKERS 2026 ===
{id:4603,name:"Luke Combs at Lambeau Field!",cat:"Event",sub:"Concert",date:"2026-05-16",dateLabel:"Sat May 16 (My Kinda Saturday Night Tour!)",venue:"Lambeau Field",loc:"Ashwaubenon",addr:"1265 Lombardi Ave, Green Bay, WI 54304",desc:"LUKE COMBS at LAMBEAU FIELD! My Kinda Saturday Night Tour, Saturday May 16, 2026. Massive outdoor stadium concert. Get tickets early!",url:"https://www.packers.com/",setting:"outdoor",walking:"someWalking",goodFor:["seniors","couples"],highlight:true,free:false,recurring:false},
{id:4604,name:"Packers Tailgate Tour (Apr 14-18!)",cat:"Event",sub:"Packers",date:"2026-04-14",dateTo:"2026-04-18",dateLabel:"Apr 14-18 (WI + Dubuque, ends in GB Apr 18)",venue:"Multiple stops ending in Green Bay",loc:"Wisconsin tour",addr:"Green Bay, WI",desc:"Packers players and alumni on tour! April 14-18 across Wisconsin + Dubuque, IA. Ends in Green Bay April 18. Limited tickets available.",url:"https://www.packers.com/",setting:"outdoor",walking:"someWalking",goodFor:["seniors","family"],highlight:true,free:false,recurring:false},
// === TRIVIA NIGHTS ===
{id:4606,name:"Trivia at Glass Nickel Pizza (Mondays 7pm!)",cat:"Activity",sub:"Trivia",date:"",dateLabel:"Mondays 7pm (America's Pub Quiz, FREE!)",venue:"Glass Nickel Pizza",loc:"Downtown Green Bay",addr:"416 Dousman St, Green Bay, WI 54303",desc:"Free weekly trivia! America's Pub Quiz every Monday at 7pm. Team quiz with gift card prizes. Great pizza + beer while you play.",url:"",setting:"indoor",walking:"lowWalking",goodFor:["seniors","couples"],highlight:true,free:true,recurring:true},
{id:4607,name:"Geeks Who Drink Trivia at Dave & Buster's (Tue!)",cat:"Activity",sub:"Trivia",date:"",dateLabel:"Tuesdays 7:30pm (FREE entry!)",venue:"Dave & Buster's",loc:"Ashwaubenon",addr:"202 Bay Park Square, Green Bay, WI 54304",desc:"Geeks Who Drink pub quiz every Tuesday at 7:30pm! Free entry. Special themed quiz last Tuesday of each month. Arcade games + food.",url:"https://www.geekswhodrink.com/",setting:"indoor",walking:"lowWalking",goodFor:["seniors","couples"],highlight:true,free:true,recurring:true},
{id:4608,name:"Noble Roots Trivia (Wednesdays 6:30pm!)",cat:"Activity",sub:"Trivia",date:"",dateLabel:"Wednesdays 6:30pm",venue:"Noble Roots Brewing",loc:"East Green Bay",addr:"2790 University Ave, Green Bay, WI 54311",desc:"Weekly team trivia at Noble Roots every Wednesday at 6:30pm! Dog-friendly patio, great craft beer, food trucks. Fun evening out.",url:"https://www.noblerootsbrewing.com/",setting:"indoor",walking:"lowWalking",goodFor:["seniors","couples"],highlight:true,free:true,recurring:true},
{id:4609,name:"Titletown Themed Trivia (Summer Thursdays, FREE!)",cat:"Event",sub:"Trivia",date:"2026-06-11",dateTo:"2026-08-27",dateLabel:"Summer Thursdays 6-7:30pm at Ariens Hill (FREE!)",venue:"Titletown (Top of Ariens Hill)",loc:"Ashwaubenon",addr:"Titletown, Green Bay, WI 54304",desc:"FREE themed trivia at Titletown every summer Thursday! Live-hosted at the top of Ariens Hill. Drink voucher prizes. Part of Titletown Night Market evening.",url:"https://www.titletown.com/",setting:"outdoor",walking:"someWalking",goodFor:["seniors","couples"],highlight:true,free:true,recurring:false},
{id:4610,name:"Bark & Brew Trivia (Wednesdays 7pm + Dogs!)",cat:"Activity",sub:"Trivia",date:"",dateLabel:"Wednesdays 7pm",venue:"Bark & Brew",loc:"Howard",addr:"2514 Glendale Ave, Howard, WI 54313",desc:"Trivia + your dog off-leash! Every Wednesday at 7pm at Bark & Brew. Your pup plays while you answer questions. Craft drinks.",url:"https://barknbrewwi.com/",setting:"indoor",walking:"lowWalking",goodFor:["seniors","couples"],highlight:true,free:true,recurring:true},
// === ESCAPE ROOMS / ENTERTAINMENT ===
{id:4612,name:"Escape Room Wisconsin (7 Themed Rooms!)",cat:"Activity",sub:"Entertainment",date:"",dateLabel:"Wed-Sun afternoons/evenings (~$35/person)",venue:"Escape Room Wisconsin",loc:"Ashwaubenon",addr:"985 Centennial St, Green Bay, WI 54304",desc:"7 themed escape rooms! Mystery Manor, Secret Agent, Naughty List + more. ~$35/person for 60 min. 2-8 players per room. Great for families and groups. (920) 731-2583.",url:"https://www.escaperoomwisconsin.com/",setting:"indoor",walking:"lowWalking",goodFor:["seniors","family","couples"],highlight:true,free:false,recurring:true},
{id:4613,name:"Player 2 Arcade Bar (60+ Retro Cabinets!)",cat:"Activity",sub:"Entertainment",date:"",dateLabel:"Mon-Thu 4pm-2am, Fri 2pm, Sat-Sun 11am",venue:"Player 2 Arcade Bar",loc:"Downtown Green Bay",addr:"219 N Washington St, Green Bay, WI 54301",desc:"60+ retro arcade cabinets + 17 pinball machines! Pac-Man, Galaga, NBA Jam, Guitar Hero + more. Tokens ~$0.25. Under 21 welcome with guardian until 8pm.",url:"https://www.player2bar.com/",setting:"indoor",walking:"lowWalking",goodFor:["family","couples"],highlight:true,free:false,recurring:true},
{id:4614,name:"Midwest Super Speedway (Indoor Go-Karts!)",cat:"Activity",sub:"Entertainment",date:"",dateLabel:"Daily (juniors 6+, ~$28/race)",venue:"Midwest Super Speedway",loc:"Ashwaubenon",addr:"1016 Tony Canadeo Run, Green Bay, WI 54304",desc:"Indoor electric go-kart racing! ~$28 for 10-lap race. Juniors 6-12 (48\"+), Adults 13+ (58\"+). Year-round, weatherproof fun near Lambeau.",url:"https://www.midwestsuperspeedway.com/",setting:"indoor",walking:"lowWalking",goodFor:["family"],highlight:true,free:false,recurring:true},
{id:4615,name:"Get Air Green Bay (Trampoline Park!)",cat:"Activity",sub:"Entertainment",date:"",dateLabel:"Tue-Sun (closed Mon, ~$16/hr)",venue:"Get Air Green Bay",loc:"Ashwaubenon",addr:"790 Hansen Rd Ste A, Green Bay, WI 54304",desc:"Trampoline park! Big Air $15.99/hr, Little Air (under 46\") $11.99. Socks $3.99. Toddler Time, Family Night Monday. Military discount. Great for grandkids!",url:"https://getairsports.com/green-bay/",setting:"indoor",walking:"someWalking",goodFor:["family"],highlight:true,free:false,recurring:true},
{id:4616,name:"Putt Social (Indoor Mini Golf!)",cat:"Activity",sub:"Entertainment",date:"",dateLabel:"Daily ~9am-10pm (~$11 adult, $8 kids)",venue:"Putt Social",loc:"East Green Bay",addr:"2255 Main St, Green Bay, WI 54302",desc:"Indoor mini golf! 9 holes (play twice for 18). ~$11 adults, ~$8 kids 4-12. Year-round, climate-controlled. Great rainy day activity!",url:"",setting:"indoor",walking:"lowWalking",goodFor:["seniors","family"],highlight:true,free:false,recurring:true},
// === DANCE ===
{id:4618,name:"Green Bay Ballroom (Social Dances + Lessons!)",cat:"Activity",sub:"Dance",date:"",dateLabel:"Group classes ~$16 (Tue-Fri 7pm)",venue:"Green Bay Ballroom",loc:"Green Bay",addr:"525 N Taylor St, Green Bay, WI 54303",desc:"Ballroom dance studio! Group classes $16/person (East Coast Swing, Cha Cha, Waltz + more). Social dance parties. Private lessons available. (920) 249-7773.",url:"https://www.greenbayballroom.com/",setting:"indoor",walking:"someWalking",goodFor:["seniors","couples"],highlight:true,free:false,recurring:true},
{id:4619,name:"Elks Lodge Line Dancing (Thursdays $5!)",cat:"Activity",sub:"Dance",date:"",dateLabel:"Thursdays: beginners 5:30pm, open 6:30pm ($5)",venue:"B.P.O. Elks (Green Bay)",loc:"Ashwaubenon",addr:"3195 S Ridge Rd, Green Bay, WI",desc:"Line dancing every Thursday! Beginners at 5:30pm, open dance at 6:30pm. Only $5. Great exercise and social time for seniors.",url:"",setting:"indoor",walking:"someWalking",goodFor:["seniors"],highlight:true,free:false,recurring:true},
{id:4620,name:"Green Bay Squares (Square Dancing Club!)",cat:"Activity",sub:"Dance",date:"",dateLabel:"2nd & 4th Thursdays 7pm (~$4-5)",venue:"Oak Park Place",loc:"Green Bay",addr:"421 Erie Rd, Green Bay, WI",desc:"Square dancing club! 2nd & 4th Thursdays at 7pm at Oak Park Place. ~$4-5. Fun, social, and great exercise. All skill levels welcome.",url:"https://www.hoedownnews.org/green-bay-squares/",setting:"indoor",walking:"someWalking",goodFor:["seniors"],highlight:true,free:false,recurring:true},
{id:4621,name:"Pulaski Polka Days (Jul 16-19!)",cat:"Event",sub:"Festival",date:"2026-07-16",dateTo:"2026-07-19",dateLabel:"Thu-Sun Jul 16-19",venue:"Pulaski, WI",loc:"Pulaski (20 min NE)",addr:"Pulaski, WI 54162",desc:"POLKA DAYS! This is Wisconsin! 4-day polka festival with live bands, dancing, food, beer. Short drive northeast of Green Bay. Classic Wisconsin tradition.",url:"https://pulaskipolkadays.com/",setting:"outdoor",walking:"someWalking",goodFor:["seniors","couples","family"],highlight:true,free:false,recurring:false},
// === ICE CREAM / DESSERT ===
{id:4623,name:"Zesty's Frozen Custard (Wisconsin Classic!)",cat:"Restaurant",sub:"Dessert",date:"",dateLabel:"Tue-Sun 11am-9pm (closed Mon)",venue:"Zesty's Frozen Custard",loc:"Allouez",addr:"508 Greene Ave, Green Bay, WI 54301",desc:"Wisconsin frozen custard tradition! Shakes, malts, sundaes, scrambles + grill food. Also at 2639 Lineville Rd (Howard — verify if open). Closed Mondays.",url:"https://www.zestyscustard.com/",setting:"indoor",walking:"lowWalking",goodFor:["seniors","family"],highlight:true,free:false,recurring:true,cuisine:"Custard"},
{id:4624,name:"Sara's Artisan Gelato (50+ Flavors!)",cat:"Restaurant",sub:"Dessert",date:"",dateLabel:"Mon-Sat 12-9pm, Sun 12-7pm (2 locations!)",venue:"Sara's Artisan Gelato",loc:"Green Bay + De Pere",addr:"933 Anderson Dr, Green Bay, WI",desc:"50+ gelato flavors! Dairy-free/sorbet options. Scratch sauces. Also at 3131 Monroe Rd, De Pere. A true artisan gelato experience.",url:"https://sarasartisangelato.com/",setting:"indoor",walking:"lowWalking",goodFor:["seniors","family","couples"],highlight:true,free:false,recurring:true,cuisine:"Gelato"},
{id:4625,name:"BrainFreeze Ice Cream (Half-Price Waffle Cone Wed!)",cat:"Restaurant",sub:"Dessert",date:"",dateLabel:"Seasonal Mar-Oct (~11:30am-9pm)",venue:"BrainFreeze Ice Cream Shoppe",loc:"Howard",addr:"1773 Cardinal Ln, Green Bay, WI 54313",desc:"Chocolate Shoppe super-premium ice cream with dozens of flavors! HALF-PRICE WAFFLE CONE WEDNESDAY. Ice cream cakes too. Seasonal Mar-Oct.",url:"",setting:"indoor",walking:"lowWalking",goodFor:["seniors","family"],highlight:true,free:false,recurring:true,cuisine:"Ice Cream"},
{id:4626,name:"Uncle Mike's Bake Shoppe (Kringle + Donuts!)",cat:"Restaurant",sub:"Bakery",date:"",dateLabel:"Opens 5-6am daily (3 locations!)",venue:"Uncle Mike's Bake Shoppe",loc:"Multiple Locations",addr:"2999 E Mason St, Green Bay, WI 54311",desc:"Scratch bakery! Famous Kringle (Sea Salt Caramel Pecan!), donuts, pastries. Also at 2514 Lineville Rd (Suamico) + 1840 Dickinson Rd (De Pere). Opens EARLY!",url:"https://unclemikesbakeshoppe.com/",setting:"indoor",walking:"lowWalking",goodFor:["seniors","family"],highlight:true,free:false,recurring:true,cuisine:"Bakery"},
// === CULVER'S (WISCONSIN ICON) ===
{id:4628,name:"Culver's (5 Locations — ButterBurgers + Custard!)",cat:"Restaurant",sub:"Casual American",date:"",dateLabel:"Daily from ~10am (5 metro locations!)",venue:"Culver's",loc:"Multiple Locations",addr:"1219 W Mason St, Green Bay, WI 54303",desc:"Wisconsin's own! ButterBurgers, Fresh Frozen Custard (Flavor of the Day!), Concrete Mixers, cheese curds. Also at Voyager Dr, Hansen Rd, Suamico Velp, De Pere Lawrence Dr.",url:"https://www.culvers.com/",setting:"indoor",walking:"lowWalking",goodFor:["seniors","family"],highlight:true,free:false,recurring:true,cuisine:"American"},
// === KROLL'S (GB ICON) ===
{id:4629,name:"Kroll's West (Lambeau Burger Legend Since 1930s!)",cat:"Restaurant",sub:"Casual American",date:"",dateLabel:"Check hours (across from Lambeau!)",venue:"Kroll's West",loc:"Ashwaubenon",addr:"1990 S Ridge Rd, Ashwaubenon, WI 54304",desc:"GREEN BAY LEGEND across from Lambeau! Charcoal butter burgers, broasted chicken, Friday fish fry, homemade chili, malts/shakes. ~85+ year tradition. (920) 497-1111.",url:"https://www.krollswest.com/",setting:"indoor",walking:"lowWalking",goodFor:["seniors","family","couples"],highlight:true,free:false,recurring:true,cuisine:"Burgers"},
{id:4630,name:"Al's Hamburger Shop (Since 1934, TV Famous!)",cat:"Restaurant",sub:"Casual American",date:"",dateLabel:"Tue-Sat 11am-7/8pm (late night Fri-Sat!)",venue:"Al's Hamburger Shop",loc:"Downtown Green Bay",addr:"131 S Washington St, Green Bay, WI 54301",desc:"Green Bay icon since 1934! Classic griddled burgers, creative specials, amazing shakes. Featured on Man vs. Food and by Alton Brown. Fri-Sat late night to-go 10pm-2am!",url:"https://alshamburgergb.com/",setting:"indoor",walking:"lowWalking",goodFor:["seniors","family"],highlight:true,free:false,recurring:true,cuisine:"Burgers"},
// === ONEIDA CASINO ===
{id:4632,name:"Oneida Casino (2000+ Slots, Tables, Bingo!)",cat:"Activity",sub:"Casino",date:"",dateLabel:"Slots 24/7, Tables 10am-4am, Bingo daily",venue:"Oneida Casino",loc:"Ashwaubenon/Airport",addr:"2020 Airport Dr, Green Bay, WI 54313",desc:"2000+ slots (24/7), 8 table game types, poker room (Wed-Sat), sportsbook! Hotel on-site. Players Club rewards. Bingo at IMAC: AM Express 10:30am, PM/Evening sessions too. 1-800-238-4263.",url:"https://oneidacasinohotel.com/",setting:"indoor",walking:"someWalking",goodFor:["seniors","couples"],highlight:true,free:false,recurring:true},
{id:4633,name:"Oneida Bingo (Daily Sessions from $13!)",cat:"Activity",sub:"Bingo",date:"",dateLabel:"Daily: AM 10:30am, PM 6:30pm, Sat Nite Owls 9:30pm",venue:"Oneida IMAC (Irene Moore Activity Center)",loc:"Ashwaubenon",addr:"2100 Airport Dr, Green Bay, WI 54313",desc:"Daily bingo at Oneida! AM Express from $13, PM Quest from $17, Evening from $20. 692-seat hall. Nite Owls Saturday 9:30pm. Progressive jackpots! 18+ to play.",url:"https://oneidacasinohotel.com/bingo/",setting:"indoor",walking:"lowWalking",goodFor:["seniors"],highlight:true,free:false,recurring:true},
{id:4634,name:"St. Philip Parish Bingo (Tue Evenings Sep-Apr!)",cat:"Event",sub:"Bingo",date:"2026-01-06",dateTo:"2026-04-28",dateLabel:"Tuesdays Sep-Apr, doors 5pm, bingo 6:30pm",venue:"St. Philip the Apostle Parish",loc:"East Green Bay",addr:"312 Victoria St, Green Bay, WI 54302",desc:"Church bingo! Tuesdays Sep-Apr (no Dec). Doors 5pm, bingo 6:30pm. All 22 games from just $16! Kitchen 5-6:30pm. Cash only. 50/50 raffles. 18+ to play. (920) 468-7848.",url:"https://www.stphilipgb.org/bingo",setting:"indoor",walking:"lowWalking",goodFor:["seniors"],highlight:true,free:false,recurring:false},
// === FISHING ===
{id:4636,name:"WI Free Fishing Weekend (Jun 6-7, No License!)  ",cat:"Event",sub:"Nature",date:"2026-06-06",dateTo:"2026-06-07",dateLabel:"Sat-Sun Jun 6-7 (FREE, no license needed!)",venue:"All Wisconsin waters",loc:"Statewide",addr:"Any Wisconsin water",desc:"Fish Wisconsin FREE — no license, trout stamp, or salmon stamp needed! June 6-7, 2026. All other rules (seasons, limits) still apply. Great intro for grandkids!",url:"https://dnr.wisconsin.gov/topic/Fishing",setting:"outdoor",walking:"someWalking",goodFor:["seniors","family"],highlight:true,free:true,recurring:false},
{id:4637,name:"WI Senior Fishing License (Only $7 for 65+!)",cat:"Activity",sub:"Fishing",date:"",dateLabel:"Annual license $7 (65+ WI residents!)",venue:"Buy at GoWild.wi.gov or bait shops",loc:"Statewide",addr:"N/A",desc:"Wisconsin residents 65+ pay only $7/year for a fishing license! Buy online at GoWild.wi.gov or at any authorized retailer (bait shops, sporting goods stores). Great Lakes stamp $10 extra.",url:"https://dnr.wi.gov/gowild/",setting:"outdoor",walking:"lowWalking",goodFor:["seniors"],highlight:true,free:false,recurring:true},
// === FARMERS MARKETS ===
{id:4639,name:"Farmers Market on Broadway (120+ Vendors, Wed!)",cat:"Event",sub:"Farmers Market",date:"2026-05-20",dateTo:"2026-09-30",dateLabel:"Wednesdays May 20-Sep 30, 3-8pm (120+ vendors!)",venue:"Broadway District",loc:"Downtown Green Bay",addr:"N Broadway, Green Bay, WI 54303",desc:"One of Wisconsin's LARGEST farmers markets! 120+ vendors every Wednesday 3-8pm. Produce, baked goods, crafts, live music, craft beer. Rain or shine!",url:"https://downtowngreenbay.com/",setting:"outdoor",walking:"someWalking",goodFor:["seniors","family","couples"],highlight:true,free:true,recurring:false},
{id:4640,name:"Saturday Farmers Market (100+ Vendors, Yoga!)",cat:"Event",sub:"Farmers Market",date:"2026-05-23",dateTo:"2026-10-31",dateLabel:"Saturdays May 23-Oct 31, 7am-noon (100+ vendors!)",venue:"South Washington & Doty Streets",loc:"Downtown Green Bay",addr:"S Washington St, Green Bay, WI 54301",desc:"100+ vendors every Saturday morning! Live music 9-11:30am. Yoga at 7:30am alternating weeks. Family Days: Jun 13, Jul 11, Aug 8, Sep 19, Oct 31. No pets.",url:"https://downtowngreenbay.com/",setting:"outdoor",walking:"someWalking",goodFor:["seniors","family"],highlight:true,free:true,recurring:false},
{id:4641,name:"Market on Military (Thu + Winter Indoor Market!)",cat:"Event",sub:"Farmers Market",date:"2026-06-04",dateTo:"2026-10-29",dateLabel:"Summer: Thu Jun 4-Oct 29, 2-7pm | Winter: 1st/3rd Sat 9-1",venue:"216 S Military Ave (summer) / 201 S Military (winter)",loc:"West Green Bay",addr:"216 S Military Ave, Green Bay, WI 54303",desc:"Summer outdoor Thursdays 2-7pm PLUS winter indoor market 1st & 3rd Saturdays 9am-1pm! SNAP/EBT accepted with Double Your Bucks ($10 match). 10th season in 2026!",url:"https://militaryave.org/",setting:"outdoor",walking:"lowWalking",goodFor:["seniors","family"],highlight:true,free:true,recurring:false},
{id:4642,name:"De Pere Farmers Market (Thursdays, Dogs OK!)",cat:"Event",sub:"Farmers Market",date:"2026-06-04",dateTo:"2026-09-24",dateLabel:"Thursdays Jun 4-Sep 24, 3-8pm (Sep: 3-7pm)",venue:"George Street Plaza",loc:"De Pere",addr:"George St, De Pere, WI 54115",desc:"Intimate riverfront farmers market! Live music, food trucks, drinks, kids activities. LEASHED DOGS allowed! Thursdays 3-8pm (September until 7pm).",url:"https://definitelydepere.org/",setting:"outdoor",walking:"someWalking",goodFor:["seniors","family","couples"],highlight:true,free:true,recurring:false},
{id:4643,name:"Howard Market & Music (Mondays + Biergarten!)",cat:"Event",sub:"Farmers Market",date:"2026-06-08",dateTo:"2026-08-24",dateLabel:"Mondays Jun 8-Aug 24, 5-8pm",venue:"Howard Commons Activity Complex",loc:"Howard",addr:"550 Commons Place, Howard, WI",desc:"Monday evening farmers market + live music + Biergarten! Produce, flowers, handmade goods, food vendors, food trucks. Unique Monday timing — great for seniors!",url:"http://villageofhoward.com/",setting:"outdoor",walking:"someWalking",goodFor:["seniors","family"],highlight:true,free:true,recurring:false},
// === THRIFT STORES ===
{id:4645,name:"Goodwill (3 Stores — Senior Tue 10% Off 60+!)",cat:"Shop",sub:"Thrift Store",date:"",dateLabel:"Mon-Sat 9-9, Sun 9-7 (SENIOR TUE 10% off!)",venue:"Goodwill NCW",loc:"Multiple Locations",addr:"1660 W Mason St, Green Bay, WI 54303",desc:"3 Green Bay stores! EVERY TUESDAY: 10% off for age 60+. Also at 2814 S Oneida (Ashwaubenon) and 1301 S Brosig (East). Plus color-tag sales and Good Points rewards.",url:"https://goodwillncw.org/",setting:"indoor",walking:"someWalking",goodFor:["seniors"],highlight:true,free:false,recurring:true},
{id:4646,name:"St. Vincent de Paul Thrift (3 Stores + Dig & Save!)",cat:"Shop",sub:"Thrift Store",date:"",dateLabel:"Mon-Sat 9-7, Sun 11-6",venue:"St. Vincent de Paul",loc:"Multiple Locations",addr:"940 Hansen Rd, Green Bay, WI 54304",desc:"3 thrift stores + Dig & Save outlet! West (940 Hansen), East (moving to 1831 Main St spring 2026), Howard (3816 Velp Ave). Dig & Save for deep discounts.",url:"https://svdpgb.org/",setting:"indoor",walking:"someWalking",goodFor:["seniors"],highlight:true,free:false,recurring:true},
{id:4647,name:"Habitat for Humanity ReStore (Furniture + More!)",cat:"Shop",sub:"Thrift Store",date:"",dateLabel:"Tue-Fri 10-6, Sat 9-5",venue:"Habitat for Humanity ReStore",loc:"Allouez",addr:"1967 Allouez Ave, Green Bay, WI 54311",desc:"Donated furniture, appliances, building materials, decor at steep discounts! Proceeds support local Habitat for Humanity builds. Great deals!",url:"https://www.greenbayhabitat.org/",setting:"indoor",walking:"someWalking",goodFor:["seniors"],highlight:false,free:false,recurring:true},
// === TRANSPORTATION ===
{id:4649,name:"Green Bay Metro Bus (Senior Fare $1!)",cat:"Service",sub:"Transportation",date:"",dateLabel:"Mon-Fri ~5:15am-6:45pm, Sat ~7:45am-1:45pm",venue:"Green Bay Metro Transit",loc:"Green Bay",addr:"901 University Ave, Green Bay, WI 54302",desc:"City bus system! SENIOR FARE (65+) only $1 cash, $2 day pass, $31/month. Lift-equipped, wheelchair accessible. 920-448-3450. Route info: greenbaywi.gov/metro.",url:"https://www.greenbaywi.gov/",setting:"indoor",walking:"lowWalking",goodFor:["seniors"],highlight:true,free:false,recurring:true},
{id:4650,name:"Curative Connections (Senior Door-to-Door Rides!)",cat:"Service",sub:"Transportation",date:"",dateLabel:"Mon-Fri 7:30am-4:30pm ($5/ride, 60+)",venue:"Curative Connections",loc:"Brown County",addr:"Brown County area",desc:"Door-to-door transportation for 60+ and people with disabilities! $5 one-way in Brown County. Application required. Wheelchair vans available. (920) 227-4272.",url:"https://www.curativeconnections.org/",setting:"indoor",walking:"lowWalking",goodFor:["seniors"],highlight:true,free:false,recurring:true},
// === GROCERY ===
{id:4652,name:"Woodman's Food Market (Open 24 Hours!)",cat:"Shop",sub:"Grocery",date:"",dateLabel:"Grocery: 24 hours! Liquor: 8am-8:45pm",venue:"Woodman's",loc:"Howard",addr:"2400 Duck Creek Pkwy, Green Bay, WI 54303",desc:"Open 24 HOURS! Massive selection, low prices, Wisconsin-owned. Liquor store 8am-8:45pm. Online pickup 8am-10pm. One of the best grocery values around.",url:"https://www.woodmans-food.com/",setting:"indoor",walking:"someWalking",goodFor:["seniors","family"],highlight:true,free:false,recurring:true},
{id:4653,name:"Festival Foods (5 Locations — WI Chain!)",cat:"Shop",sub:"Grocery",date:"",dateLabel:"Daily 6am-11pm (5 metro locations!)",venue:"Festival Foods",loc:"Multiple Locations",addr:"2430 University Ave, Green Bay, WI 54302",desc:"5 Green Bay area stores! University Ave, Steffens Ct, W Mason, Suamico Lineville, De Pere Main Ave. Wisconsin-owned, great deli and bakery. Daily 6am-11pm.",url:"https://www.festfoods.com/",setting:"indoor",walking:"someWalking",goodFor:["seniors","family"],highlight:false,free:false,recurring:true},
// === SENIOR SERVICES ===
{id:4655,name:"ADRC of Brown County (Senior Resource Hub!)",cat:"Service",sub:"Senior Services",date:"",dateLabel:"Mon-Fri 8am-4:30pm",venue:"ADRC of Brown County",loc:"Downtown Green Bay",addr:"300 S Adams St, Green Bay, WI 54301",desc:"THE resource hub for seniors! Free info & referrals, Medicare counseling, caregiver support, Meals on Wheels signup, fall prevention workshops, Bingocize, support groups. (920) 448-4300.",url:"https://adrcofbrowncounty.org/",setting:"indoor",walking:"lowWalking",goodFor:["seniors"],highlight:true,free:true,recurring:true},
{id:4656,name:"Alzheimer's Association — Green Bay Office",cat:"Service",sub:"Senior Services",date:"",dateLabel:"24/7 Helpline: (800) 272-3900",venue:"Alzheimer's Association NE WI",loc:"Green Bay",addr:"2700 Vernon Dr, Ste 340, Green Bay, WI 54304",desc:"Support groups, education, care consultations for Alzheimer's/dementia families. Local office (920) 469-2110. 24/7 Helpline (800) 272-3900. You are NOT alone.",url:"https://www.alz.org/wi",setting:"indoor",walking:"lowWalking",goodFor:["seniors"],highlight:true,free:true,recurring:true},
];

let newStr = '';
for (const e of entries) {
  const descEsc = e.desc.replace(/"/g, '\\"');
  const nameEsc = e.name.replace(/"/g, '\\"');
  let s = ',\n{id:' + e.id + ',name:"' + nameEsc + '",cat:"' + e.cat + '",sub:"' + e.sub + '"';
  s += ',price:"' + (e.free ? 'free' : '$$') + '",priceNum:' + (e.free ? 0 : 2);
  s += ',date:"' + (e.date||'') + '"';
  if (e.dateTo) s += ',dateTo:"' + e.dateTo + '"';
  s += ',dateLabel:"' + (e.dateLabel || '') + '"';
  s += ',venue:"' + e.venue + '"';
  s += ',desc:"' + descEsc + '"';
  s += ',url:"' + (e.url || '') + '"';
  s += ',setting:"' + e.setting + '",walking:"' + e.walking + '"';
  s += ',goodFor:' + JSON.stringify(e.goodFor);
  s += ',highlight:' + e.highlight;
  s += ',cuisine:"' + (e.cuisine || '') + '",established:""';
  s += ',free:' + e.free + ',recurring:' + (e.recurring || false) + '}';
  newStr += s;
}

const lastEntry = 'free:true,recurring:true}';
const idx = html.lastIndexOf(lastEntry);
if (idx === -1) { console.log('ERROR: insertion point not found'); process.exit(1); }
html = html.substring(0, idx + lastEntry.length) + newStr + html.substring(idx + lastEntry.length);

fs.writeFileSync(path, html, 'utf8');
console.log('Added ' + entries.length + ' entries (IDs ' + Math.min(...entries.map(e=>e.id)) + '-' + Math.max(...entries.map(e=>e.id)) + ')');
console.log('File size: ' + Buffer.byteLength(html, 'utf8'));
