const fs = require('fs');
const path = 'C:/Users/shawn/Downloads/Green Bay Explorer.html';
let html = fs.readFileSync(path, 'utf8');

const entries = [
// === NEW ZOO ===
{id:3870,name:"NEW Zoo & Adventure Park (Senior $11!)",cat:"Attraction",sub:"Zoo",date:"",dateLabel:"Daily year-round (Apr-Oct 9-6, Nov-Mar 9-4)",venue:"NEW Zoo & Adventure Park",loc:"Suamico",addr:"4378 Reforestation Rd, Green Bay, WI 54313",desc:"Lions, snow leopards, giraffes, penguins! Senior (62+) $11. Feed giraffes $2/serving! Adventure Park zipline + ropes. Half-off zoo admission Wed 4-6pm Jun-Aug. Moms FREE Mother's Day, Dads FREE Father's Day!",url:"https://newzoo.org/",setting:"outdoor",walking:"someWalking",goodFor:["seniors","family"],highlight:true,free:false,recurring:true},
{id:3871,name:"NEW Zoo — Sip 'n' Safari (Wine + Animals!)",cat:"Event",sub:"Food & Wine",date:"2026-06-16",dateLabel:"Tue Jun 16, 5-8pm",venue:"NEW Zoo & Adventure Park",loc:"Suamico",addr:"4378 Reforestation Rd, Green Bay, WI 54313",desc:"Wine and cheese paired with animal viewing! A sophisticated evening at the zoo. Tickets on sale May 1.",url:"https://newzoo.org/",setting:"outdoor",walking:"someWalking",goodFor:["seniors","couples"],highlight:true,free:false,recurring:false},
// === DE PERE ===
{id:3875,name:"Celebrate De Pere (Memorial Day Weekend!)",cat:"Event",sub:"Festival",date:"2026-05-23",dateTo:"2026-05-25",dateLabel:"Fri-Sun May 23-25",venue:"Voyageur Park, De Pere",loc:"De Pere",addr:"Voyageur Park, De Pere, WI 54115",desc:"De Pere's BIG summer festival! Live music, carnival, food, fireworks. $5 before 6pm, $10 after. Kids 6 & under free. Veterans free. Three days of fun!",url:"https://www.celebratedepere.com/",setting:"outdoor",walking:"someWalking",goodFor:["family","seniors","couples"],highlight:true,free:false,recurring:false},
{id:3876,name:"De Pere City Band — Free Thursday Concerts",cat:"Event",sub:"Free Concert Series",date:"2026-06-11",dateTo:"2026-08-06",dateLabel:"Thursdays 7-8pm: Jun 11, 25, Jul 9, 23, 30, Aug 6",venue:"Voyageur Park, De Pere",loc:"De Pere",addr:"Voyageur Park, De Pere, WI 54115",desc:"FREE concerts by the De Pere City Band! Themed nights: Celebrate America, Music of the 70s, Christmas in July, Big Bands. Bring a lawn chair!",url:"https://www.deperewi.gov/",setting:"outdoor",walking:"lowWalking",goodFor:["seniors","couples","family"],highlight:true,free:true,recurring:true},
{id:3877,name:"Knights on the Fox — Free Summer Concerts (SNC)",cat:"Event",sub:"Free Concert Series",date:"2026-07-07",dateTo:"2026-08-04",dateLabel:"Tuesdays 6:30pm: Jul 7, 14, 21, 28, Aug 4",venue:"St. Norbert College campus",loc:"De Pere",addr:"100 Grant St, De Pere, WI 54115",desc:"FREE outdoor concerts on the Fox River at St. Norbert College! Bring a picnic or buy food at Phil's. Beautiful campus riverfront setting. 5 Tuesday evenings.",url:"https://www.snc.edu/",setting:"outdoor",walking:"lowWalking",goodFor:["seniors","couples","family"],highlight:true,free:true,recurring:true},
{id:3878,name:"De Pere Beer Gardens (Tuesday Evenings)",cat:"Event",sub:"Food & Drink",date:"2026-06-09",dateTo:"2026-08-18",dateLabel:"Tuesdays 4:30-8:30pm, Jun-Aug",venue:"Voyageur Park / Nelson Family Pavilion",loc:"De Pere",addr:"Voyageur Park, De Pere, WI 54115",desc:"Craft beer, seltzer, live music, food trucks, games every Tuesday evening! Proceeds benefit De Pere parks. A relaxed summer evening tradition.",url:"https://www.deperewi.gov/",setting:"outdoor",walking:"lowWalking",goodFor:["seniors","couples"],highlight:true,free:true,recurring:true},
{id:3879,name:"De Pere Farmers Market (Thursdays)",cat:"Event",sub:"Farmers Market",date:"2026-06-04",dateTo:"2026-09-24",dateLabel:"Thursdays 3-8pm, Jun 4 - Sep 24",venue:"George Street Plaza, De Pere",loc:"De Pere",addr:"George St, De Pere, WI 54115",desc:"Downtown De Pere farmers market on the Fox River! Fresh produce, baked goods, music, food trucks. Fox River views! September hours 3-7pm.",url:"https://definitelydepere.org/",setting:"outdoor",walking:"someWalking",goodFor:["seniors","family","couples"],highlight:true,free:true,recurring:true},
{id:3880,name:"De Pere Senior Picnic ($6, Ages 55+)",cat:"Event",sub:"Senior Social",date:"2026-08-22",dateLabel:"Sat Aug 22, doors 10:30am, lunch noon",venue:"De Pere Community Center",loc:"De Pere",addr:"De Pere Community Center, De Pere, WI 54115",desc:"Annual Senior Picnic! $6 per person, ages 55+. Lunch at noon, bingo after. A fun afternoon!",url:"https://www.deperewi.gov/",setting:"indoor",walking:"lowWalking",goodFor:["seniors"],highlight:true,free:false,recurring:false},
// === PULASKI POLKA DAYS ===
{id:3885,name:"Pulaski Polka Days (47th Annual!)",cat:"Event",sub:"Festival",date:"2026-07-16",dateTo:"2026-07-19",dateLabel:"Thu-Sun Jul 16-19",venue:"Pulaski Community Park",loc:"Pulaski (Day Trip)",addr:"429 E Pulaski St, Pulaski, WI 54162",desc:"Wisconsin's PREMIER polka festival! 4 days, 2 tents, dozens of bands. Thu $5 (Community Night w/ fireworks), Fri $20, Sat $20, Sun FREE + parade at 11am. Polka Mass 9:30am Sunday. ~20 min from GB.",url:"https://pulaskipolkadays.com/",setting:"outdoor",walking:"someWalking",goodFor:["seniors","couples","family"],highlight:true,free:false,recurring:false},
// === FREEDOM COUNTRY FEST ===
{id:3886,name:"Freedom Country Fest",cat:"Event",sub:"Concert",date:"2026-06-12",dateLabel:"Fri Jun 12, gates 5pm",venue:"County Rd S & E, Freedom",loc:"Freedom (Day Trip)",addr:"W2035 County Rd S, Freedom, WI 54130",desc:"Country music festival! Emily Ann Roberts (6pm), Darryl Worley (8pm), Parmalee (10pm). GA $50 in person / $56.50 online. ~25 min from GB.",url:"https://www.freedomcountryfest.com/",setting:"outdoor",walking:"someWalking",goodFor:["couples"],highlight:false,free:false,recurring:false},
// === FOX CITIES PAC ===
{id:3890,name:"Fox Cities PAC — The Great Gatsby (Broadway!)",cat:"Event",sub:"Day Trip",date:"2026-04-14",dateTo:"2026-04-19",dateLabel:"Tue-Sun Apr 14-19 (matinee + evening shows)",venue:"Fox Cities PAC, Appleton",loc:"Appleton (Day Trip)",addr:"400 W College Ave, Appleton, WI 54911",desc:"Broadway's The Great Gatsby comes to Appleton! Six days of performances at the stunning Fox Cities PAC. ~30 min from Green Bay.",url:"https://foxcitiespac.com/",setting:"indoor",walking:"lowWalking",goodFor:["seniors","couples"],highlight:true,free:false,recurring:false},
{id:3891,name:"Fox Cities PAC — & Juliet (Broadway Hit!)",cat:"Event",sub:"Day Trip",date:"2026-06-02",dateTo:"2026-06-07",dateLabel:"Tue-Sun Jun 2-7 (matinee + evening shows)",venue:"Fox Cities PAC, Appleton",loc:"Appleton (Day Trip)",addr:"400 W College Ave, Appleton, WI 54911",desc:"Max Martin pop jukebox musical! What if Juliet didn't die? Backstreet Boys, Britney, Bon Jovi hits. A joyful Broadway sensation. ~30 min from GB.",url:"https://foxcitiespac.com/",setting:"indoor",walking:"lowWalking",goodFor:["seniors","couples"],highlight:true,free:false,recurring:false},
// === FISH FRY ===
{id:3895,name:"Maricque's Fish Fry (Green Bay Institution!)",cat:"Restaurant",sub:"Fish Fry",date:"",dateLabel:"Wed & Fri (Fri: lunch 11-1:30, dinner 4:30-10)",venue:"Maricque's",loc:"East Green Bay",addr:"1517 University Ave, Green Bay, WI 54302",desc:"Green Bay's legendary fish fry since 1928! Perch, bluegill, walleye, cod, catfish. Order by piece count. Also open Wed 4:30-10. A MUST for fish fry lovers.",url:"https://www.greenbayfishfry.com/",setting:"indoor",walking:"lowWalking",goodFor:["seniors","family","couples"],highlight:true,free:false,recurring:true,cuisine:"Seafood"},
{id:3896,name:"Buck's Bar & Grill — Best Fish Fry (Voted #1!)",cat:"Restaurant",sub:"Fish Fry",date:"",dateLabel:"Fridays (call for hours)",venue:"Buck's Bar & Grill",loc:"Pulaski",addr:"2977 State Hwy 32, Pulaski, WI 54162",desc:"Press-Gazette readers voted Buck's #1 fish fry! ALL-YOU-CAN-EAT walleye ~$12.95. Plus perch, bluegill, haddock. ~20 min from GB.",url:"",setting:"indoor",walking:"lowWalking",goodFor:["seniors","family"],highlight:true,free:false,recurring:true,cuisine:"Seafood"},
// === SUPPER CLUBS ===
{id:3898,name:"Club Chalet Supper Club (Since 1944!)",cat:"Restaurant",sub:"Supper Club",date:"",dateLabel:"Tue-Sat (Tue-Thu 4-8:30, Fri-Sat 4-9:30)",venue:"Club Chalet",loc:"East Green Bay",addr:"4642 Nicolet Dr, Green Bay, WI 54311",desc:"Bay views, 40+ ice cream drinks, salad bar! Green Bay's classic 1944 supper club. Prime rib, steaks, seafood, Friday fish fry. Reservations Tue-Thu only.",url:"https://www.clubchaletgb.com/",setting:"indoor",walking:"lowWalking",goodFor:["seniors","couples"],highlight:true,free:false,recurring:true,cuisine:"Supper Club"},
{id:3899,name:"Kropp's Supper Club (1946 Heritage!)",cat:"Restaurant",sub:"Supper Club",date:"",dateLabel:"Wed, Fri, Sat only (4-8/9pm)",venue:"Kropp's Supper Club",loc:"West Green Bay",addr:"4570 Shawano Ave, Green Bay, WI 54313",desc:"Historic 1904 brick building, supper club since 1946. Perch, walleye, steaks, warm rolls. The quintessential Wisconsin supper club experience. Limited nights — plan ahead!",url:"https://kroppssupperclub.com/",setting:"indoor",walking:"lowWalking",goodFor:["seniors","couples"],highlight:true,free:false,recurring:true,cuisine:"Supper Club"},
// === KROLL'S & AL'S ===
{id:3900,name:"Kroll's West — Butter Burgers (Since 1936!)",cat:"Restaurant",sub:"American",date:"",dateLabel:"Daily ~10:30am-9pm+ (check hours)",venue:"Kroll's West",loc:"Ashwaubenon",addr:"1990 S Ridge Rd, Green Bay, WI 54304",desc:"THE butter burger tradition! Charcoal-grilled since 1936 near Lambeau. Also chili, broasted chicken, Friday fish fry. A Green Bay LEGEND.",url:"https://www.krollswest.com/",setting:"indoor",walking:"lowWalking",goodFor:["seniors","family","couples"],highlight:true,free:false,recurring:true,cuisine:"American"},
{id:3901,name:"Al's Hamburger Shop (Since 1934!)",cat:"Restaurant",sub:"American",date:"",dateLabel:"Tue-Sat 11am-7/8pm, Sun 11-7, Mon 11-2",venue:"Al's Hamburger Shop",loc:"Downtown Green Bay",addr:"131 S Washington St, Green Bay, WI 54301",desc:"Downtown Green Bay's iconic 1934 diner! Counter + booths, creative burgers. Featured on Man vs. Food. Cash-focused (ATM on site).",url:"http://alshamburgergb.com/",setting:"indoor",walking:"lowWalking",goodFor:["seniors","family","couples"],highlight:true,free:false,recurring:true,cuisine:"American"},
// === SEROOGY'S ===
{id:3903,name:"Seroogy's Chocolates (Since 1899!)",cat:"Shop",sub:"Candy & Chocolate",date:"",dateLabel:"Mon-Sat 9am-6pm+, Sun 9/10-6pm",venue:"Seroogy's Chocolates",loc:"De Pere / Ashwaubenon",addr:"144 N Wisconsin St, De Pere OR 784 Willard Dr, Ashwaubenon",desc:"Family chocolate maker since 1899! Meltaways, clusters, fudge, coffee. TWO locations. The ultimate Green Bay gift shop. Perfect grandparent-grandkid outing!",url:"https://seroogys.com/",setting:"indoor",walking:"lowWalking",goodFor:["seniors","family","couples"],highlight:true,free:false,recurring:true},
{id:3904,name:"Zesty's Frozen Custard — Fresh Churned Daily!",cat:"Restaurant",sub:"Dessert",date:"",dateLabel:"Tue-Sun 11am-9pm (closed Mon)",venue:"Zesty's Frozen Custard",loc:"Allouez",addr:"508 Greene Ave, Green Bay, WI 54301",desc:"Fresh-churned frozen custard made throughout the day! Concretes, sundaes, shakes, plus grill food and La Java coffee. The local custard institution.",url:"https://www.zestyscustard.com/",setting:"outdoor",walking:"lowWalking",goodFor:["seniors","family","couples"],highlight:true,free:false,recurring:true,cuisine:"Dessert"},
// === SCENIC NATURE ===
{id:3907,name:"Fonferek's Glen Waterfall (FREE!)",cat:"Park",sub:"Nature Preserve",date:"",dateLabel:"Daily 8am-dusk (best after rain)",venue:"Fonferek's Glen",loc:"Ledgeview",addr:"2825 Dutchman Rd, Green Bay, WI 54311",desc:"Beautiful 30-foot waterfall and dolomite cliffs! FREE. Paved overlook (2019) for easy viewing. Best in spring or after heavy rain. Gate locks at dusk!",url:"https://www.browncountywi.gov/",setting:"outdoor",walking:"lowWalking",goodFor:["seniors","couples","family"],highlight:true,free:true,recurring:true},
{id:3908,name:"Barkhausen Waterfowl Preserve (FREE!)",cat:"Park",sub:"Nature Preserve",date:"",dateLabel:"Trails dawn-dusk, Center Mon-Fri 9-4, Sat-Sun 12-4",venue:"Barkhausen Waterfowl Preserve",loc:"Suamico",addr:"2024 Lakeview Dr, Suamico, WI 54313",desc:"Wetlands, waterfowl, nature trails — all FREE! New Sensory Woods with boardwalk & seating (dementia-friendly design). Interpretive Center with exhibits. 9+ miles of trails.",url:"https://www.browncountywi.gov/",setting:"outdoor",walking:"someWalking",goodFor:["seniors","family"],highlight:true,free:true,recurring:true},
// === BOWLING & ENTERTAINMENT ===
{id:3910,name:"District 82 Pinball Arcade (100+ Machines!)",cat:"Activity",sub:"Entertainment",date:"",dateLabel:"Fri 5-10, Sat 11-10, Sun 11-8",venue:"District 82",loc:"De Pere",addr:"800 O'Keefe Rd, De Pere, WI 54115",desc:"100+ pinball machines, ALL free play after admission! Adults $15/hr or $25/day. A nostalgia paradise for couples and friends.",url:"https://www.district82.com/",setting:"indoor",walking:"lowWalking",goodFor:["seniors","couples"],highlight:true,free:false,recurring:true},
{id:3911,name:"Field of Scenes Drive-In Theater",cat:"Activity",sub:"Movie Theater",date:"",dateLabel:"Seasonal (check schedule)",venue:"Field of Scenes",loc:"Freedom",addr:"N3712 WI-55, Freedom, WI 54130",desc:"Twin-screen drive-in! Double features included. Adults $8, kids 4-11 $4, under 3 free. ~15-25 min from Green Bay. Walk-up sales only.",url:"https://www.fieldofscenes.biz/",setting:"outdoor",walking:"lowWalking",goodFor:["family","couples","seniors"],highlight:true,free:false,recurring:true},
{id:3912,name:"De Pere Cinema — $5 Senior Tickets!",cat:"Activity",sub:"Movie Theater",date:"",dateLabel:"Daily (matinee $5, Tue all shows $5)",venue:"De Pere Cinema (Get Reel)",loc:"De Pere",addr:"417 George St, De Pere, WI 54115",desc:"Best movie value in the area! Seniors 62+ always $5. Matinees (before 5:30) $5 for everyone. Tuesdays all shows $5. Dine-at-seat: pizza, sandwiches delivered to your table!",url:"https://www.getreelcinemas.com/",setting:"indoor",walking:"lowWalking",goodFor:["seniors","family","couples"],highlight:true,free:false,recurring:true},
// === FATHOM CLASSICS ===
{id:3915,name:"Fathom Classics: Willy Wonka (55th Anniversary!)",cat:"Event",sub:"Movie Theater",date:"2026-08-02",dateTo:"2026-08-05",dateLabel:"Sun Aug 2 & Wed Aug 5",venue:"Marcus Bay Park / GB East Cinema",loc:"Ashwaubenon / East Green Bay",addr:"755 Willard Dr, Ashwaubenon, WI 54304",desc:"Willy Wonka & the Chocolate Factory on the big screen for its 55th anniversary! With Leonard Maltin intro. Check Fathom for showtimes.",url:"https://www.fathomentertainment.com/",setting:"indoor",walking:"lowWalking",goodFor:["seniors","family"],highlight:true,free:false,recurring:false},
{id:3916,name:"Fathom Classics: Citizen Kane (85th Anniversary)",cat:"Event",sub:"Movie Theater",date:"2026-07-05",dateTo:"2026-07-08",dateLabel:"Sun Jul 5 & Wed Jul 8",venue:"Marcus Bay Park / GB East Cinema",loc:"Ashwaubenon / East Green Bay",addr:"755 Willard Dr, Ashwaubenon, WI 54304",desc:"The greatest film ever made on the big screen! 85th anniversary of Orson Welles' masterpiece. With Leonard Maltin intro.",url:"https://www.fathomentertainment.com/",setting:"indoor",walking:"lowWalking",goodFor:["seniors","couples"],highlight:true,free:false,recurring:false},
// === ANTIQUES ===
{id:3918,name:"Antique Mall of Greater Green Bay (HUGE!)",cat:"Shop",sub:"Antiques",date:"",dateLabel:"Check hours (outdoor flea Wed-Thu 2-8pm May+)",venue:"Antique Mall of Greater Green Bay",loc:"De Pere",addr:"1358 Mid Valley Dr, De Pere, WI 54115",desc:"Massive multi-dealer antique mall with 250ft Art Walk! Plus outdoor flea market Wed & Thu afternoons May-fall. One of the biggest antique destinations in NE Wisconsin.",url:"",setting:"indoor",walking:"someWalking",goodFor:["seniors","couples"],highlight:true,free:true,recurring:true},
{id:3919,name:"Goodwill — Senior 10% Off Tuesdays!",cat:"Shop",sub:"Thrift Store",date:"",dateLabel:"Daily 9am-9pm (Senior discount Tuesdays)",venue:"Goodwill NCW",loc:"Multiple Locations",addr:"2814 S Oneida (Ashwaubenon), 1301 Brosig (East), 1660 W Mason (West)",desc:"THREE Green Bay area Goodwill stores! Seniors 60+ get 10% off donated merchandise every TUESDAY. Color Tag of the Week: 50% off rotating tag colors. Great treasure hunting!",url:"https://goodwillncw.org/",setting:"indoor",walking:"someWalking",goodFor:["seniors"],highlight:true,free:false,recurring:true},
// === FARMERS MARKETS ===
{id:3921,name:"Farmers' Market on Broadway (Wed Evenings!)",cat:"Event",sub:"Farmers Market",date:"2026-05-20",dateTo:"2026-09-30",dateLabel:"Wednesdays 3-8pm, May 20 - Sep 30",venue:"Broadway District",loc:"Downtown Green Bay",addr:"N Broadway, Green Bay, WI 54303",desc:"120+ vendors! Wednesday evening market in the Broadway District. Craft beer, live music on main stage, fresh produce. A different vibe than the Saturday market!",url:"https://downtowngreenbay.com/",setting:"outdoor",walking:"someWalking",goodFor:["seniors","couples","family"],highlight:true,free:true,recurring:true},
{id:3922,name:"Summer Market on Military (Thursdays)",cat:"Event",sub:"Farmers Market",date:"2026-06-04",dateTo:"2026-10-29",dateLabel:"Thursdays 2-7pm, Jun 4 - Oct 29",venue:"216 S Military Ave",loc:"West Green Bay",addr:"216 S Military Ave, Green Bay, WI 54303",desc:"West-side farmers market! Wisconsin-grown/made focus. SNAP + Double Your Bucks (up to $10). Thursday afternoons all summer.",url:"https://militaryave.org/",setting:"outdoor",walking:"someWalking",goodFor:["seniors","family"],highlight:true,free:true,recurring:true},
{id:3923,name:"Oneida Farmers Market (Thursdays)",cat:"Event",sub:"Farmers Market",date:"2026-06-04",dateTo:"2026-10-01",dateLabel:"Thursdays noon-6pm, Jun - early Oct",venue:"Oneida Farmers Market",loc:"Oneida",addr:"N7284 County Rd J, Oneida, WI 54155",desc:"Native American community market! Produce, honey, maple syrup, baked goods, sweetgrass, Native handcrafted goods. A unique and calmer market experience.",url:"https://oneida-nsn.gov/",setting:"outdoor",walking:"lowWalking",goodFor:["seniors","family"],highlight:true,free:true,recurring:true},
// === DAY TRIPS ===
{id:3925,name:"Bookworm Gardens — Storybook Gardens! (Sheboygan)",cat:"Attraction",sub:"Day Trip",date:"2026-05-01",dateTo:"2026-10-31",dateLabel:"May-Oct (Tue-Sun 9-5 summer)",venue:"Bookworm Gardens",loc:"Sheboygan (Day Trip)",addr:"1415 Campus Dr, Sheboygan, WI 53081",desc:"Magical storybook-themed gardens! Walk through scenes from children's books. Adult $13. Secret Garden Dinner Series, Fairyfolk Festival Aug 4-9. Perfect grandkid outing! ~1 hr from GB.",url:"https://www.bookwormgardens.org/",setting:"outdoor",walking:"someWalking",goodFor:["seniors","family"],highlight:true,free:false,recurring:true},
{id:3926,name:"John Michael Kohler Arts Center (FREE!, Sheboygan)",cat:"Attraction",sub:"Day Trip",date:"",dateLabel:"Tue-Sun 10-4/5/8 (closed Mon)",venue:"John Michael Kohler Arts Center",loc:"Sheboygan (Day Trip)",addr:"608 New York Ave, Sheboygan, WI 53081",desc:"World-class art museum with FREE admission! Plus the new Art Preserve. Contemporary art, artist environments, workshops. ~1 hr from GB.",url:"https://www.jmkac.org/",setting:"indoor",walking:"someWalking",goodFor:["seniors","couples"],highlight:true,free:true,recurring:true},
{id:3927,name:"Wisconsin Maritime Museum + USS Cobia Submarine",cat:"Attraction",sub:"Day Trip",date:"",dateLabel:"Daily (summer 9-5, winter 10-4)",venue:"Wisconsin Maritime Museum",loc:"Manitowoc (Day Trip)",addr:"75 Maritime Dr, Manitowoc, WI 54220",desc:"Tour a REAL WWII submarine! Senior (65+) $17. Self-guided sub tours included with admission. Think & Drink evenings, submarine sleepovers! ~45 min from GB.",url:"https://www.wisconsinmaritime.org/",setting:"indoor",walking:"someWalking",goodFor:["seniors","family"],highlight:true,free:false,recurring:true},
{id:3928,name:"Hamilton Wood Type Museum (Senior $5!, Two Rivers)",cat:"Attraction",sub:"Day Trip",date:"",dateLabel:"Wed-Sat 10am-4pm",venue:"Hamilton Wood Type & Printing Museum",loc:"Two Rivers (Day Trip)",addr:"1816 10th St, Two Rivers, WI 54241",desc:"World's only museum dedicated to wood type! Senior (65+) only $5. Hands-on printing workshops. A hidden gem for typography and history lovers. ~50 min from GB.",url:"https://woodtype.org/",setting:"indoor",walking:"lowWalking",goodFor:["seniors","couples"],highlight:true,free:false,recurring:true},
// === SENIOR FITNESS / WELLNESS ===
{id:3930,name:"YMCA of Greater Green Bay (6 Locations! SilverSneakers)",cat:"Activity",sub:"Senior Fitness",date:"",dateLabel:"Mon-Sun (hours vary by branch)",venue:"YMCA of Greater Green Bay",loc:"Multiple Locations",addr:"235 N Jefferson St (Ferguson) + 5 more locations",desc:"SIX locations! ForeverWell Chair Yoga, Chair Strength, Water Aerobics, Line Dancing. SilverSneakers, Renew Active, Silver&Fit accepted. 65+ from $46/mo. Active Older Adults social group with bus trips!",url:"https://www.greenbayymca.org/",setting:"indoor",walking:"lowWalking",goodFor:["seniors"],highlight:true,free:false,recurring:true},
{id:3931,name:"Bellin Health Fitness (Pool + Senior $44/mo)",cat:"Activity",sub:"Senior Fitness",date:"",dateLabel:"Check hours (pool, classes, gym)",venue:"Bellin Health Fitness Center",loc:"Downtown Green Bay",addr:"744 S Webster Ave, Green Bay, WI 54305",desc:"Indoor pool, hot tub, sauna, walking track, group classes. Senior (62+) $44/mo. SilverSneakers, Renew Active, Silver&Fit accepted (may be $0!). Water aerobics and land classes.",url:"https://bellin.org/",setting:"indoor",walking:"lowWalking",goodFor:["seniors"],highlight:true,free:false,recurring:true},
{id:3932,name:"Salvation Army Kroc Center (Pool + Pickleball!)",cat:"Activity",sub:"Senior Fitness",date:"",dateLabel:"Check hours",venue:"Salvation Army Kroc Center",loc:"West Green Bay",addr:"1315 Lime Kiln Rd, Green Bay, WI 54311",desc:"Aqua classes, pickleball, SilverSneakers Splash/Stability, Deep Water Aerobics, Aqua Yoga. SilverSneakers/Renew Active/Silver&Fit accepted. Senior programs with grocery trips and Wednesday bingo lunch!",url:"https://cms.gbkroccenter.org/",setting:"indoor",walking:"lowWalking",goodFor:["seniors"],highlight:true,free:false,recurring:true},
// === ADRC ===
{id:3934,name:"ADRC Free Senior Programs (Tai Chi, StrongBodies)",cat:"Activity",sub:"Senior Service",date:"",dateLabel:"Various (see ADRC calendar)",venue:"ADRC of Brown County",loc:"Downtown Green Bay",addr:"300 S Adams St, Green Bay, WI 54301",desc:"FREE evidence-based programs! StrongBodies (strength), Walk With Ease, Stepping On (falls prevention), Bingocize, Tai Chi. Plus support groups, caregiver workshops, and Community Café lunch ($5 suggested, 60+).",url:"https://adrcofbrowncounty.org/",setting:"indoor",walking:"lowWalking",goodFor:["seniors"],highlight:true,free:true,recurring:true},
// === WALKING GROUPS ===
{id:3935,name:"Ashwaubenon Walking Club (Wednesdays, FREE)",cat:"Activity",sub:"Senior Fitness",date:"",dateLabel:"Wednesdays ~9am, ~1 hour",venue:"Various (Titletown in winter)",loc:"Ashwaubenon",addr:"Ashwaubenon, WI 54304",desc:"FREE senior walking group! Meet Wednesdays at 9am, walk about 3 miles at your own pace (~1 hour). Titletown indoor route in winter, outdoor routes spring-fall.",url:"https://ashwaubenon.gov/",setting:"outdoor",walking:"someWalking",goodFor:["seniors"],highlight:true,free:true,recurring:true},
// === CHURCH FESTIVALS ===
{id:3937,name:"St. Willy's Jam (Parish Street Festival)",cat:"Event",sub:"Festival",date:"2026-06-14",dateLabel:"Sun Jun 14, 10:30am-5pm (confirm date)",venue:"St. Willebrord Parish",loc:"Downtown Green Bay",addr:"209 S Adams St, Green Bay, WI 54301",desc:"Downtown parish street festival! Outdoor bilingual Mass, live music, tacos, brats, burgers, games, bounce house. Open to ALL! Confirm 2026 date with parish.",url:"https://stwillys.org/",setting:"outdoor",walking:"someWalking",goodFor:["family","seniors"],highlight:true,free:true,recurring:false},
// === MIDWEST SUPER SPEEDWAY ===
{id:3939,name:"Midwest Super Speedway (Indoor Go-Karts!)",cat:"Activity",sub:"Entertainment",date:"",dateLabel:"Check hours (book online)",venue:"Midwest Super Speedway",loc:"West Green Bay",addr:"1016 Tony Canadeo Run, Green Bay, WI 54304",desc:"Indoor electric go-kart racing! 10-lap adult race ~$28. Must be 13+ and 58in+ for adult karts. Junior karts for ages 6-12 (48in+). Near Badger State Brewing!",url:"https://midwestsuperspeedway.com/",setting:"indoor",walking:"lowWalking",goodFor:["family","couples"],highlight:true,free:false,recurring:true},
// === PAINTING POTTERY ===
{id:3940,name:"Paintin' Pottery (Walk-In Creative Studio)",cat:"Activity",sub:"Art Classes",date:"",dateLabel:"Wed-Sun 10-4/5/7/8/9 (closed Tue)",venue:"Paintin' Pottery",loc:"De Pere",addr:"520 George St, De Pere, WI 54115",desc:"Walk-in paint-your-own pottery, glass, mosaics, canvas, wheel throwing! No appointment needed. Perfect rainy-day activity for seniors and grandkids. Calm, seated, creative.",url:"",setting:"indoor",walking:"lowWalking",goodFor:["seniors","family","couples"],highlight:true,free:false,recurring:true},
];

let newStr = '';
for (const e of entries) {
  const descEsc = e.desc.replace(/"/g, '\\"');
  const nameEsc = e.name.replace(/"/g, '\\"');
  let s = ',\n{id:' + e.id + ',name:"' + nameEsc + '",cat:"' + e.cat + '",sub:"' + e.sub + '"';
  s += ',price:"' + (e.free ? 'free' : '$$') + '",priceNum:' + (e.free ? 0 : 2);
  s += ',date:"' + (e.date||'') + '"';
  if (e.dateTo) s += ',dateTo:"' + e.dateTo + '"';
  s += ',dateLabel:"' + e.dateLabel + '"';
  s += ',venue:"' + e.venue + '"';
  s += ',desc:"' + descEsc + '"';
  s += ',url:"' + (e.url || '') + '"';
  s += ',setting:"' + e.setting + '",walking:"' + e.walking + '"';
  s += ',goodFor:' + JSON.stringify(e.goodFor);
  s += ',highlight:' + e.highlight;
  s += ',cuisine:"' + (e.cuisine || '') + '",established:""';
  s += ',free:' + e.free + ',recurring:' + (e.recurring || false) + '}';
  newStr += s;
}

const lastEntry = 'free:false,recurring:false}';
const idx = html.lastIndexOf(lastEntry);
if (idx === -1) { console.log('ERROR: insertion point not found'); process.exit(1); }
html = html.substring(0, idx + lastEntry.length) + newStr + html.substring(idx + lastEntry.length);

fs.writeFileSync(path, html, 'utf8');
console.log('Added ' + entries.length + ' entries (IDs ' + Math.min(...entries.map(e=>e.id)) + '-' + Math.max(...entries.map(e=>e.id)) + ')');
console.log('File size: ' + Buffer.byteLength(html, 'utf8'));
