const fs = require('fs');
const path = 'C:/Users/shawn/Downloads/Green Bay Explorer.html';
let html = fs.readFileSync(path, 'utf8');

const entries = [
// === ASIAN RESTAURANTS ===
{id:4700,name:"Bangkok Garden (Thai + Weekday Lunch Buffet!)",cat:"Restaurant",sub:"Thai",date:"",dateLabel:"Mon-Sat lunch 11-2:45, dinner 4-9:30/10; Sun dinner",venue:"Bangkok Garden",loc:"Downtown Green Bay",addr:"240 N Broadway, Green Bay, WI 54303",desc:"Thai restaurant with weekday LUNCH BUFFET 11-2:30! Full dinner menu with curries, pad thai, satay. Great downtown location on Broadway.",url:"http://www.greenbaythaifood.com/",setting:"indoor",walking:"lowWalking",goodFor:["seniors","couples"],highlight:true,free:false,recurring:true,cuisine:"Thai"},
{id:4701,name:"Pho 1 Noodle and Grill (Vietnamese!)",cat:"Restaurant",sub:"Vietnamese",date:"",dateLabel:"Mon, Wed-Sun 10-9/10 (closed Tue)",venue:"Pho 1 Noodle and Grill",loc:"Ashwaubenon",addr:"2201 S Oneida St Ste 1, Green Bay, WI 54304",desc:"Vietnamese pho, banh mi, rice plates, noodle dishes! Closed Tuesdays. Authentic flavors, generous portions. (920) 494-3009.",url:"https://pho1noodlegrill.com/",setting:"indoor",walking:"lowWalking",goodFor:["seniors","couples"],highlight:true,free:false,recurring:true,cuisine:"Vietnamese"},
{id:4702,name:"Mayflower Chinese Restaurant",cat:"Restaurant",sub:"Chinese",date:"",dateLabel:"Mon, Wed-Sat 10-10/11; Sun 11-10 (closed Tue)",venue:"Mayflower",loc:"West Green Bay",addr:"414 Military Ave, Green Bay, WI 54303",desc:"Long-running Chinese restaurant on Military Ave! Full menu of traditional Chinese dishes. (920) 496-3083.",url:"https://mayflowergreenbay.com/",setting:"indoor",walking:"lowWalking",goodFor:["seniors","family"],highlight:false,free:false,recurring:true,cuisine:"Chinese"},
{id:4703,name:"Golden Thai Restaurant",cat:"Restaurant",sub:"Thai",date:"",dateLabel:"Wed-Sat 11-8, Sun 11-8 (closed Mon-Tue)",venue:"Golden Thai Restaurant",loc:"East Green Bay",addr:"1742 E Mason St Ste 3, Green Bay, WI 54302",desc:"Authentic Thai cuisine! Curries, stir-fries, Thai noodles. Closed Mon-Tue. (920) 371-8467.",url:"https://goldenthairestaurantwi.com/",setting:"indoor",walking:"lowWalking",goodFor:["seniors","couples"],highlight:false,free:false,recurring:true,cuisine:"Thai"},
{id:4704,name:"Plia's Kitchen (Hmong + Thai + SE Asian!)",cat:"Restaurant",sub:"Asian",date:"",dateLabel:"Mon-Fri 10-7:30 (closed Sat-Sun)",venue:"Plia's Kitchen",loc:"Green Bay",addr:"1300 S Webster Ave, Green Bay, WI 54301",desc:"Hmong, Thai, and Southeast Asian flavors! Authentic family cooking. Weekdays only. Green Bay has a significant Hmong community and this is a local favorite. (920) 437-3303.",url:"",setting:"indoor",walking:"lowWalking",goodFor:["seniors","family"],highlight:true,free:false,recurring:true,cuisine:"Hmong/Thai"},
{id:4705,name:"Boba Bae (Bubble Tea + Banh Mi!)",cat:"Restaurant",sub:"Asian",date:"",dateLabel:"Tue-Sat 11-8, Sun 1-8 (closed Mon)",venue:"Boba Bae",loc:"Ashwaubenon",addr:"2321 S Oneida St, Green Bay, WI 54304",desc:"Bubble tea AND banh mi sandwiches! Great boba drinks and Vietnamese snacks. Fun, trendy spot. (920) 544-0747.",url:"",setting:"indoor",walking:"lowWalking",goodFor:["family","couples"],highlight:false,free:false,recurring:true,cuisine:"Vietnamese/Boba"},
{id:4706,name:"Main Oriental Market + Mai's House (Asian Grocery!)",cat:"Shop",sub:"Grocery",date:"",dateLabel:"Daily 9am-7pm",venue:"Main Oriental Market",loc:"Downtown Green Bay",addr:"607 Pine St, Green Bay, WI 54304",desc:"Asian grocery store with HOT FOOD DELI (Mai's House) inside! Fresh produce, meats, noodles, sauces, spices. Ready-to-eat meals too. (920) 435-5271.",url:"",setting:"indoor",walking:"lowWalking",goodFor:["seniors","family"],highlight:false,free:false,recurring:true},
// === ITALIAN ===
{id:4708,name:"Olive Garden Green Bay",cat:"Restaurant",sub:"Italian",date:"",dateLabel:"Mon-Sun 11-10/11",venue:"Olive Garden",loc:"Ashwaubenon",addr:"2819 S Oneida St, Green Bay, WI 54304",desc:"Unlimited soup, salad, and breadsticks! Baked pastas, Tour of Italy combos. Familiar chain comfort. Good for families and groups.",url:"",setting:"indoor",walking:"lowWalking",goodFor:["seniors","family"],highlight:false,free:false,recurring:true,cuisine:"Italian"},
{id:4709,name:"Sammy's Pizza (Homemade Gnocchi & Ravioli!)",cat:"Restaurant",sub:"Italian",date:"",dateLabel:"Mon-Sat 11-9, Sun 11-8",venue:"Sammy's Pizza & Italian Restaurant",loc:"Ashwaubenon",addr:"2161 S Oneida St, Green Bay, WI 54304",desc:"Thin-crust pizza plus homemade gnocchi and ravioli! Family pasta sauces. A local favorite for Italian comfort food.",url:"",setting:"indoor",walking:"lowWalking",goodFor:["seniors","family"],highlight:false,free:false,recurring:true,cuisine:"Italian"},
{id:4710,name:"Aldo's Pizza (50+ Year Local Standby!)",cat:"Restaurant",sub:"Italian",date:"",dateLabel:"Tue-Sat 4-10, Sun 4-8 (closed Mon)",venue:"Aldo's Pizza",loc:"Green Bay",addr:"1247 Velp Ave, Green Bay, WI 54302",desc:"Thin-crust tavern-style pizza for 50+ years! A Green Bay institution. Classic no-frills pizza joint. Closed Mondays.",url:"",setting:"indoor",walking:"lowWalking",goodFor:["seniors","family"],highlight:false,free:false,recurring:true,cuisine:"Italian/Pizza"},
// === ART / CRAFTS ===
{id:4712,name:"The Art Garage (Free Gallery + Workshops!)",cat:"Attraction",sub:"Art",date:"",dateLabel:"Tue 3-6, Wed-Fri 12-6, Sat 10-4, Sun 12-4",venue:"The Art Garage",loc:"Downtown Green Bay",addr:"1400 Cedar St, Green Bay, WI 54302",desc:"FREE gallery admission! Adult workshops ~$25-45 (painting, photography, watercolor). FREE Weekly Sketch Wed 5-8pm (18+, bring supplies). Exhibitions + performances. (920) 448-6800.",url:"https://theartgarage.org/",setting:"indoor",walking:"lowWalking",goodFor:["seniors","couples"],highlight:true,free:false,recurring:true},
{id:4713,name:"Board & Brush (DIY Wood Sign + Wine!)",cat:"Activity",sub:"Art Classes",date:"",dateLabel:"Evenings/weekends (~$73/person)",venue:"Board & Brush Green Bay",loc:"Downtown Green Bay",addr:"235 N Broadway, Green Bay, WI 54303",desc:"DIY wood sign workshops with beer/wine! Instructor-led, ~$73 for Pick Your Project. Great date night or girls' night. (920) 593-9411.",url:"https://boardandbrush.com/greenbay/",setting:"indoor",walking:"lowWalking",goodFor:["seniors","couples"],highlight:true,free:false,recurring:true},
{id:4714,name:"NWTC Artisan Center (Ceramics, Glass, Wood!)",cat:"Activity",sub:"Art Classes",date:"",dateLabel:"Multi-week evening classes ($160-240)",venue:"NWTC Artisan & Business Center",loc:"Downtown Green Bay",addr:"1417 Cedar St, Green Bay, WI 54302",desc:"Ceramics, fused glass, woodturning, pyrography! Multi-week evening classes $160-240. Professional instruction. (920) 544-5018. Perfect for creative seniors!",url:"https://events.nwtc.edu/artisan-center",setting:"indoor",walking:"lowWalking",goodFor:["seniors"],highlight:true,free:false,recurring:true},
{id:4715,name:"Quilting Divas Sewing Boutique (Free Sew Days!)",cat:"Shop",sub:"Quilting",date:"",dateLabel:"Tue-Sat (FREE Sew Days!)",venue:"Quilting Divas Sewing Boutique",loc:"Howard",addr:"445 Cardinal Ln, Ste 108, Green Bay, WI 54313",desc:"Quilt shop with Free Sew Days! Bring your own project and sew for FREE. Fabrics, notions, classes. (920) 434-9980.",url:"https://www.quiltingdivassew.com/",setting:"indoor",walking:"lowWalking",goodFor:["seniors"],highlight:true,free:false,recurring:true},
{id:4716,name:"Glass Haus Stained Glass Studio (Classes!)",cat:"Activity",sub:"Art Classes",date:"",dateLabel:"Tue-Fri 12-5, Sat 10-1",venue:"The Glass Haus Stained Glass Studio",loc:"Downtown Green Bay",addr:"633 E Walnut St, Green Bay, WI 54301",desc:"Stained glass instruction from beginner to advanced! Supplies, restoration, bead making. A unique creative outlet. (920) 432-7709.",url:"",setting:"indoor",walking:"lowWalking",goodFor:["seniors"],highlight:false,free:false,recurring:true},
// === BOOKSTORES ===
{id:4718,name:"Barnes & Noble Green Bay",cat:"Shop",sub:"Bookstore",date:"",dateLabel:"Mon-Sat 10-9, Sun 10-7",venue:"Barnes & Noble",loc:"Ashwaubenon",addr:"2498 S Oneida St, Green Bay, WI 54304",desc:"Major bookstore near Bay Park Square! Books, gifts, cafe, events. Mon-Sat 10-9, Sun 10-7.",url:"https://stores.barnesandnoble.com/",setting:"indoor",walking:"someWalking",goodFor:["seniors"],highlight:false,free:false,recurring:true},
{id:4719,name:"Lion's Mouth Bookstore (Indie + Cafe!)",cat:"Shop",sub:"Bookstore",date:"",dateLabel:"Mon-Fri 9-6, Sat 9-5, Sun 10-2",venue:"Lion's Mouth Bookstore",loc:"Downtown Green Bay",addr:"211 N Washington St, Ste 107, Green Bay, WI 54301",desc:"Independent bookstore with new and used books, gifts, and cafe! Support local. (920) 406-0200.",url:"https://lionsmouthbookstore.com/",setting:"indoor",walking:"lowWalking",goodFor:["seniors","couples"],highlight:true,free:false,recurring:true},
{id:4720,name:"Rock N Roll Land (Vinyl + Live Music!)",cat:"Shop",sub:"Music",date:"",dateLabel:"Tue-Fri 11-5, Sat 10-5",venue:"Rock N Roll Land",loc:"West Green Bay",addr:"838 W Military Ave, Green Bay, WI 54303",desc:"New and used vinyl records, CDs, music memorabilia! Listening stations, buys collections. Live music venue too. (920) 490-2881.",url:"https://rocknrollland.com/",setting:"indoor",walking:"lowWalking",goodFor:["seniors","couples"],highlight:true,free:false,recurring:true},
// === BBQ ===
{id:4722,name:"MISSION BBQ (Smoked Meats + Military Tribute!)",cat:"Restaurant",sub:"BBQ",date:"",dateLabel:"Mon-Sat 11-9, Sun 11:30-8",venue:"MISSION BBQ",loc:"Ashwaubenon",addr:"2302 S Oneida St, Green Bay, WI 54304",desc:"Slow-smoked BBQ! Brisket, ribs, pulled pork, turkey breast. Patriotic theme with military tribute at noon daily. (920) 264-0874.",url:"https://mission-bbq.com/",setting:"indoor",walking:"lowWalking",goodFor:["seniors","family"],highlight:true,free:false,recurring:true,cuisine:"BBQ"},
{id:4723,name:"Parker John's BBQ & Pizza (Near Lambeau!)",cat:"Restaurant",sub:"BBQ",date:"",dateLabel:"Mon-Sat 11-9, Sun 11-8",venue:"Parker John's BBQ & Pizza",loc:"Ashwaubenon",addr:"2851 S Oneida St, Green Bay, WI 54304",desc:"Low-and-slow smoked meats PLUS pizza! Near Lambeau Field stadium corridor. Great combo for families who can't agree. (920) 405-6705.",url:"https://www.parkerjohns.com/",setting:"indoor",walking:"lowWalking",goodFor:["seniors","family"],highlight:false,free:false,recurring:true,cuisine:"BBQ"},
// === SENIOR FITNESS ===
{id:4725,name:"ADRC Bingocize (FREE Exercise + Bingo!)",cat:"Event",sub:"Senior Fitness",date:"2026-03-03",dateTo:"2026-05-07",dateLabel:"Tue & Thu 11am-noon, Mar 3-May 7 (FREE!)",venue:"ADRC of Brown County",loc:"Downtown Green Bay",addr:"300 S Adams St, Green Bay, WI 54301",desc:"FREE exercise program combined with BINGO! Tue & Thu 11am-noon at ADRC. Fall prevention focus. Fun way to stay active. Register: (920) 448-4300.",url:"https://adrcofbrowncounty.org/",setting:"indoor",walking:"lowWalking",goodFor:["seniors"],highlight:true,free:true,recurring:false},
{id:4726,name:"Empowered By Movement (Music + Dance, Seniors!)",cat:"Activity",sub:"Senior Fitness",date:"",dateLabel:"Tuesdays 1:30-2:45pm (FREE from Apr 2026!)",venue:"Western Racquet & Fitness Club",loc:"Green Bay",addr:"2500 S Ashland Ave, Green Bay, WI",desc:"Creative music & movement for older adults and Parkinson's-friendly! Seated or standing. In person or Zoom. FREE from April 2026 (donor-supported). Tuesdays 1:30-2:45pm.",url:"https://empoweredbymovement.org/",setting:"indoor",walking:"lowWalking",goodFor:["seniors"],highlight:true,free:true,recurring:true},
{id:4727,name:"Prevea Walk Into the Weekend (FREE Fri Walks!)",cat:"Activity",sub:"Walking",date:"",dateLabel:"Fridays 7:30-8:30am (summer, FREE!)",venue:"Various Green Bay routes",loc:"Green Bay",addr:"Various routes (emailed weekly)",desc:"FREE guided walking group! Fridays 7:30-8:30am, roughly June-September. Routes emailed weekly. Pre-registration required. Prevea Health organized.",url:"https://www.prevea.com/",setting:"outdoor",walking:"someWalking",goodFor:["seniors"],highlight:true,free:true,recurring:true},
// === SANDWICH SHOPS ===
{id:4729,name:"Not By Bread Alone (Scratch Soups + House Bread!)",cat:"Restaurant",sub:"Deli",date:"",dateLabel:"Lunch hours",venue:"Not By Bread Alone",loc:"Ashwaubenon",addr:"940 Hansen Rd, Green Bay, WI 54304",desc:"Long-running local lunch spot! Scratch soups, salads, sandwiches on HOUSE-MADE bread. A Green Bay favorite. (920) 429-9422.",url:"",setting:"indoor",walking:"lowWalking",goodFor:["seniors"],highlight:true,free:false,recurring:true,cuisine:"Deli"},
{id:4730,name:"Freddy's Frozen Custard & Steakburgers",cat:"Restaurant",sub:"Casual American",date:"",dateLabel:"Daily ~10:30am-10/11pm",venue:"Freddy's",loc:"Bellevue",addr:"2415 Costco Way, Green Bay, WI 54311",desc:"Steakburgers cooked-to-order + frozen custard! Shakes, concrete sundaes. Opened 2023. Great value casual dining. (920) 301-3791.",url:"",setting:"indoor",walking:"lowWalking",goodFor:["seniors","family"],highlight:false,free:false,recurring:true,cuisine:"Burgers"},
// === FISHING ===
{id:4732,name:"Sturgeon Spearing Season (Feb 14 - Mar 1!)",cat:"Event",sub:"Nature",date:"2026-02-14",dateTo:"2026-03-01",dateLabel:"Feb 14 - Mar 1 (Lake Winnebago, ~1hr south)",venue:"Lake Winnebago System",loc:"Fond du Lac area (~1hr south)",addr:"Lake Winnebago, WI",desc:"Wisconsin's ICONIC winter tradition! Sturgeon spearing on Lake Winnebago system. Feb 14-Mar 1, 2026 (or until caps close). Resident license $20. Shanty towns, family permits, registration stations.",url:"https://dnr.wisconsin.gov/topic/fishing/sturgeon",setting:"outdoor",walking:"someWalking",goodFor:["seniors","family"],highlight:true,free:false,recurring:false},
];

let newStr = '';
for (const e of entries) {
  const descEsc = e.desc.replace(/"/g, '\\"');
  const nameEsc = e.name.replace(/"/g, '\\"');
  let s = ',\n{id:' + e.id + ',name:"' + nameEsc + '",cat:"' + e.cat + '",sub:"' + e.sub + '"';
  s += ',price:"' + (e.free ? 'free' : '$$') + '",priceNum:' + (e.free ? 0 : 2);
  s += ',date:"' + (e.date||'') + '"';
  if (e.dateTo) s += ',dateTo:"' + e.dateTo + '"';
  s += ',dateLabel:"' + (e.dateLabel || '') + '"';
  s += ',venue:"' + e.venue + '"';
  s += ',desc:"' + descEsc + '"';
  s += ',url:"' + (e.url || '') + '"';
  s += ',setting:"' + e.setting + '",walking:"' + e.walking + '"';
  s += ',goodFor:' + JSON.stringify(e.goodFor);
  s += ',highlight:' + e.highlight;
  s += ',cuisine:"' + (e.cuisine || '') + '",established:""';
  s += ',free:' + e.free + ',recurring:' + (e.recurring || false) + '}';
  newStr += s;
}

const lastEntry = 'free:true,recurring:true}';
const idx = html.lastIndexOf(lastEntry);
if (idx === -1) { console.log('ERROR: insertion point not found'); process.exit(1); }
html = html.substring(0, idx + lastEntry.length) + newStr + html.substring(idx + lastEntry.length);

fs.writeFileSync(path, html, 'utf8');
console.log('Added ' + entries.length + ' entries (IDs ' + Math.min(...entries.map(e=>e.id)) + '-' + Math.max(...entries.map(e=>e.id)) + ')');
console.log('File size: ' + Buffer.byteLength(html, 'utf8'));
