const fs = require('fs');
const path = 'C:/Users/shawn/Downloads/Green Bay Explorer.html';
let html = fs.readFileSync(path, 'utf8');

const entries = [
// === KAYAK / PADDLEBOARD ===
{id:4200,name:"Hang Loose Rentals — Kayak & SUP Delivery!",cat:"Activity",sub:"Water Sports",date:"",dateLabel:"May-Sep, daily 7:30am-8:30pm",venue:"Hang Loose Rentals",loc:"Green Bay (mobile delivery)",addr:"1352 Kellogg St, Green Bay, WI 54303",desc:"Kayak & SUP rentals with FREE delivery to launches in Suamico, Howard, Green Bay, De Pere! 1hr $15, 2hr $20, full day $50. Pontoon rentals too. Easy for seniors.",url:"",setting:"outdoor",walking:"someWalking",goodFor:["seniors","couples"],highlight:true,free:false,recurring:true},
{id:4201,name:"Foxy Paddler — Fox River Pedal-Powered Cruise!",cat:"Activity",sub:"Water Sports",date:"",dateLabel:"Seasonal (departs Leicht Park, 2hr trips)",venue:"Foxy Paddler",loc:"Downtown Green Bay",addr:"128 Dousman St, Green Bay, WI 54303",desc:"Pedal-powered pontoon cruises on the Fox River! Mix & mingle $45-47/person. Pedaling is optional — great for seniors! Departs Leicht Memorial Park.",url:"",setting:"outdoor",walking:"lowWalking",goodFor:["seniors","couples"],highlight:true,free:false,recurring:true},
{id:4202,name:"Fox River Kayaking Co. — Guided Tours!",cat:"Activity",sub:"Water Sports",date:"",dateLabel:"Seasonal (~3hr trips, $70/person)",venue:"Fox River Kayaking Co.",loc:"De Pere/Fox Valley",addr:"1353 N Lake St, Neenah, WI 54956",desc:"Guided kayak tours! De Pere Lock paddle with wildlife/beaver viewing. Novice-friendly sit-on-tops. $70/person, 15% off groups 10+. Sunset options available.",url:"https://foxriverkayakingcompany.com/",setting:"outdoor",walking:"someWalking",goodFor:["seniors","couples"],highlight:true,free:false,recurring:true},
// === GOLF (more) ===
{id:4204,name:"Wander Springs Golf (Senior $27 for 18! Ages 60+)",cat:"Activity",sub:"Golf",date:"",dateLabel:"Mon-Fri senior 18-hole: $27 (weekdays only)",venue:"Wander Springs Golf Course",loc:"Greenleaf (25 min)",addr:"4342 Wayside Rd, Greenleaf, WI 54126",desc:"Best senior deal around! 60+ weekday: 18 holes just $27, 9 holes $17. Beautiful course in Greenleaf. After 5pm unlimited play $20 walk. Tax included.",url:"https://wandersprings.com/",setting:"outdoor",walking:"someWalking",goodFor:["seniors"],highlight:true,free:false,recurring:true},
{id:4205,name:"Crystal Springs Golf (Senior $28 for 18! Ages 55+)",cat:"Activity",sub:"Golf",date:"",dateLabel:"Mon-Fri senior 18-hole walk: $28 (55+)",venue:"Crystal Springs Golf Course",loc:"Seymour (30 min)",addr:"N8055 French Rd, Seymour, WI 54165",desc:"Senior (55+) weekday 18-hole: $28 walk, $48 with cart. After 5pm unlimited play $20! Wednesday Night Women's League. Great value.",url:"https://www.crystalspringsgolf.com/",setting:"outdoor",walking:"someWalking",goodFor:["seniors"],highlight:true,free:false,recurring:true},
{id:4206,name:"Twin Oaks Golf (Senior $28 for 18! Ages 60+)",cat:"Activity",sub:"Golf",date:"",dateLabel:"Mon-Fri senior 18-hole walk: $28 (60+)",venue:"Twin Oaks Golf Course",loc:"Denmark (20 min)",addr:"4871 County Rd R, Denmark, WI 54208",desc:"Senior (60+) weekday: 18 holes $28 walk, 9 holes $18. Range buckets $6-13. Beautiful Denmark countryside. Not valid with league play.",url:"https://golftwinoaks.com/",setting:"outdoor",walking:"someWalking",goodFor:["seniors"],highlight:true,free:false,recurring:true},
// === MUSEUM EVENTS ===
{id:4208,name:"Railroad Museum — Great Pumpkin Train!",cat:"Event",sub:"Family",date:"2026-10-10",dateTo:"2026-10-11",dateLabel:"Sat-Sun Oct 10-11, 9am-5pm",venue:"National Railroad Museum",loc:"Ashwaubenon",addr:"2285 S Broadway, Green Bay, WI 54304",desc:"Pumpkin patch train ride, haunted house, crafts, live entertainment! $20 ages 2+. Tickets on sale July 2026. Sells out fast!",url:"https://nationalrrmuseum.org/the-great-pumpkin-train/",setting:"outdoor",walking:"someWalking",goodFor:["family"],highlight:true,free:false,recurring:false},
{id:4209,name:"Railroad Museum — Festival of Trees (FREE w/ Admission!)",cat:"Event",sub:"Holiday Lights",date:"2026-11-19",dateTo:"2027-01-03",dateLabel:"Nov 19, 2026 - Jan 3, 2027 (museum hours)",venue:"National Railroad Museum",loc:"Ashwaubenon",addr:"2285 S Broadway, Green Bay, WI 54304",desc:"Beautiful holiday tree displays! Included with daily admission (Senior $12). Over 6 weeks of festive trees. Pair with Polar Express!",url:"https://nationalrrmuseum.org/festival-of-trees/",setting:"indoor",walking:"lowWalking",goodFor:["seniors","family"],highlight:true,free:false,recurring:false},
{id:4210,name:"Green Bay Botanical Garden — Spring Blooms!",cat:"Event",sub:"Nature / Birding",date:"2026-05-02",dateTo:"2026-05-26",dateLabel:"Daily May 2-26, 9am-8pm",venue:"Green Bay Botanical Garden",loc:"East Green Bay",addr:"2600 Larsen Rd, Green Bay, WI 54303",desc:"350,000+ spring blooms! Included with daily admission (Senior/AAA/AARP $13). BOGO Wednesdays Jun-Aug. Beautiful gardens and walking paths.",url:"https://www.gbbg.org/",setting:"outdoor",walking:"someWalking",goodFor:["seniors","couples","family"],highlight:true,free:false,recurring:false},
{id:4211,name:"Botanical Garden — Fall Festival (FREE ADMISSION!)",cat:"Event",sub:"Festival",date:"2026-09-27",dateLabel:"Sun Sep 27, 9am-6:30pm (activities 9-4)",venue:"Green Bay Botanical Garden",loc:"East Green Bay",addr:"2600 Larsen Rd, Green Bay, WI 54303",desc:"FREE admission all day! Activities 9-4 with workshops, vendors, food. Suggested donation $5/person or $20/family. A gorgeous fall day out.",url:"https://www.gbbg.org/",setting:"outdoor",walking:"someWalking",goodFor:["seniors","couples","family"],highlight:true,free:true,recurring:false},
// === ADRC / SENIOR SERVICES ===
{id:4213,name:"ADRC of Brown County — FREE Programs!",cat:"Activity",sub:"Senior Services",date:"",dateLabel:"Mon-Fri 8am-4:30pm (300 S Adams St)",venue:"ADRC of Brown County",loc:"Downtown Green Bay",addr:"300 S Adams St, Green Bay, WI 54301",desc:"FREE programs for seniors! Bingocize, StrongBodies, Walk With Ease, Medicare help, caregiver support groups, falls prevention. Call (920) 448-4300.",url:"https://adrcofbrowncounty.org/",setting:"indoor",walking:"lowWalking",goodFor:["seniors"],highlight:true,free:true,recurring:true},
{id:4214,name:"YMCA Green Bay — SilverSneakers Accepted!",cat:"Activity",sub:"Fitness",date:"",dateLabel:"6 locations, early 5am openings!",venue:"Greater Green Bay YMCA",loc:"Multiple Locations",addr:"380 Broadview Dr, Green Bay, WI 54301",desc:"6 branches accept SilverSneakers, Renew Active, Silver&Fit! Pools, group exercise, strength training. Senior single ~$44/mo if paying out of pocket. Brain & Body Fitness program for early memory loss.",url:"https://www.greenbayymca.org/",setting:"indoor",walking:"someWalking",goodFor:["seniors"],highlight:true,free:false,recurring:true},
{id:4215,name:"Bellin Health Fitness — SilverSneakers Gym!",cat:"Activity",sub:"Fitness",date:"",dateLabel:"Check schedule",venue:"Bellin Health Fitness Center",loc:"Green Bay",addr:"Bellin Health Campus, Green Bay, WI",desc:"SilverSneakers, Renew Active, Silver&Fit, Active&Fit accepted! Senior single ~$44/mo (62+) out of pocket. Pool, group exercise, cardiac/pulmonary rehab available.",url:"https://bellin.org/",setting:"indoor",walking:"someWalking",goodFor:["seniors"],highlight:true,free:false,recurring:true},
// === ESCAPE ROOMS / VR ===
{id:4217,name:"Escape Room Wisconsin — 7 Adventures!",cat:"Activity",sub:"Entertainment",date:"",dateLabel:"Book online (~$35/person)",venue:"Escape Room Wisconsin",loc:"Ashwaubenon",addr:"985 Centennial St, Green Bay, WI 54304",desc:"7 escape room adventures! Alchemyst, Mystery Manor, Contest of Kings, and more. ~$35/person. Mental puzzles — great brain exercise. Private rooms, no running required.",url:"https://www.escaperoomwisconsin.com/",setting:"indoor",walking:"lowWalking",goodFor:["seniors","couples","family"],highlight:true,free:false,recurring:true},
{id:4218,name:"Edge VR Arcade — Virtual Reality!",cat:"Activity",sub:"Entertainment",date:"",dateLabel:"Wed-Sun (from $20/session)",venue:"Edge VR Arcade",loc:"Green Bay",addr:"2642 Packerland Dr, Green Bay, WI 54313",desc:"Virtual reality experiences! Booth VR $20-28, VR escape $28/person, Arena VR $10-28. Staff guides you to games matching your comfort level. Wed-Fri afternoon quietest.",url:"https://www.edgevrarcade.com/",setting:"indoor",walking:"lowWalking",goodFor:["family","couples"],highlight:true,free:false,recurring:true},
// === BOOKSTORES / ANTIQUES ===
{id:4220,name:"Book Stop (50,000+ Used Books!)",cat:"Shop",sub:"Books",date:"",dateLabel:"Mon-Fri 10-5, Sat 10-4",venue:"Book Stop",loc:"West Green Bay",addr:"603 S Military Ave, Green Bay, WI 54303",desc:"50,000+ used books! Trade credit available. Puzzles, bookish gifts. Cozy independent bookshop on Military Ave. Paradise for readers.",url:"https://www.bookstopinc.info/",setting:"indoor",walking:"lowWalking",goodFor:["seniors"],highlight:true,free:false,recurring:true},
{id:4221,name:"Rock N' Roll Land (Vinyl Records!)",cat:"Shop",sub:"Music/Records",date:"",dateLabel:"Tue-Fri 11-5, Sat 10-5",venue:"Rock N' Roll Land",loc:"Military Ave",addr:"838 Military Ave, Green Bay, WI 54303",desc:"Green Bay's vinyl destination! Large selection of new & used records, CDs, collectibles. Listening stations. Find that rare album you've been looking for.",url:"https://rocknrollland.com/",setting:"indoor",walking:"lowWalking",goodFor:["seniors","couples"],highlight:true,free:false,recurring:true},
{id:4222,name:"Antique Mall of Greater Green Bay (HUGE!)",cat:"Shop",sub:"Antiques",date:"",dateLabel:"Sun-Mon 10-6, Tue-Sat 12-8",venue:"Antique Mall of Greater Green Bay",loc:"De Pere",addr:"1358 Mid Valley Dr, De Pere, WI 54115",desc:"Massive multi-dealer antique mall! 2nd Saturday outdoor flea market (8am-2pm, free). Art Walk events. Endless treasures for collectors.",url:"",setting:"indoor",walking:"someWalking",goodFor:["seniors","couples"],highlight:true,free:false,recurring:true},
// === SCENIC / NATURE ===
{id:4224,name:"High Cliff State Park (Stunning Lake Winnebago Views!)",cat:"Park",sub:"Scenic Drive",date:"",dateLabel:"Year-round (35-50 min from GB)",venue:"High Cliff State Park",loc:"Sherwood (Calumet Co.)",addr:"N7630 State Park Rd, Sherwood, WI 54169",desc:"Niagara Escarpment cliffs with observation tower overlooking Lake Winnebago! Effigy mounds, lime kiln ruins, trails. Spectacular fall colors. State park pass required.",url:"https://dnr.wisconsin.gov/topic/parks/highcliff",setting:"outdoor",walking:"someWalking",goodFor:["seniors","couples","family"],highlight:true,free:false,recurring:true},
{id:4225,name:"Rustic Road R-8 (Scenic Suamico Loop!)",cat:"Activity",sub:"Scenic Drive",date:"",dateLabel:"Year-round (3-mile loop near Suamico)",venue:"Wisconsin Rustic Road R-8",loc:"Suamico",addr:"Off County IR, Suamico, WI",desc:"Official Wisconsin Rustic Road! 3-mile paved loop on Sunrise, Pine, and Westview roads. 45mph max. Near Barkhausen Preserve and Reforestation Camp. Lovely drive.",url:"https://wisconsindot.gov/Pages/travel/road/rustic-roads/rr8.aspx",setting:"outdoor",walking:"lowWalking",goodFor:["seniors","couples"],highlight:true,free:true,recurring:true},
// === COMMUNITY ===
{id:4227,name:"NEW Bird Alliance — Spring Birding Field Trips!",cat:"Event",sub:"Nature / Birding",date:"2026-04-04",dateTo:"2026-05-09",dateLabel:"Apr 4 (waterfowl 7am), Apr 30 (banquet), May 2 (Ken Euers), May 9 (songbirds 6:30am)",venue:"Various Green Bay locations",loc:"Green Bay area",addr:"Varies by trip",desc:"Expert-led birding trips! Apr 4: Spring Waterfowl Migration. Apr 30: Annual Banquet at Brickhouse, De Pere. May 2: Ken Euers cleanup+birds. May 9: Bay Beach songbirds. All welcome!",url:"https://newbirdalliance.org/",setting:"outdoor",walking:"someWalking",goodFor:["seniors"],highlight:true,free:true,recurring:false},
{id:4228,name:"Neville Museum — Holiday Memories of Downtown GB!",cat:"Event",sub:"Holiday",date:"2026-11-20",dateTo:"2027-01-31",dateLabel:"Nov 20, 2026 - Jan 2027",venue:"Neville Public Museum",loc:"Downtown Green Bay",addr:"210 Museum Pl, Green Bay, WI 54303",desc:"Beloved annual exhibit! Prange's holiday figures, Bruce the Spruce, nostalgic downtown Green Bay memories. Senior $10. A holiday tradition for all ages.",url:"https://www.nevillepublicmuseum.org/",setting:"indoor",walking:"lowWalking",goodFor:["seniors","family"],highlight:true,free:false,recurring:false},
// === PIZZA (more) ===
{id:4230,name:"Cocoon Brewing — Brick-Fired Neapolitan Pizza!",cat:"Restaurant",sub:"Pizza",date:"",dateLabel:"Mon-Wed 3-9, Thu-Sat 11-11, Sun 11-7/8",venue:"Cocoon Brewing",loc:"De Pere",addr:"2233 Kaftan Wy, De Pere, WI 54115",desc:"Brick-fired Neapolitan-style pizza + craft beer! Seasonal pies, full bar. Beautiful De Pere location. The best wood-fired pizza in the Green Bay area.",url:"",setting:"indoor",walking:"lowWalking",goodFor:["couples","seniors"],highlight:true,free:false,recurring:true,cuisine:"Pizza"},
// === LENTEN FISH FRY ===
{id:4232,name:"Holy Cross Lenten Fish Fry ($15 — Knights of Columbus!)",cat:"Event",sub:"Fish Fry",date:"2026-02-13",dateTo:"2026-03-27",dateLabel:"Fridays Feb 13 - Mar 27, 4-7pm",venue:"Holy Cross Parish Hall",loc:"Bay Settlement",addr:"3009 Bay Settlement Rd, Green Bay, WI 54311",desc:"$15 fish dinner! Fried, baked, or shrimp. Includes roll, slaw, potato, desserts, drinks. Knights of Columbus #7414. Classic Wisconsin Lenten tradition.",url:"https://holycrossdov.org/lenten-fish-fry/",setting:"indoor",walking:"lowWalking",goodFor:["seniors","family"],highlight:true,free:false,recurring:false,cuisine:"Fish Fry"},
// === RESTAURANTS ===
{id:4234,name:"Al's Hamburgers (Since 1934 — The Green Bay Classic!)",cat:"Restaurant",sub:"American",date:"",dateLabel:"Mon 11-2, Tue-Thu 11-7, Fri-Sat 11-8, Sun 11-7",venue:"Al's Hamburgers",loc:"Downtown Green Bay",addr:"131 S Washington St, Green Bay, WI 54301",desc:"Green Bay institution since 1934! Butter-bun burgers, malts, shakes from a real malt shop counter. Late-night Fri-Sat to-go window. You MUST visit Al's.",url:"",setting:"indoor",walking:"lowWalking",goodFor:["seniors","family","couples"],highlight:true,free:false,recurring:true,cuisine:"Burgers"},
{id:4235,name:"Gyro Kabobs (Mediterranean in De Pere!)",cat:"Restaurant",sub:"Mediterranean",date:"",dateLabel:"Mon-Fri 11-4 (closed weekends)",venue:"Gyro Kabobs",loc:"De Pere",addr:"337 Main Ave, De Pere, WI 54115",desc:"Gyros, Greek salad, falafel, kabobs! Quick lunch spot on Main Ave in De Pere. Fresh Mediterranean flavors. Mon-Fri lunch only.",url:"",setting:"indoor",walking:"lowWalking",goodFor:["seniors","couples"],highlight:true,free:false,recurring:true,cuisine:"Mediterranean"},
// === WINE EVENTS ===
{id:4237,name:"Door County Wine Fest (27th Annual!)",cat:"Event",sub:"Food",date:"2026-06-27",dateLabel:"Sat Jun 27 (VIP 11am, GA noon, last call 3:45pm)",venue:"About Thyme Farm",loc:"Baileys Harbor (Door Co.)",addr:"Baileys Harbor, WI",desc:"27th annual wine festival! 10+ wineries, GA $65-75, VIP $85-95 with wine & cheese pairings + lounge. DD $15. Beautiful farm setting in Door County.",url:"https://www.doorcountywinefest.com/",setting:"outdoor",walking:"someWalking",goodFor:["seniors","couples"],highlight:true,free:false,recurring:false},
{id:4238,name:"von Stiehl Wet Whistle Wine Festival!",cat:"Event",sub:"Food",date:"2026-09-18",dateTo:"2026-09-19",dateLabel:"Fri Sep 18 5-9pm (FREE!) & Sat Sep 19 10am-6pm ($10)",venue:"von Stiehl Winery",loc:"Algoma (45 min)",addr:"115 Navarino St, Algoma, WI 54201",desc:"Grape stomps, wine tastings, live music, festival food! Friday FREE admission 5-9pm. Saturday $10 (under 12 free). A must-do wine event!",url:"https://vonstiehl.com/",setting:"outdoor",walking:"someWalking",goodFor:["seniors","couples"],highlight:true,free:false,recurring:false},
// === MORE ENTERTAINMENT ===
{id:4240,name:"Player 2 Arcade Bar (Downtown GB!)",cat:"Bar/Nightlife",sub:"Entertainment",date:"",dateLabel:"Mon-Thu 4pm-2am, Fri 2pm-2am, Sat-Sun 11am-2am",venue:"Player 2 Arcade Bar",loc:"Downtown Green Bay",addr:"219 N Washington St, Green Bay, WI 54301",desc:"Retro arcade bar! Classic games ~25-50 cents. Under 21 allowed until 8pm with guardian. 21+ after 8pm. Fun for everyone during the day!",url:"",setting:"indoor",walking:"lowWalking",goodFor:["family","couples"],highlight:true,free:false,recurring:true},
{id:4241,name:"Midwest Super Speedway — Indoor Go-Karts!",cat:"Activity",sub:"Entertainment",date:"",dateLabel:"Daily (Mon-Thu 11-9, Fri-Sat 10-11, Sun 10-8)",venue:"Midwest Super Speedway",loc:"Near Lambeau",addr:"1016 Tony Canadeo Run, Green Bay, WI",desc:"Indoor electric go-karts! ~$28/10-lap adult race. Junior karts for ages 6-12. Fun adrenaline rush near Lambeau Field.",url:"https://www.midwestsuperspeedway.com/",setting:"indoor",walking:"lowWalking",goodFor:["family"],highlight:true,free:false,recurring:true},
// === HOLIDAY ===
{id:4243,name:"Green Bay Holiday Parade (42nd Annual, FREE!)",cat:"Event",sub:"Parade",date:"2026-11-21",dateLabel:"Sat Nov 21, 10-11am",venue:"Downtown Green Bay",loc:"Downtown Green Bay",addr:"Downtown Green Bay, WI",desc:"42nd annual holiday parade! Downtown Green Bay, 10-11am. Floats, bands, Santa! Presented by HSHS St. Vincent Children's Hospital. FREE to watch. Bundle up!",url:"https://downtowngreenbay.com/parade",setting:"outdoor",walking:"lowWalking",goodFor:["family","seniors"],highlight:true,free:true,recurring:false},
{id:4244,name:"Celebrate De Pere (Memorial Day Weekend!)",cat:"Event",sub:"Festival",date:"2026-05-23",dateTo:"2026-05-25",dateLabel:"Sat-Mon May 23-25",venue:"Downtown De Pere / Riverfront",loc:"De Pere",addr:"Downtown De Pere, WI 54115",desc:"30+ year Memorial Day tradition! Marketplace, national bands, fireworks, veteran tributes. Mon parade at 10am. Free Mon programming. De Pere's biggest party!",url:"https://www.celebratedepere.com/",setting:"outdoor",walking:"someWalking",goodFor:["family","seniors","couples"],highlight:true,free:false,recurring:false},
];

let newStr = '';
for (const e of entries) {
  const descEsc = e.desc.replace(/"/g, '\\"');
  const nameEsc = e.name.replace(/"/g, '\\"');
  let s = ',\n{id:' + e.id + ',name:"' + nameEsc + '",cat:"' + e.cat + '",sub:"' + e.sub + '"';
  s += ',price:"' + (e.free ? 'free' : '$$') + '",priceNum:' + (e.free ? 0 : 2);
  s += ',date:"' + (e.date||'') + '"';
  if (e.dateTo) s += ',dateTo:"' + e.dateTo + '"';
  s += ',dateLabel:"' + (e.dateLabel || '') + '"';
  s += ',venue:"' + e.venue + '"';
  s += ',desc:"' + descEsc + '"';
  s += ',url:"' + (e.url || '') + '"';
  s += ',setting:"' + e.setting + '",walking:"' + e.walking + '"';
  s += ',goodFor:' + JSON.stringify(e.goodFor);
  s += ',highlight:' + e.highlight;
  s += ',cuisine:"' + (e.cuisine || '') + '",established:""';
  s += ',free:' + e.free + ',recurring:' + (e.recurring || false) + '}';
  newStr += s;
}

const lastEntry = 'free:false,recurring:false}';
const idx = html.lastIndexOf(lastEntry);
if (idx === -1) { console.log('ERROR: insertion point not found'); process.exit(1); }
html = html.substring(0, idx + lastEntry.length) + newStr + html.substring(idx + lastEntry.length);

fs.writeFileSync(path, html, 'utf8');
console.log('Added ' + entries.length + ' entries (IDs ' + Math.min(...entries.map(e=>e.id)) + '-' + Math.max(...entries.map(e=>e.id)) + ')');
console.log('File size: ' + Buffer.byteLength(html, 'utf8'));
