const fs = require('fs');
const path = 'C:/Users/shawn/Downloads/Green Bay Explorer.html';
let html = fs.readFileSync(path, 'utf8');

const entries = [
// === PIZZA ===
{id:4800,name:"Gallagher's Pizza (4 Locations — Thin Crust!)",cat:"Restaurant",sub:"Pizza",date:"",dateLabel:"Daily 11-9/10 (4 locations!)",venue:"Gallagher's Pizza",loc:"Multiple Locations",addr:"2655 W Mason St, Green Bay, WI 54303",desc:"Thin crust, local ingredients, vegan/GF options! Also at 1651 S Webster (East), 330 Reid St (De Pere), 2306 Lineville Rd (Suamico). Lenten Friday seafood buffet!",url:"",setting:"indoor",walking:"lowWalking",goodFor:["seniors","family"],highlight:true,free:false,recurring:true,cuisine:"Pizza"},
{id:4801,name:"Cranky Pat's (Thin Crust Since 1950s!)",cat:"Restaurant",sub:"Pizza",date:"",dateLabel:"Mon-Sat 11-10 (closed Sun)",venue:"Cranky Pat's",loc:"Green Bay",addr:"709 Bellevue St, Green Bay, WI 54302",desc:"Thin crust since the 1950s! Pat's Special loaded pies, classic pub atmosphere. A Green Bay institution.",url:"",setting:"indoor",walking:"lowWalking",goodFor:["seniors","family"],highlight:true,free:false,recurring:true,cuisine:"Pizza"},
{id:4802,name:"Jake's Pizza (Downtown Specialty Pies!)",cat:"Restaurant",sub:"Pizza",date:"",dateLabel:"Wed-Sun 4-9pm (closed Mon-Tue)",venue:"Jake's Pizza",loc:"Downtown Green Bay",addr:"112 S Broadway St, Green Bay, WI 54303",desc:"Local specialty pies in downtown! Creative combinations, small intimate spot. (920) 437-5542.",url:"http://jakespizzagb.com/",setting:"indoor",walking:"lowWalking",goodFor:["couples"],highlight:false,free:false,recurring:true,cuisine:"Pizza"},
{id:4803,name:"Pizza Ranch (Buffet + Fried Chicken!)",cat:"Restaurant",sub:"Pizza",date:"",dateLabel:"Daily: lunch buffet 11-3, dinner 3-8:30",venue:"Pizza Ranch",loc:"Green Bay",addr:"2206 Main St, Green Bay, WI 54302",desc:"Pizza BUFFET plus fried chicken! Party rooms available. Great value for families and groups.",url:"",setting:"indoor",walking:"lowWalking",goodFor:["seniors","family"],highlight:false,free:false,recurring:true,cuisine:"Pizza"},
// === SUPPER CLUBS (WISCONSIN TRADITION!) ===
{id:4805,name:"Club Chalet Supper Club (Bay Views + Prime Rib!)",cat:"Restaurant",sub:"Supper Club",date:"",dateLabel:"Tue-Sat dinner (closed Sun-Mon)",venue:"Club Chalet Supper Club",loc:"East Green Bay",addr:"4642 Nicolet Dr, Green Bay, WI 54311",desc:"Classic Wisconsin supper club with BAY VIEWS! Prime rib, baby-back ribs, baked lobster, 40+ flavors of ice cream cocktails, salad bar. Friday fish fry! (920) 866-2341.",url:"https://www.clubchaletgb.com/",setting:"indoor",walking:"lowWalking",goodFor:["seniors","couples"],highlight:true,free:false,recurring:true,cuisine:"Supper Club"},
{id:4806,name:"River's Bend (Riverside Fine Dining Supper Club!)",cat:"Restaurant",sub:"Supper Club",date:"",dateLabel:"Tue-Sat dinner, Sun brunch 10-2 + dinner",venue:"River's Bend",loc:"Green Bay",addr:"792 Riverview Dr, Green Bay, WI 54303",desc:"Fine dining supper club on the river! Prime rib, walleye, Sunday brunch with carving/omelet stations + mimosas. Friday fish fry (perch/cod). (920) 544-9860.",url:"https://riversbendgb.com/",setting:"indoor",walking:"lowWalking",goodFor:["seniors","couples"],highlight:true,free:false,recurring:true,cuisine:"Supper Club"},
{id:4807,name:"Union Hotel (Historic 1880s De Pere Supper Club!)",cat:"Restaurant",sub:"Supper Club",date:"",dateLabel:"Wed-Sun dinner 5-9pm (closed Mon-Tue)",venue:"Union Hotel & Restaurant",loc:"De Pere",addr:"200 N Broadway, De Pere, WI 54115",desc:"Historic 1880s hotel! Hand-cut steaks, lobster ravioli, house rolls, relish tray culture. Art Deco details from 1930s remodel. Friday fish fry. (920) 336-6131.",url:"https://www.unionhoteldepere.com/",setting:"indoor",walking:"lowWalking",goodFor:["seniors","couples"],highlight:true,free:false,recurring:true,cuisine:"Supper Club"},
{id:4808,name:"Kropp's Supper Club (1904 Brick Building, WI Classic!)",cat:"Restaurant",sub:"Supper Club",date:"",dateLabel:"Limited nights (Wed/Fri/Sat typical — call)",venue:"Kropp's Supper Club",loc:"Howard",addr:"4570 Shawano Ave, Green Bay, WI 54313",desc:"Quintessential old Wisconsin! 1904 brick building, multi-generation family. Steaks (Maplewood Meats), fried chicken, perch, frog legs, Friday fish fry. (920) 865-7331.",url:"https://kroppssupperclub.com/",setting:"indoor",walking:"lowWalking",goodFor:["seniors","couples"],highlight:true,free:false,recurring:true,cuisine:"Supper Club"},
{id:4809,name:"Heritage Modern Supper Club (Near Lambeau!)",cat:"Restaurant",sub:"Supper Club",date:"",dateLabel:"Daily breakfast/lunch/dinner",venue:"Heritage (Legacy Hotel)",loc:"Ashwaubenon",addr:"1004 Brett Favre Pass, Green Bay, WI 54304",desc:"MODERN supper club near Lambeau! Upscale steaks, sea bass, duck, Grasshopper/Brandy Alexander ice cream cocktails. Friday fish fry. (920) 770-5900.",url:"https://legacygb.com/",setting:"indoor",walking:"lowWalking",goodFor:["seniors","couples"],highlight:true,free:false,recurring:true,cuisine:"Supper Club"},
{id:4810,name:"Wally's Spot Supper Club (Since 1948!)",cat:"Restaurant",sub:"Supper Club",date:"",dateLabel:"Bar 4pm, dinner 5pm (Tue lunch 11-1:30)",venue:"Wally's Spot Supper Club",loc:"Green Bay",addr:"1978 Main St, Green Bay, WI",desc:"Classic Wisconsin since 1948! Steaks, walleye, baked cod, homemade bread, salad bar. The ORIGINAL steakhouse supper club vibe. Friday fish fry. (920) 357-6813.",url:"https://www.wallysspot.com/",setting:"indoor",walking:"lowWalking",goodFor:["seniors","couples"],highlight:true,free:false,recurring:true,cuisine:"Supper Club"},
// === FISH FRY (WISCONSIN TRADITION!) ===
{id:4812,name:"Maricque's (Legendary Fish Fry Since 1932!)",cat:"Restaurant",sub:"Fish Fry",date:"",dateLabel:"Wed 4:30-10, Fri lunch 11-1:30 + dinner 4:30-10",venue:"Maricque's",loc:"Green Bay",addr:"1517 University Ave, Green Bay, WI 54302",desc:"Fish fry LEGEND since 1932! Perch, pike, cod, bluegill, catfish. Wednesday + Friday. Classic Wisconsin supper club lineage with Old Fashioneds. (920) 432-9871.",url:"https://www.greenbayfishfry.com/",setting:"indoor",walking:"lowWalking",goodFor:["seniors","couples"],highlight:true,free:false,recurring:true,cuisine:"Fish Fry"},
{id:4813,name:"Lenten Fish Fries (Fridays Feb-Mar at Churches!)",cat:"Event",sub:"Fish Fry / Lenten",date:"2026-02-20",dateTo:"2026-03-27",dateLabel:"Fridays Feb 20-Mar 27 (Lent 2026, 5-7pm typical)",venue:"Multiple Churches (Green Bay area)",loc:"Green Bay area",addr:"Various Green Bay churches",desc:"WISCONSIN CATHOLIC TRADITION! Church fish fries every Friday during Lent. Resurrection Parish (333 Hilltop), St. Bernard (2040 Hillside), KofC 11445, St. Matthew + more. ~$14-22/plate.",url:"",setting:"indoor",walking:"lowWalking",goodFor:["seniors","family"],highlight:true,free:false,recurring:false},
// === BARS / PUBS ===
{id:4815,name:"St. Brendan's Inn (Irish Pub on the River!)",cat:"Bar/Nightlife",sub:"Irish Pub",date:"",dateLabel:"Open daily",venue:"St. Brendan's Inn",loc:"Downtown Green Bay",addr:"234 S Washington St, Green Bay, WI 54301",desc:"Authentic Irish inn and pub with river views! Traditional Irish pub menu, whiskey + beer focus. Lodging available. One of downtown's most distinctive experiences.",url:"",setting:"indoor",walking:"lowWalking",goodFor:["seniors","couples"],highlight:true,free:false,recurring:true},
{id:4816,name:"Fox Harbor Pub & Grill (Riverfront + Fish Fry!)",cat:"Bar/Nightlife",sub:"Pub",date:"",dateLabel:"Open daily from 11am",venue:"Fox Harbor Pub & Grill",loc:"Downtown Green Bay",addr:"348 S Washington St, Green Bay, WI 54301",desc:"Downtown on the Fox River! Patio, boat docking, FRIDAY FISH FRY (hand-breaded perch, baked haddock, salmon). Great after-work/river-walk vibe.",url:"https://foxharborpubandgrill.com/",setting:"indoor",walking:"lowWalking",goodFor:["seniors","couples"],highlight:true,free:false,recurring:true},
{id:4817,name:"Cock & Bull Publick House (200+ Beers!)",cat:"Bar/Nightlife",sub:"Pub",date:"",dateLabel:"Open daily",venue:"Cock & Bull Publick House",loc:"Green Bay",addr:"1237 Main St, Green Bay, WI 54302",desc:"English-style pub in century-old brick building! 200+ specialty beers, pool, shuffleboard, darts. Strong Packers game following. A beer library!",url:"",setting:"indoor",walking:"lowWalking",goodFor:["seniors","couples"],highlight:true,free:false,recurring:true},
// === PICKLEBALL ===
{id:4819,name:"Edison Park Pickleball (10 Courts, FREE!)",cat:"Activity",sub:"Pickleball",date:"",dateLabel:"Dawn to dusk (FREE, 10 outdoor courts!)",venue:"Edison Park",loc:"Green Bay",addr:"442 Alpine Dr, Green Bay, WI",desc:"10 outdoor pickleball courts — FREE! Dawn to dusk. The FASTEST growing sport among seniors. Bring your own paddles and balls.",url:"https://greenbaywi.gov/869/Pickleball",setting:"outdoor",walking:"someWalking",goodFor:["seniors"],highlight:true,free:true,recurring:true},
{id:4820,name:"The Picklr Green Bay (7 Indoor Courts!)",cat:"Activity",sub:"Pickleball",date:"",dateLabel:"Daily 6am-11pm ($99/mo unlimited)",venue:"The Picklr",loc:"Ashwaubenon",addr:"2610 Holmgren Way, Green Bay, WI 54304",desc:"7 indoor pickleball courts! Open 6am-11pm daily. Memberships: $99/mo unlimited, $69/mo social, $199/mo family. Clinics, leagues, tournaments. Near Lambeau!",url:"https://thepicklr.com/location/green-bay/",setting:"indoor",walking:"someWalking",goodFor:["seniors"],highlight:true,free:false,recurring:true},
// === DISC GOLF ===
{id:4822,name:"Pamperin Park Disc Golf (18 Holes, FREE!)",cat:"Activity",sub:"Disc Golf",date:"",dateLabel:"Dawn to dusk (FREE, 18 holes, very hilly!)",venue:"Pamperin Park",loc:"Howard",addr:"2801 County Road RK, Howard, WI",desc:"18-hole disc golf course — FREE! Very hilly terrain with woods and pond/quarry areas. Challenging course. Brown County park with playground and shelters too.",url:"",setting:"outdoor",walking:"someWalking",goodFor:["family"],highlight:true,free:true,recurring:true},
// === MOVIE THEATERS ===
{id:4824,name:"Marcus Bay Park Cinema (Senior $7 Before 4pm!)",cat:"Activity",sub:"Movie Theater",date:"",dateLabel:"Daily (Senior 60+ matinee $7 before 4pm!)",venue:"Marcus Bay Park Cinema",loc:"Ashwaubenon",addr:"755 Willard Dr, Ashwaubenon, WI 54304",desc:"Major movie theater! SENIOR (60+) MATINEE $7 before 4pm. Value Tuesday ~$6-7. Young at Heart Friday: $3.50 popcorn/soda (60+). (920) 497-2453.",url:"https://www.marcustheatres.com/",setting:"indoor",walking:"lowWalking",goodFor:["seniors","couples"],highlight:true,free:false,recurring:true},
{id:4825,name:"Field of Scenes Drive-In (~20 min south!)",cat:"Activity",sub:"Movie Theater",date:"",dateLabel:"Seasonal (double feature! Adults $8, kids $4)",venue:"Field of Scenes",loc:"Freedom area (~20 min south)",addr:"N3712 WI-55, Freedom, WI",desc:"DRIVE-IN MOVIE THEATER! Double feature for $8 adults, $4 kids (11-4), 3 & under FREE. No advance tickets — first come first served. Seasonal. Bring a blanket!",url:"https://www.fieldofscenes.biz/",setting:"outdoor",walking:"lowWalking",goodFor:["seniors","family","couples"],highlight:true,free:false,recurring:true},
// === PARKS / SPLASH PADS ===
{id:4827,name:"Bay Beach Amusement Park (Rides from 25¢!)",cat:"Attraction",sub:"Amusement Park",date:"",dateLabel:"~May-Sep (rides 25¢ per ticket, 1-4 tix/ride!)",venue:"Bay Beach Amusement Park",loc:"Green Bay",addr:"1313 Bay Beach Rd, Green Bay, WI 54302",desc:"Classic amusement park with Zippin Pippin coaster! NO admission fee — rides 25¢ per ticket (most rides 1-4 tickets). Budget ~$7/person. Free parking. Grandkid heaven!",url:"https://greenbaywi.gov/445/Bay-Beach",setting:"outdoor",walking:"someWalking",goodFor:["seniors","family"],highlight:true,free:false,recurring:true},
{id:4828,name:"FREE Splash Pads (9 Locations Citywide!)",cat:"Activity",sub:"Splash Pad",date:"",dateLabel:"Summer, FREE! (9 parks across Green Bay)",venue:"Multiple City Parks",loc:"Green Bay",addr:"Various Green Bay parks",desc:"9 FREE splash pads! CityDeck (downtown), Fort Howard, Eastman, Red Smith, Farlin, Fisk, Bay View, Seymour, Tank parks. Bring towels. Perfect hot summer day with grandkids!",url:"https://www.greenbaywi.gov/819/Splashpads",setting:"outdoor",walking:"someWalking",goodFor:["family"],highlight:true,free:true,recurring:true},
{id:4829,name:"Barkhausen Waterfowl Preserve (9+ Mi Trails!)",cat:"Activity",sub:"Nature / Birding",date:"",dateLabel:"Trails dawn-dusk, center weekdays 9-4, weekends 12-4",venue:"L.H. Barkhausen Waterfowl Preserve",loc:"Suamico",addr:"2024 Lakeview Dr, Suamico, WI 54173",desc:"9+ miles of trails through marsh, meadow, forest! 200+ bird species. Interpretive center with exhibits. Sensory Woods trail for inclusive exploration. FREE. (920) 448-6242.",url:"https://www.browncountywi.gov/",setting:"outdoor",walking:"someWalking",goodFor:["seniors","family"],highlight:true,free:true,recurring:true},
{id:4830,name:"Wequiock Falls (Niagara Escarpment Waterfall!)",cat:"Attraction",sub:"Nature",date:"",dateLabel:"Dawn-dusk (FREE, short walk)",venue:"Wequiock Falls",loc:"East Green Bay",addr:"3426 Bay Settlement Rd, Green Bay, WI 54311",desc:"Seasonal waterfall on the Niagara Escarpment! Very short walk (~0.2 mi round trip). Jean Nicolet monument. Restrooms, drinking water. FREE county park.",url:"https://www.browncountywi.gov/",setting:"outdoor",walking:"lowWalking",goodFor:["seniors","family"],highlight:true,free:true,recurring:true},
// === BOWLING ===
{id:4832,name:"Ashwaubenon Bowling Alley (60 Lanes + Cosmic!)",cat:"Activity",sub:"Bowling",date:"",dateLabel:"Daily 10am+ (~$4-5/game, Cosmic Fri-Sat 9:30pm $15)",venue:"Ashwaubenon Bowling Alley",loc:"Ashwaubenon",addr:"2929 Allied St, Green Bay, WI 54304",desc:"60 lanes! Open bowling ~$4-5/game. COSMIC bowling Fri-Sat 9:30pm-1am ($15 AYCB + shoes). Full bar & restaurant, arcade. Birthday packages from $59.99/lane. (920) 336-0400.",url:"https://ashbowl.com/",setting:"indoor",walking:"lowWalking",goodFor:["seniors","family"],highlight:true,free:false,recurring:true},
{id:4833,name:"Riviera Lanes (Senior Leagues + Since ????)",cat:"Activity",sub:"Bowling",date:"",dateLabel:"Check hours ($3.50/game, MULTIPLE senior leagues!)",venue:"Riviera Lanes",loc:"Green Bay",addr:"2450 University Ave, Green Bay, WI 54302",desc:"Multiple SENIOR bowling leagues! Tue 9:30am, Thu 9:00am Oldtimers, Men's Retired 50+, Sat Golden Niners Couples. $3.50/game. Birthday parties $13-14/child. (920) 468-1815.",url:"http://www.rivieralanesgb.com/",setting:"indoor",walking:"lowWalking",goodFor:["seniors"],highlight:true,free:false,recurring:true},
// === WINERIES ===
{id:4835,name:"Captain's Walk Winery (Downtown GB Wine Bar!)",cat:"Bar/Nightlife",sub:"Winery",date:"",dateLabel:"Most days (hours vary by day)",venue:"Captain's Walk Winery",loc:"Downtown Green Bay",addr:"345 S Adams St, Green Bay, WI 54301",desc:"Urban winery in a historic house! Flights, glasses, bottles. Ciders and cocktails too. Dog-friendly porch. Small bites and pairings. (920) 431-9255.",url:"",setting:"indoor",walking:"lowWalking",goodFor:["seniors","couples"],highlight:true,free:false,recurring:true},
// === STEAKHOUSES ===
{id:4837,name:"Republic Chophouse (Dry-Aged Steaks + Seafood!)",cat:"Restaurant",sub:"Fine Dining",date:"",dateLabel:"Mon-Sun dinner 5-10/11",venue:"Republic Chophouse",loc:"Downtown Green Bay",addr:"218 N Adams St, Green Bay, WI 54301",desc:"Urban steakhouse! Dry-aged center-cut steaks, seafood towers, scallops, lobster, king crab. Special occasion dining. Reservations recommended.",url:"",setting:"indoor",walking:"lowWalking",goodFor:["couples"],highlight:true,free:false,recurring:true,cuisine:"Steakhouse"},
{id:4838,name:"Taverne in the Sky (Lambeau Views, 5th Floor!)",cat:"Restaurant",sub:"Fine Dining",date:"",dateLabel:"Daily (hours vary, reservations recommended)",venue:"Taverne in the Sky (Lodge Kohler)",loc:"Titletown",addr:"1950 S Ridge Rd, Green Bay, WI 54304",desc:"5th floor with VIEWS OF LAMBEAU! Wood-fired steaks, rotisserie chicken, two sommeliers, extensive wine list. Special occasion dining at its finest.",url:"https://www.lodgekohler.com/",setting:"indoor",walking:"lowWalking",goodFor:["couples"],highlight:true,free:false,recurring:true,cuisine:"Steakhouse"},
// === HOTELS ===
{id:4840,name:"Lodge Kohler (Luxury Titletown, Kohler Spa!)",cat:"Lodging",sub:"Hotel",date:"",dateLabel:"~$200-400+/night (near Lambeau!)",venue:"Lodge Kohler",loc:"Titletown",addr:"1950 S Ridge Rd, Green Bay, WI 54304",desc:"Luxury Titletown hotel with KOHLER WATERS SPA! Indoor pool, rooftop Taverne in the Sky, steps from Lambeau. Top pick for visiting family. Game weekends spike.",url:"https://www.lodgekohler.com/",setting:"indoor",walking:"lowWalking",goodFor:["couples"],highlight:true,free:false,recurring:true},
{id:4841,name:"Tundra Lodge (Waterpark Resort Near Lambeau!)",cat:"Lodging",sub:"Hotel",date:"",dateLabel:"~$90-220+/night (waterpark included!)",venue:"Tundra Lodge Resort & Waterpark",loc:"Ashwaubenon",addr:"865 Lombardi Ave, Green Bay, WI 54304",desc:"Indoor WATERPARK resort near Lambeau! Suite-style rooms. Perfect for families with grandkids. Many packages include waterpark access.",url:"https://www.tundralodge.com/",setting:"indoor",walking:"lowWalking",goodFor:["family"],highlight:true,free:false,recurring:true},
// === ESSENTIAL SERVICES ===
{id:4843,name:"DMV / DOT Green Bay (Licenses & Registration)",cat:"Service",sub:"Government",date:"",dateLabel:"Mon-Fri 8:30am-4:45pm",venue:"Wisconsin DOT Green Bay Service Center",loc:"Green Bay",addr:"942 Vanderperren Way, Green Bay, WI 54304",desc:"Wisconsin DOT customer service center for driver licenses, ID cards, vehicle registration, titles. Mon-Fri 8:30am-4:45pm.",url:"",setting:"indoor",walking:"lowWalking",goodFor:["seniors"],highlight:false,free:false,recurring:true},
{id:4844,name:"Social Security Office Green Bay",cat:"Service",sub:"Government",date:"",dateLabel:"Mon-Fri 9am-4pm (appointments recommended)",venue:"Social Security Administration",loc:"Green Bay",addr:"1561 Dousman St, Green Bay, WI 54303",desc:"Social Security field office for benefits, Medicare cards, disability claims. Appointments recommended — schedule at ssa.gov or call your local office.",url:"https://www.ssa.gov/",setting:"indoor",walking:"lowWalking",goodFor:["seniors"],highlight:false,free:true,recurring:true},
{id:4845,name:"Home Depot Green Bay (Hardware + Tool Rental!)",cat:"Shop",sub:"Hardware",date:"",dateLabel:"Mon-Sat 6am-10pm, Sun 8am-8pm",venue:"The Home Depot",loc:"West Green Bay",addr:"810 S Taylor St, Green Bay, WI 54303",desc:"Hardware, lumber, paint, appliances + TOOL RENTAL. Pro desk for contractors. Garden center. (920) 405-0893.",url:"https://www.homedepot.com/",setting:"indoor",walking:"someWalking",goodFor:["seniors"],highlight:false,free:false,recurring:true},
{id:4846,name:"Menards (2 Locations — WI Home Improvement!)",cat:"Shop",sub:"Hardware",date:"",dateLabel:"Long hours daily (2 metro locations!)",venue:"Menards",loc:"Multiple Locations",addr:"2300 Woodman Dr, Green Bay, WI 54303",desc:"Wisconsin-based home improvement! Also at 2560 Steffens Ct (East). Rebate promos on materials. (920) 497-7547.",url:"https://www.menards.com/",setting:"indoor",walking:"someWalking",goodFor:["seniors"],highlight:false,free:false,recurring:true},
// === PET SERVICES ===
{id:4848,name:"Safe Haven Pet Sanctuary (Cage-Free Cat Lounge!)",cat:"Attraction",sub:"Animals",date:"",dateLabel:"Tue-Sun (varies, closed Mon & Thu)",venue:"Safe Haven Pet Sanctuary",loc:"Downtown Green Bay",addr:"151 N Broadway, Green Bay, WI 54303",desc:"Cage-free CAT LOUNGE! Coffee, couches, WiFi. Many special needs cats. Yoga with cats events! 501(c)(3) nonprofit. Haven Books used bookstore supports mission. (920) 489-2462.",url:"",setting:"indoor",walking:"lowWalking",goodFor:["seniors","family"],highlight:true,free:false,recurring:true},
{id:4849,name:"24/7 Emergency Vet (Animal Referral Center!)",cat:"Service",sub:"Veterinary",date:"",dateLabel:"24/7 — 365 days a year",venue:"Animal Referral Center of Green Bay",loc:"Bellevue",addr:"2141 Lime Kiln Rd, Green Bay, WI 54311",desc:"24/7 EMERGENCY animal hospital! After-hours critical care when your regular vet is closed. Specialist-level equipment. Save this number: (920) 494-9400.",url:"",setting:"indoor",walking:"lowWalking",goodFor:["seniors"],highlight:true,free:false,recurring:true},
// === SENIOR LIVING ===
{id:4851,name:"Woodside Senior Communities (Full Campus!)",cat:"Service",sub:"Senior Living",date:"",dateLabel:"Multiple care levels on one campus",venue:"Woodside Senior Communities",loc:"Ashwaubenon",addr:"1040 Pilgrim Way, Green Bay, WI 54304",desc:"Full continuum! Skilled nursing (Woodside Lutheran Home), assisted living (Manor), memory care (Villa), independent living (Oaks), income-based (Haven). (920) 499-1481.",url:"",setting:"indoor",walking:"lowWalking",goodFor:["seniors"],highlight:true,free:false,recurring:true},
];

let newStr = '';
for (const e of entries) {
  const descEsc = e.desc.replace(/"/g, '\\"');
  const nameEsc = e.name.replace(/"/g, '\\"');
  let s = ',\n{id:' + e.id + ',name:"' + nameEsc + '",cat:"' + e.cat + '",sub:"' + e.sub + '"';
  s += ',price:"' + (e.free ? 'free' : '$$') + '",priceNum:' + (e.free ? 0 : 2);
  s += ',date:"' + (e.date||'') + '"';
  if (e.dateTo) s += ',dateTo:"' + e.dateTo + '"';
  s += ',dateLabel:"' + (e.dateLabel || '') + '"';
  s += ',venue:"' + e.venue + '"';
  s += ',desc:"' + descEsc + '"';
  s += ',url:"' + (e.url || '') + '"';
  s += ',setting:"' + e.setting + '",walking:"' + e.walking + '"';
  s += ',goodFor:' + JSON.stringify(e.goodFor);
  s += ',highlight:' + e.highlight;
  s += ',cuisine:"' + (e.cuisine || '') + '",established:""';
  s += ',free:' + e.free + ',recurring:' + (e.recurring || false) + '}';
  newStr += s;
}

const lastEntry = 'free:true,recurring:true}';
const idx = html.lastIndexOf(lastEntry);
if (idx === -1) { console.log('ERROR: insertion point not found'); process.exit(1); }
html = html.substring(0, idx + lastEntry.length) + newStr + html.substring(idx + lastEntry.length);

fs.writeFileSync(path, html, 'utf8');
console.log('Added ' + entries.length + ' entries (IDs ' + Math.min(...entries.map(e=>e.id)) + '-' + Math.max(...entries.map(e=>e.id)) + ')');
console.log('File size: ' + Buffer.byteLength(html, 'utf8'));
