const fs = require('fs');
const path = 'C:/Users/shawn/Downloads/Green Bay Explorer.html';
let html = fs.readFileSync(path, 'utf8');

const entries = [
// === GREEN BAY BLIZZARD (IFL INDOOR FOOTBALL) ===
{id:3985,name:"Green Bay Blizzard — Indoor Football!",cat:"Event",sub:"Sports",date:"2026-03-21",dateTo:"2026-06-27",dateLabel:"Home games: Mar 21, Apr 18, Apr 24, May 8, May 29, Jun 12, Jun 27",venue:"Resch Center",loc:"Ashwaubenon",addr:"820 Armed Forces Dr, Ashwaubenon, WI 54304",desc:"Indoor football action at the Resch Center! Theme nights: Star Wars, Military Appreciation, Kids Night, Dairy Night. Group discounts 10+. Call 920-499-BLIZ.",url:"https://www.greenbayblizzard.com/",setting:"indoor",walking:"lowWalking",goodFor:["family","seniors","couples"],highlight:true,free:false,recurring:false},
// === PACKERS TRAINING CAMP ===
{id:3986,name:"Packers Training Camp (FREE! Late July)",cat:"Event",sub:"Packers",date:"2026-07-22",dateTo:"2026-08-15",dateLabel:"Late Jul - mid Aug (dates TBA, check packers.com)",venue:"Ray Nitschke Field / Lambeau",loc:"Ashwaubenon",addr:"1265 Lombardi Ave, Green Bay, WI 54304",desc:"Watch the Packers practice for FREE! Gates open ~90 min before practice (~10:30am). Bleacher seating first-come. DreamDrive, food trucks, autographs. Arrive early for shade! May move indoors (closed to public).",url:"https://www.packers.com/training-camp",setting:"outdoor",walking:"someWalking",goodFor:["seniors","family","couples"],highlight:true,free:true,recurring:false},
{id:3987,name:"Packers Family Night at Lambeau (~$12)",cat:"Event",sub:"Packers",date:"2026-08-01",dateLabel:"Early Aug (date TBA, ~Sat evening)",venue:"Lambeau Field",loc:"Ashwaubenon",addr:"1265 Lombardi Ave, Green Bay, WI 54304",desc:"Practice inside Lambeau Field with fireworks! ~$12 tickets via Ticketmaster. Doors ~5:30pm, practice ~7:30pm. Everyone needs a ticket. Pre-purchase parking pass!",url:"https://www.packers.com/familynight",setting:"outdoor",walking:"someWalking",goodFor:["seniors","family","couples"],highlight:true,free:false,recurring:false},
// === 1919 KITCHEN ===
{id:3988,name:"1919 Kitchen & Tap (Lambeau Field Restaurant)",cat:"Restaurant",sub:"American",date:"",dateLabel:"Mon-Thu 11-8, Fri-Sat 11-9, Sun 11-7",venue:"Lambeau Field",loc:"Ashwaubenon",addr:"1265 Lombardi Ave, Green Bay, WI 54304",desc:"Dine INSIDE Lambeau Field! Wisconsin-focused plates, burgers, shareables. Reservations on OpenTable. Weekly specials: Taco Tue, Wine Wed. Campus is cashless.",url:"https://www.1919kitchenandtap.com/",setting:"indoor",walking:"lowWalking",goodFor:["seniors","couples","family"],highlight:true,free:false,recurring:true,cuisine:"American"},
// === BELLIN RUN ===
{id:3990,name:"Bellin Run 10K & 5K — 50th Annual!",cat:"Event",sub:"Sports",date:"2026-06-13",dateLabel:"Sat Jun 13, 8am start",venue:"Webster Ave / Bellin Hospital",loc:"Green Bay",addr:"744 S Webster Ave, Green Bay, WI 54305",desc:"50th annual Bellin Run! One of the largest 10Ks in the US (~20K runners). 10K, 5K run/walk, virtual option. Walkers welcome (last corral). $35 early, $55 race day. Friday expo 3-8pm at Astor Park with pasta dinner ($9).",url:"https://www.bellinrun.com/",setting:"outdoor",walking:"someWalking",goodFor:["seniors","family","couples"],highlight:true,free:false,recurring:false},
// === EPIC MARATHON ===
{id:3991,name:"EPIC Marathon & Running Festival",cat:"Event",sub:"Sports",date:"2026-05-17",dateLabel:"Sun May 17 (marathon, half, 5K, kids dash)",venue:"EPIC Event Center",loc:"Ashwaubenon",addr:"2351 Holmgren Way, Green Bay, WI 54304",desc:"Full marathon, half marathon, 5K, relays, and kids dash! Start 7am. Marathon $125, Half $110, 5K $40. Expo Fri-Sat before. Successor to Cellcom Marathon.",url:"https://www.epicmarathon.com/",setting:"outdoor",walking:"someWalking",goodFor:["couples"],highlight:false,free:false,recurring:false},
// === TITLETOWN EVENTS ===
{id:3993,name:"Movies at Titletown (FREE!)",cat:"Event",sub:"Family",date:"2026-06-14",dateTo:"2026-07-26",dateLabel:"Jun 14: Tangled+Twisters, Jul 25: Cars, Jul 26: National Treasure",venue:"Ariens Hill, Titletown",loc:"Ashwaubenon",addr:"1065 Lombardi Ave, Green Bay, WI 54304",desc:"FREE outdoor movies on Ariens Hill! Bring blankets and lawn chairs. Activities 1 hour before showtime. Family-friendly fun next to Lambeau Field.",url:"https://www.titletown.com/events/movies-at-titletown",setting:"outdoor",walking:"lowWalking",goodFor:["family","couples","seniors"],highlight:true,free:true,recurring:false},
{id:3994,name:"Titletown Free Yoga (Summer Tuesdays & Thursdays)",cat:"Activity",sub:"Senior Fitness",date:"2026-06-15",dateTo:"2026-08-24",dateLabel:"Tue 6:30pm (football field) & Thu 5:30pm (square)",venue:"Titletown District",loc:"Ashwaubenon",addr:"1065 Lombardi Ave, Green Bay, WI 54304",desc:"FREE outdoor yoga all summer! Tuesdays 6:30pm on the Titletown Football Field, Thursdays 5:30pm at Titletown Square. Mats available. All levels welcome!",url:"https://www.titletown.com/",setting:"outdoor",walking:"lowWalking",goodFor:["seniors","couples"],highlight:true,free:true,recurring:true},
{id:3995,name:"Titletown Free Cardio Dance (Sundays!)",cat:"Activity",sub:"Senior Fitness",date:"2026-06-15",dateTo:"2026-08-24",dateLabel:"Sundays 9-9:45am, Jun-Aug",venue:"Hy-Vee Plaza, Titletown",loc:"Ashwaubenon",addr:"1065 Lombardi Ave, Green Bay, WI 54304",desc:"FREE Sunday morning cardio dance at Titletown! 9-9:45am on Hy-Vee Plaza. Fun, social, and a great way to start the day!",url:"https://www.titletown.com/",setting:"outdoor",walking:"lowWalking",goodFor:["seniors","couples"],highlight:true,free:true,recurring:true},
// === MULTICULTURAL ===
{id:3997,name:"UWGB Festival of Cultures (FREE!)",cat:"Event",sub:"Cultural",date:"2026-04-25",dateLabel:"Sat Apr 25, 11am-4pm",venue:"Richard Mauthe Center, UWGB",loc:"East Green Bay",addr:"2418 Leon Bond Dr, Green Bay, WI 54311",desc:"FREE multicultural festival! Student and community booths, performances, food vendors from around the world. First 100 students get free food item.",url:"https://www.uwgb.edu/",setting:"indoor",walking:"lowWalking",goodFor:["family","seniors","couples"],highlight:true,free:true,recurring:false},
{id:3998,name:"S.E.A. the Arts (Southeast Asian Arts Festival)",cat:"Event",sub:"Cultural",date:"2026-05-30",dateLabel:"Sat May 30, 11am-3pm",venue:"Stadium View Bar & Event Hall",loc:"Ashwaubenon",addr:"1963 Holmgren Way, Green Bay, WI 54304",desc:"Southeast Asian artists: performances, demos, food! Presented by Hmong Center of Green Bay. Day program free. Evening party follows.",url:"https://www.hmongcenterofgb.org/",setting:"indoor",walking:"lowWalking",goodFor:["seniors","family","couples"],highlight:true,free:true,recurring:false},
{id:3999,name:"Estamos Aqui! Festival Hispano (FREE!)",cat:"Event",sub:"Cultural",date:"2026-09-13",dateLabel:"Sun Sep 13 (confirm exact date)",venue:"UW-Green Bay campus",loc:"East Green Bay",addr:"2420 Nicolet Dr, Green Bay, WI 54311",desc:"FREE Hispanic Heritage festival! Live music, art, food, mercadito, car show. Kicks off Hispanic Heritage Month. Presented by The Weidner. Open to all!",url:"https://www.weidnercenter.com/",setting:"outdoor",walking:"someWalking",goodFor:["family","seniors","couples"],highlight:true,free:true,recurring:false},
// === BREWERIES ===
{id:4001,name:"Copper State Brewing — Tuesday Jazz Night!",cat:"Bar/Nightlife",sub:"Brewery",date:"",dateLabel:"Tuesdays 6-9pm (upstairs lounge)",venue:"Copper State Brewing Co.",loc:"Downtown Green Bay",addr:"313 Dousman St, Green Bay, WI 54303",desc:"Tuesday jazz & blues in the upstairs lounge! 6-9pm. No cover. Full gastropub kitchen with wood-fired pizza. Senior-friendly: quieter lounge, seated, early hours.",url:"https://www.copperstate.beer/",setting:"indoor",walking:"lowWalking",goodFor:["seniors","couples"],highlight:true,free:false,recurring:true,cuisine:"Brewpub"},
{id:4002,name:"Badger State Brewing (Monthly Trivia + Live Music)",cat:"Bar/Nightlife",sub:"Brewery",date:"",dateLabel:"Check calendar (Mon-Thu 3-10, Fri-Sat 12-12, Sun 12-8)",venue:"Badger State Brewing",loc:"Ashwaubenon",addr:"990 Tony Canadeo Run, Green Bay, WI 54304",desc:"Monthly themed trivia in the Barrel Haus (~6pm, teams up to 10). Regular live music. Dog-friendly beer garden! Pizza and snacks. Near Lambeau.",url:"https://badgerstatebrewing.com/",setting:"indoor",walking:"lowWalking",goodFor:["couples"],highlight:true,free:false,recurring:true,cuisine:"Brewpub"},
{id:4003,name:"Paradise North Distillery (Bay Views + Tours!)",cat:"Bar/Nightlife",sub:"Distillery",date:"",dateLabel:"Happy hour Wed-Fri 4-6pm",venue:"Paradise North Distillery",loc:"Bay Beach area",addr:"101 Bay Beach Rd, Green Bay, WI 54302",desc:"Craft spirits distillery with Bay of Green Bay views! Bookable tours with tastings + 10% off. Outside food welcome. Live music select evenings. Seasonal igloo rentals!",url:"https://www.paradisenorthdistillery.com/",setting:"indoor",walking:"lowWalking",goodFor:["seniors","couples"],highlight:true,free:false,recurring:true},
// === DAY TRIPS ===
{id:4005,name:"EAA AirVenture Oshkosh 2026 (World's Largest!)",cat:"Event",sub:"Day Trip",date:"2026-07-20",dateTo:"2026-07-26",dateLabel:"Mon-Sun Jul 20-26",venue:"Wittman Regional Airport, Oshkosh",loc:"Oshkosh (Day Trip)",addr:"3000 Poberezny Rd, Oshkosh, WI 54902",desc:"WORLD'S largest fly-in and air show! Daily $48 members/$69 non-members. EAA Museum open year-round (senior 62+ $13). ~1 hour from GB. Bring hat, sunscreen, portable seat!",url:"https://www.eaa.org/airventure",setting:"outdoor",walking:"someWalking",goodFor:["seniors","family","couples"],highlight:true,free:false,recurring:false},
{id:4006,name:"Waterfest Oshkosh 2026 (8 Concert Nights!)",cat:"Event",sub:"Day Trip",date:"2026-06-15",dateTo:"2026-08-17",dateLabel:"8 nights: Jun 15, 22, 29, Jul 13, 20, Aug 3, 10, 17",venue:"Leach Amphitheater, Oshkosh",loc:"Oshkosh (Day Trip)",addr:"Leach Amphitheater, Oshkosh, WI 54901",desc:"Summer concert series! 38 Special, Trombone Shorty, Ziggy Marley, Tower of Power, Warrant, and more! Gates ~5:45pm. Veterans FREE all season. ~1 hour from GB.",url:"https://www.waterfest.org/",setting:"outdoor",walking:"someWalking",goodFor:["seniors","couples"],highlight:true,free:false,recurring:false},
{id:4007,name:"Houdini Museum + History Museum at the Castle (Appleton)",cat:"Attraction",sub:"Day Trip",date:"",dateLabel:"Daily 10am-4pm",venue:"History Museum at the Castle",loc:"Appleton (Day Trip)",addr:"330 E College Ave, Appleton, WI 54911",desc:"Appleton was Houdini's hometown! Houdini collection + regional history. Adult $12. Museums for All $3 with SNAP. ~30 min from GB.",url:"https://myhistorymuseum.org/",setting:"indoor",walking:"someWalking",goodFor:["seniors","family"],highlight:true,free:false,recurring:true},
{id:4008,name:"Bergstrom-Mahler Museum of Glass (FREE! Neenah)",cat:"Attraction",sub:"Day Trip",date:"",dateLabel:"Tue-Sat 10-4:30, Thu til 8, Sun 1-4:30",venue:"Bergstrom-Mahler Museum of Glass",loc:"Neenah (Day Trip)",addr:"165 N Park Ave, Neenah, WI 54956",desc:"Stunning glass art museum with FREE admission! Paperweights, contemporary glass, rotating exhibits. GLASS Arts Festival Aug 8, 2026. ~30 min from GB.",url:"https://bmmglass.com/",setting:"indoor",walking:"lowWalking",goodFor:["seniors","couples"],highlight:true,free:true,recurring:true},
{id:4009,name:"Mile of Music Festival — FREE! (Appleton)",cat:"Event",sub:"Day Trip",date:"2026-07-30",dateTo:"2026-08-02",dateLabel:"Thu-Sun Jul 30 - Aug 2",venue:"Downtown Appleton",loc:"Appleton (Day Trip)",addr:"Downtown Appleton, WI 54911",desc:"FREE 4-day music festival across downtown Appleton! 200+ live original music performances. No festival ticket needed. ~30 min from GB.",url:"https://mileofmusic.com/",setting:"outdoor",walking:"someWalking",goodFor:["seniors","couples"],highlight:true,free:true,recurring:false},
// === DOOR COUNTY ADDITIONS ===
{id:4011,name:"Door County Maritime Museum (Senior $14!)",cat:"Attraction",sub:"Day Trip",date:"",dateLabel:"Daily (summer 9-5, winter 10-4)",venue:"Door County Maritime Museum",loc:"Sturgeon Bay (Day Trip)",addr:"120 N Madison Ave, Sturgeon Bay, WI 54235",desc:"Explore maritime history + tour the WWII tugboat John Purves! Senior (65+) $14 ($17 w/tug). FREE Community Appreciation Apr 3-4! Lighthouse Passport Days May-Oct.",url:"https://dcmm.org/",setting:"indoor",walking:"someWalking",goodFor:["seniors","family"],highlight:true,free:false,recurring:true},
{id:4012,name:"Steel Bridge Day — FREE! (Sturgeon Bay)",cat:"Event",sub:"Day Trip",date:"2026-06-13",dateLabel:"Sat Jun 13, noon-8pm",venue:"Martin Park & Downtown Sturgeon Bay",loc:"Sturgeon Bay (Day Trip)",addr:"Downtown Sturgeon Bay, WI 54235",desc:"FREE music festival celebrating Sturgeon Bay's iconic steel bridge! Live music at multiple venues. Part of Steel Bridge Songfest tradition.",url:"https://steelbridgesongfest.org/",setting:"outdoor",walking:"someWalking",goodFor:["seniors","couples"],highlight:true,free:true,recurring:false},
// === SPAS ===
{id:4014,name:"Kohler Waters Spa at Lodge Kohler (Titletown)",cat:"Activity",sub:"Spa & Wellness",date:"",dateLabel:"Mon-Thu 8:30am-8:30pm, Fri-Sun 7:30am-8:30pm",venue:"Lodge Kohler",loc:"Ashwaubenon",addr:"1950 S Ridge Rd, Green Bay, WI 54304",desc:"Luxury spa next to Lambeau! Hydrotherapy pool, thermal suite, sauna, steam. Deep Sleep Massage 80min $265. Himalayan salt stone 50min $195. The ultimate Green Bay pampering experience.",url:"https://www.lodgekohler.com/spa",setting:"indoor",walking:"lowWalking",goodFor:["seniors","couples"],highlight:true,free:false,recurring:true},
// === VOLUNTEER ===
{id:4016,name:"RSVP — Senior Volunteer Program (Ages 55+)",cat:"Activity",sub:"Volunteering / Senior",date:"",dateLabel:"Flexible schedule with 30+ partners",venue:"Volunteer Center of Brown County",loc:"West Green Bay",addr:"984 9th St, Green Bay, WI 54304",desc:"Retired Senior Volunteer Program! 30+ partner organizations. Tutoring, meal delivery, transportation, food pantries, Habitat ReStore. Mileage reimbursement + insurance provided!",url:"https://volunteergb.org/",setting:"indoor",walking:"lowWalking",goodFor:["seniors"],highlight:true,free:true,recurring:true},
// === BREAKFAST ===
{id:4018,name:"The Pancake Place (Best of Bay 16 Years!)",cat:"Restaurant",sub:"Breakfast",date:"",dateLabel:"Daily 5am-2pm",venue:"The Pancake Place",loc:"West Green Bay",addr:"143 Military Ave, Green Bay, WI 54303",desc:"Green Bay's legendary breakfast spot! 50 years, 16x Best of the Bay. Famous stuffed hash browns, stuffed pancakes, Benedicts. Huge portions. Go early weekends!",url:"https://www.thepancakeplacegb.com/",setting:"indoor",walking:"lowWalking",goodFor:["seniors","family","couples"],highlight:true,free:false,recurring:true,cuisine:"Breakfast"},
{id:4019,name:"River's Bend Sunday Brunch Buffet (Fox River Views!)",cat:"Restaurant",sub:"Breakfast",date:"",dateLabel:"Sundays 10am-2pm (reservations recommended)",venue:"River's Bend",loc:"East Green Bay",addr:"792 Riverview Dr, Green Bay, WI 54303",desc:"Sunday brunch buffet with Fox River views! Omelet station, carving station, salads, desserts, Bloody Marys & mimosas. Supper club quality. Since 1974.",url:"https://riversbendgb.com/",setting:"indoor",walking:"lowWalking",goodFor:["seniors","couples"],highlight:true,free:false,recurring:true,cuisine:"Brunch"},
{id:4020,name:"Black Honey Hashery (Creative Hashes & Brunch!)",cat:"Restaurant",sub:"Breakfast",date:"",dateLabel:"Wed-Sun 6am-2pm (closed Mon-Tue)",venue:"Black Honey Hashery",loc:"De Pere",addr:"1104 Honey Ct, De Pere, WI 54115",desc:"Creative hashes, Benedicts, biscuits & gravy! Drive-through + patio. Hidden gem brunch spot in De Pere. Known for unique flavor combos.",url:"",setting:"indoor",walking:"lowWalking",goodFor:["seniors","couples"],highlight:true,free:false,recurring:true,cuisine:"Breakfast"},
// === DOG PARKS ===
{id:4022,name:"Brown County Dog Park ($3/day, $25/year)",cat:"Park",sub:"Dog Park",date:"",dateLabel:"Daily dawn-dusk",venue:"Brown County Dog Park",loc:"Hobart",addr:"1000 Pleasant Ln, Hobart, WI 54313",desc:"~4 acres fenced with separate small-dog and all-dog sections! Shaded, tree-covered. Daily pass $3, annual $25. Dawn to dusk.",url:"https://www.browncountywi.gov/",setting:"outdoor",walking:"someWalking",goodFor:["seniors","family"],highlight:true,free:false,recurring:true},
{id:4023,name:"De Pere Dog Park (6 Acres, Wooded Trails!)",cat:"Park",sub:"Dog Park",date:"",dateLabel:"Daily 6am-10pm",venue:"De Pere Dog Park",loc:"De Pere",addr:"1400 Biotech Way, De Pere, WI 54115",desc:"~6 acres fenced with large/small areas, wooded trails, water features, agility equipment, shelter, benches, and restrooms! One of the best dog parks in the area.",url:"https://deperewi.gov/",setting:"outdoor",walking:"someWalking",goodFor:["seniors","family"],highlight:true,free:true,recurring:true},
// === GARDEN CENTERS / U-PICK ===
{id:4025,name:"Moder's Gardens — PYO Strawberries & Raspberries!",cat:"Activity",sub:"U-Pick Farm",date:"",dateLabel:"Mid-Jun - Jul (call for PYO dates)",venue:"Moder's Gardens",loc:"Howard / Suamico",addr:"3439 Lineville Rd, Green Bay, WI 54313",desc:"Pick-your-own strawberries (mid-June) and raspberries! Plus jams, maple syrup, farm market. A beloved local farm tradition. Call for current PYO availability.",url:"",setting:"outdoor",walking:"someWalking",goodFor:["seniors","family"],highlight:true,free:false,recurring:true},
{id:4026,name:"Potter Creek Lavender Farm (PYO Lavender!)",cat:"Activity",sub:"U-Pick Farm",date:"2026-07-01",dateTo:"2026-08-01",dateLabel:"July 2026 (check exact dates)",venue:"Potter Creek Lavender",loc:"Pulaski",addr:"3987 WI-32, Pulaski, WI 54162",desc:"Organic lavender farm! Pick your own lavender bundles in July. Body products, sachets. Beautiful and fragrant. ~20 min from Green Bay.",url:"https://pottercreeklavender.com/",setting:"outdoor",walking:"someWalking",goodFor:["seniors","couples"],highlight:true,free:false,recurring:true},
// === COMMUNITY ED ===
{id:4028,name:"UWGB Lifelong Learning Institute (Ages 50+!)",cat:"Activity",sub:"Education / Classes",date:"",dateLabel:"Fall & Spring semesters",venue:"UW-Green Bay campus",loc:"East Green Bay",addr:"2420 Nicolet Dr, Green Bay, WI 54311",desc:"No grades, no tests, just learning! Huge catalog: history, nature, culture, crafts, science. Annual membership $150, spring-only $100. In-person, online, and outdoor options.",url:"https://www.uwgb.edu/continuing-education/",setting:"indoor",walking:"lowWalking",goodFor:["seniors"],highlight:true,free:false,recurring:true},
{id:4029,name:"NWTC Artisan Center (Ceramics, Glass, Jewelry!)",cat:"Activity",sub:"Art Classes",date:"",dateLabel:"Check schedule (1417 Cedar St)",venue:"NWTC Artisan Center",loc:"Downtown Green Bay",addr:"1417 Cedar St, Green Bay, WI 54302",desc:"Hands-on workshops: ceramics, fused glass, drawing, jewelry, textiles, woodworking! Open studio memberships available. Classes ~$85-240. A creative oasis downtown.",url:"https://events.nwtc.edu/artisan-center",setting:"indoor",walking:"lowWalking",goodFor:["seniors","couples"],highlight:true,free:false,recurring:true},
{id:4030,name:"Green Bay Ballroom Dance (Ballroom, Swing, Latin!)",cat:"Activity",sub:"Entertainment",date:"",dateLabel:"Group classes ~7pm (check schedule)",venue:"Green Bay Ballroom",loc:"East Green Bay",addr:"525 N Taylor St, Green Bay, WI 54303",desc:"Ballroom, Latin, line dance, swing, Lindy Hop! Group classes ~$16/person. 5-week workshops ~$52. All levels welcome. Perfect for couples or solo dancers!",url:"https://www.greenbayballroom.com/",setting:"indoor",walking:"someWalking",goodFor:["seniors","couples"],highlight:true,free:false,recurring:true},
// === CAMPING ===
{id:4032,name:"Bay Shore County Park Camping (Bay Views!)",cat:"Activity",sub:"Camping",date:"",dateLabel:"Apr-Oct (W/E $34, rustic $22)",venue:"Bay Shore County Park",loc:"New Franken",addr:"5637 Sturgeon Bay Rd, Green Bay, WI 54229",desc:"107 sites on the Bay of Green Bay! 90 water/electric (30A+50A), 15 rustic. Showers, dump station, boat launch, WiFi near playground. Scenic Niagara Escarpment location.",url:"https://www.browncountywi.gov/",setting:"outdoor",walking:"someWalking",goodFor:["seniors","family","couples"],highlight:true,free:false,recurring:true},
{id:4033,name:"Reforestation Camp — Full Hookup RV Camping!",cat:"Activity",sub:"Camping",date:"",dateLabel:"Apr-Oct (FHU $44, W/E $34, rustic $22)",venue:"Reforestation Camp",loc:"Suamico",addr:"4418 Reforestation Rd, Green Bay, WI 54313",desc:"15 full hookup 50A sites ($44), 24 W/E 30A ($34), plus rustic and equestrian sites. Showers, dump station. Walk to the NEW Zoo! Reserve online via WebTrac.",url:"https://www.browncountywi.gov/",setting:"outdoor",walking:"someWalking",goodFor:["seniors","family"],highlight:true,free:false,recurring:true},
// === LIVE MUSIC ===
{id:4035,name:"The Bottle Room Wine Bar (Live Acoustic, No Cover!)",cat:"Bar/Nightlife",sub:"Live Music",date:"",dateLabel:"Weekends 7-10pm (no cover)",venue:"The Bottle Room",loc:"Howard",addr:"2300 Lineville Rd Ste 101, Green Bay, WI 54313",desc:"Light acoustic live music weekends 7-10pm. NO cover charge! Wine bar with great atmosphere. Senior-friendly: earlier hours, seated, not too loud.",url:"https://www.the-bottle-room.com/",setting:"indoor",walking:"lowWalking",goodFor:["seniors","couples"],highlight:true,free:false,recurring:true},
{id:4036,name:"Bark & Brew (Dog-Friendly Brewery!)",cat:"Bar/Nightlife",sub:"Brewery",date:"",dateLabel:"Check hours",venue:"Bark & Brew",loc:"Howard",addr:"2514 Glendale Ave, Howard, WI 54313",desc:"Dog-friendly brewery — dogs OFF-LEASH in designated areas! Beer, craft beverages. Unique concept: bring your pup for a pint. No outside dog treats allowed.",url:"",setting:"indoor",walking:"lowWalking",goodFor:["couples"],highlight:true,free:false,recurring:true},
// === HEARTHSTONE ===
{id:4038,name:"Hearthstone House — First Home Lit by Hydroelectric!",cat:"Attraction",sub:"Day Trip",date:"",dateLabel:"Thu-Sat tours 10:30, 12, 1:30, 3; Sun 1:30, 3",venue:"Hearthstone Historic House Museum",loc:"Appleton (Day Trip)",addr:"625 W Prospect Ave, Appleton, WI 54911",desc:"First home in the WORLD lit by a central-station hydroelectric Edison system! Guided tours of this stunning Victorian home. Museums for All participant. ~30 min from GB.",url:"https://www.hearthstonemuseum.org/",setting:"indoor",walking:"someWalking",goodFor:["seniors","couples"],highlight:true,free:false,recurring:true},
// === HAZELWOOD ===
{id:4039,name:"Hazelwood Historic House Museum (Senior $5!)",cat:"Attraction",sub:"Museum",date:"",dateLabel:"By appointment (call 920-437-1840)",venue:"Hazelwood Historic House",loc:"Green Bay",addr:"1008 S Monroe Ave, Green Bay, WI 54301",desc:"1837 Greek Revival house on its original lot! Senior (60+) $5, adults $6. By appointment through Brown County Historical Society. Rich early Green Bay history.",url:"https://browncohistoricalsoc.org/",setting:"indoor",walking:"lowWalking",goodFor:["seniors","couples"],highlight:true,free:false,recurring:true},
// === GREEN BAY WRITERS GUILD ===
{id:4040,name:"Green Bay Area Writers Guild (FREE Monthly!)",cat:"Activity",sub:"Social Club",date:"",dateLabel:"First Tuesday 5:30-7:30pm",venue:"Bay Family Restaurant",loc:"West Green Bay",addr:"1301 S Military Ave, Green Bay, WI 54303",desc:"FREE monthly writers group! No dues, guests welcome. Meet first Tuesday of every month at Bay Family Restaurant. Share your writing, get feedback, meet fellow writers.",url:"https://gbwriters.com/",setting:"indoor",walking:"lowWalking",goodFor:["seniors"],highlight:true,free:true,recurring:true},
];

let newStr = '';
for (const e of entries) {
  const descEsc = e.desc.replace(/"/g, '\\"');
  const nameEsc = e.name.replace(/"/g, '\\"');
  let s = ',\n{id:' + e.id + ',name:"' + nameEsc + '",cat:"' + e.cat + '",sub:"' + e.sub + '"';
  s += ',price:"' + (e.free ? 'free' : '$$') + '",priceNum:' + (e.free ? 0 : 2);
  s += ',date:"' + (e.date||'') + '"';
  if (e.dateTo) s += ',dateTo:"' + e.dateTo + '"';
  s += ',dateLabel:"' + (e.dateLabel || '') + '"';
  s += ',venue:"' + e.venue + '"';
  s += ',desc:"' + descEsc + '"';
  s += ',url:"' + (e.url || '') + '"';
  s += ',setting:"' + e.setting + '",walking:"' + e.walking + '"';
  s += ',goodFor:' + JSON.stringify(e.goodFor);
  s += ',highlight:' + e.highlight;
  s += ',cuisine:"' + (e.cuisine || '') + '",established:""';
  s += ',free:' + e.free + ',recurring:' + (e.recurring || false) + '}';
  newStr += s;
}

const lastEntry = 'free:true,recurring:true}';
const idx = html.lastIndexOf(lastEntry);
if (idx === -1) { console.log('ERROR: insertion point not found'); process.exit(1); }
html = html.substring(0, idx + lastEntry.length) + newStr + html.substring(idx + lastEntry.length);

fs.writeFileSync(path, html, 'utf8');
console.log('Added ' + entries.length + ' entries (IDs ' + Math.min(...entries.map(e=>e.id)) + '-' + Math.max(...entries.map(e=>e.id)) + ')');
console.log('File size: ' + Buffer.byteLength(html, 'utf8'));
