const fs = require('fs');
const path = 'C:/Users/shawn/Downloads/Green Bay Explorer.html';
let html = fs.readFileSync(path, 'utf8');

const entries = [
// === RESCH CENTER CONCERTS ===
{id:4100,name:"Journey — Final Frontier Tour at Resch Center!",cat:"Event",sub:"Concert",date:"2026-06-21",dateLabel:"Sun Jun 21, 7:30pm",venue:"Resch Center",loc:"Ashwaubenon",addr:"820 Armed Forces Dr, Ashwaubenon, WI 54304",desc:"JOURNEY at the Resch Center! Final Frontier Tour 2026. Doors 6pm, show 7:30pm. Tickets via TicketStar.",url:"https://www.reschcomplex.com/",setting:"indoor",walking:"lowWalking",goodFor:["seniors","couples"],highlight:true,free:false,recurring:false},
{id:4101,name:"Brooks & Dunn — Neon Moon Tour at Resch!",cat:"Event",sub:"Concert",date:"2026-09-26",dateLabel:"Sat Sep 26, 7pm",venue:"Resch Center",loc:"Ashwaubenon",addr:"820 Armed Forces Dr, Ashwaubenon, WI 54304",desc:"Brooks & Dunn with David Lee Murphy! Neon Moon Tour. Doors 6pm. Tickets via TicketStar/Ticketmaster.",url:"https://www.reschcomplex.com/",setting:"indoor",walking:"lowWalking",goodFor:["seniors","couples"],highlight:true,free:false,recurring:false},
{id:4102,name:"'Weird Al' Yankovic at Resch Center!",cat:"Event",sub:"Comedy",date:"2026-10-16",dateLabel:"Fri Oct 16, 8pm",venue:"Resch Center",loc:"Ashwaubenon",addr:"820 Armed Forces Dr, Ashwaubenon, WI 54304",desc:"Weird Al Yankovic — Bigger & Weirder 2026 Tour with Puddles Pity Party! Doors 6:30pm. VIP packages available.",url:"https://www.reschcomplex.com/",setting:"indoor",walking:"lowWalking",goodFor:["seniors","family","couples"],highlight:true,free:false,recurring:false},
{id:4103,name:"Monster Jam Freestyle Mania at Resch!",cat:"Event",sub:"Family",date:"2026-03-27",dateTo:"2026-03-29",dateLabel:"Mar 27-29 (Fri 7pm, Sat 12+7, Sun 12+6)",venue:"Resch Center",loc:"Ashwaubenon",addr:"820 Armed Forces Dr, Ashwaubenon, WI 54304",desc:"Monster trucks at the Resch Center! 5 shows over 3 days. Pit party available. Huge family fun!",url:"https://www.reschcomplex.com/",setting:"indoor",walking:"lowWalking",goodFor:["family"],highlight:true,free:false,recurring:false},
{id:4104,name:"Beja Shrine Circus (5 Shows!)",cat:"Event",sub:"Family",date:"2026-05-02",dateTo:"2026-05-03",dateLabel:"May 2 (11am, 3pm, 7pm) & May 3 (1pm, 5pm)",venue:"Resch Center",loc:"Ashwaubenon",addr:"820 Armed Forces Dr, Ashwaubenon, WI 54304",desc:"The circus comes to the Resch! 5 performances over 2 days. Family fun tradition. Tickets via TicketStar.",url:"https://www.reschcomplex.com/",setting:"indoor",walking:"lowWalking",goodFor:["family","seniors"],highlight:true,free:false,recurring:false},
// === MEYER THEATRE ===
{id:4106,name:"Jake Owen at Meyer Theatre!",cat:"Event",sub:"Concert",date:"2026-03-26",dateLabel:"Thu Mar 26, 7:30pm",venue:"Meyer Theatre",loc:"Downtown Green Bay",addr:"117 S Washington St, Green Bay, WI 54301",desc:"Country star Jake Owen — Dream to Dreams Tour! $60-101. Beautiful historic Meyer Theatre downtown.",url:"https://www.meyertheatre.org/",setting:"indoor",walking:"lowWalking",goodFor:["couples"],highlight:true,free:false,recurring:false},
{id:4107,name:"Glenn Miller Orchestra at Meyer Theatre!",cat:"Event",sub:"Concert",date:"2026-04-29",dateLabel:"Wed Apr 29, 7:30pm",venue:"Meyer Theatre",loc:"Downtown Green Bay",addr:"117 S Washington St, Green Bay, WI 54301",desc:"The legendary Glenn Miller Orchestra! Big band swing classics. From $44.50. Perfect for seniors who love the classics!",url:"https://www.meyertheatre.org/",setting:"indoor",walking:"lowWalking",goodFor:["seniors","couples"],highlight:true,free:false,recurring:false},
{id:4108,name:"Jay and The Americans at Meyer Theatre!",cat:"Event",sub:"Concert",date:"2026-07-08",dateLabel:"Wed Jul 8, 7pm",venue:"Meyer Theatre",loc:"Downtown Green Bay",addr:"117 S Washington St, Green Bay, WI 54301",desc:"Jay and The Americans — classic 60s hits! This Magic Moment, Come A Little Bit Closer. From $58. Great for oldies fans!",url:"https://www.meyertheatre.org/",setting:"indoor",walking:"lowWalking",goodFor:["seniors","couples"],highlight:true,free:false,recurring:false},
// === LET ME BE FRANK ===
{id:4110,name:"'Shopko: Say Hello to a Goodbye' — LMBF Show!",cat:"Event",sub:"Theater",date:"2026-04-09",dateTo:"2026-04-26",dateLabel:"Apr 9-26 (multiple shows, $43)",venue:"Meyer Theatre",loc:"Downtown Green Bay",addr:"117 S Washington St, Green Bay, WI 54301",desc:"Let Me Be Frank's hilarious original show about Green Bay's beloved Shopko! 70s-80s musical comedy. $43 including fees. Multiple matinee & evening shows.",url:"https://letmebefranks.com/",setting:"indoor",walking:"lowWalking",goodFor:["seniors","couples","family"],highlight:true,free:false,recurring:false},
{id:4111,name:"'Dingaling Brothers Circus' — LMBF Summer Show!",cat:"Event",sub:"Theater",date:"2026-07-23",dateTo:"2026-08-09",dateLabel:"Jul 23 - Aug 9 (multiple shows, $43)",venue:"Meyer Theatre",loc:"Downtown Green Bay",addr:"117 S Washington St, Green Bay, WI 54301",desc:"Let Me Be Frank's 60s circus musical comedy! $43. Multiple evening and matinee shows. Green Bay's favorite comedy troupe!",url:"https://letmebefranks.com/",setting:"indoor",walking:"lowWalking",goodFor:["seniors","couples","family"],highlight:true,free:false,recurring:false},
{id:4112,name:"'A Frank's Christmas' — LMBF Holiday Show!",cat:"Event",sub:"Theater",date:"2026-11-27",dateTo:"2026-12-26",dateLabel:"Nov 27 - Dec 26 (many shows, $46.50)",venue:"Meyer Theatre",loc:"Downtown Green Bay",addr:"117 S Washington St, Green Bay, WI 54301",desc:"Green Bay's #1 holiday tradition! Let Me Be Frank's Christmas show. $46.50. Matinee & evening performances throughout the holiday season.",url:"https://letmebefranks.com/",setting:"indoor",walking:"lowWalking",goodFor:["seniors","couples","family"],highlight:true,free:false,recurring:false},
// === WEIDNER CENTER ===
{id:4114,name:"Harry Potter: Prisoner of Azkaban in Concert!",cat:"Event",sub:"Concert",date:"2026-04-18",dateLabel:"Sat Apr 18",venue:"Weidner Center — Cofrin Family Hall",loc:"East Green Bay",addr:"2420 Nicolet Dr, Green Bay, WI 54311",desc:"Full film with live orchestra performing John Williams' score! Weidner Philharmonic. A magical night at the Weidner Center.",url:"https://www.weidnercenter.com/",setting:"indoor",walking:"lowWalking",goodFor:["family","seniors","couples"],highlight:true,free:false,recurring:false},
// === LEVITT AMP FREE CONCERTS ===
{id:4116,name:"Levitt AMP Free Concerts at Leicht Park (12 Sundays!)",cat:"Event",sub:"Free Concert Series",date:"2026-05-31",dateTo:"2026-08-09",dateLabel:"Sundays 4-6:30pm, May 31 - Aug 9 (12 shows)",venue:"Leicht Memorial Park",loc:"Downtown Green Bay",addr:"128 Dousman St, Green Bay, WI 54303",desc:"FREE live music every Sunday on the Fox River! 12 concerts from May 31 through Aug 9. Food vendors. Bring lawn chairs and blankets. Band lineup TBA.",url:"https://downtowngreenbay.com/",setting:"outdoor",walking:"lowWalking",goodFor:["seniors","couples","family"],highlight:true,free:true,recurring:false},
{id:4117,name:"Howard Market & Music (Free Monday Nights!)",cat:"Event",sub:"Free Concert Series",date:"2026-06-08",dateTo:"2026-08-24",dateLabel:"Mondays 5-8pm, Jun 8 - Aug 24",venue:"Howard Commons Pavilion",loc:"Howard",addr:"550 Commons Place, Howard, WI 54313",desc:"FREE Monday evening market + live music! Food trucks, biergarten, vendors. Bands include Nathan Grajeda, Jim Counter, Charms, Jimi Anderson, and more!",url:"https://www.villageofhoward.com/",setting:"outdoor",walking:"lowWalking",goodFor:["seniors","family","couples"],highlight:true,free:true,recurring:false},
{id:4118,name:"De Pere City Band — FREE Concerts on the Fox!",cat:"Event",sub:"Free Concert Series",date:"2026-06-11",dateTo:"2026-08-06",dateLabel:"Select Thursdays 7-8pm (Jun 11, 25, Jul 9, 23, 30, Aug 6)",venue:"Voyageur Park",loc:"De Pere",addr:"Voyageur Park, De Pere, WI 54115",desc:"FREE Thursday evening band concerts on the Fox River! Themed programs: 70s Music, Christmas in July, Big Bands, and more. Classic Green Bay tradition.",url:"https://www.deperewi.gov/",setting:"outdoor",walking:"lowWalking",goodFor:["seniors","family","couples"],highlight:true,free:true,recurring:false},
// === FESTIVALS ===
{id:4120,name:"Brown County Fair (Rides Included w/ Admission!)",cat:"Event",sub:"Festival",date:"2026-08-19",dateTo:"2026-08-23",dateLabel:"Wed-Sun Aug 19-23",venue:"Brown County Fairgrounds",loc:"De Pere",addr:"1500 Fort Howard Ave, De Pere, WI 54115",desc:"Brown County's big fair! $15 gate ($12 presale, $10 Sun). RIDES INCLUDED! PRCA rodeo, demo derby, truck/tractor pulls, 4-H, midway music. Under 3 free.",url:"https://browncountyfair.com/",setting:"outdoor",walking:"someWalking",goodFor:["family","seniors"],highlight:true,free:false,recurring:false},
{id:4121,name:"ArtFest Green Bay (FREE Downtown Art Fair!)",cat:"Event",sub:"Art",date:"2026-08-22",dateTo:"2026-08-23",dateLabel:"Sat Aug 22, 9am-7pm & Sun Aug 23, 10am-4pm",venue:"Downtown Green Bay (Jefferson/Cherry)",loc:"Downtown Green Bay",addr:"Downtown Green Bay, WI",desc:"FREE juried outdoor art fair! Live music, Experience Zone, food. FBI & the Untouchable Horns Sat, Copper Box Sun. Support local artists!",url:"https://downtowngreenbay.com/artfest",setting:"outdoor",walking:"someWalking",goodFor:["seniors","couples","family"],highlight:true,free:true,recurring:false},
{id:4122,name:"Danish Festival (Denmark, WI — 62nd Annual!)",cat:"Event",sub:"Festival",date:"2026-08-19",dateTo:"2026-08-23",dateLabel:"Wed Aug 19 (opening) - Sun Aug 23",venue:"Downtown Denmark",loc:"Denmark (20 min)",addr:"Denmark, WI 54208",desc:"62nd annual Danish Festival! Heritage celebration with parade, food court, Tivoli, children's events, artisan fair. Opening ceremony Wed at Heritage Park 5:30pm.",url:"https://danishfestival.org/",setting:"outdoor",walking:"someWalking",goodFor:["seniors","family"],highlight:true,free:false,recurring:false},
{id:4123,name:"Fire Over the Fox — July 4th Celebration (FREE!)",cat:"Event",sub:"Festival",date:"2026-07-04",dateLabel:"Sat Jul 4, ~3pm-10:30pm",venue:"Downtown Green Bay Waterfront",loc:"Downtown Green Bay",addr:"Leicht Memorial Park, Green Bay, WI",desc:"Green Bay's BIG July 4th party! Multi-stage live music, food trucks, family activities, spectacular fireworks over the Fox River at dusk. FREE general admission!",url:"https://downtowngreenbay.com/",setting:"outdoor",walking:"someWalking",goodFor:["family","seniors","couples"],highlight:true,free:true,recurring:false},
// === ONEIDA CASINO ===
{id:4125,name:"Oneida Casino Bingo (Daily Sessions!)",cat:"Activity",sub:"Entertainment",date:"",dateLabel:"Daily AM/PM/Evening sessions (18+)",venue:"Irene Moore Activity Center, Oneida Casino",loc:"Ashwaubenon",addr:"2020 Airport Dr, Green Bay, WI 54313",desc:"Daily bingo! AM Express 10:30am, PM Quest Mon-Wed 6:30pm, Evening Thu-Sun. Buy-in from $13-23. Chance at $250K JumbOneida jackpot! 18+.",url:"https://oneidacasinohotel.com/bingo/",setting:"indoor",walking:"lowWalking",goodFor:["seniors"],highlight:true,free:false,recurring:true},
// === SUPPER CLUBS ===
{id:4127,name:"Wally's Spot Supper Club (Since 1948!)",cat:"Restaurant",sub:"Supper Club",date:"",dateLabel:"Daily dinner from 5pm, Tue lunch 11-1:30",venue:"Wally's Spot",loc:"Green Bay",addr:"1979 Main St, Green Bay, WI 54302",desc:"Classic Wisconsin supper club since 1948! Prime rib, steaks, seafood, brandy Old Fashioneds. Salad bar included with entrees. Friday fish fry. Reservations recommended.",url:"",setting:"indoor",walking:"lowWalking",goodFor:["seniors","couples"],highlight:true,free:false,recurring:true,cuisine:"Supper Club"},
{id:4128,name:"Club Chalet (Bay Views + 40 Ice Cream Drinks!)",cat:"Restaurant",sub:"Supper Club",date:"",dateLabel:"Tue-Sat dinner (no reservations Fri-Sat)",venue:"Club Chalet",loc:"Bay Shore area",addr:"4642 Nicolet Dr, Green Bay, WI 54311",desc:"Supper club since 1944 with Bay of Green Bay views! 40+ ice cream cocktails, prime rib, Friday fish fry. Salad bar included. No reservations Fri-Sat.",url:"https://www.clubchaletgb.com/",setting:"indoor",walking:"lowWalking",goodFor:["seniors","couples"],highlight:true,free:false,recurring:true,cuisine:"Supper Club"},
{id:4129,name:"Union Hotel (Historic De Pere, Relish Tray!)",cat:"Restaurant",sub:"Supper Club",date:"",dateLabel:"Wed-Sun dinner 4:45-8:30",venue:"Union Hotel & Restaurant",loc:"De Pere",addr:"200 N Broadway, De Pere, WI 54115",desc:"Classic WI supper club since the 1870s! Famous relish tray with ham salad, family-recipe rolls. Art Deco interior. Friday fish fry, steaks, brandy Old Fashioneds.",url:"http://unionhoteldepere.com/",setting:"indoor",walking:"lowWalking",goodFor:["seniors","couples"],highlight:true,free:false,recurring:true,cuisine:"Supper Club"},
// === ICE CREAM / DESSERT ===
{id:4131,name:"Seroogy's Chocolates (Since 1899! De Pere)",cat:"Shop",sub:"Candy/Chocolate",date:"",dateLabel:"Check hours (flagship: 144 N Wisconsin St, De Pere)",venue:"Seroogy's Chocolates",loc:"De Pere",addr:"144 N Wisconsin St, De Pere, WI 54115",desc:"Wisconsin chocolate institution since 1899! Famous meltaway bars, sea salt caramels, fudge, house-roasted coffee. The blue box is a Green Bay tradition.",url:"https://seroogys.com/",setting:"indoor",walking:"lowWalking",goodFor:["seniors","couples","family"],highlight:true,free:false,recurring:true},
{id:4132,name:"Beerntsen's Candies (Since 1925! Downtown GB)",cat:"Shop",sub:"Candy/Chocolate",date:"",dateLabel:"Mon-Fri 9am-8pm, Sat 10-5, Sun 10-4",venue:"Beerntsen's Candies",loc:"Downtown Green Bay",addr:"200 N Broadway, Green Bay, WI 54303",desc:"Handmade turtles, truffles, fudge, brittle, caramel apples since 1925! Old-school candy kitchen and retail shop. A downtown Green Bay icon.",url:"",setting:"indoor",walking:"lowWalking",goodFor:["seniors","couples","family"],highlight:true,free:false,recurring:true},
{id:4133,name:"Zesty's Frozen Custard (Wisconsin Custard!)",cat:"Restaurant",sub:"Dessert",date:"",dateLabel:"Tue-Sun 11am-9pm (closed Mon)",venue:"Zesty's Frozen Custard",loc:"Allouez",addr:"508 Greene Ave, Green Bay, WI 54301",desc:"Fresh-churned Wisconsin frozen custard + full grill! Flavor of the Day calendar. Shakes, malts, sundaes. Local favorite.",url:"https://www.zestyscustard.com/",setting:"indoor",walking:"lowWalking",goodFor:["seniors","family","couples"],highlight:true,free:false,recurring:true,cuisine:"Frozen Custard"},
{id:4134,name:"BrainFreeze Ice Cream Shoppe (40+ Flavors!)",cat:"Restaurant",sub:"Dessert",date:"",dateLabel:"Open daily (extended summer hours Jun-Sep)",venue:"BrainFreeze Ice Cream Shoppe",loc:"Howard",addr:"1773 Cardinal Ln, Green Bay, WI 54313",desc:"40+ rotating premium ice cream flavors! Paninis too. Summer hours from June: 10am-10pm daily. A hidden gem for ice cream lovers.",url:"",setting:"indoor",walking:"lowWalking",goodFor:["seniors","family"],highlight:true,free:false,recurring:true,cuisine:"Ice Cream"},
// === WINERIES ===
{id:4136,name:"Captain's Walk Winery (Downtown GB Wine Bar!)",cat:"Bar/Nightlife",sub:"Winery",date:"",dateLabel:"Check hours (345 S Adams St)",venue:"Captain's Walk Winery",loc:"Downtown Green Bay",addr:"345 S Adams St, Green Bay, WI 54301",desc:"Small-batch wines and ciders in a charming downtown setting! Piano bar nights, wine cocktails, small bites. Relaxed and social atmosphere.",url:"http://www.captainswalkwinery.com/",setting:"indoor",walking:"lowWalking",goodFor:["seniors","couples"],highlight:true,free:false,recurring:true},
{id:4137,name:"von Stiehl Winery (Historic Algoma — Tours $10!)",cat:"Attraction",sub:"Day Trip",date:"",dateLabel:"Daily (Jan-Apr 10-4, May-Dec 10-5)",venue:"von Stiehl Winery",loc:"Algoma (45 min)",addr:"115 Navarino St, Algoma, WI 54201",desc:"Historic winery with cellar tours ($10, Fri-Sun 11am+1pm)! Tastings: Premier 6 samples $12, Select $9. Summer concert series Sat 12:30-4pm Jul-Sep. Wet Whistle Wine Fest Sep 18-19!",url:"https://vonstiehl.com/",setting:"indoor",walking:"someWalking",goodFor:["seniors","couples"],highlight:true,free:false,recurring:true},
// === FISH FRY ===
{id:4139,name:"Maricque's Bar — Green Bay's Fish Fry HQ!",cat:"Restaurant",sub:"Fish Fry",date:"",dateLabel:"Wed 4:30-10 & Fri lunch 11-1:30, dinner 4:30-10",venue:"Maricque's Bar",loc:"University Ave",addr:"1517 University Ave, Green Bay, WI 54302",desc:"THE Green Bay fish fry destination! Perch (bone-in or fillet), bluegill, cod, walleye, whitefish, catfish. Single perch $14.75. Wed & Fri. A Wisconsin tradition!",url:"https://www.greenbayfishfry.com/",setting:"indoor",walking:"lowWalking",goodFor:["seniors","couples","family"],highlight:true,free:false,recurring:true,cuisine:"Fish Fry"},
{id:4140,name:"Fox Harbor Pub — Perch & Haddock Fish Fry!",cat:"Restaurant",sub:"Fish Fry",date:"",dateLabel:"Kitchen daily 11-9",venue:"Fox Harbor Pub & Grill",loc:"Downtown Green Bay",addr:"348 S Washington St, Green Bay, WI 54301",desc:"Hand-breaded perch (market price), baked haddock $17, fish & chips $20, fried shrimp. Classic downtown pub atmosphere.",url:"https://foxharborpubandgrill.com/",setting:"indoor",walking:"lowWalking",goodFor:["seniors","couples"],highlight:true,free:false,recurring:true,cuisine:"Fish Fry"},
// === NEVILLE / RAILROAD / HERITAGE HILL ===
{id:4142,name:"Neville Museum — FREE First Wednesdays!",cat:"Event",sub:"Art",date:"2026-04-01",dateTo:"2026-12-02",dateLabel:"1st Wed monthly: Apr 1, May 7, Jun 4, Jul 1, Aug 6, Sep 3, Oct 7, Nov 4, Dec 2",venue:"Neville Public Museum",loc:"Downtown Green Bay",addr:"210 Museum Pl, Green Bay, WI 54303",desc:"FREE admission for Brown County residents every first Wednesday 9am-8pm! Explorer Wednesday crafts. Regular: Senior (62+) $10. New exhibit: A Place at the Table (food/culture).",url:"https://www.nevillepublicmuseum.org/",setting:"indoor",walking:"lowWalking",goodFor:["seniors","family"],highlight:true,free:true,recurring:false},
{id:4143,name:"National Railroad Museum — Senior Day Sep 15 FREE!",cat:"Event",sub:"History",date:"2026-09-15",dateLabel:"Mon Sep 15, 9am-8pm (62+ FREE!)",venue:"National Railroad Museum",loc:"Ashwaubenon",addr:"2285 S Broadway, Green Bay, WI 54304",desc:"SENIORS 62+ FREE ADMISSION on Sep 15! Behind-the-scenes tours at 5pm & 6:30pm. Part of the museum's 70th anniversary celebration. Regular senior admission $12.",url:"https://nationalrrmuseum.org/",setting:"indoor",walking:"someWalking",goodFor:["seniors","family"],highlight:true,free:true,recurring:false},
{id:4144,name:"Heritage Hill — Maple Sugaring Day!",cat:"Event",sub:"History",date:"2026-03-14",dateLabel:"Sat Mar 14, 9am-4pm",venue:"Heritage Hill State Historical Park",loc:"Allouez",addr:"2640 S Webster Ave, Green Bay, WI 54301",desc:"Living history maple sugaring! Traditional Indigenous & settler sugaring demonstrations. See how maple syrup was made. Senior (65+) $12, adults $14.",url:"https://heritagehillgb.org/",setting:"outdoor",walking:"someWalking",goodFor:["seniors","family"],highlight:true,free:false,recurring:false},
{id:4145,name:"Polar Express Train Ride (Tickets Jul 25!)",cat:"Event",sub:"Holiday Lights",date:"2026-11-20",dateTo:"2026-12-13",dateLabel:"Nov 20 - Dec 13 (Fri/Sat/Sun)",venue:"National Railroad Museum",loc:"Ashwaubenon",addr:"2285 S Broadway, Green Bay, WI 54304",desc:"The magical Polar Express Train Ride! Hot chocolate, story, train to 'North Pole'. TICKETS ON SALE JULY 25, 10am via TicketStar. Sells out fast!",url:"https://nationalrrmuseum.org/the-polar-express-train-ride/",setting:"indoor",walking:"someWalking",goodFor:["family","seniors"],highlight:true,free:false,recurring:false},
// === FARMERS MARKETS (extras) ===
{id:4147,name:"Saturday Farmers Market (100+ Vendors, Downtown!)",cat:"Event",sub:"Farmers Market",date:"2026-05-23",dateTo:"2026-10-31",dateLabel:"Saturdays 7am-noon, May 23-Oct 31",venue:"S Washington & Doty Streets",loc:"Downtown Green Bay",addr:"South Washington St, Green Bay, WI 54301",desc:"Green Bay's flagship market! 100+ vendors, live music 9-11:30am, Family Days. Produce, meat, cheese, baked goods, crafts. Rain or shine!",url:"https://downtowngreenbay.com/",setting:"outdoor",walking:"someWalking",goodFor:["seniors","family","couples"],highlight:true,free:true,recurring:false},
{id:4148,name:"Market on Military (Summer Thursdays!)",cat:"Event",sub:"Farmers Market",date:"2026-06-04",dateTo:"2026-10-29",dateLabel:"Thursdays 2-7pm, Jun 4-Oct 29",venue:"216 S Military Ave (former Shopko lot)",loc:"West Green Bay",addr:"216 S Military Ave, Green Bay, WI 54303",desc:"Outdoor summer market on the west side! Produce, crafts, food trucks. SNAP + Double Your Bucks accepted. Thursdays all summer long.",url:"https://militaryave.org/",setting:"outdoor",walking:"someWalking",goodFor:["seniors","family"],highlight:true,free:true,recurring:false},
// === BOWLING ===
{id:4150,name:"Village Lanes — Senior Rate $4.49/Game!",cat:"Activity",sub:"Entertainment",date:"",dateLabel:"Daily (check hours)",venue:"Village Lanes",loc:"Howard",addr:"3798 Velp Ave, Green Bay, WI 54313",desc:"Senior bowling rate: $4.49/game (vs $4.99 regular)! Shoes $2.49. Leagues available. Quieter weekday mornings are perfect for seniors.",url:"",setting:"indoor",walking:"lowWalking",goodFor:["seniors"],highlight:true,free:false,recurring:true},
// === ETHNIC RESTAURANTS ===
{id:4152,name:"India Bhavan (Lunch Buffet + Dinner!)",cat:"Restaurant",sub:"Indian",date:"",dateLabel:"Tue-Sun (lunch 10:15-2:15, dinner 4:30-9:30)",venue:"India Bhavan",loc:"Ashwaubenon",addr:"2611 Holmgren Way, Green Bay, WI 54304",desc:"Indian cuisine with lunch buffet! Chicken tikka masala, masala dosa, curries, naan. Popular lunch buffet Tue-Sun. Closed Monday.",url:"",setting:"indoor",walking:"lowWalking",goodFor:["seniors","couples"],highlight:true,free:false,recurring:true,cuisine:"Indian"},
{id:4153,name:"Bangkok Garden (Thai + Lunch Buffet!)",cat:"Restaurant",sub:"Thai",date:"",dateLabel:"Mon-Sun (lunch 11-2:45, dinner 4-9/10)",venue:"Bangkok Garden",loc:"Downtown Green Bay",addr:"240 N Broadway, Green Bay, WI 54303",desc:"Thai cuisine with weekday lunch buffet! Pad Thai, curries, and more. Beautiful downtown location on Broadway. Lunch buffet Mon-Sat ~11-2:30.",url:"",setting:"indoor",walking:"lowWalking",goodFor:["seniors","couples"],highlight:true,free:false,recurring:true,cuisine:"Thai"},
{id:4154,name:"Pho 1 Noodle and Grill (Vietnamese Pho!)",cat:"Restaurant",sub:"Vietnamese",date:"",dateLabel:"Mon & Wed-Sun 10-9 (Fri-Sat til 10, closed Tue)",venue:"Pho 1 Noodle and Grill",loc:"Ashwaubenon",addr:"2201 S Oneida St Ste 1, Green Bay, WI 54304",desc:"Authentic Vietnamese pho, banh mi sandwiches, rice plates. The #12 rare steak pho is a local favorite. Fresh and flavorful!",url:"",setting:"indoor",walking:"lowWalking",goodFor:["seniors","couples"],highlight:true,free:false,recurring:true,cuisine:"Vietnamese"},
{id:4155,name:"Little Tokyo Sushi (Downtown!)",cat:"Restaurant",sub:"Japanese",date:"",dateLabel:"Mon-Sat lunch 11-2:30, dinner 4:30-9 (closed Sun)",venue:"Little Tokyo",loc:"Downtown Green Bay",addr:"121 N Broadway, Green Bay, WI 54303",desc:"Sushi, sashimi, and Japanese cuisine downtown! Maki rolls, nigiri, classic Japanese dishes. Intimate setting on Broadway.",url:"",setting:"indoor",walking:"lowWalking",goodFor:["seniors","couples"],highlight:true,free:false,recurring:true,cuisine:"Japanese"},
// === PIZZA ===
{id:4157,name:"Polito's Pizza (Giant NY Slices!)",cat:"Restaurant",sub:"Pizza",date:"",dateLabel:"Mon-Sat 11-10/3am (closed Sun)",venue:"Polito's Pizza",loc:"Downtown Green Bay",addr:"201 N Washington St, Green Bay, WI 54303",desc:"Massive New York-style slices! Late night Fri-Sat til 3am. Also in De Pere (310 Main Ave). Specialty pies and huge portions.",url:"http://politospizzaria.weebly.com/",setting:"indoor",walking:"lowWalking",goodFor:["family","couples"],highlight:true,free:false,recurring:true,cuisine:"Pizza"},
{id:4158,name:"Gallagher's Pizza (Deep Dish + Lunch Buffet!)",cat:"Restaurant",sub:"Pizza",date:"",dateLabel:"Daily 11am-10/11pm (4 locations!)",venue:"Gallagher's Pizza",loc:"Multiple Locations",addr:"2655 W Mason St, Green Bay, WI 54303",desc:"Chicago deep dish, stuffed, thin crust AND hand-tossed! 4 locations (W Mason, E Webster, De Pere, Suamico). Mon-Sat lunch buffet 11-1:30. Mon dinner buffet 5-8.",url:"https://gallagherspizza.com/",setting:"indoor",walking:"lowWalking",goodFor:["seniors","family"],highlight:true,free:false,recurring:true,cuisine:"Pizza"},
{id:4159,name:"Cranky Pat's Pizza (Since 1955, Thin Crispy!)",cat:"Restaurant",sub:"Pizza",date:"",dateLabel:"Mon-Sat 11-10 (closed Sun)",venue:"Cranky Pat's",loc:"East Green Bay",addr:"709 Bellevue St, Green Bay, WI 54302",desc:"Green Bay pizza institution since 1955! Famous thin crispy tavern-style pizza. Pat's Special is a must-try. Old-school Wisconsin neighborhood joint.",url:"",setting:"indoor",walking:"lowWalking",goodFor:["seniors","family"],highlight:true,free:false,recurring:true,cuisine:"Pizza"},
// === SCENIC DRIVES ===
{id:4161,name:"Bay Shore Park Scenic Drive (Escarpment Views!)",cat:"Activity",sub:"Scenic Drive",date:"",dateLabel:"Year-round (15-25 min from Green Bay)",venue:"Bay Shore County Park",loc:"New Franken",addr:"5637 Sturgeon Bay Rd, New Franken, WI 54229",desc:"Short scenic drive to stunning Niagara Escarpment bluffs overlooking the Bay of Green Bay! Picnic shelters, trails, camping. Fall colors spectacular. ~15 min from GB.",url:"https://www.browncountywi.gov/",setting:"outdoor",walking:"someWalking",goodFor:["seniors","couples"],highlight:true,free:false,recurring:true},
{id:4162,name:"Door County Coastal Byway (66-Mile Loop!)",cat:"Activity",sub:"Scenic Drive",date:"",dateLabel:"Year-round (~1 hr to Sturgeon Bay, full day for loop)",venue:"Door County Peninsula",loc:"Door County (Day Trip)",addr:"Sturgeon Bay to Northport, WI",desc:"66-mile National Scenic Byway loop! Hwy 42 & 57 around the Door Peninsula. Lighthouses, harbors, orchards, state parks, charming villages. Peak fall color mid-October.",url:"https://doorcountycoastalbyway.org/",setting:"outdoor",walking:"lowWalking",goodFor:["seniors","couples"],highlight:true,free:true,recurring:true},
// === CHURCH EVENTS ===
{id:4164,name:"St. Willy's Jam — Parish Festival (FREE!)",cat:"Event",sub:"Festival",date:"2026-06-14",dateLabel:"Sun Jun 14, 10:30am-5pm",venue:"St. Willebrord Parish",loc:"Downtown Green Bay",addr:"209 S Adams St, Green Bay, WI 54301",desc:"Annual parish jam! Tacos, brats, burgers, Mexican snacks, desserts, drinks. Live music and family fun. A beloved Green Bay community tradition. Donations welcome.",url:"https://stwillys.org/",setting:"outdoor",walking:"lowWalking",goodFor:["seniors","family"],highlight:true,free:true,recurring:false},
{id:4165,name:"Washington St Block Party + Booyah Battle!",cat:"Event",sub:"Food",date:"2026-04-25",dateLabel:"Sat Apr 25, noon-7pm (already listed but adding booyah detail)",venue:"Downtown Green Bay (Washington St)",loc:"Downtown Green Bay",addr:"Washington St, Green Bay, WI 54301",desc:"12 booyah recipes compete! $20 tasting punch card. Plus Kringle Combine ($5 donation). Live music, food vendors. Uniquely Wisconsin!",url:"",setting:"outdoor",walking:"someWalking",goodFor:["family","seniors","couples"],highlight:true,free:false,recurring:false},
// === GOLF ===
{id:4167,name:"Brown County Golf Course (Senior $37, Ages 62+!)",cat:"Activity",sub:"Golf",date:"",dateLabel:"Weekday 18-hole senior walk $37 (vs $40 regular)",venue:"Brown County Golf Course",loc:"Oneida",addr:"897 Riverdale Dr, Oneida, WI 54155",desc:"Senior (62+) weekday 18-hole walking: $37 (save $3!). Weekend $41. Twilight Sat/Sun after 3pm: $35 walk/$48 ride. Nice course near the NEW Zoo.",url:"https://www.browncountygc.com/",setting:"outdoor",walking:"someWalking",goodFor:["seniors"],highlight:true,free:false,recurring:true},
{id:4168,name:"Hilly Haven Golf (Senior $34 for 18, Ages 60+!)",cat:"Activity",sub:"Golf",date:"",dateLabel:"Mon-Thu senior 18-hole: $34 (before 3pm)",venue:"Hilly Haven Golf Course",loc:"De Pere",addr:"5911 County Rd PP, De Pere, WI 54115",desc:"Senior (60+) weekday rate: 18 holes $34, 9 holes $21 (Mon-Thu before 3pm). After 6pm: 9 holes just $20! Lil' Haven par-3 practice course too.",url:"https://hillyhaven.com/",setting:"outdoor",walking:"someWalking",goodFor:["seniors"],highlight:true,free:false,recurring:true},
// === THRIFT ===
{id:4170,name:"Goodwill NCW — 10% Senior Tuesdays (60+!)",cat:"Shop",sub:"Thrift Store",date:"",dateLabel:"Daily 9am-9pm (3 Green Bay locations)",venue:"Goodwill NCW",loc:"Multiple Locations",addr:"1660 W Mason St, Green Bay, WI 54303",desc:"10% off donated goods every Tuesday for ages 60+! Plus weekly 50% off color tag for everyone. 3 stores: W Mason, S Brosig, S Oneida.",url:"https://goodwillncw.org/",setting:"indoor",walking:"lowWalking",goodFor:["seniors"],highlight:true,free:false,recurring:true},
{id:4171,name:"St. Vincent de Paul Dig & Save (By the Pound!)",cat:"Shop",sub:"Thrift Store",date:"",dateLabel:"Mon-Sat 10-6, Sun 11-6",venue:"SVDP Dig & Save",loc:"East Green Bay",addr:"2121 Van Deuren St, Green Bay, WI 54302",desc:"Bins priced BY THE POUND! Textiles, hard goods, books. Treasure hunting at its finest. 3 regular SVDP thrift stores in Green Bay too.",url:"https://svdpgb.org/dig-save/",setting:"indoor",walking:"someWalking",goodFor:["seniors"],highlight:true,free:false,recurring:true},
{id:4172,name:"AbleLight Thrift — 25% Off Wed for 55+!",cat:"Shop",sub:"Thrift Store",date:"",dateLabel:"Mon-Sat 10-6, Sun 12-4",venue:"AbleLight Thrift Shop",loc:"East Green Bay",addr:"2269 True Ln, Green Bay, WI 54311",desc:"25% off for ages 55+ every Wednesday! Clothing, housewares, furniture. Proceeds support people with disabilities. Great selection.",url:"https://ablelight.org/thrift-stores/green-bay/",setting:"indoor",walking:"lowWalking",goodFor:["seniors"],highlight:true,free:false,recurring:true},
// === NATURE / BIRDING ===
{id:4174,name:"Bay Beach Wildlife Sanctuary (FREE! Year-Round!)",cat:"Attraction",sub:"Nature / Birding",date:"",dateLabel:"Daily 8am-4:30pm (summer til 7:30pm)",venue:"Bay Beach Wildlife Sanctuary",loc:"East Green Bay",addr:"1660 E Shore Dr, Green Bay, WI 54302",desc:"FREE nature center! Wolves, raptors, ponds, trails. Daily wolf feedings at 1:30pm. Noon Nature Walks, Bird of Prey Tours. Great spring birding May migration.",url:"https://www.baybeachwildlife.com/",setting:"outdoor",walking:"someWalking",goodFor:["seniors","family"],highlight:true,free:true,recurring:true},
{id:4175,name:"Ken Euers Nature Area (30+ Shorebird Species!)",cat:"Park",sub:"Nature / Birding",date:"",dateLabel:"Daily 6am-10pm",venue:"Ken Euers Nature Area",loc:"West Green Bay",addr:"1701 N Military Ave, Green Bay, WI 54303",desc:"Premier birding spot! 30+ shorebird species possible in May. Dikes and marsh trails. Yellow-headed Blackbirds, gallinules, grebes. Easy flat walking.",url:"",setting:"outdoor",walking:"someWalking",goodFor:["seniors"],highlight:true,free:true,recurring:true},
];

let newStr = '';
for (const e of entries) {
  const descEsc = e.desc.replace(/"/g, '\\"');
  const nameEsc = e.name.replace(/"/g, '\\"');
  let s = ',\n{id:' + e.id + ',name:"' + nameEsc + '",cat:"' + e.cat + '",sub:"' + e.sub + '"';
  s += ',price:"' + (e.free ? 'free' : '$$') + '",priceNum:' + (e.free ? 0 : 2);
  s += ',date:"' + (e.date||'') + '"';
  if (e.dateTo) s += ',dateTo:"' + e.dateTo + '"';
  s += ',dateLabel:"' + (e.dateLabel || '') + '"';
  s += ',venue:"' + e.venue + '"';
  s += ',desc:"' + descEsc + '"';
  s += ',url:"' + (e.url || '') + '"';
  s += ',setting:"' + e.setting + '",walking:"' + e.walking + '"';
  s += ',goodFor:' + JSON.stringify(e.goodFor);
  s += ',highlight:' + e.highlight;
  s += ',cuisine:"' + (e.cuisine || '') + '",established:""';
  s += ',free:' + e.free + ',recurring:' + (e.recurring || false) + '}';
  newStr += s;
}

const lastEntry = 'free:true,recurring:true}';
const idx = html.lastIndexOf(lastEntry);
if (idx === -1) { console.log('ERROR: insertion point not found'); process.exit(1); }
html = html.substring(0, idx + lastEntry.length) + newStr + html.substring(idx + lastEntry.length);

fs.writeFileSync(path, html, 'utf8');
console.log('Added ' + entries.length + ' entries (IDs ' + Math.min(...entries.map(e=>e.id)) + '-' + Math.max(...entries.map(e=>e.id)) + ')');
console.log('File size: ' + Buffer.byteLength(html, 'utf8'));
