const fs = require('fs');
const path = 'C:/Users/shawn/Downloads/Green Bay Explorer.html';
let html = fs.readFileSync(path, 'utf8');

const entries = [
// === DOOR COUNTY DAY TRIPS ===
{id:4300,name:"Door County Trolley — Narrated Scenic Tour!",cat:"Activity",sub:"Day Trip",date:"",dateLabel:"May-Oct, 3 departures daily (~1.5 hrs, $29.95)",venue:"Door County Trolley",loc:"Egg Harbor (Door Co.)",addr:"8030 WI-42, Egg Harbor, WI 54209",desc:"Narrated trolley tour of Door County! $29.95 adults. Also wine tours ($89.95), ghost tours ($39.95), lighthouse tour ($79.95). Seated, no driving, perfect for seniors.",url:"https://doorcountytrolley.com/",setting:"outdoor",walking:"lowWalking",goodFor:["seniors","couples"],highlight:true,free:false,recurring:true},
{id:4301,name:"Pelletier's Fish Boil (Fish Creek — Tradition!)",cat:"Restaurant",sub:"Day Trip",date:"",dateLabel:"Opens Fri May 8; seatings 5, 6 & 7pm ($27)",venue:"Pelletier's Restaurant",loc:"Fish Creek (Door Co.)",addr:"4199 Main St, Fish Creek, WI 54212",desc:"The Door County fish boil tradition! Whitefish, potatoes, onions, coleslaw, cherry pie. $27/adult. Outdoor boil-over show then indoor dining. Reserve ahead!",url:"https://www.doorcountyfishboil.com/",setting:"outdoor",walking:"lowWalking",goodFor:["seniors","couples","family"],highlight:true,free:false,recurring:true,cuisine:"Fish Boil"},
{id:4302,name:"Fish Creek Scenic Boat Tour (Senior $29!)",cat:"Activity",sub:"Day Trip",date:"",dateLabel:"Seasonal (~1-1.75 hrs, senior $29, sunset $45)",venue:"Fish Creek Scenic Boat Tours",loc:"Fish Creek (Door Co.)",addr:"Fish Creek, WI 54212",desc:"Narrated Door County boat cruises with SENIOR DISCOUNT! Day tours from $29 senior. Sunset live music cruises $45. Partly covered boat, restroom onboard. BYO food OK on sunset.",url:"https://fishcreekscenicboattours.com/",setting:"outdoor",walking:"lowWalking",goodFor:["seniors","couples"],highlight:true,free:false,recurring:true},
{id:4303,name:"Washington Island Ferry (Death's Door Crossing!)",cat:"Activity",sub:"Day Trip",date:"",dateLabel:"Year-round (summer: many daily crossings, $15 RT)",venue:"Washington Island Ferry",loc:"Ellison Bay (Door Co.)",addr:"215 WI-42, Ellison Bay, WI 54210",desc:"Ferry to Washington Island through Death's Door! Adult $15 RT, car $30 RT, under 6 FREE. Heated cabin, short crossing. Walk-on avoids island driving stress.",url:"https://wisferry.com/",setting:"outdoor",walking:"lowWalking",goodFor:["seniors","couples","family"],highlight:true,free:false,recurring:true},
// === COFFEE SHOPS ===
{id:4305,name:"Kavarna Coffeehouse (Downtown Arts + Coffee!)",cat:"Restaurant",sub:"Coffee",date:"",dateLabel:"Mon-Fri 7am-3pm, Sat 8-3, Sun 8-2",venue:"Kavarna Coffeehouse",loc:"Downtown Green Bay",addr:"143 N Broadway, Green Bay, WI 54303",desc:"Women-owned downtown coffee institution! Local art, live events, vegetarian-friendly. Parisi's Deli on-site. A perfect spot for seniors to sit and chat.",url:"",setting:"indoor",walking:"lowWalking",goodFor:["seniors","couples"],highlight:true,free:false,recurring:true,cuisine:"Coffee"},
{id:4306,name:"The Attic (80+ Teas + Used Books!)",cat:"Restaurant",sub:"Coffee",date:"",dateLabel:"Closed Mon; Tue-Fri 7am-3pm, Sat 8-3, Sun 8-1",venue:"The Attic",loc:"Downtown Green Bay",addr:"730 Bodart St, Green Bay, WI 54303",desc:"80+ teas, espresso, used books, 3000+ sq ft lounge! Quiet, cozy, perfect for a long chat. WiFi available. A hidden gem for book lovers and tea enthusiasts.",url:"https://theatticcorner.com/",setting:"indoor",walking:"lowWalking",goodFor:["seniors","couples"],highlight:true,free:false,recurring:true,cuisine:"Tea/Coffee"},
{id:4307,name:"Copper Rock Coffee (River Patio + Daily Roasting!)",cat:"Restaurant",sub:"Coffee",date:"",dateLabel:"Mon-Fri 6:30am-10pm, Sat 7-10 (closed Sun)",venue:"Copper Rock Coffee Company",loc:"Downtown Green Bay",addr:"313 Dousman St, Green Bay, WI 54303",desc:"Daily on-site coffee roasting! Large Fox River patio, fireplace room, free WiFi. Events and live music. Part of Copper State Brewing complex.",url:"https://www.copperrockcoffee.com/",setting:"indoor",walking:"lowWalking",goodFor:["seniors","couples"],highlight:true,free:false,recurring:true,cuisine:"Coffee"},
// === MOVIES ===
{id:4309,name:"De Pere Cinema — Senior Only $5! Matinee $5!",cat:"Activity",sub:"Movie Theater",date:"",dateLabel:"Daily (senior 62+ $5, matinee $5, Tue $5 everyone)",venue:"De Pere Cinema",loc:"De Pere",addr:"417 George St, De Pere, WI 54115",desc:"Best movie deal for seniors! $5 senior (62+), $5 any matinee before 5:30pm, $5 Tuesdays for everyone. Plus $2 popcorn + $2 soda deals. Recliner seating!",url:"",setting:"indoor",walking:"lowWalking",goodFor:["seniors","couples"],highlight:true,free:false,recurring:true},
{id:4310,name:"Marcus Bay Park Cinema — Value Tuesdays $6!",cat:"Activity",sub:"Movie Theater",date:"",dateLabel:"Daily (senior matinee ~$7.50, Value Tue ~$6)",venue:"Marcus Bay Park Cinema",loc:"Ashwaubenon",addr:"755 Willard Dr, Ashwaubenon, WI 54304",desc:"SuperScreen DLX with Dolby Atmos! Senior (60+) matinee before 4pm ~$7.50. Value Tuesday ~$6 with Marcus Rewards. Friday Young at Heart concession specials for 60+.",url:"https://www.marcustheatres.com/",setting:"indoor",walking:"lowWalking",goodFor:["seniors","couples","family"],highlight:true,free:false,recurring:true},
{id:4311,name:"Field of Scenes Drive-In (Double Feature $8!)",cat:"Activity",sub:"Movie Theater",date:"",dateLabel:"Seasonal May-Sep (~$8 adults, $4 kids)",venue:"Field of Scenes",loc:"Freedom (20-30 min)",addr:"N4032 Hwy E, Freedom, WI 54130",desc:"Outdoor drive-in double feature! ~$8 adults, $4 kids (4-11), under 4 free. Classic Wisconsin summer evening. ~20-30 minutes from Green Bay.",url:"https://www.fieldofscenes.biz/",setting:"outdoor",walking:"lowWalking",goodFor:["seniors","couples","family"],highlight:true,free:false,recurring:true},
// === APPLETON DAY TRIPS ===
{id:4313,name:"Fox Cities PAC — Broadway Shows! (30 min drive)",cat:"Activity",sub:"Day Trip",date:"2026-10-16",dateTo:"2027-05-02",dateLabel:"2026-27 Season: Sound of Music, Phantom, SIX + more",venue:"Fox Cities Performing Arts Center",loc:"Appleton (30 min)",addr:"400 W College Ave, Appleton, WI 54911",desc:"National Broadway tours! 2026-27: Sound of Music (Nov 3-8), Maybe Happy Ending (Dec 15-20), SIX (Feb 9-14), Phantom of the Opera (Mar 31-Apr 11), Water for Elephants (Apr 27-May 2). 30 min from GB!",url:"https://foxcitiespac.com/",setting:"indoor",walking:"lowWalking",goodFor:["seniors","couples"],highlight:true,free:false,recurring:false},
{id:4314,name:"Mile of Music — FREE Festival (Appleton, 30 min!)",cat:"Event",sub:"Festival",date:"2026-07-30",dateTo:"2026-08-02",dateLabel:"Thu Jul 30 - Sun Aug 2 (FREE!)",venue:"Downtown Appleton (30+ venues)",loc:"Appleton (30 min)",addr:"Downtown Appleton, WI 54911",desc:"Hundreds of FREE live original music performances over 4 days! 30+ venues on College Ave. No tickets needed. One of Wisconsin's best free festivals. 30 min from GB.",url:"https://mileofmusic.com/",setting:"outdoor",walking:"someWalking",goodFor:["seniors","couples"],highlight:true,free:true,recurring:false},
{id:4315,name:"Appleton Octoberfest (Sep 25-26!)",cat:"Event",sub:"Festival",date:"2026-09-25",dateTo:"2026-09-26",dateLabel:"Fri Sep 25 (car show) + Sat Sep 26 (main fest)",venue:"Downtown Appleton (College Ave)",loc:"Appleton (30 min)",addr:"College Ave, Appleton, WI 54911",desc:"Largest downtown street festival in the region! Friday: License to Cruise classic car show. Saturday: music, vendors, beer gardens, German food. Many free activities.",url:"https://octoberfestonline.org/",setting:"outdoor",walking:"someWalking",goodFor:["seniors","couples","family"],highlight:true,free:false,recurring:false},
{id:4316,name:"Fox River Mall — Senior Walking (Doors Open Early!)",cat:"Activity",sub:"Walking",date:"",dateLabel:"Doors open 1 hour before stores for walkers",venue:"Fox River Mall",loc:"Appleton (30 min)",addr:"4301 W Wisconsin Ave, Appleton, WI 54913",desc:"Largest enclosed mall in the area! Doors open 1 HOUR BEFORE stores for mall walkers daily. Climate-controlled, flat, safe walking. Free parking. Scheels, food court, shops.",url:"https://www.foxrivermall.com/",setting:"indoor",walking:"someWalking",goodFor:["seniors"],highlight:true,free:true,recurring:true},
// === BREAKFAST / BRUNCH ===
{id:4318,name:"The Pancake Place (Legendary! Opens 5am!)",cat:"Restaurant",sub:"Breakfast",date:"",dateLabel:"Daily 5am-2pm",venue:"The Pancake Place",loc:"West Green Bay",addr:"143 S Military Ave, Green Bay, WI 54303",desc:"Green Bay breakfast legend! Opens 5am daily. Huge pancakes, famous stuffed hash browns, eggs Benedict, chicken & waffles. Best of the Bay winner.",url:"https://www.thepancakeplacegb.com/",setting:"indoor",walking:"lowWalking",goodFor:["seniors","family"],highlight:true,free:false,recurring:true,cuisine:"Breakfast"},
{id:4319,name:"The Creamery Downtown (Trendy Brunch!)",cat:"Restaurant",sub:"Breakfast",date:"",dateLabel:"Daily 7am-3pm",venue:"The Creamery Downtown",loc:"Downtown Green Bay",addr:"114 Pine St, Green Bay, WI 54301",desc:"Scratch brunch spot! Benedicts, chilaquiles, chicken & waffles, Bloody Marys. Riverfront location. Modern and delicious.",url:"https://thecreamerycafe.com/",setting:"indoor",walking:"lowWalking",goodFor:["seniors","couples"],highlight:true,free:false,recurring:true,cuisine:"Breakfast"},
// === LAMBEAU / PACKERS ===
{id:4321,name:"Lambeau Field Stadium Tour (Senior $20!)",cat:"Attraction",sub:"Museum",date:"",dateLabel:"Daily (Classic tour senior $20, combo w/HoF $30)",venue:"Lambeau Field",loc:"Ashwaubenon",addr:"1265 Lombardi Ave, Green Bay, WI 54304",desc:"Tour the legendary Lambeau Field! Senior (62+) Classic tour $20. Down to field level through the tunnel. Champions ($28), Legendary ($36) tours also available. Combo with Hall of Fame saves!",url:"https://www.packershofandtours.com/",setting:"indoor",walking:"someWalking",goodFor:["seniors","family","couples"],highlight:true,free:false,recurring:true},
{id:4322,name:"Packers Hall of Fame (Senior $17!)",cat:"Attraction",sub:"Museum",date:"",dateLabel:"Mon-Sat 9am-6pm, Sun 10am-5pm (senior $17)",venue:"Packers Hall of Fame",loc:"Ashwaubenon",addr:"1265 Lombardi Ave, Green Bay, WI 54304",desc:"15,000 sq ft, 9 galleries of Packers history! Ice Bowl theater, Lombardi's office replica, trophy room. Free audio tour. Senior (62+) $17. Brown County residents save more!",url:"https://www.packershofandtours.com/",setting:"indoor",walking:"someWalking",goodFor:["seniors","family"],highlight:true,free:false,recurring:true},
// === LIBRARIES ===
{id:4324,name:"Brown County Library — FREE Programs All Year!",cat:"Activity",sub:"Library",date:"",dateLabel:"Central: Mon-Thu 9-8, Fri 9-5, Sat 10-4 (9 branches!)",venue:"Brown County Central Library",loc:"Downtown Green Bay",addr:"515 Pine St, Green Bay, WI 54301",desc:"FREE! 9 branches countywide. Adult programs: book clubs, tech classes (Intro to AI!), crafts, trivia, genealogy resources (2nd floor). Seed Library! AARP Tax-Aide (free tax help).",url:"https://www.browncountylibrary.org/",setting:"indoor",walking:"lowWalking",goodFor:["seniors"],highlight:true,free:true,recurring:true},
// === MEXICAN RESTAURANTS ===
{id:4326,name:"El Sarape (2 Locations — Big Menu!)",cat:"Restaurant",sub:"Mexican",date:"",dateLabel:"Sun-Thu 11-9, Fri-Sat 11-10",venue:"El Sarape",loc:"Multiple Locations",addr:"2615 S Oneida St, Green Bay, WI 54304",desc:"Huge Mexican menu! Tacos, burritos, enchiladas, fajitas, carne asada, seafood. Also at 2245 Costco Way, Bellevue. Generous portions and good margaritas.",url:"https://www.elsarape-gb.com/",setting:"indoor",walking:"lowWalking",goodFor:["seniors","family","couples"],highlight:true,free:false,recurring:true,cuisine:"Mexican"},
{id:4327,name:"Mexico Lindo (Tableside Guacamole!)",cat:"Restaurant",sub:"Mexican",date:"",dateLabel:"Daily 11-9 (Fri-Sat til 10)",venue:"Mexico Lindo",loc:"Howard",addr:"445 Cardinal Ln, Green Bay, WI 54313",desc:"Upscale-casual Mexican! Famous tableside guacamole, fajitas, steak tacos, great margaritas. Nicely decorated with attentive service.",url:"https://mexicolindogb.com/",setting:"indoor",walking:"lowWalking",goodFor:["seniors","couples"],highlight:true,free:false,recurring:true,cuisine:"Mexican"},
{id:4328,name:"Pastorcito Mexican Restaurant (Late Night!)",cat:"Restaurant",sub:"Mexican",date:"",dateLabel:"Daily 11am-midnight",venue:"Pastorcito Mexican Restaurant",loc:"Green Bay",addr:"741 Abrams St #4, Green Bay, WI",desc:"Al pastor-style plates, authentic Mexican food, open late! Great for a genuine taqueria experience. Friendly family restaurant.",url:"https://pastorcitomexicanrestaurant.com/",setting:"indoor",walking:"lowWalking",goodFor:["seniors","family"],highlight:true,free:false,recurring:true,cuisine:"Mexican"},
// === FINE DINING ===
{id:4330,name:"Republic Chophouse (Anniversary Steakhouse!)",cat:"Restaurant",sub:"Fine Dining",date:"",dateLabel:"Sun-Thu 5-10, Fri-Sat 5-11",venue:"Republic Chophouse",loc:"Downtown Green Bay",addr:"218 N Adams St, Green Bay, WI 54301",desc:"Green Bay's premier modern steakhouse! Perfect for anniversaries and special occasions. Smart casual dress. Reservations via OpenTable recommended.",url:"https://republicchophouse.com/",setting:"indoor",walking:"lowWalking",goodFor:["seniors","couples"],highlight:true,free:false,recurring:true,cuisine:"Steakhouse"},
{id:4331,name:"Taverne in the Sky (Lambeau Views!)",cat:"Restaurant",sub:"Fine Dining",date:"",dateLabel:"Check Lodge Kohler for hours",venue:"Taverne in the Sky at Lodge Kohler",loc:"Ashwaubenon",addr:"1950 S Ridge Rd, Green Bay, WI 54304",desc:"Wood-fired steaks with LAMBEAU FIELD panoramic views! Special occasion dining at Lodge Kohler. Kohler Waters Spa also on-site. Smart casual to dressy.",url:"https://www.lodgekohler.com/",setting:"indoor",walking:"lowWalking",goodFor:["seniors","couples"],highlight:true,free:false,recurring:true,cuisine:"Steakhouse"},
// === MEDICAL / PRACTICAL ===
{id:4333,name:"HSHS St. Vincent Hospital (24/7 ER)",cat:"Service",sub:"Medical",date:"",dateLabel:"ER: 24/7 | Main: (920) 433-0111",venue:"HSHS St. Vincent Hospital",loc:"Downtown Green Bay",addr:"835 S Van Buren St, Green Bay, WI 54301",desc:"Level II trauma center with 24/7 emergency department. Major Green Bay hospital. ER entrance from Webster Ave side.",url:"https://www.hshs.org/st-vincent/",setting:"indoor",walking:"lowWalking",goodFor:["seniors"],highlight:false,free:false,recurring:true},
{id:4334,name:"AARP Tax-Aide — FREE Tax Help for Seniors!",cat:"Activity",sub:"Senior Services",date:"2026-02-01",dateTo:"2026-04-15",dateLabel:"Feb-Apr at 6+ library/community sites (FREE!)",venue:"Multiple Brown County locations",loc:"Green Bay area",addr:"Varies (libraries, community centers)",desc:"FREE IRS-certified tax preparation! AARP membership NOT required. 6+ Brown County sites. Schedule: (920) 393-7863. Sites include libraries, Ashwaubenon Community Center, and more.",url:"https://www.aarp.org/money/taxes/aarp-taxaide/",setting:"indoor",walking:"lowWalking",goodFor:["seniors"],highlight:true,free:true,recurring:false},
// === WALKING TRAILS ===
{id:4336,name:"CityDeck Riverwalk (ADA, Benches, Splash Pad!)",cat:"Park",sub:"Trail",date:"",dateLabel:"Open daily (paved, flat, very easy, ~1/4 mile)",venue:"CityDeck",loc:"Downtown Green Bay",addr:"301 N Washington St, Green Bay, WI 54301",desc:"Beautiful riverfront promenade! ADA accessible, benches, restrooms, splash pad, art installations. Between Walnut & Main St bridges. Connect to Fox River Trail for longer walks.",url:"https://downtowngreenbay.com/",setting:"outdoor",walking:"lowWalking",goodFor:["seniors","family","couples"],highlight:true,free:true,recurring:true},
{id:4337,name:"Fox River State Trail (11 Paved Miles!)",cat:"Park",sub:"Trail",date:"",dateLabel:"Year-round 5am-9pm (flat, paved first 11 mi)",venue:"Fox River State Trail",loc:"Downtown Green Bay to Greenleaf",addr:"Porlier St & Adams St, Green Bay, WI",desc:"25-mile rail-trail along the Fox River! First 11 miles PAVED (asphalt) from downtown through Allouez/De Pere. Flat, easy, great for seniors. Free walking (bike pass for cycling 16+).",url:"https://dnr.wisconsin.gov/topic/parks/foxriver",setting:"outdoor",walking:"someWalking",goodFor:["seniors","couples"],highlight:true,free:true,recurring:true},
// === SWIMMING / AQUATICS ===
{id:4339,name:"Kroc Center — SilverSneakers Splash + Aqua Yoga!",cat:"Activity",sub:"Fitness",date:"",dateLabel:"Check class schedule",venue:"Salvation Army Kroc Center",loc:"East Green Bay",addr:"1315 Lime Kiln Rd, Green Bay, WI 54311",desc:"SilverSneakers Splash, Joint Movement (arthritis-friendly), Aqua Yoga, Deep Water Aerobics! Perfect senior water exercise. Membership or day pass. (920) 884-5007.",url:"https://cms.gbkroccenter.org/",setting:"indoor",walking:"lowWalking",goodFor:["seniors"],highlight:true,free:false,recurring:true},
{id:4340,name:"Ashwaubenon Community Pool (Warm Water 87-90°F!)",cat:"Activity",sub:"Fitness",date:"",dateLabel:"Senior (60+) $3 admission",venue:"Ashwaubenon Community Aquatic Center",loc:"Ashwaubenon",addr:"2391 S Ridge Rd, Ashwaubenon, WI 54304",desc:"8-lane pool + WARM WATER POOL (87-90°F) for therapy/exercise/water walking! Senior (60+) just $3. Competition pool ~78-80°F for lap swimming. (920) 492-2993.",url:"https://ashwaubenon.gov/",setting:"indoor",walking:"lowWalking",goodFor:["seniors"],highlight:true,free:false,recurring:true},
// === BREWERIES ===
{id:4342,name:"Copper State Brewing — Tuesday Jazz Night!",cat:"Bar/Nightlife",sub:"Brewery",date:"",dateLabel:"Tuesdays 6-9pm (upstairs lounge)",venue:"Copper State Brewing Co.",loc:"Downtown Green Bay",addr:"313 Dousman St, Green Bay, WI 54303",desc:"Tuesday Jazz, Blues & Brews in the upstairs lounge! House trio + jam session 6-9pm. Gastropub food, great beer. Also houses Copper Rock Coffee.",url:"https://www.copperstate.beer/",setting:"indoor",walking:"lowWalking",goodFor:["seniors","couples"],highlight:true,free:false,recurring:true},
{id:4343,name:"Noble Roots Brewing (Dog-Friendly Patio!)",cat:"Bar/Nightlife",sub:"Brewery",date:"",dateLabel:"Wed-Fri 4-9, Sat 2-9",venue:"Noble Roots Brewing",loc:"East Green Bay",addr:"2790 University Ave, Green Bay, WI 54311",desc:"Dog-friendly patio! Live music, trivia nights, book club, food truck series. Great craft beer in a welcoming atmosphere. Garage doors open in warm weather.",url:"https://www.noblerootsbrewing.com/",setting:"indoor",walking:"lowWalking",goodFor:["seniors","couples"],highlight:true,free:false,recurring:true},
// === DOG PARKS ===
{id:4345,name:"De Pere Dog Park (6 Acres, Agility!)",cat:"Park",sub:"Dog Park",date:"",dateLabel:"Call (920) 339-4065 for hours",venue:"De Pere Dog Park",loc:"De Pere",addr:"1400 Biotech Way, De Pere, WI 54115",desc:"6 fenced acres! Separate large and small dog areas, agility equipment, wooded trails, water. Free (De Pere residents). Great for senior dog owners.",url:"https://www.deperewi.gov/",setting:"outdoor",walking:"someWalking",goodFor:["seniors","family"],highlight:true,free:true,recurring:true},
{id:4346,name:"Bark & Brew (Indoor Off-Leash Dog Bar!)",cat:"Bar/Nightlife",sub:"Dog Park",date:"",dateLabel:"Tue-Fri 3-9, Sat 12-9, Sun 12-8 (closed Mon)",venue:"Bark & Brew",loc:"Howard",addr:"2514 Glendale Ave, Howard, WI 54313",desc:"Off-leash INDOOR + outdoor fenced play! Dog butlers, water bowls. Drinks for humans too. Your dog socializes while you relax with a craft beer.",url:"https://barknbrewwi.com/",setting:"indoor",walking:"lowWalking",goodFor:["seniors","couples"],highlight:true,free:false,recurring:true},
// === GARDEN CENTERS ===
{id:4348,name:"Stein's Garden & Home (Plants + Gifts!)",cat:"Shop",sub:"Garden Center",date:"",dateLabel:"Mon-Fri 9-8, Sat-Sun 9-6",venue:"Stein's Garden & Home",loc:"Ashwaubenon",addr:"980 Waube Ln, Green Bay, WI 54304",desc:"Big garden center! Annuals, perennials, trees, shrubs, houseplants, gardening supplies, home decor and gifts. Great selection for Wisconsin gardeners.",url:"https://www.shopsteins.com/",setting:"indoor",walking:"someWalking",goodFor:["seniors"],highlight:true,free:false,recurring:true},
// === BUFFETS ===
{id:4350,name:"China Buffet (Sushi Bar + Chinese AYCE!)",cat:"Restaurant",sub:"Buffet",date:"",dateLabel:"Daily 11am-8:30pm (lunch $16.85, dinner $19.99)",venue:"China Buffet",loc:"East Green Bay",addr:"2241 Main St, Green Bay, WI 54302",desc:"All-you-can-eat Chinese + sushi bar + American dishes + desserts! Lunch Mon-Fri ~$16.85, dinner/weekends ~$19.99. Large selection, good value.",url:"",setting:"indoor",walking:"lowWalking",goodFor:["seniors","family"],highlight:true,free:false,recurring:true,cuisine:"Chinese Buffet"},
{id:4351,name:"Pizza Ranch (Buffet + Chicken + Dessert!)",cat:"Restaurant",sub:"Buffet",date:"",dateLabel:"Lunch 11-3, evening 3-8",venue:"Pizza Ranch",loc:"East Green Bay",addr:"2206 Main St, Green Bay, WI 54302",desc:"All-you-can-eat pizza, chicken, salad bar, and dessert! Lunch and evening buffet tiers. Kids 0-3 free, 4-12 $1.10 x age. Country Fried Chicken is the hidden star!",url:"https://pizzaranch.com/",setting:"indoor",walking:"lowWalking",goodFor:["seniors","family"],highlight:true,free:false,recurring:true,cuisine:"Buffet"},
{id:4352,name:"HuHot Mongolian Grill (Build Your Own AYCE!)",cat:"Restaurant",sub:"Buffet",date:"",dateLabel:"Lunch & dinner",venue:"HuHot Mongolian Grill",loc:"Ashwaubenon",addr:"2621 S Oneida St, Ashwaubenon, WI 54304",desc:"All-you-can-eat Mongolian stir-fry! Pick your meats, veggies, noodles, sauces and watch them cook on a giant grill. Fun and interactive. Build exactly what you want.",url:"",setting:"indoor",walking:"lowWalking",goodFor:["seniors","family","couples"],highlight:true,free:false,recurring:true,cuisine:"Mongolian"},
// === PRACTICAL SERVICES ===
{id:4354,name:"AAA Green Bay Office (Roadside + Travel!)",cat:"Service",sub:"Auto",date:"",dateLabel:"Mon-Wed 8:30-5:30, Thu 8:30-7, Fri 8:30-5:30",venue:"AAA Green Bay",loc:"Ashwaubenon",addr:"2285 S Oneida St, Ste 1, Green Bay, WI 54304",desc:"Membership, roadside assistance, travel planning, insurance, discounts. (920) 498-6120. Essential for road-tripping seniors!",url:"https://www.aaa.com/",setting:"indoor",walking:"lowWalking",goodFor:["seniors"],highlight:false,free:false,recurring:true},
{id:4355,name:"Wisconsin DMV — Green Bay Service Center",cat:"Service",sub:"Government",date:"",dateLabel:"Mon-Fri 8:30am-4:45pm",venue:"WI DMV Green Bay",loc:"Ashwaubenon",addr:"942 Vanderperren Way, Green Bay, WI 54304",desc:"Driver license/ID, knowledge tests, plates, registration, disabled parking credentials. Walk-in or schedule. Mon-Fri 8:30-4:45.",url:"https://trust.dot.state.wi.us/",setting:"indoor",walking:"lowWalking",goodFor:["seniors"],highlight:false,free:false,recurring:true},
];

let newStr = '';
for (const e of entries) {
  const descEsc = e.desc.replace(/"/g, '\\"');
  const nameEsc = e.name.replace(/"/g, '\\"');
  let s = ',\n{id:' + e.id + ',name:"' + nameEsc + '",cat:"' + e.cat + '",sub:"' + e.sub + '"';
  s += ',price:"' + (e.free ? 'free' : '$$') + '",priceNum:' + (e.free ? 0 : 2);
  s += ',date:"' + (e.date||'') + '"';
  if (e.dateTo) s += ',dateTo:"' + e.dateTo + '"';
  s += ',dateLabel:"' + (e.dateLabel || '') + '"';
  s += ',venue:"' + e.venue + '"';
  s += ',desc:"' + descEsc + '"';
  s += ',url:"' + (e.url || '') + '"';
  s += ',setting:"' + e.setting + '",walking:"' + e.walking + '"';
  s += ',goodFor:' + JSON.stringify(e.goodFor);
  s += ',highlight:' + e.highlight;
  s += ',cuisine:"' + (e.cuisine || '') + '",established:""';
  s += ',free:' + e.free + ',recurring:' + (e.recurring || false) + '}';
  newStr += s;
}

const lastEntry = 'free:true,recurring:true}';
const idx = html.lastIndexOf(lastEntry);
if (idx === -1) { console.log('ERROR: insertion point not found'); process.exit(1); }
html = html.substring(0, idx + lastEntry.length) + newStr + html.substring(idx + lastEntry.length);

fs.writeFileSync(path, html, 'utf8');
console.log('Added ' + entries.length + ' entries (IDs ' + Math.min(...entries.map(e=>e.id)) + '-' + Math.max(...entries.map(e=>e.id)) + ')');
console.log('File size: ' + Buffer.byteLength(html, 'utf8'));
