const fs = require('fs');
const path = 'C:/Users/shawn/Downloads/Green Bay Explorer.html';
let html = fs.readFileSync(path, 'utf8');

const newEntries = [
{id:3400,name:"Jake Owen — Dream to Dreams Tour",cat:"Event",sub:"Concert",date:"2026-03-26",dateLabel:"Thu Mar 26, 7:30pm",venue:"Meyer Theatre, 117 S Washington St",loc:"Downtown Green Bay",addr:"117 S Washington St, Green Bay, WI 54301",desc:"Country star Jake Owen with Kendall Marvel. Dreams to Dreams Tour at the intimate Meyer Theatre. 7:30pm.",url:"https://meyertheatre.org/",setting:"indoor",walking:"lowWalking",goodFor:["couples","seniors"],highlight:false,free:false,recurring:false},
{id:3401,name:"Glenn Miller Orchestra",cat:"Event",sub:"Concert",date:"2026-04-29",dateLabel:"Wed Apr 29, 7:30pm",venue:"Meyer Theatre, 117 S Washington St",loc:"Downtown Green Bay",addr:"117 S Washington St, Green Bay, WI 54301",desc:"The legendary Glenn Miller Orchestra — big band swing classics! Moonlight Serenade, In the Mood, Chattanooga Choo Choo. Perfect for seniors who love the classics. 7:30pm.",url:"https://meyertheatre.org/",setting:"indoor",walking:"lowWalking",goodFor:["seniors","couples"],highlight:true,free:false,recurring:false},
{id:3402,name:"REO Speedwagon Tribute — Ridin' the Storm Out",cat:"Event",sub:"Concert",date:"2026-05-01",dateLabel:"Fri May 1, 7:30pm",venue:"Meyer Theatre",loc:"Downtown Green Bay",addr:"117 S Washington St, Green Bay, WI 54301",desc:"America's #1 REO Speedwagon tribute band. Can't Fight This Feeling, Keep On Loving You, Take It on the Run. 7:30pm.",url:"https://meyertheatre.org/",setting:"indoor",walking:"lowWalking",goodFor:["seniors","couples"],highlight:false,free:false,recurring:false},
{id:3403,name:"The Lovin' Spoonful",cat:"Event",sub:"Concert",date:"2026-05-28",dateLabel:"Thu May 28, 7pm",venue:"Meyer Theatre",loc:"Downtown Green Bay",addr:"117 S Washington St, Green Bay, WI 54301",desc:"60s legends! Do You Believe in Magic, Summer in the City, Daydream. A nostalgia treat. 7pm.",url:"https://meyertheatre.org/",setting:"indoor",walking:"lowWalking",goodFor:["seniors","couples"],highlight:true,free:false,recurring:false},
{id:3404,name:"Liverpool Legends — Beatles Experience",cat:"Event",sub:"Concert",date:"2026-05-29",dateLabel:"Fri May 29, 7:30pm",venue:"Meyer Theatre",loc:"Downtown Green Bay",addr:"117 S Washington St, Green Bay, WI 54301",desc:"The complete Beatles experience — costumes, instruments, and note-perfect performances from early Cavern Club to Abbey Road. 7:30pm.",url:"https://meyertheatre.org/",setting:"indoor",walking:"lowWalking",goodFor:["seniors","couples"],highlight:true,free:false,recurring:false},
{id:3405,name:"BoDeans — 40 Years",cat:"Event",sub:"Concert",date:"2026-06-05",dateLabel:"Fri Jun 5, 7:30pm",venue:"Meyer Theatre",loc:"Downtown Green Bay",addr:"117 S Washington St, Green Bay, WI 54301",desc:"Wisconsin's own BoDeans celebrate 40 years! Fadeaway, Good Things, Closer to Free. Iconic Midwest rock. 7:30pm.",url:"https://meyertheatre.org/",setting:"indoor",walking:"lowWalking",goodFor:["seniors","couples"],highlight:true,free:false,recurring:false},
{id:3406,name:"Jay and The Americans",cat:"Event",sub:"Concert",date:"2026-07-08",dateLabel:"Wed Jul 8, 7pm",venue:"Meyer Theatre",loc:"Downtown Green Bay",addr:"117 S Washington St, Green Bay, WI 54301",desc:"Classic 60s hits: Come a Little Bit Closer, This Magic Moment, Cara Mia. Great nostalgic concert. 7pm.",url:"https://meyertheatre.org/",setting:"indoor",walking:"lowWalking",goodFor:["seniors","couples"],highlight:true,free:false,recurring:false},
{id:3407,name:"Get The Led Out — Led Zeppelin Tribute",cat:"Event",sub:"Concert",date:"2026-07-15",dateLabel:"Wed Jul 15, 7:30pm",venue:"Meyer Theatre",loc:"Downtown Green Bay",addr:"117 S Washington St, Green Bay, WI 54301",desc:"Ultimate Led Zeppelin experience. Full orchestral arrangements of Stairway to Heaven, Kashmir, and more. 7:30pm.",url:"https://meyertheatre.org/",setting:"indoor",walking:"lowWalking",goodFor:["couples"],highlight:false,free:false,recurring:false},
{id:3410,name:"Mrs. Doubtfire (Broadway in Green Bay)",cat:"Event",sub:"Theater",date:"2026-03-23",dateLabel:"Mon Mar 23, 7:30pm",venue:"Weidner Center, UWGB",loc:"UWGB Campus",addr:"2420 Nicolet Dr, Green Bay, WI 54311",desc:"The hilarious Broadway musical based on the beloved Robin Williams film. Laugh-out-loud family fun at the Weidner Center! 7:30pm.",url:"https://www.weidnercenter.com/",setting:"indoor",walking:"lowWalking",goodFor:["family","seniors","couples"],highlight:true,free:false,recurring:false},
{id:3411,name:"Harry Potter — Prisoner of Azkaban in Concert",cat:"Event",sub:"Concert",date:"2026-04-18",dateLabel:"Sat Apr 18, 7:30pm",venue:"Weidner Center, UWGB",loc:"UWGB Campus",addr:"2420 Nicolet Dr, Green Bay, WI 54311",desc:"Watch the full Harry Potter film on the big screen while the Weidner Philharmonic performs John Williams' score live! A magical experience. 7:30pm.",url:"https://www.weidnercenter.com/",setting:"indoor",walking:"lowWalking",goodFor:["family","couples"],highlight:true,free:false,recurring:false},
{id:3412,name:"Weidner Philharmonic — Beethoven's 9th",cat:"Event",sub:"Concert",date:"2026-05-02",dateLabel:"Sat May 2, 7pm",venue:"Weidner Center, UWGB",loc:"UWGB Campus",addr:"2420 Nicolet Dr, Green Bay, WI 54311",desc:"Beethoven's 9th Symphony with Dudley Birder Chorale and UWGB Choirs. Triumphant Ode to Joy finale! Season closer. 7pm.",url:"https://www.weidnercenter.com/",setting:"indoor",walking:"lowWalking",goodFor:["seniors","couples"],highlight:true,free:false,recurring:false},
{id:3415,name:"Titletown Beats — Jesse McCartney (FREE)",cat:"Event",sub:"Concert",date:"2026-07-19",dateLabel:"Sun Jul 19, 5:30pm",venue:"Titletown, near Lambeau Field",loc:"Ashwaubenon",addr:"1065 Lombardi Ave, Green Bay, WI 54304",desc:"FREE summer concert! Jesse McCartney headlines with opener 7000apart. Activities 5:30pm, opener 6:30pm, headliner 8pm. No tickets needed.",url:"https://www.titletown.com/events/titletown-beats",setting:"outdoor",walking:"lowWalking",goodFor:["family","seniors","couples"],highlight:true,free:true,recurring:false},
{id:3416,name:"Titletown Beats — Chase Rice (FREE)",cat:"Event",sub:"Concert",date:"2026-08-26",dateLabel:"Wed Aug 26, 5:30pm",venue:"Titletown, near Lambeau Field",loc:"Ashwaubenon",addr:"1065 Lombardi Ave, Green Bay, WI 54304",desc:"FREE summer concert! Chase Rice headlines with Outlaw'd. Activities 5:30pm, opener 6:30pm, headliner 8pm.",url:"https://www.titletown.com/events/titletown-beats",setting:"outdoor",walking:"lowWalking",goodFor:["family","seniors","couples"],highlight:true,free:true,recurring:false},
{id:3420,name:"Bay Beach — Season Opening Day!",cat:"Event",sub:"Family",date:"2026-05-02",dateLabel:"Sat May 2, 10am-6pm",venue:"Bay Beach Amusement Park",loc:"Green Bay",addr:"1313 Bay Beach Rd, Green Bay, WI 54302",desc:"Bay Beach opens for the 2026 season! Rides just 25 cents each. Free parking, free admission. Opening weekend 10am-6pm.",url:"https://www.greenbaywi.gov/",setting:"outdoor",walking:"someWalking",goodFor:["family","seniors"],highlight:true,free:true,recurring:false},
{id:3421,name:"Bay Beach — Free Concert",cat:"Event",sub:"Concert",date:"2026-06-30",dateLabel:"Jun 30, Jul 14, Jul 28, Aug 11 — 6-8pm",venue:"Bay Beach Amusement Park",loc:"Green Bay",addr:"1313 Bay Beach Rd, Green Bay, WI 54302",desc:"Four free evening concerts at Bay Beach this summer! Enjoy live music while kids ride. 6-8pm. Park open 10am-8pm. Jun 30, Jul 14, Jul 28, Aug 11.",url:"https://www.greenbaywi.gov/",setting:"outdoor",walking:"someWalking",goodFor:["family","seniors"],highlight:true,free:true,recurring:true},
{id:3423,name:"Bay Beach LEGO Event",cat:"Event",sub:"Family",date:"2026-07-18",dateTo:"2026-07-19",dateLabel:"Sat-Sun Jul 18-19",venue:"Bay Beach Amusement Park",loc:"Green Bay",addr:"1313 Bay Beach Rd, Green Bay, WI 54302",desc:"Huge LEGO display and building contests! FoxLUG builders. Sat 10am-5pm (contests), Sun 10am-3pm (display). $1 admission, $5 contest entry.",url:"https://www.greenbaywi.gov/",setting:"outdoor",walking:"someWalking",goodFor:["family"],highlight:true,free:false,recurring:false},
{id:3430,name:"Luke Combs at Lambeau Field",cat:"Event",sub:"Concert",date:"2026-05-15",dateTo:"2026-05-16",dateLabel:"Fri-Sat May 15-16, 5:20pm",venue:"Lambeau Field",loc:"Ashwaubenon",addr:"1265 Lombardi Ave, Green Bay, WI 54304",desc:"Country superstar Luke Combs' stadium tour comes to Lambeau! Two nights with Dierks Bentley, Ty Myers, Jake Worthington, Thelma & James. Show 5:20pm.",url:"https://www.packers.com/lambeau-field/luke-combs",setting:"outdoor",walking:"someWalking",goodFor:["couples"],highlight:true,free:false,recurring:false},
{id:3432,name:"Cellcom Green Bay Marathon Weekend",cat:"Event",sub:"Sports",date:"2026-05-19",dateLabel:"Sun May 19 (expo Sat May 18)",venue:"Lambeau Field / Stadium District",loc:"Ashwaubenon",addr:"1265 Lombardi Ave, Green Bay, WI 54304",desc:"Marathon, half marathon, 5K, and relay — all starting/finishing near Lambeau Field! Expo/packet pickup Sat May 18. Marathon 7am, Half 8am, 5K 8:15am.",url:"https://www.cellcomgreenbaymarathon.com/",setting:"outdoor",walking:"someWalking",goodFor:["family","seniors"],highlight:true,free:false,recurring:false},
{id:3433,name:"Walk to Mary Pilgrimage",cat:"Event",sub:"Faith / Pilgrimage",date:"2026-05-02",dateLabel:"Sat May 2, starting 7am",venue:"St. Norbert College to Our Lady of Champion Shrine",loc:"De Pere to Champion",addr:"100 Grant St, De Pere, WI 54115",desc:"22-mile walking pilgrimage from St. Norbert College to the National Shrine of Our Lady of Champion. Multiple join-in points with shuttles. A beautiful day of faith and community.",url:"https://walktomary.com/",setting:"outdoor",walking:"longWalking",goodFor:["seniors"],highlight:true,free:true,recurring:false},
{id:3434,name:"Celebrate De Pere — Memorial Day Festival",cat:"Event",sub:"Festival",date:"2026-05-23",dateTo:"2026-05-25",dateLabel:"Sat-Mon May 23-25",venue:"Voyageur Park, Downtown De Pere",loc:"De Pere",addr:"100 William St, De Pere, WI 54115",desc:"Three-day Memorial Day festival! Live music, marketplace, carnival, fireworks, food. Monday FREE admission.",url:"https://www.celebratedepere.com/",setting:"outdoor",walking:"someWalking",goodFor:["family","seniors","couples"],highlight:true,free:false,recurring:false},
{id:3435,name:"Bellin Run — 50th Annual (10K & 5K)",cat:"Event",sub:"Sports",date:"2026-06-13",dateLabel:"Sat Jun 13, 8am start",venue:"Bellin Hospital, Webster Ave",loc:"Downtown Green Bay",addr:"744 S Webster Ave, Green Bay, WI 54301",desc:"The 50th anniversary Bellin Run! Wisconsin's premier 10K. Children's runs Fri evening. National anthem 7:50am, race starts 8:00am. Registration $35-$55.",url:"https://www.bellinrun.com/",setting:"outdoor",walking:"someWalking",goodFor:["family","seniors"],highlight:true,free:false,recurring:false},
{id:3436,name:"Fire Over the Fox — July 4th",cat:"Event",sub:"Festival",date:"2026-07-04",dateLabel:"Sat Jul 4, 3-10:30pm",venue:"Downtown Green Bay Waterfront",loc:"Downtown Green Bay",addr:"CityDeck, 301 N Washington St, Green Bay, WI 54301",desc:"Green Bay's premier July 4th celebration! Live entertainment, food, family activities along the Fox River. Fireworks over the water ~9:45pm. FREE.",url:"https://downtowngreenbay.com/",setting:"outdoor",walking:"someWalking",goodFor:["family","seniors","couples"],highlight:true,free:true,recurring:false},
{id:3437,name:"Pulaski Polka Days",cat:"Event",sub:"Festival",date:"2026-07-16",dateTo:"2026-07-19",dateLabel:"Thu-Sun Jul 16-19",venue:"Pulaski Community Park",loc:"Pulaski",addr:"429 E Pulaski St, Pulaski, WI 54162",desc:"Four-day polka festival with live bands, dancing, parade, pancake breakfast, arts & crafts fair. Thursday fireworks at dusk. Gate tickets only.",url:"",setting:"outdoor",walking:"someWalking",goodFor:["seniors","couples","family"],highlight:true,free:false,recurring:false},
{id:3438,name:"Brown County Fair",cat:"Event",sub:"Festival",date:"2026-08-19",dateTo:"2026-08-23",dateLabel:"Tue-Sat Aug 19-23",venue:"Brown County Fairgrounds",loc:"De Pere",addr:"1500 Fort Howard Ave, De Pere, WI 54115",desc:"Five-day county fair! Livestock, exhibits, carnival midway, grandstand entertainment, demolition derby. $15 gate ($12 presale). Under 3 free. Sunday $10.",url:"https://browncountyfair.com/",setting:"outdoor",walking:"someWalking",goodFor:["family","seniors","couples"],highlight:true,free:false,recurring:false},
{id:3439,name:"ArtFest Green Bay",cat:"Event",sub:"Art",date:"2026-08-22",dateTo:"2026-08-23",dateLabel:"Sat-Sun Aug 22-23",venue:"Downtown Green Bay",loc:"Downtown Green Bay",addr:"Downtown Green Bay, WI",desc:"Major downtown fine art festival. Artists, live demos, interactive art, music, food. Sat 9am-7pm, Sun 10am-4pm.",url:"",setting:"outdoor",walking:"someWalking",goodFor:["seniors","couples","family"],highlight:true,free:true,recurring:false},
{id:3440,name:"Heritage Hill — Maple Sugaring Day",cat:"Event",sub:"History",date:"2026-03-14",dateLabel:"Sat Mar 14, 9am-4pm",venue:"Heritage Hill State Historical Park",loc:"Allouez",addr:"2640 S Webster Ave, Green Bay, WI 54301",desc:"Living history fur trade event with maple sugaring! Plus blacksmithing (9am-1pm) and poetry workshop (2-4pm).",url:"https://heritagehillgb.org/",setting:"outdoor",walking:"someWalking",goodFor:["family","seniors"],highlight:true,free:false,recurring:false},
{id:3441,name:"Heritage Hill — Snap Dragon Tavern",cat:"Event",sub:"History",date:"2026-05-24",dateLabel:"Sat May 24, 5-9pm",venue:"Heritage Hill State Historical Park",loc:"Allouez",addr:"2640 S Webster Ave, Green Bay, WI 54301",desc:"Historic tavern evening with food, drinks, and entertainment in the park's setting. 5-9pm.",url:"https://heritagehillgb.org/",setting:"outdoor",walking:"someWalking",goodFor:["couples","seniors"],highlight:false,free:false,recurring:false},
{id:3442,name:"Heritage Hill — Sunset Sips Wine Evenings",cat:"Event",sub:"Food & Wine",date:"2026-06-10",dateLabel:"Jun 10, Jul 8, Aug 12 — 5-9pm",venue:"Heritage Hill State Historical Park",loc:"Allouez",addr:"2640 S Webster Ave, Green Bay, WI 54301",desc:"Wine tasting evenings with Captain's Walk Winery in the historic park. Three summer dates: Jun 10, Jul 8, Aug 12. 5-9pm.",url:"https://heritagehillgb.org/",setting:"outdoor",walking:"someWalking",goodFor:["couples","seniors"],highlight:true,free:false,recurring:true},
{id:3443,name:"Heritage Hill — War For Empire Encampment",cat:"Event",sub:"History",date:"2026-08-30",dateLabel:"Sun Aug 30, 9am-4pm",venue:"Heritage Hill State Historical Park",loc:"Allouez",addr:"2640 S Webster Ave, Green Bay, WI 54301",desc:"Military reenactment of French & Indian War era. Musket demonstrations, camp life, period crafts.",url:"https://heritagehillgb.org/",setting:"outdoor",walking:"someWalking",goodFor:["family","seniors"],highlight:true,free:false,recurring:false},
{id:3444,name:"Railroad Museum — Tales on the Rails",cat:"Event",sub:"Family",date:"2026-03-28",dateTo:"2026-03-29",dateLabel:"Sat-Sun Mar 28-29",venue:"National Railroad Museum",loc:"Ashwaubenon",addr:"2285 S Broadway, Green Bay, WI 54304",desc:"Special ticketed festival with train rides all day! Choose standard or premium ride times. Great family spring break outing.",url:"https://nationalrrmuseum.org/tales-on-the-rails/",setting:"indoor",walking:"someWalking",goodFor:["family","seniors"],highlight:true,free:false,recurring:false},
{id:3445,name:"Railroad Museum — 70th Anniversary Day",cat:"Event",sub:"Family",date:"2026-05-02",dateLabel:"Sat May 2, 9am-5pm",venue:"National Railroad Museum",loc:"Ashwaubenon",addr:"2285 S Broadway, Green Bay, WI 54304",desc:"Free kids admission + free train rides! Celebrating 70 years. Great for grandkids.",url:"https://nationalrrmuseum.org/70th/",setting:"indoor",walking:"someWalking",goodFor:["family","seniors"],highlight:true,free:false,recurring:false},
{id:3446,name:"Railroad Museum — PAW Patrol Paw-Palooza",cat:"Event",sub:"Family",date:"2026-06-12",dateTo:"2026-06-14",dateLabel:"Fri-Sun Jun 12-14",venue:"National Railroad Museum",loc:"Ashwaubenon",addr:"2285 S Broadway, Green Bay, WI 54304",desc:"PAW Patrol characters visit the museum! Themed train rides, activities, photo ops. Ticketed — buy early!",url:"https://nationalrrmuseum.org/paw-patrol-paw-palooza/",setting:"indoor",walking:"someWalking",goodFor:["family"],highlight:true,free:false,recurring:false},
{id:3450,name:"NEW Zoo — Sip 'n' Safari",cat:"Event",sub:"Food & Wine",date:"2026-06-16",dateLabel:"Tue Jun 16, 5-8pm",venue:"NEW Zoo & Adventure Park",loc:"Suamico",addr:"4378 Reforestation Rd, Suamico, WI 54173",desc:"Wine and cheese pairings while viewing wildlife at dusk! Adults-only zoo evening. Tickets on sale May 1.",url:"https://newzoo.org/events/",setting:"outdoor",walking:"someWalking",goodFor:["couples","seniors"],highlight:true,free:false,recurring:false},
{id:3451,name:"NEW Zoo — Twilight Canopy Tours",cat:"Event",sub:"Nature",date:"2026-05-30",dateLabel:"May 30, Jun 27, Jul 25, Aug 29 — 6-8pm",venue:"NEW Zoo & Adventure Park",loc:"Suamico",addr:"4378 Reforestation Rd, Suamico, WI 54173",desc:"Evening zipline canopy tours through the treetops at dusk! Four summer dates. 6-8pm.",url:"https://newzoo.org/events/",setting:"outdoor",walking:"someWalking",goodFor:["couples","family"],highlight:false,free:false,recurring:true},
{id:3455,name:"Green Bay Rockers — Home Opener",cat:"Event",sub:"Sports",date:"2026-05-27",dateLabel:"Wed May 27, 6:35pm",venue:"Capital Credit Union Park",loc:"Ashwaubenon",addr:"2231 Holmgren Way, Ashwaubenon, WI 54304",desc:"Opening night for the 2026 Rockers! Affordable Northwoods League summer college baseball. Promotions, fireworks, fun. Tickets from $8.",url:"https://northwoodsleague.com/green-bay-rockers/",setting:"outdoor",walking:"lowWalking",goodFor:["family","seniors","couples"],highlight:true,free:false,recurring:false},
{id:3456,name:"Green Bay Rockers — 36 Summer Home Games",cat:"Event",sub:"Sports",date:"2026-05-27",dateTo:"2026-08-05",dateLabel:"36 home games May 27 - Aug 5",venue:"Capital Credit Union Park",loc:"Ashwaubenon",addr:"2231 Holmgren Way, Ashwaubenon, WI 54304",desc:"36 home games of affordable baseball! Dollar dog nights, fireworks Fridays, family Sundays. 6:35pm weeknights, 1:05pm weekends. Tickets from $8.",url:"https://northwoodsleague.com/green-bay-rockers/",setting:"outdoor",walking:"lowWalking",goodFor:["family","seniors","couples"],highlight:true,free:false,recurring:true},
{id:3460,name:"Absolutely Country, Definitely Gospel Show",cat:"Event",sub:"Concert",date:"2026-03-18",dateLabel:"Wed Mar 18, 5pm dinner / 7pm show (+ Thu matinee)",venue:"Riverside Ballroom, 1560 Main St",loc:"Downtown Green Bay",addr:"1560 Main St, Green Bay, WI 54302",desc:"Branson-style country & gospel dinner show! Inspiring country and gospel music. Dinner 6pm, show 7pm. Also matinee Mar 19 (lunch noon, show 1pm).",url:"",setting:"indoor",walking:"lowWalking",goodFor:["seniors","couples"],highlight:true,free:false,recurring:false},
{id:3461,name:"Josiah Queen — Mt. Zion Worship Tour",cat:"Event",sub:"Concert",date:"2026-05-01",dateLabel:"Fri May 1, 7pm",venue:"EPIC Event Center",loc:"Ashwaubenon",addr:"2351 Holmgren Way, Ashwaubenon, WI 54304",desc:"Contemporary Christian worship concert! Josiah Queen brings the Mt. Zion Tour. VIP doors 5:15pm, GA 6:15pm, show 7pm.",url:"",setting:"indoor",walking:"lowWalking",goodFor:["seniors","couples","family"],highlight:true,free:false,recurring:false},
{id:3462,name:"Marian Conference at Our Lady of Champion",cat:"Event",sub:"Faith / Pilgrimage",date:"2026-05-22",dateTo:"2026-05-23",dateLabel:"Fri-Sat May 22-23",venue:"National Shrine of Our Lady of Champion",loc:"Champion",addr:"4047 Chapel Dr, Champion, WI 54229",desc:"5th annual Marian Conference. Friday dinner & talk. Saturday: confessions 8am, talks, rosary procession, Mass. 4pm Mass fulfills Sunday obligation.",url:"https://www.shrineofourladyofchampion.org/",setting:"indoor",walking:"lowWalking",goodFor:["seniors"],highlight:true,free:false,recurring:false},
{id:3465,name:"Door County Fyr Bal Festival",cat:"Event",sub:"Festival",date:"2026-06-20",dateLabel:"Sat Jun 20 (all day + bonfire/fireworks at dusk)",venue:"Ephraim Waterfront / Eagle Harbor",loc:"Door County (Day Trip)",addr:"Ephraim, WI 54211",desc:"61st annual Scandinavian heritage festival! Music, crafts, food, parade. Spectacular bonfire + fireworks over Eagle Harbor. ~1 hr drive.",url:"https://ephraim-doorcounty.com/events/fyr-bal-festival/",setting:"outdoor",walking:"someWalking",goodFor:["seniors","couples","family"],highlight:true,free:true,recurring:false},
{id:3466,name:"Door County Beer Festival",cat:"Event",sub:"Festival",date:"2026-06-20",dateLabel:"Sat Jun 20, noon-4pm",venue:"About Thyme Farm, Baileys Harbor",loc:"Door County (Day Trip)",addr:"8425 County F, Baileys Harbor, WI 54202",desc:"Large craft beer festival at a scenic farm. 40+ breweries. 21+. Shuttle parking. ~1 hr from Green Bay.",url:"https://doorcountybeer.com/",setting:"outdoor",walking:"someWalking",goodFor:["couples"],highlight:false,free:false,recurring:false},
{id:3467,name:"Door County Wine Fest (10th Anniversary)",cat:"Event",sub:"Festival",date:"2026-06-27",dateLabel:"Sat Jun 27, noon-4pm",venue:"About Thyme Farm, Baileys Harbor",loc:"Door County (Day Trip)",addr:"8425 County F, Baileys Harbor, WI 54202",desc:"10th anniversary wine festival! VIP 11am, general tasting noon. Beautiful farm setting. 21+.",url:"https://www.doorcountywinefest.com/",setting:"outdoor",walking:"someWalking",goodFor:["couples","seniors"],highlight:true,free:false,recurring:false},
{id:3468,name:"Peninsula Music Festival — 74th Season",cat:"Event",sub:"Concert",date:"2026-08-04",dateTo:"2026-08-22",dateLabel:"9 concerts Aug 4-22 (Mon/Wed/Fri), 7:30pm",venue:"Door Community Auditorium, Fish Creek",loc:"Door County (Day Trip)",addr:"3926 WI-42, Fish Creek, WI 54212",desc:"World-class symphony in Door County! Nine concerts over three weeks at 7:30pm. A cultural gem. ~1 hr from Green Bay.",url:"https://www.musicfestival.com/",setting:"indoor",walking:"lowWalking",goodFor:["seniors","couples"],highlight:true,free:false,recurring:true},
{id:3469,name:"Northern Sky Theater — Outdoor Musicals",cat:"Event",sub:"Theater",date:"2026-06-24",dateTo:"2026-08-29",dateLabel:"Nightly Jun 24 - Aug 29, 7:30pm (most nights)",venue:"Peninsula State Park Amphitheater",loc:"Door County (Day Trip)",addr:"10169 Shore Rd, Fish Creek, WI 54212",desc:"Beloved outdoor musical theater under the stars! Three rotating original musicals. Bring a blanket. ~1 hr from Green Bay.",url:"https://www.northernskytheater.com/",setting:"outdoor",walking:"someWalking",goodFor:["seniors","couples","family"],highlight:true,free:false,recurring:true},
{id:3470,name:"Jacksonport Cherry Fest",cat:"Event",sub:"Festival",date:"2026-08-01",dateLabel:"Sat Aug 1, 9am-4pm",venue:"Lakeside Park, Jacksonport",loc:"Door County (Day Trip)",addr:"Lakeside Park, Jacksonport, WI 54235",desc:"Cherry-themed festival with arts, car show, live music, cherry pie on the Lake Michigan shore.",url:"",setting:"outdoor",walking:"someWalking",goodFor:["seniors","family","couples"],highlight:false,free:true,recurring:false},
{id:3471,name:"Door County Fair",cat:"Event",sub:"Festival",date:"2026-08-12",dateTo:"2026-08-16",dateLabel:"Wed-Sun Aug 12-16",venue:"John Miles County Park, Sturgeon Bay",loc:"Door County (Day Trip)",addr:"812 N 14th Ave, Sturgeon Bay, WI 54235",desc:"County fair with midway, livestock, grandstand shows, demo derby. ~45 min from Green Bay.",url:"https://www.co.door.wi.gov/1007/Door-County-Fair-Website",setting:"outdoor",walking:"someWalking",goodFor:["family","seniors"],highlight:false,free:false,recurring:false},
{id:3475,name:"Pour Another Round — Outdoor Beer Fest",cat:"Event",sub:"Festival",date:"2026-03-21",dateLabel:"Sat Mar 21, 1-4pm",venue:"Hinterland Brewery",loc:"Ashwaubenon",addr:"1001 Lombardi Ave, Green Bay, WI 54304",desc:"4th annual outdoor winter beer fest! 15+ breweries, food, yard games, fan vote. 1-4pm.",url:"",setting:"outdoor",walking:"someWalking",goodFor:["couples"],highlight:false,free:false,recurring:false},
{id:3476,name:"Run for the Roses Wine Walk",cat:"Event",sub:"Food & Wine",date:"2026-05-02",dateLabel:"Sat May 2, 1-5pm",venue:"Broadway District, Downtown Green Bay",loc:"Downtown Green Bay",addr:"Broadway District, Green Bay, WI",desc:"Annual Derby-themed wine walk through Broadway shops! Sample wines, wear your best hat. Ticketed.",url:"https://downtowngreenbay.com/",setting:"outdoor",walking:"someWalking",goodFor:["couples","seniors"],highlight:false,free:false,recurring:false},
{id:3480,name:"Ashwaubenon Village-Wide Rummage Sale",cat:"Event",sub:"Flea Market",date:"2026-05-07",dateTo:"2026-05-09",dateLabel:"Thu-Sat May 7-9, 8am-3pm",venue:"Homes across Ashwaubenon",loc:"Ashwaubenon",addr:"Ashwaubenon, WI",desc:"Three days of community-wide rummage sales! Maps from the village. Dozens of participating homes. 8am-3pm.",url:"https://ashwaubenon.gov/",setting:"outdoor",walking:"someWalking",goodFor:["seniors"],highlight:true,free:true,recurring:false},
{id:3481,name:"MeatFest at Resch Expo",cat:"Event",sub:"Food",date:"2026-05-30",dateLabel:"Sat May 30, VIP 10am / GA 11am-4pm",venue:"Resch Expo",loc:"Ashwaubenon",addr:"840 Armed Forces Dr, Ashwaubenon, WI 54304",desc:"Pelkin's Smokey Meat Market presents MeatFest! BBQ tastings, vendors, samples, competitions.",url:"",setting:"indoor",walking:"someWalking",goodFor:["couples","family"],highlight:false,free:false,recurring:false},
{id:3485,name:"Downtown De Pere Farmers Market",cat:"Event",sub:"Farmers Market",date:"2026-06-04",dateTo:"2026-09-24",dateLabel:"Thursdays 3-8pm, Jun 4 - Sep 24",venue:"George Street Plaza, Downtown De Pere",loc:"De Pere",addr:"George St, De Pere, WI 54115",desc:"Weekly farmers market in downtown De Pere! Produce, baked goods, crafts. 3-8pm (September 3-7pm).",url:"https://definitelydepere.org/downtown-de-pere-farmers-market/",setting:"outdoor",walking:"someWalking",goodFor:["seniors","family"],highlight:true,free:true,recurring:true},
{id:3486,name:"Gardeners Club — Garden Walk",cat:"Event",sub:"Garden",date:"2026-07-18",dateLabel:"Sat Jul 18, 9am-3pm",venue:"Seven private gardens",loc:"Allouez / De Pere / Green Bay",addr:"Multiple locations (tickets at McAllister, Plant People, Take 5)",desc:"4th Annual Garden Walk! Tour seven beautiful private gardens. Tickets from April at local retailers.",url:"",setting:"outdoor",walking:"someWalking",goodFor:["seniors","couples"],highlight:true,free:false,recurring:false},
{id:3487,name:"Botanical Garden — Sanimax Summer Concerts",cat:"Event",sub:"Concert",date:"2026-06-13",dateTo:"2026-08-29",dateLabel:"Select Thursdays 6-8pm, Jun-Aug",venue:"Green Bay Botanical Garden",loc:"Allouez",addr:"2600 Larsen Rd, Green Bay, WI 54311",desc:"Ticketed Thursday evening concerts in the beautiful Botanical Garden. Music among the flowers! Check gbbg.org for dates.",url:"https://www.gbbg.org/",setting:"outdoor",walking:"someWalking",goodFor:["seniors","couples"],highlight:true,free:false,recurring:true},
{id:3488,name:"Packers Heritage Trail Trolley Tour",cat:"Event",sub:"History",date:"2026-07-25",dateLabel:"Sat Jul 25 — departures 9:45am, 10:15am, 11:45am, 12:15pm",venue:"Lambeau Field (American Family Insurance Gate)",loc:"Ashwaubenon",addr:"1265 Lombardi Ave, Green Bay, WI 54304",desc:"Guided 90-min trolley tour of Packers Heritage Trail landmarks! Arrive 20 min early. Waiver required.",url:"https://www.packershofandtours.com/explore/heritage-trail/trolley-tour",setting:"outdoor",walking:"lowWalking",goodFor:["seniors","family"],highlight:true,free:false,recurring:false},
{id:3489,name:"De Pere Foodie Walk",cat:"Event",sub:"Food",date:"2026-05-09",dateLabel:"Sat May 9, 1-5pm",venue:"Downtown De Pere restaurants",loc:"De Pere",addr:"Downtown De Pere, WI",desc:"Walk downtown De Pere sampling dishes from local restaurants! 300 tickets, $25.",url:"https://definitelydepere.org/",setting:"outdoor",walking:"someWalking",goodFor:["couples","seniors"],highlight:false,free:false,recurring:false},
{id:3490,name:"Acoustic Lunch at Titletown (FREE)",cat:"Event",sub:"Free Concert Series",date:"2026-05-29",dateTo:"2026-09-25",dateLabel:"Fridays 11:30am-1:30pm, May 29 - Sep 25",venue:"46 Below patio, Titletown",loc:"Ashwaubenon",addr:"1065 Lombardi Ave, Green Bay, WI 54304",desc:"FREE Friday lunchtime acoustic concerts at Titletown! Different artists each week. 11:30am-1:30pm.",url:"https://www.titletown.com/events/acoustic-lunch",setting:"outdoor",walking:"lowWalking",goodFor:["seniors","couples"],highlight:true,free:true,recurring:true},
{id:3491,name:"Movies at Titletown (FREE)",cat:"Event",sub:"Family",date:"2026-06-14",dateLabel:"Jun 14, Jul 25-26 — FREE outdoor movies",venue:"Titletown, near Lambeau Field",loc:"Ashwaubenon",addr:"1065 Lombardi Ave, Green Bay, WI 54304",desc:"FREE outdoor movies! Jun 14: Tangled (4pm) & Twisters (6:30pm). Jul 25: Cars (6:30pm). Jul 26: National Treasure (6:30pm).",url:"https://www.titletown.com/events/movies-at-titletown",setting:"outdoor",walking:"lowWalking",goodFor:["family","seniors","couples"],highlight:true,free:true,recurring:false},
{id:3493,name:"Brown County Library — Summer Programs",cat:"Event",sub:"Education / Classes",date:"2026-06-01",dateTo:"2026-08-15",dateLabel:"Jun-Aug (all branches)",venue:"Brown County Library (all branches)",loc:"Multiple locations",addr:"515 Pine St, Green Bay, WI 54301 (Central)",desc:"Free summer reading, author visits, storytimes, crafts, tech help, book clubs, and movie screenings at all branches. Check browncountylibrary.org.",url:"https://browncounty.librarycalendar.com/events",setting:"indoor",walking:"lowWalking",goodFor:["family","seniors"],highlight:true,free:true,recurring:true},
];

let newStr = '';
for (const e of newEntries) {
  const descEsc = e.desc.replace(/"/g, '\\"');
  const nameEsc = e.name.replace(/"/g, '\\"');
  let entry = ',\n{id:' + e.id + ',name:"' + nameEsc + '",cat:"' + e.cat + '",sub:"' + e.sub + '"';
  if (e.neighborhood) entry += ',neighborhood:"' + e.neighborhood + '"';
  entry += ',price:"' + (e.free ? 'free' : '$$') + '",priceNum:' + (e.free ? 0 : 2);
  entry += ',date:"' + e.date + '"';
  if (e.dateTo) entry += ',dateTo:"' + e.dateTo + '"';
  entry += ',dateLabel:"' + e.dateLabel + '"';
  entry += ',venue:"' + e.venue + '"';
  entry += ',desc:"' + descEsc + '"';
  entry += ',url:"' + (e.url || '') + '"';
  entry += ',setting:"' + e.setting + '",walking:"' + e.walking + '"';
  entry += ',goodFor:' + JSON.stringify(e.goodFor);
  entry += ',highlight:' + e.highlight;
  entry += ',cuisine:"' + (e.cuisine || '') + '",established:"' + (e.established || '') + '"';
  entry += ',free:' + e.free + ',recurring:' + e.recurring + '}';
  newStr += entry;
}

// Find the last entry (id:3383) and insert after it
const lastEntry = 'recurring:true}\n];';
const insertIdx = html.indexOf(lastEntry);
if (insertIdx === -1) {
  // Try without newline
  const lastEntry2 = 'free:false,recurring:true}';
  const idx2 = html.lastIndexOf(lastEntry2);
  if (idx2 === -1) {
    console.log('ERROR: Could not find insertion point');
    process.exit(1);
  }
  html = html.substring(0, idx2 + lastEntry2.length) + newStr + html.substring(idx2 + lastEntry2.length);
} else {
  html = html.substring(0, insertIdx + 'recurring:true}'.length) + newStr + html.substring(insertIdx + 'recurring:true}'.length);
}

fs.writeFileSync(path, html, 'utf8');

const finalSize = Buffer.byteLength(html, 'utf8');
console.log('New entries added: ' + newEntries.length);
console.log('ID range: ' + Math.min(...newEntries.map(e=>e.id)) + '-' + Math.max(...newEntries.map(e=>e.id)));
console.log('File size: ' + finalSize + ' bytes');
console.log('Done!');
