const fs = require('fs');
const path = 'C:/Users/shawn/Downloads/Green Bay Explorer.html';
let html = fs.readFileSync(path, 'utf8');

const entries = [
// === OSHKOSH GRAND THEATER ===
{id:3640,name:"Grand Oshkosh — Rocky Mountain High (John Denver Tribute)",cat:"Event",sub:"Concert",date:"2026-03-20",dateLabel:"Fri Mar 20, 7:30pm",venue:"The Grand Oshkosh",loc:"Oshkosh (Day Trip)",addr:"100 High Ave, Oshkosh, WI 54901",desc:"John Denver tribute concert! Country Roads, Sunshine, Rocky Mountain High. Beautiful historic theater. ~1 hr from Green Bay.",url:"https://www.thegrandoshkosh.org/",setting:"indoor",walking:"lowWalking",goodFor:["seniors","couples"],highlight:false,free:false,recurring:false},
{id:3641,name:"Grand Oshkosh — Elvis Tribute Show",cat:"Event",sub:"Concert",date:"2026-03-22",dateLabel:"Sun Mar 22, 3pm",venue:"The Grand Oshkosh",loc:"Oshkosh (Day Trip)",addr:"100 High Ave, Oshkosh, WI 54901",desc:"International Elvis Tribute Artist Show! Sunday matinee at the Grand. ~1 hr from Green Bay.",url:"https://www.thegrandoshkosh.org/",setting:"indoor",walking:"lowWalking",goodFor:["seniors","couples"],highlight:false,free:false,recurring:false},
{id:3642,name:"Grand Oshkosh — Olivia Newton-John Tribute",cat:"Event",sub:"Concert",date:"2026-03-29",dateLabel:"Sun Mar 29, 3pm",venue:"The Grand Oshkosh",loc:"Oshkosh (Day Trip)",addr:"100 High Ave, Oshkosh, WI 54901",desc:"Celebrate the music of Olivia Newton-John! Physical, Grease, Have You Never Been Mellow. Sunday matinee.",url:"https://www.thegrandoshkosh.org/",setting:"indoor",walking:"lowWalking",goodFor:["seniors","couples"],highlight:false,free:false,recurring:false},
{id:3643,name:"Oshkosh Saturday Farmers Market",cat:"Event",sub:"Farmers Market",date:"2026-05-30",dateTo:"2026-10-31",dateLabel:"Saturdays 8am-12:30pm, May 30 - Oct (no Jul 4)",venue:"Downtown Oshkosh (N Main St)",loc:"Oshkosh (Day Trip)",addr:"400-500 N Main St, Oshkosh, WI 54901",desc:"140+ vendors! Fresh produce, artisan goods, live music. One of the best farmers markets in the Fox Valley. No market July 4th. ~1 hr from Green Bay.",url:"http://www.osfmi.com/",setting:"outdoor",walking:"someWalking",goodFor:["seniors","family","couples"],highlight:true,free:true,recurring:true},
{id:3644,name:"Paine Art Center — Rooms of Blooms",cat:"Event",sub:"Art",date:"2026-03-05",dateTo:"2026-03-15",dateLabel:"Mar 5-15 (Thu-Sun)",venue:"Paine Art Center & Gardens",loc:"Oshkosh (Day Trip)",addr:"1410 Algoma Blvd, Oshkosh, WI 54901",desc:"Stunning floral takeover of a historic mansion! Thousands of fresh flowers throughout the rooms. $33 adult (before 4pm), $22 after. Community First CU: 2-for-1. Tea time add-on $12.",url:"https://www.thepaine.org/",setting:"indoor",walking:"someWalking",goodFor:["seniors","couples"],highlight:true,free:false,recurring:false},
// === NEVILLE MUSEUM PROGRAMS ===
{id:3650,name:"Neville Museum — International Film Series (Free!)",cat:"Event",sub:"Film",date:"2026-03-22",dateTo:"2026-05-06",dateLabel:"1st Wednesdays 7pm: Apr 1, May 6",venue:"Neville Public Museum",loc:"Downtown Green Bay",addr:"210 Museum Pl, Green Bay, WI 54303",desc:"FREE international film screenings! First Wednesday of each month at 7pm. Apr 1: Italian film (with Italo-Americano Club). May 6: Dead Pigs (China 2018). Mature audiences.",url:"https://www.nevillepublicmuseum.org/",setting:"indoor",walking:"lowWalking",goodFor:["seniors","couples"],highlight:true,free:true,recurring:true},
{id:3651,name:"Neville Museum — Dinner Programs",cat:"Event",sub:"Cultural",date:"2026-03-19",dateLabel:"Mar 19: Gaelic Harp, Apr 16: Civil War, May 14: One Room Schools",venue:"Neville Public Museum",loc:"Downtown Green Bay",addr:"210 Museum Pl, Green Bay, WI 54303",desc:"Evening dinner and program series! Mar 19: Gaelic Harp music. Apr 16: Angel in a Gray Bonnet (Civil War). May 14: One Room Schools. Dinner 5pm, program ~6pm. Tickets required.",url:"https://www.nevillepublicmuseum.org/",setting:"indoor",walking:"lowWalking",goodFor:["seniors","couples"],highlight:true,free:false,recurring:false},
{id:3652,name:"Neville Museum — Curiosity Unveiled Tours",cat:"Event",sub:"Cultural",date:"2026-03-24",dateTo:"2026-08-18",dateLabel:"Monthly Mondays 6pm (various dates)",venue:"Neville Public Museum",loc:"Downtown Green Bay",addr:"210 Museum Pl, Green Bay, WI 54303",desc:"Guided deep-dive tours! Mar 24: A Place at the Table. Apr 21: Earth Day. May 19: Collections Tour ($15/$9 members). Jun 16: LGBTQ+ NE WI. Jul 21: America 250. Aug 18: Ice Age exhibit.",url:"https://www.nevillepublicmuseum.org/",setting:"indoor",walking:"lowWalking",goodFor:["seniors","couples"],highlight:false,free:false,recurring:false},
{id:3653,name:"Neville Museum — Veterans Lunch Program",cat:"Event",sub:"Senior Social",date:"2026-03-13",dateLabel:"Mar 13, Jun 12 (10am-noon)",venue:"Neville Public Museum",loc:"Downtown Green Bay",addr:"210 Museum Pl, Green Bay, WI 54303",desc:"Lunch and speaker program for veterans! Pre-registration required through ADRC of Brown County (920) 448-4300. Mar 13: Vietnam reflections. Jun 12: topic TBA.",url:"https://www.nevillepublicmuseum.org/",setting:"indoor",walking:"lowWalking",goodFor:["seniors"],highlight:true,free:false,recurring:false},
// === CELEBRATE DE PERE ===
{id:3660,name:"Celebrate De Pere (Memorial Day Weekend)",cat:"Event",sub:"Festival",date:"2026-05-23",dateTo:"2026-05-25",dateLabel:"Sat-Mon May 23-25",venue:"Voyageur Park area, De Pere",loc:"De Pere",addr:"Voyageur Park, De Pere, WI",desc:"The BIG Memorial Day weekend festival in De Pere! Three days of food, rides, live music, entertainment. Sat-Sun 11am-11pm, Mon 11am-4pm. Kiwanis Memorial Day Parade Mon 10am through downtown.",url:"https://www.celebratedepere.com/",setting:"outdoor",walking:"someWalking",goodFor:["seniors","family","couples"],highlight:true,free:true,recurring:false},
{id:3661,name:"De Pere Sip & Shop Wine Walk (Spring)",cat:"Event",sub:"Food & Drink",date:"2026-04-10",dateLabel:"Fri Apr 10, 4-8pm",venue:"Downtown De Pere shops",loc:"De Pere",addr:"117 N Wisconsin St, De Pere, WI 54115",desc:"Wine walk through downtown De Pere shops! Wine samples, bites, and retail deals at participating stores. 21+. $25 tickets. Check-in at 117 N Wisconsin St.",url:"https://definitelydepere.org/",setting:"indoor",walking:"someWalking",goodFor:["couples","seniors"],highlight:true,free:false,recurring:false},
{id:3662,name:"De Pere Foodie Walk",cat:"Event",sub:"Food & Drink",date:"2026-05-09",dateLabel:"Sat May 9, 1-5pm",venue:"Downtown De Pere restaurants",loc:"De Pere",addr:"Downtown De Pere, WI",desc:"Ticketed tasting walk through downtown De Pere restaurants and bars! Sample signature dishes from the best local spots. $25. Proceeds support downtown programming.",url:"https://definitelydepere.org/",setting:"indoor",walking:"someWalking",goodFor:["couples","seniors"],highlight:true,free:false,recurring:false},
{id:3663,name:"Music on the Plaza — De Pere (3 dates)",cat:"Event",sub:"Free Concert Series",date:"2026-06-26",dateTo:"2026-08-28",dateLabel:"Fri 5-9pm: Jun 26, Jul 24, Aug 28",venue:"Michael J. Walsh Plaza, De Pere",loc:"De Pere",addr:"James St (between Wisconsin & Broadway), De Pere, WI",desc:"Live music, beer & seltzer, food trucks! Three summer Friday evenings on De Pere's beautiful Walsh Plaza (NOT George Street Plaza). Free admission. A great De Pere evening out.",url:"https://definitelydepere.org/events2/music-on-the-plaza/",setting:"outdoor",walking:"lowWalking",goodFor:["seniors","couples"],highlight:true,free:true,recurring:true},
// === FATHOM CLASSIC MOVIES ===
{id:3670,name:"Fathom: Ben-Hur on the Big Screen",cat:"Event",sub:"Classic Film",date:"2026-03-29",dateLabel:"Sun Mar 29 (also Apr 1-2)",venue:"Marcus Bay Park Cinema",loc:"Ashwaubenon",addr:"755 Willard Dr, Ashwaubenon, WI 54304",desc:"Charlton Heston in BEN-HUR on the big screen! The 1959 epic masterpiece like you've never seen it. Part of Fathom's 2026 Big Screen Classics series.",url:"https://www.fathomevents.com/",setting:"indoor",walking:"lowWalking",goodFor:["seniors","couples"],highlight:true,free:false,recurring:false},
{id:3671,name:"Fathom: Fried Green Tomatoes",cat:"Event",sub:"Classic Film",date:"2026-05-10",dateLabel:"Sun May 10 (also May 13)",venue:"Marcus Bay Park Cinema",loc:"Ashwaubenon",addr:"755 Willard Dr, Ashwaubenon, WI 54304",desc:"Fried Green Tomatoes (1991) back on the big screen! Mother's Day weekend treat. Jessica Tandy, Kathy Bates, Mary-Louise Parker.",url:"https://www.fathomevents.com/",setting:"indoor",walking:"lowWalking",goodFor:["seniors","couples"],highlight:true,free:false,recurring:false},
{id:3672,name:"Fathom: Willy Wonka & the Chocolate Factory (1971)",cat:"Event",sub:"Classic Film",date:"2026-08-02",dateLabel:"Sun Aug 2 (also Aug 5)",venue:"Marcus Bay Park Cinema",loc:"Ashwaubenon",addr:"755 Willard Dr, Ashwaubenon, WI 54304",desc:"Pure imagination! The original 1971 Willy Wonka with Gene Wilder on the big screen. Bring the grandkids!",url:"https://www.fathomevents.com/",setting:"indoor",walking:"lowWalking",goodFor:["seniors","family","couples"],highlight:true,free:false,recurring:false},
// === ARTFEST ===
{id:3675,name:"ArtFest Green Bay",cat:"Event",sub:"Festival",date:"2026-08-22",dateTo:"2026-08-23",dateLabel:"Sat 9am-7pm, Sun 10am-4pm",venue:"Downtown Green Bay (Pine St area)",loc:"Downtown Green Bay",addr:"Downtown Green Bay, WI 54301",desc:"FREE outdoor art festival in downtown Green Bay! Local and regional artists, live music, food trucks, Kids' Experience Art Zone. A wonderful weekend celebrating creativity.",url:"https://downtowngreenbay.com/artfest",setting:"outdoor",walking:"someWalking",goodFor:["seniors","family","couples"],highlight:true,free:true,recurring:false},
// === ONEIDA FARMERS MARKET ===
{id:3680,name:"Oneida Farmers Market (Thursdays)",cat:"Event",sub:"Farmers Market",date:"2026-06-04",dateTo:"2026-10-01",dateLabel:"Thursdays noon-6pm, Jun-Oct",venue:"Oneida Farmer's Market",loc:"Oneida",addr:"N7284 County Rd J, Oneida, WI 54155",desc:"Thursday afternoon farmers market at Oneida! Produce, crafts, food vendors. Free to attend. ~10 min west of Green Bay on Hwy 54.",url:"",setting:"outdoor",walking:"someWalking",goodFor:["seniors","family"],highlight:false,free:true,recurring:true},
// === TITLETOWN FREE FITNESS ===
{id:3685,name:"Titletown — Free Barre Classes (Summer)",cat:"Activity",sub:"Senior Fitness",date:"2026-06-09",dateTo:"2026-08-25",dateLabel:"Mon-Fri 5:30-6:15pm, Jun 9 - Aug 25",venue:"Titletown (Football Field)",loc:"Ashwaubenon",addr:"1065 Lombardi Ave, Green Bay, WI 54304",desc:"FREE barre fitness classes 5 days a week at Titletown District! Low-impact, great for all ages. On the football field next to Lambeau. Waiver required. Extra mats available.",url:"https://www.titletown.com/",setting:"outdoor",walking:"lowWalking",goodFor:["seniors","couples"],highlight:true,free:true,recurring:true},
// === HINTERLAND BEER FEST ===
{id:3690,name:"Pour Another Round — Outdoor Beer Festival",cat:"Event",sub:"Festival",date:"2026-03-21",dateLabel:"Sat Mar 21, 1-4pm",venue:"Hinterland Brewery",loc:"Ashwaubenon",addr:"1001 Lombardi Ave, Green Bay, WI 54304",desc:"4th Annual outdoor winter beer festival at Hinterland! Sample craft beers from multiple breweries. Unique winter outdoor tasting experience next to Lambeau Field.",url:"https://www.hinterlandbeer.com/",setting:"outdoor",walking:"someWalking",goodFor:["couples"],highlight:false,free:false,recurring:false},
// === RIVERSIDE BOXING ===
{id:3691,name:"Riverside Ballroom — Heavyweight Boxing Night",cat:"Event",sub:"Sports",date:"2026-03-21",dateLabel:"Sat Mar 21, doors 6pm",venue:"Riverside Ballroom",loc:"Downtown Green Bay",addr:"1560 Main St, Green Bay, WI 54302",desc:"THE CATACLYSM heavyweight title fight! Dennis 'King Mongoose' Morris. GA $40, ringside $100, VIP table (8) $1,000. Historic venue, exciting night of boxing.",url:"https://riversideballroom.com/",setting:"indoor",walking:"lowWalking",goodFor:["couples"],highlight:false,free:false,recurring:false},
// === EARTH DAY ===
{id:3692,name:"'Natural World of the Bay' Film Premiere (Earth Day)",cat:"Event",sub:"Film",date:"2026-04-22",dateLabel:"Wed Apr 22, 5pm open house, 6pm screening",venue:"UW-Green Bay University Theatre",loc:"Allouez / UWGB",addr:"2420 Nicolet Dr, Green Bay, WI 54311",desc:"Earth Day premiere of a new documentary about the ecology of Green Bay and the Lower Fox River watershed! Open house at 5pm, film at 6pm, exhibits after. Benefits scholarships and environmental monitoring.",url:"https://news.uwgb.edu/",setting:"indoor",walking:"lowWalking",goodFor:["seniors","couples"],highlight:true,free:true,recurring:false},
// === KROC CENTER SUPER SENIOR DAY ===
{id:3695,name:"Kroc Center — Super Senior Day (Monthly)",cat:"Activity",sub:"Senior Social",date:"2026-03-22",dateTo:"2026-08-31",dateLabel:"4th Friday monthly, ~10am",venue:"Ray & Joan Kroc Center",loc:"Green Bay",addr:"1315 Lime Kiln Rd, Green Bay, WI 54311",desc:"Monthly Super Senior Day with bingo, crafts, games, entertainment! $5. Arrive 9:30am. SilverSneakers, Renew Active, Silver&Fit accepted for gym membership. Pickleball courts too! (920) 884-5007.",url:"https://www.gbkroccenter.org/",setting:"indoor",walking:"lowWalking",goodFor:["seniors"],highlight:true,free:false,recurring:true},
// === CRIBBAGE CLUB ===
{id:3696,name:"PackerLand Peggers Cribbage Club (Wednesdays)",cat:"Activity",sub:"Card Games",date:"2026-03-22",dateTo:"2026-08-31",dateLabel:"Wednesdays 7pm",venue:"Burkel's Sports Bar",loc:"Green Bay",addr:"1007 Tony Canadeo Run, Green Bay, WI 54304",desc:"Weekly cribbage league! ~9 games over ~2.5 hours. Open to all skill levels. Contact Jeanne Wauters (920) 863-3703 for details.",url:"http://cribbage.org/",setting:"indoor",walking:"lowWalking",goodFor:["seniors"],highlight:false,free:false,recurring:true},
// === ANDUZZI'S TRIVIA & BINGO ===
{id:3697,name:"Anduzzi's — Wednesday DJ Trivia (3 locations!)",cat:"Activity",sub:"Trivia Night",date:"2026-03-22",dateTo:"2026-08-31",dateLabel:"Wednesdays 7-9pm",venue:"Anduzzi's Sports Club",loc:"Multiple",addr:"900 Kepler Dr (East) / 1992 Holmgren Way (Stadium) / 2555 Lineville Rd (Howard)",desc:"DJ Trivia every Wednesday at all three Anduzzi's! Plus DJ Bingo on Tuesdays 7-9pm at the Stadium District location. Fun casual night out with food and drinks.",url:"https://anduzzis.com/",setting:"indoor",walking:"lowWalking",goodFor:["couples","seniors"],highlight:false,free:true,recurring:true},
];

let newStr = '';
for (const e of entries) {
  const descEsc = e.desc.replace(/"/g, '\\"');
  const nameEsc = e.name.replace(/"/g, '\\"');
  let s = ',\n{id:' + e.id + ',name:"' + nameEsc + '",cat:"' + e.cat + '",sub:"' + e.sub + '"';
  s += ',price:"' + (e.free ? 'free' : '$$') + '",priceNum:' + (e.free ? 0 : 2);
  s += ',date:"' + (e.date||'') + '"';
  if (e.dateTo) s += ',dateTo:"' + e.dateTo + '"';
  s += ',dateLabel:"' + e.dateLabel + '"';
  s += ',venue:"' + e.venue + '"';
  s += ',desc:"' + descEsc + '"';
  s += ',url:"' + (e.url || '') + '"';
  s += ',setting:"' + e.setting + '",walking:"' + e.walking + '"';
  s += ',goodFor:' + JSON.stringify(e.goodFor);
  s += ',highlight:' + e.highlight;
  s += ',cuisine:"",established:""';
  s += ',free:' + e.free + ',recurring:' + (e.recurring || false) + '}';
  newStr += s;
}

const lastEntry = 'free:false,recurring:false}';
const idx = html.lastIndexOf(lastEntry);
if (idx === -1) { console.log('ERROR: insertion point not found'); process.exit(1); }
html = html.substring(0, idx + lastEntry.length) + newStr + html.substring(idx + lastEntry.length);

fs.writeFileSync(path, html, 'utf8');
console.log('Added ' + entries.length + ' entries (IDs ' + Math.min(...entries.map(e=>e.id)) + '-' + Math.max(...entries.map(e=>e.id)) + ')');
console.log('File size: ' + Buffer.byteLength(html, 'utf8'));
