const fs = require('fs');
const path = 'C:/Users/shawn/Downloads/Green Bay Explorer.html';
let html = fs.readFileSync(path, 'utf8');

const entries = [
// === UWGB ATHLETICS (FREE!) ===
{id:4050,name:"UWGB Phoenix Softball — FREE Admission!",cat:"Event",sub:"Sports",date:"2026-03-27",dateTo:"2026-04-25",dateLabel:"Home: Mar 27-28, Apr 1,3-4,7,20,22,24-25",venue:"King Park",loc:"East Green Bay",addr:"UWGB Campus, Green Bay, WI 54311",desc:"FREE admission! UWGB softball home games at King Park. Doubleheaders most dates. Great college sports atmosphere. Go Phoenix!",url:"https://www.greenbayphoenix.com/sports/softball/schedule/2026",setting:"outdoor",walking:"lowWalking",goodFor:["family","seniors"],highlight:true,free:true,recurring:false},
{id:4051,name:"UWGB Men's Soccer — FREE (Spring Exhibition)",cat:"Event",sub:"Sports",date:"2026-04-03",dateTo:"2026-04-19",dateLabel:"Apr 3, 11, 19 at Aldo Santaga Stadium",venue:"Festival Foods Field at Aldo Santaga Stadium",loc:"East Green Bay",addr:"UWGB Campus, Green Bay, WI 54311",desc:"FREE admission to UWGB Phoenix soccer! Spring home games at Aldo Santaga Stadium. Wisconsin Cup semifinal Apr 19 vs Milwaukee!",url:"https://www.greenbayphoenix.com/sports/mens-soccer/schedule",setting:"outdoor",walking:"lowWalking",goodFor:["family","seniors"],highlight:true,free:true,recurring:false},
// === ST. NORBERT ATHLETICS (FREE!) ===
{id:4052,name:"St. Norbert Baseball — FREE Admission! (De Pere)",cat:"Event",sub:"Sports",date:"2026-03-28",dateTo:"2026-04-28",dateLabel:"Home DH: Mar 28, 31, Apr 11, 22, 25, 28",venue:"Mel Nicks Sports Complex",loc:"De Pere",addr:"St. Norbert College, De Pere, WI 54115",desc:"FREE admission! Division III baseball doubleheaders at Mel Nicks Sports Complex. Aurora, Illinois Tech, Concordia, and more.",url:"https://athletics.snc.edu/sports/baseball/schedule/2026",setting:"outdoor",walking:"lowWalking",goodFor:["family","seniors"],highlight:true,free:true,recurring:false},
{id:4053,name:"St. Norbert Softball — FREE! (De Pere)",cat:"Event",sub:"Sports",date:"2026-03-28",dateTo:"2026-05-02",dateLabel:"Home DH: Mar 28, Apr 4, 18-19, May 1-2",venue:"Mel Nicks Sports Complex",loc:"De Pere",addr:"St. Norbert College, De Pere, WI 54115",desc:"FREE admission! St. Norbert softball doubleheaders. Great afternoon outing. Benedictine, Concordia, Rockford, Marian, Edgewood.",url:"https://athletics.snc.edu/sports/softball/schedule/2026",setting:"outdoor",walking:"lowWalking",goodFor:["family","seniors"],highlight:true,free:true,recurring:false},
// === LIBRARY EVENTS ===
{id:4055,name:"Brown County Library — Computer Basics Class (FREE!)",cat:"Activity",sub:"Education / Classes",date:"2026-04-21",dateLabel:"Apr 21, 2-3:30pm (Central Library)",venue:"Brown County Central Library",loc:"Downtown Green Bay",addr:"515 Pine St, Green Bay, WI 54301",desc:"FREE Computer Basics class at the Central Library! Learn essential skills. Also: Internet Basics May 19. Tech & Brain Wellness at Kress Branch. 920-448-4400.",url:"https://browncounty.librarycalendar.com/",setting:"indoor",walking:"lowWalking",goodFor:["seniors"],highlight:true,free:true,recurring:false},
{id:4056,name:"Friends of the Library BIG Book Sale!",cat:"Event",sub:"Shopping",date:"2026-04-27",dateTo:"2026-04-30",dateLabel:"Apr 27 (members only), Apr 28-30 open to all",venue:"Brown County Central Library",loc:"Downtown Green Bay",addr:"515 Pine St, Green Bay, WI 54301",desc:"HUGE book sale! Members-only preview Apr 27. Public sale Apr 28-30 9am-7:30pm (last day til 5:30). Great deals on books, DVDs, puzzles. Auditorium & Meeting Rooms.",url:"https://browncounty.librarycalendar.com/",setting:"indoor",walking:"someWalking",goodFor:["seniors","family"],highlight:true,free:true,recurring:false},
{id:4057,name:"Brown County Library — Intro to AI (FREE! De Pere)",cat:"Activity",sub:"Education / Classes",date:"2026-03-25",dateLabel:"Wed Mar 25, 6:30-7:30pm",venue:"Kress Family Library",loc:"De Pere",addr:"333 N Broadway, De Pere, WI 54115",desc:"FREE Introduction to AI class at the Kress Library in De Pere! Learn about artificial intelligence in an accessible format. No experience needed.",url:"https://browncounty.librarycalendar.com/",setting:"indoor",walking:"lowWalking",goodFor:["seniors"],highlight:true,free:true,recurring:false},
// === FOOD TRUCKS ===
{id:4060,name:"Ashwaubenon Food Truck Rally (4 Nights!)",cat:"Event",sub:"Food",date:"2026-06-01",dateTo:"2026-08-31",dateLabel:"4 nights summer (check village calendar)",venue:"Ashwaubomay Lake",loc:"Ashwaubenon",addr:"Ashwaubomay Lake, Ashwaubenon, WI 54304",desc:"Food truck rally with beer garden and extended beach hours! 4:30-8:30pm. Multiple food trucks, live atmosphere. Check ashwaubenon.gov for exact 2026 dates.",url:"https://ashwaubenon.gov/",setting:"outdoor",walking:"someWalking",goodFor:["family","seniors","couples"],highlight:true,free:true,recurring:false},
{id:4061,name:"Washington Street Block Party + Booyah Battle!",cat:"Event",sub:"Food",date:"2026-04-25",dateLabel:"Sat Apr 25, noon-7pm",venue:"Downtown Green Bay (Washington St)",loc:"Downtown Green Bay",addr:"Washington St, Green Bay, WI 54301",desc:"Downtown block party with the famous Booyah Battle and Kringle Combine! Food competitions, vendors, live music. A uniquely Wisconsin food experience!",url:"",setting:"outdoor",walking:"someWalking",goodFor:["family","seniors","couples"],highlight:true,free:true,recurring:false},
// === HISTORICAL ===
{id:4063,name:"Hotel Northland (Marriott Autograph — Historic Lobby!)",cat:"Attraction",sub:"Historic Building",date:"",dateLabel:"Hotel lobby open to public",venue:"Hotel Northland, Autograph Collection",loc:"Downtown Green Bay",addr:"304 N Adams St, Green Bay, WI 54301",desc:"Stunning 1924 Tudor Revival hotel, fully restored! Walk through the gorgeous lobby, enjoy the bar/restaurant. Hosted Packers, NFL meetings, politicians. National Register of Historic Places.",url:"https://www.marriott.com/en-us/hotels/grbak-hotel-northland-autograph-collection/overview/",setting:"indoor",walking:"lowWalking",goodFor:["seniors","couples"],highlight:true,free:true,recurring:true},
{id:4064,name:"Green Bay Historic Walking Tours (FREE App!)",cat:"Activity",sub:"Walking Tour",date:"",dateLabel:"Anytime (self-guided on your phone)",venue:"Various Downtown Neighborhoods",loc:"Downtown Green Bay",addr:"Downtown Green Bay, WI",desc:"FREE self-guided historic walking tours on your phone! Routes: Astor, Broadway-Dousman, Downtown, Oakland-Dousman, GBFD History. ArcGIS StoryMaps with photos and history.",url:"https://www.greenbaywi.gov/549/Walking-Tours",setting:"outdoor",walking:"someWalking",goodFor:["seniors","couples"],highlight:true,free:true,recurring:true},
// === JUNETEENTH ===
{id:4065,name:"Green Bay Juneteenth Celebration (FREE!)",cat:"Event",sub:"Cultural",date:"2026-06-14",dateLabel:"Mid-June Saturday (confirm date)",venue:"Joannes Park",loc:"Green Bay",addr:"Joannes Park, Green Bay, WI 54302",desc:"Annual Juneteenth celebration by We All Rise African American Resource Center! Vendors, parade, music, food. FREE! Watch weallriseaarc.org for confirmed 2026 date.",url:"https://www.weallriseaarc.org/",setting:"outdoor",walking:"someWalking",goodFor:["family","seniors","couples"],highlight:true,free:true,recurring:false},
// === OSHKOSH DAY TRIPS ===
{id:4067,name:"EAA Aviation Museum (Senior $13! Year-Round)",cat:"Attraction",sub:"Day Trip",date:"",dateLabel:"Daily 10am-5pm (closed holidays)",venue:"EAA Aviation Museum",loc:"Oshkosh (Day Trip)",addr:"3000 Poberezny Rd, Oshkosh, WI 54902",desc:"Amazing aviation museum! Senior (62+) $13, adults $15. EAA members FREE. Pioneer Airport biplane rides May-Oct (seasonal). ~1 hour from GB.",url:"https://www.eaa.org/eaa-museum",setting:"indoor",walking:"someWalking",goodFor:["seniors","family"],highlight:true,free:false,recurring:true},
{id:4068,name:"Paine Art Center & Gardens (FREE Mother's Day!)",cat:"Attraction",sub:"Day Trip",date:"",dateLabel:"Tue-Sun 11am-4pm",venue:"Paine Art Center and Gardens",loc:"Oshkosh (Day Trip)",addr:"1410 Algoma Blvd, Oshkosh, WI 54901",desc:"Stunning estate with art and gardens! Adult $12. FREE on Mother's Day (May 10) and Festival of Spring (May 16). Dancing with Life: Mexican Masks exhibit through May 17. ~1 hour from GB.",url:"https://www.thepaine.org/",setting:"indoor",walking:"someWalking",goodFor:["seniors","couples"],highlight:true,free:false,recurring:true},
{id:4069,name:"Menominee Park Zoo (FREE! Oshkosh)",cat:"Attraction",sub:"Day Trip",date:"",dateLabel:"Year-round (peak: daily 9-6 summer)",venue:"Menominee Park Zoo",loc:"Oshkosh (Day Trip)",addr:"Menominee Park, Oshkosh, WI 54901",desc:"FREE zoo in Oshkosh! Animals, playground, beautiful lakeside park. Open year-round (reduced winter hours). ~1 hour from GB.",url:"https://www.oshkoshzoo.org/",setting:"outdoor",walking:"someWalking",goodFor:["seniors","family"],highlight:true,free:true,recurring:true},
// === ART AT THE PARK ===
{id:4071,name:"Art at the Park — FREE! (Appleton)",cat:"Event",sub:"Art",date:"2026-07-25",dateTo:"2026-07-26",dateLabel:"Sat-Sun Jul 25-26 (9am-5/4pm)",venue:"City Park, Appleton",loc:"Appleton (Day Trip)",addr:"500 E Franklin St, Appleton, WI 54911",desc:"FREE fine art fair in beautiful City Park! Live music (Mile of Music curated), food vendors, family activities. Sat 9-5, Sun 9-4. ~30 min from GB.",url:"https://artattheparkappleton.org/",setting:"outdoor",walking:"someWalking",goodFor:["seniors","couples","family"],highlight:true,free:true,recurring:false},
// === STURGEON BAY ===
{id:4073,name:"Sturgeon Bay Farmers Market (Sat mornings!)",cat:"Event",sub:"Farmers Market",date:"2026-05-31",dateTo:"2026-10-11",dateLabel:"Saturdays 8am-noon, May 31-Oct 11",venue:"Sturgeon Bay Farmers Market",loc:"Sturgeon Bay (Day Trip)",addr:"36 S 3rd Ave, Sturgeon Bay, WI 54235",desc:"Saturday morning farmers market in charming Sturgeon Bay! Fresh produce, baked goods, crafts. Free to browse. ~45 min from GB.",url:"https://www.sturgeonbayfarmersmarket.net/",setting:"outdoor",walking:"someWalking",goodFor:["seniors","couples"],highlight:true,free:true,recurring:false},
{id:4074,name:"Door County Lighthouse Passport Days!",cat:"Event",sub:"Day Trip",date:"2026-05-22",dateTo:"2026-10-04",dateLabel:"May 22-24, Jun 5-7, Aug 7, Oct 2-4",venue:"Various Door County Lighthouses",loc:"Door County (Day Trip)",addr:"Door County, WI",desc:"Tour historic lighthouses normally closed to public! Sherwood Point, Canal Station, and more. Self-guided grounds ($5 donation) + special evening programs. Trolley tours available $84.95.",url:"https://dcmm.org/door-county-lighthouse-passport-days/",setting:"outdoor",walking:"someWalking",goodFor:["seniors","couples"],highlight:true,free:false,recurring:false},
// === FOOD TRUCK COALITION ===
{id:4076,name:"Green Bay Food Truck Coalition (25+ Trucks!)",cat:"Activity",sub:"Food Truck",date:"",dateLabel:"Events all summer (check greenbayfoodtrucks.com)",venue:"Various Locations",loc:"Green Bay Area",addr:"Various, Green Bay, WI",desc:"25+ food trucks! BBQ, Mexican, Caribbean, Jamaican, Hmong egg rolls, Asian fusion, gyros, Cuban, pizza, desserts. Follow @greenbayareafoodtrucks on Instagram for weekly locations.",url:"https://greenbayfoodtrucks.com/",setting:"outdoor",walking:"lowWalking",goodFor:["family","seniors","couples"],highlight:true,free:false,recurring:true},
// === XRoads41 ===
{id:4078,name:"XRoads41 Music Festival (Oshkosh)",cat:"Event",sub:"Day Trip",date:"2026-08-06",dateTo:"2026-08-08",dateLabel:"Thu-Sat Aug 6-8",venue:"Oshkosh",loc:"Oshkosh (Day Trip)",addr:"Oshkosh, WI 54901",desc:"Multi-day music festival in Oshkosh! Plus Hard Drive one-day rock event Aug 9. Ticketed. ~1 hour from GB.",url:"https://www.xroads41.com/",setting:"outdoor",walking:"someWalking",goodFor:["couples"],highlight:false,free:false,recurring:false},
// === CAMPING EXTRAS ===
{id:4080,name:"WI State Parks — Senior Vehicle Pass ($3/day!)",cat:"Activity",sub:"State Park Info",date:"",dateLabel:"Year-round (WI residents 65+)",venue:"All Wisconsin State Parks",loc:"Statewide",addr:"Wisconsin State Parks",desc:"Wisconsin residents 65+ get HUGE discount: $3/day or $13/year vehicle admission (vs $13/$28 regular). Buy at shop.wi.gov or any state park office. Works at ALL WI state parks!",url:"https://dnr.wisconsin.gov/topic/parks/admission",setting:"outdoor",walking:"someWalking",goodFor:["seniors"],highlight:true,free:false,recurring:true},
// === CREATIVE CAKE SUPPLIES ===
{id:4081,name:"Creative Cake Supplies — Decorating Classes!",cat:"Activity",sub:"Art Classes",date:"",dateLabel:"Check class calendar",venue:"Creative Cake Supplies",loc:"West Green Bay",addr:"1544 W Mason St, Green Bay, WI 54303",desc:"Learn cake decorating! Wilton courses ~$60, seasonal cookie/icing workshops. Supplies included + 10% store discount on class day. Fun creative outlet!",url:"https://www.creativecakesupplies.com/",setting:"indoor",walking:"lowWalking",goodFor:["seniors","couples"],highlight:true,free:false,recurring:true},
// === EMPOWERED BY MOVEMENT ===
{id:4082,name:"Dance for Seniors — Music & Movement (FREE!)",cat:"Activity",sub:"Senior Fitness",date:"",dateLabel:"1st, 3rd, 4th Thursdays 10:30-11:15am",venue:"McCormick Assisted Living",loc:"Green Bay",addr:"212 Iroquois Ave, Green Bay, WI 54301",desc:"FREE gentle dance & movement class! Seated/standing options. Dance for Parkinson's-trained instructor. 1st, 3rd, 4th Thursdays. All seniors welcome!",url:"",setting:"indoor",walking:"lowWalking",goodFor:["seniors"],highlight:true,free:true,recurring:true},
// === POLLY'S PUMPKIN PATCH ===
{id:4083,name:"Polly's Pumpkin Patch & Corn Maze (Fall!)",cat:"Activity",sub:"U-Pick Farm",date:"2026-09-01",dateTo:"2026-10-31",dateLabel:"Sept-Oct (check hours)",venue:"Polly's Pumpkin Patch",loc:"Chilton (30 min)",addr:"N4367 Hwy 57, Chilton, WI 53014",desc:"Giant corn maze (day + night versions!), 30+ pumpkin varieties, animals, slides, farm store, apple cider donuts! A fall tradition. ~30 min from GB.",url:"",setting:"outdoor",walking:"someWalking",goodFor:["family","seniors"],highlight:true,free:false,recurring:false},
// === GERIATRIC MASSAGE ===
{id:4084,name:"Green Bay Massage Therapy — Geriatric Massage",cat:"Activity",sub:"Spa & Wellness",date:"",dateLabel:"By appointment",venue:"Green Bay Massage Therapy",loc:"East Green Bay",addr:"2420 Finger Rd, Green Bay, WI 54302",desc:"Specialized geriatric massage for seniors! Gentle pressure, adapted for fragile skin and mobility needs. Experienced therapists. Call 920-753-9332.",url:"https://greenbaymassagetherapy.com/geriatric-massage/",setting:"indoor",walking:"lowWalking",goodFor:["seniors"],highlight:true,free:false,recurring:true},
// === JOYFUL ESCAPE SPA ===
{id:4085,name:"Joyful Escape Wellness Spa (Halotherapy + Foot Care!)",cat:"Activity",sub:"Spa & Wellness",date:"",dateLabel:"Tue/Wed/Fri 9-6, Sat 8:30-3",venue:"Joyful Escape Wellness Spa",loc:"West Green Bay",addr:"425 S Military Ave Ste 202, Green Bay, WI 54303",desc:"Organic/holistic spa! Facials $85/60min, halotherapy $25, Serenity Foot Care from $35 (for those who struggle with foot care). Body treatments $50-145.",url:"https://www.joyfulescapedayspa.com/",setting:"indoor",walking:"lowWalking",goodFor:["seniors","couples"],highlight:true,free:false,recurring:true},
// === HMONG MARKETS ===
{id:4086,name:"Xiong Oriental Market (Southeast Asian Groceries)",cat:"Shop",sub:"Ethnic Market",date:"",dateLabel:"Daily 9am-7pm",venue:"Xiong Oriental Market",loc:"East Green Bay",addr:"610 Bodart St, Green Bay, WI 54302",desc:"Southeast Asian grocery store! Hmong household staples, fresh produce, spices, rice, frozen goods. A taste of Southeast Asia in Green Bay.",url:"",setting:"indoor",walking:"lowWalking",goodFor:["seniors","family"],highlight:false,free:false,recurring:true},
{id:4087,name:"Makelelesho African Food Market",cat:"Shop",sub:"Ethnic Market",date:"",dateLabel:"Mon-Sat ~11am-7pm (confirm hours)",venue:"Makelelesho African Food Market",loc:"Green Bay",addr:"521 E Walnut St, Green Bay, WI 54301",desc:"West African grocery store! Plantains, yams, spices, smoked fish, goat meat. Authentic African ingredients. One of few African markets in NE Wisconsin.",url:"",setting:"indoor",walking:"lowWalking",goodFor:["seniors","family"],highlight:false,free:false,recurring:true},
{id:4088,name:"La Rosa Bakery — Mexican Panaderia!",cat:"Restaurant",sub:"Bakery",date:"",dateLabel:"Daily ~8:30am-8pm",venue:"La Rosa Bakery",loc:"University Ave corridor",addr:"1742 University Ave, Green Bay, WI 54302",desc:"Authentic Mexican bakery! Fresh conchas, pan dulce, cakes, tres leches. The aroma alone is worth the trip. A Green Bay cultural gem.",url:"",setting:"indoor",walking:"lowWalking",goodFor:["seniors","family"],highlight:true,free:false,recurring:true,cuisine:"Mexican Bakery"},
// === SALT ROOM ===
{id:4090,name:"Salt Room Appleton (Halotherapy $40/session)",cat:"Activity",sub:"Spa & Wellness",date:"",dateLabel:"Mon/Tue/Thu 9-6/8, Wed/Fri 9-3, Sat 9-2",venue:"The Salt Room Appleton",loc:"Appleton (30 min)",addr:"1196 N Mayflower Dr, Appleton, WI 54913",desc:"True salt room experience! 45-minute sessions in zero-gravity chairs, $40/adult. 5-pack $175. Breathe Himalayan salt air for respiratory and relaxation benefits. ~30 min from GB.",url:"https://www.saltroomappleton.com/",setting:"indoor",walking:"lowWalking",goodFor:["seniors","couples"],highlight:true,free:false,recurring:true},
// === FLOAT THERAPY ===
{id:4091,name:"Float Light — Sensory Deprivation Float (Appleton)",cat:"Activity",sub:"Spa & Wellness",date:"",dateLabel:"By appointment (7am-11pm)",venue:"Float Light",loc:"Appleton (30 min)",addr:"609 W College Ave, Appleton, WI 54911",desc:"90-minute float in a sensory deprivation tank, ~$99. Total relaxation! Multiple cabins/pods + Salt Loft. HSA/FSA accepted. ~30 min from GB.",url:"https://floatlight.floathelm.com/",setting:"indoor",walking:"lowWalking",goodFor:["seniors","couples"],highlight:true,free:false,recurring:true},
];

let newStr = '';
for (const e of entries) {
  const descEsc = e.desc.replace(/"/g, '\\"');
  const nameEsc = e.name.replace(/"/g, '\\"');
  let s = ',\n{id:' + e.id + ',name:"' + nameEsc + '",cat:"' + e.cat + '",sub:"' + e.sub + '"';
  s += ',price:"' + (e.free ? 'free' : '$$') + '",priceNum:' + (e.free ? 0 : 2);
  s += ',date:"' + (e.date||'') + '"';
  if (e.dateTo) s += ',dateTo:"' + e.dateTo + '"';
  s += ',dateLabel:"' + (e.dateLabel || '') + '"';
  s += ',venue:"' + e.venue + '"';
  s += ',desc:"' + descEsc + '"';
  s += ',url:"' + (e.url || '') + '"';
  s += ',setting:"' + e.setting + '",walking:"' + e.walking + '"';
  s += ',goodFor:' + JSON.stringify(e.goodFor);
  s += ',highlight:' + e.highlight;
  s += ',cuisine:"' + (e.cuisine || '') + '",established:""';
  s += ',free:' + e.free + ',recurring:' + (e.recurring || false) + '}';
  newStr += s;
}

const lastEntry = 'free:false,recurring:true}';
const idx = html.lastIndexOf(lastEntry);
if (idx === -1) { console.log('ERROR: insertion point not found'); process.exit(1); }
html = html.substring(0, idx + lastEntry.length) + newStr + html.substring(idx + lastEntry.length);

fs.writeFileSync(path, html, 'utf8');
console.log('Added ' + entries.length + ' entries (IDs ' + Math.min(...entries.map(e=>e.id)) + '-' + Math.max(...entries.map(e=>e.id)) + ')');
console.log('File size: ' + Buffer.byteLength(html, 'utf8'));
