const fs = require('fs');
const path = 'C:/Users/shawn/Downloads/Green Bay Explorer.html';
let html = fs.readFileSync(path, 'utf8');

const entries = [
// === EPIC EVENT CENTER ===
{id:3800,name:"One Night of Queen — EPIC Event Center",cat:"Event",sub:"Concert",date:"2026-04-03",dateLabel:"Fri Apr 3, 7:30pm",venue:"EPIC Event Center",loc:"Ashwaubenon",addr:"2350 Airport Dr, Green Bay, WI 54313",desc:"Gary Mullen & The Works deliver a mind-blowing Queen tribute! We Will Rock You, Bohemian Rhapsody, Somebody to Love. $42-$94.",url:"https://epicgreenbay.com/",setting:"indoor",walking:"lowWalking",goodFor:["seniors","couples"],highlight:true,free:false,recurring:false},
{id:3801,name:"Edwin McCain & Five For Fighting at EPIC",cat:"Event",sub:"Concert",date:"2026-06-19",dateLabel:"Fri Jun 19, 7:30pm",venue:"EPIC Event Center",loc:"Ashwaubenon",addr:"2350 Airport Dr, Green Bay, WI 54313",desc:"Two acoustic legends! I'll Be (Edwin McCain) and Superman (Five For Fighting). A mellow, singalong evening. $32-$63.",url:"https://epicgreenbay.com/",setting:"indoor",walking:"lowWalking",goodFor:["seniors","couples"],highlight:true,free:false,recurring:false},
{id:3802,name:"Uncle Kracker at EPIC",cat:"Event",sub:"Concert",date:"2026-07-09",dateLabel:"Thu Jul 9, 7:30pm",venue:"EPIC Event Center",loc:"Ashwaubenon",addr:"2350 Airport Dr, Green Bay, WI 54313",desc:"Follow Me, Drift Away, Smile! Uncle Kracker's feel-good summer concert with The Wannabes. $37-$99.",url:"https://epicgreenbay.com/",setting:"indoor",walking:"lowWalking",goodFor:["couples"],highlight:false,free:false,recurring:false},
{id:3803,name:"Pop 2000 Tour at EPIC (NSYNC, O-Town, LFO!)",cat:"Event",sub:"Concert",date:"2026-08-28",dateLabel:"Fri Aug 28, 7:15pm",venue:"EPIC Event Center",loc:"Ashwaubenon",addr:"2350 Airport Dr, Green Bay, WI 54313",desc:"NSYNC's Chris Kirkpatrick, O-Town, Ryan Cabrera, and LFO! All your 2000s hits live. $42-$104.",url:"https://epicgreenbay.com/",setting:"indoor",walking:"lowWalking",goodFor:["couples"],highlight:false,free:false,recurring:false},
// === RESCH CONCERTS ===
{id:3805,name:"Bailey Zimmerman at the Resch Center",cat:"Event",sub:"Concert",date:"2026-04-17",dateLabel:"Fri Apr 17, 7pm",venue:"Resch Center",loc:"Ashwaubenon",addr:"820 Armed Forces Dr, Green Bay, WI 54304",desc:"Country star Bailey Zimmerman's Different Night Same Rodeo Tour! With Hudson Westbrook and Blake Whiten. From $35. Doors 6pm.",url:"https://www.reschcomplex.com/",setting:"indoor",walking:"lowWalking",goodFor:["couples"],highlight:false,free:false,recurring:false},
{id:3806,name:"Riley Green at the Resch Center",cat:"Event",sub:"Concert",date:"2026-07-16",dateLabel:"Thu Jul 16, 7pm",venue:"Resch Center",loc:"Ashwaubenon",addr:"820 Armed Forces Dr, Green Bay, WI 54304",desc:"Cowboy As It Gets Tour! Riley Green with Justin Moore, Drake White, and Hannah McFarland. Country summer night! From $51.50.",url:"https://www.reschcomplex.com/",setting:"indoor",walking:"lowWalking",goodFor:["couples"],highlight:true,free:false,recurring:false},
// === DOOR COUNTY DEEP DIVE ===
{id:3810,name:"Door County Triathlon",cat:"Event",sub:"Day Trip",date:"2026-07-11",dateTo:"2026-07-12",dateLabel:"Sat Jul 11 (Sprint/Kids), Sun Jul 12 (Olympic)",venue:"Murphy Park, Egg Harbor",loc:"Door County (Day Trip)",addr:"Murphy Park, Egg Harbor, WI 54209",desc:"Beautiful triathlon through Door County! Sprint, Olympic, and kids divisions. Swim, bike, run through some of Wisconsin's most scenic landscapes.",url:"https://www.doorcountytriathlon.com/",setting:"outdoor",walking:"longWalking",goodFor:["couples"],highlight:false,free:false,recurring:false},
{id:3811,name:"Door County Half Marathon & Nicolet Bay 5K",cat:"Event",sub:"Day Trip",date:"2026-05-02",dateLabel:"Sat May 2, 10am",venue:"Peninsula State Park, Fish Creek",loc:"Door County (Day Trip)",addr:"Peninsula State Park, Fish Creek, WI 54212",desc:"Run through Peninsula State Park! Closed-road course, post-race party with music. Half $110, 5K $48. One of the most scenic races in the Midwest.",url:"https://doorcountyhalfmarathon.com/",setting:"outdoor",walking:"longWalking",goodFor:["couples"],highlight:false,free:false,recurring:false},
{id:3812,name:"Door County Classic & Wooden Boat Show",cat:"Event",sub:"Day Trip",date:"2026-08-01",dateTo:"2026-08-02",dateLabel:"Sat-Sun Aug 1-2, 10am-4pm",venue:"Door County Maritime Museum, Sturgeon Bay",loc:"Door County (Day Trip)",addr:"120 N Madison Ave, Sturgeon Bay, WI 54235",desc:"35th annual! Beautiful classic and wooden boats on display and in the water. Build-A-Boat challenge, boat parade Sat 5:15pm. Craft and history at the maritime museum.",url:"https://dcmm.org/",setting:"outdoor",walking:"someWalking",goodFor:["seniors","couples"],highlight:true,free:false,recurring:false},
{id:3813,name:"Sister Bay Concerts in the Park (FREE, Door County)",cat:"Event",sub:"Day Trip",date:"2026-06-17",dateTo:"2026-08-12",dateLabel:"Wednesdays 6pm, Jun 17 - Aug 12",venue:"Sister Bay Performance Pavilion",loc:"Door County (Day Trip)",addr:"Sister Bay, WI 54234",desc:"FREE Wednesday evening concerts at the waterfront in Sister Bay! Bring a chair, catch the sunset. 9 weeks of live music in one of Door County's most charming villages.",url:"https://www.sisterbay.com/",setting:"outdoor",walking:"lowWalking",goodFor:["seniors","couples"],highlight:true,free:true,recurring:true},
{id:3814,name:"Sturgeon Bay Fine Art Fair",cat:"Event",sub:"Day Trip",date:"2026-05-23",dateTo:"2026-05-24",dateLabel:"Sat 10-4, Sun 10-3",venue:"Martin Park, Sturgeon Bay",loc:"Door County (Day Trip)",addr:"Martin Park, Sturgeon Bay, WI 54235",desc:"80+ artists, live entertainment, kids activities, food. The 28th annual juried fine art fair in the Gateway to Door County.",url:"https://sturgeonbay.net/",setting:"outdoor",walking:"someWalking",goodFor:["seniors","couples"],highlight:true,free:true,recurring:false},
{id:3815,name:"Steel Bridge Day (Sturgeon Bay)",cat:"Event",sub:"Day Trip",date:"2026-06-13",dateLabel:"Sat Jun 13, noon-8pm",venue:"Martin Park + The MUSE, Sturgeon Bay",loc:"Door County (Day Trip)",addr:"Martin Park, Sturgeon Bay, WI 54235",desc:"Music, art, and culture festival! Flagship public day of the Steel Bridge Creative Foundation. Live music across multiple venues from noon to 8pm.",url:"https://steelbridgesongfest.org/",setting:"outdoor",walking:"someWalking",goodFor:["couples"],highlight:false,free:false,recurring:false},
// === ELECTRIC CITY RIVER JAM ===
{id:3820,name:"Electric City River Jam (Kaukauna)",cat:"Event",sub:"Festival",date:"2026-06-17",dateTo:"2026-06-20",dateLabel:"Wed-Sat Jun 17-20",venue:"Hydro Park, Kaukauna",loc:"Kaukauna (Day Trip)",addr:"100 Crooks Ave, Kaukauna, WI 54130",desc:"Music festival with carnival! Four days of live entertainment at Hydro Park. Carnival rides, food, concerts. ~25 min from Green Bay.",url:"https://www.kaukauna.gov/",setting:"outdoor",walking:"someWalking",goodFor:["family","couples"],highlight:false,free:false,recurring:false},
{id:3821,name:"Kaukauna Live! from Hydro Park Summer Concerts (FREE)",cat:"Event",sub:"Free Concert Series",date:"2026-06-03",dateTo:"2026-08-05",dateLabel:"Wednesdays 5:30-8:30pm, Jun 3 - Aug 5",venue:"Hydro Park, Kaukauna",loc:"Kaukauna (Day Trip)",addr:"100 Crooks Ave, Kaukauna, WI 54130",desc:"FREE Wednesday evening concert series all summer! 10 concerts at beautiful Hydro Park along the Fox River locks. Kaukauna's Downtown Farmers Market same night 4:30-8pm!",url:"https://www.kaukauna.gov/",setting:"outdoor",walking:"lowWalking",goodFor:["seniors","couples"],highlight:true,free:true,recurring:true},
// === PAPERFEST ===
{id:3822,name:"Paperfest — Free Fox Valley Festival (Kimberly)",cat:"Event",sub:"Festival",date:"2026-07-16",dateTo:"2026-07-19",dateLabel:"Thu-Sun Jul 16-19",venue:"Sunset Park, Kimberly",loc:"Kimberly (Day Trip)",addr:"800 W Kimberly Ave, Kimberly, WI 54136",desc:"Large FREE admission community festival! 4 days of music, food, sports, family activities. Thu 5-11pm, Fri noon-midnight, Sat 10am-midnight, Sun 11am-7pm. ~30 min from GB.",url:"https://www.paperfest.com/",setting:"outdoor",walking:"someWalking",goodFor:["family","seniors","couples"],highlight:true,free:true,recurring:false},
// === LIBRARY HIGHLIGHTS ===
{id:3825,name:"Brown County Library — Big Book Sale",cat:"Event",sub:"Shopping",date:"2026-04-28",dateTo:"2026-04-30",dateLabel:"Tue-Thu Apr 28-30, 9am-7:30pm (Thu 9-5:30)",venue:"Central Library",loc:"Downtown Green Bay",addr:"515 Pine St, Green Bay, WI 54301",desc:"Huge used book sale! Friends of the Library annual event. Great deals on thousands of books. Three days at Central Library.",url:"https://browncountylibrary.org/",setting:"indoor",walking:"someWalking",goodFor:["seniors"],highlight:false,free:true,recurring:false},
{id:3826,name:"Library Renaissance Faire (6th Annual!)",cat:"Event",sub:"Family",date:"2026-05-09",dateLabel:"Sat May 9, 11am-3pm",venue:"Weyers-Hilliard Branch (Howard)",loc:"Howard",addr:"Weyers-Hilliard Branch, Howard, WI",desc:"FREE Renaissance Faire at the library! Live performances, music, crafts, history exhibits. A fun and free family outing.",url:"https://browncountylibrary.org/",setting:"indoor",walking:"lowWalking",goodFor:["family","seniors"],highlight:true,free:true,recurring:false},
{id:3827,name:"Library: ABCDs of Medicare (Free!)",cat:"Event",sub:"Senior Social",date:"2026-04-16",dateLabel:"Thu Apr 16, 2-3:30pm (multiple dates)",venue:"Various library branches",loc:"Various",addr:"515 Pine St, Green Bay, WI 54301",desc:"FREE unbiased Medicare overview from the ADRC. Multiple dates at different branches: Apr 16 (Howard), May 12 (Ashwaubenon), Jul 15 (Pulaski). No sales pitch, just the facts you need.",url:"https://browncountylibrary.org/",setting:"indoor",walking:"lowWalking",goodFor:["seniors"],highlight:true,free:true,recurring:true},
{id:3828,name:"Library Lunch & Learn Series (Free!)",cat:"Event",sub:"Senior Social",date:"2026-04-20",dateTo:"2026-08-17",dateLabel:"Monthly, various branches (see schedule)",venue:"Various library branches",loc:"Various",addr:"515 Pine St, Green Bay, WI 54301",desc:"FREE lunch-hour programs: Brown County courthouse history Apr 20, Building Blocks of Advocacy May 18, Stay Active Jun 9, Financial Health Jul 14, Stay Safe Online Jul 20, Volunteering After 55 Aug 17. Perfect for seniors!",url:"https://browncountylibrary.org/",setting:"indoor",walking:"lowWalking",goodFor:["seniors"],highlight:true,free:true,recurring:true},
// === BAY BEACH WILDLIFE SANCTUARY ===
{id:3830,name:"Bay Beach Wildlife Sanctuary — Free Wolf Feeding!",cat:"Attraction",sub:"Nature",date:"",dateLabel:"Mon/Tue/Fri 1:30pm year-round (see schedule)",venue:"Bay Beach Wildlife Sanctuary",loc:"East Green Bay",addr:"1660 E Shore Dr, Green Bay, WI 54302",desc:"FREE! Watch wolves eat at 1:30pm multiple days per week. Plus nature trails, birds of prey, free story time Mondays, Awesome Ambassadors Sundays. All FREE admission. Next door to Bay Beach Amusement Park.",url:"https://www.baybeachwildlife.com/",setting:"outdoor",walking:"someWalking",goodFor:["seniors","family"],highlight:true,free:true,recurring:true},
// === WASHINGTON ST BLOCK PARTY ===
{id:3835,name:"Washington St Block Party & Booyah Battle",cat:"Event",sub:"Festival",date:"2026-04-25",dateLabel:"Sat Apr 25, noon-7pm",venue:"100 block S Washington St",loc:"Downtown Green Bay",addr:"100 S Washington St, Green Bay, WI 54301",desc:"Street festival with Booyah Battle ($20 tasting card, noon-3pm), Kringle Combine ($5 suggested donation), Bike Bash, live bands. A uniquely Green Bay spring celebration!",url:"https://downtowngreenbay.com/block-party",setting:"outdoor",walking:"someWalking",goodFor:["seniors","family","couples"],highlight:true,free:true,recurring:false},
// === NEVILLE MUSEUM ===
{id:3837,name:"Neville Public Museum (Free First Wednesdays!)",cat:"Attraction",sub:"Museum",date:"",dateLabel:"Tue-Sat 9-5, Sun noon-5 (1st Wed free for BC residents)",venue:"Neville Public Museum",loc:"Downtown Green Bay",addr:"210 Museum Pl, Green Bay, WI 54303",desc:"Brown County's museum of art, history, and science! Senior (62+) $10. FREE first Wednesday for Brown County residents. Outdoor sculptures on the Fox River. Elevator, wheelchair accessible, benches throughout.",url:"https://nevillepublicmuseum.org/",setting:"indoor",walking:"someWalking",goodFor:["seniors","family","couples"],highlight:true,free:false,recurring:true},
// === SENIOR RESTAURANT DEALS ===
{id:3840,name:"Perkins — Senior 55+ Menu (2 locations!)",cat:"Restaurant",sub:"American",date:"",dateLabel:"Daily, all day",venue:"Perkins Restaurant",loc:"Multiple Locations",addr:"2306 E Mason St OR 100 N Military Ave, Green Bay",desc:"55+ menu with smaller portions at great prices! Breakfast: one-egg classic, French toast, pancakes (~$6.90-$7.80). Dinner: pot roast, salmon, meatloaf (~$7.50-$12.50). Kids eat free Tuesdays 4-10pm with adult entree! Perfect for grandparent outings.",url:"https://www.perkinsrestaurants.com/",setting:"indoor",walking:"lowWalking",goodFor:["seniors","family"],highlight:true,free:false,recurring:true,cuisine:"American"},
{id:3841,name:"Denny's — Senior 55+ Menu",cat:"Restaurant",sub:"American",date:"",dateLabel:"Daily, all day",venue:"Denny's",loc:"West Green Bay",addr:"2894 S Oneida St, Green Bay, WI 54304",desc:"55+ menu! Starter (1 egg + bacon/sausage, hash browns ~$3.99), 55+ Omelette, 55+ Wild Alaska Salmon, 55+ Grilled Cheese & Soup. Kids eat free with adult entree 4-9pm. Great value for seniors!",url:"https://www.dennys.com/menu/55",setting:"indoor",walking:"lowWalking",goodFor:["seniors","family"],highlight:true,free:false,recurring:true,cuisine:"American"},
{id:3842,name:"Plae Bistro — Chef's Table Experience",cat:"Restaurant",sub:"Fine Dining",date:"",dateLabel:"By reservation",venue:"Plae Bistro",loc:"West Green Bay",addr:"1671 Hoffman Rd Suite 10, Green Bay, WI 54311",desc:"Intimate Chef's Table for up to 12 guests! 4-course lunch $80/person, 6-course dinner $100/person. Reservation-only, paced and seated. A special occasion treat.",url:"https://plaebistro.com/",setting:"indoor",walking:"lowWalking",goodFor:["seniors","couples"],highlight:true,free:false,recurring:true,cuisine:"Fine Dining"},
// === MEYER THEATRE — more shows ===
{id:3845,name:"Meyer Theatre — Jake Owen (Country)",cat:"Event",sub:"Concert",date:"2026-03-26",dateLabel:"Thu Mar 26, 7:30pm",venue:"Meyer Theatre",loc:"Downtown Green Bay",addr:"117 S Washington St, Green Bay, WI 54301",desc:"Country star Jake Owen's Dream to Dreams Tour with Kendall Marvel! Barefoot Blue Jean Night, Alone with You. $60.50-$101.50.",url:"https://meyertheatre.org/",setting:"indoor",walking:"lowWalking",goodFor:["couples"],highlight:false,free:false,recurring:false},
{id:3846,name:"Meyer Theatre — Eaglemania (Eagles Tribute)",cat:"Event",sub:"Concert",date:"2026-04-04",dateLabel:"Sat Apr 4, 7:30pm",venue:"Meyer Theatre",loc:"Downtown Green Bay",addr:"117 S Washington St, Green Bay, WI 54301",desc:"Hotel California, Take It Easy, Life in the Fast Lane! The premier Eagles tribute band. $54-$65.",url:"https://meyertheatre.org/",setting:"indoor",walking:"lowWalking",goodFor:["seniors","couples"],highlight:true,free:false,recurring:false},
{id:3847,name:"Meyer Theatre — Toast (Tribute to Bread)",cat:"Event",sub:"Concert",date:"2026-05-11",dateLabel:"Mon May 11, 7pm",venue:"Meyer Theatre",loc:"Downtown Green Bay",addr:"117 S Washington St, Green Bay, WI 54301",desc:"Make It with You, Everything I Own, Baby I'm a Want You. Tribute to the soft-rock legends. $38-$68.",url:"https://meyertheatre.org/",setting:"indoor",walking:"lowWalking",goodFor:["seniors","couples"],highlight:true,free:false,recurring:false},
{id:3848,name:"Meyer — Sputnik Manitowoc (Dinner Theater!)",cat:"Event",sub:"Dinner Theater",date:"2026-05-14",dateTo:"2026-05-16",dateLabel:"Thu-Sat May 14-16 (1pm & 7pm shows)",venue:"Backstage at the Meyer",loc:"Downtown Green Bay",addr:"117 S Washington St, Green Bay, WI 54301",desc:"Cold War comedy musical with dinner! $70 with dinner buffet, $41.25 show only. 1960s music. Dinner cutoff Mon May 11. Let Me Be Frank's popular dinner theater format.",url:"https://letmebefranks.com/",setting:"indoor",walking:"lowWalking",goodFor:["seniors","couples"],highlight:true,free:false,recurring:false},
{id:3849,name:"Meyer — Liverpool Legends (Beatles Experience)",cat:"Event",sub:"Concert",date:"2026-05-29",dateLabel:"Fri May 29, 7:30pm",venue:"Meyer Theatre",loc:"Downtown Green Bay",addr:"117 S Washington St, Green Bay, WI 54301",desc:"The only Beatles tribute recommended by Louise Harrison (George's sister)! Costumes, instruments, harmonies. $62.75-$87.",url:"https://meyertheatre.org/",setting:"indoor",walking:"lowWalking",goodFor:["seniors","couples"],highlight:true,free:false,recurring:false},
// === LODGE KOHLER ===
{id:3852,name:"Lodge Kohler — Door County Wine Tour",cat:"Event",sub:"Tour",date:"2026-03-21",dateLabel:"Multiple Saturdays (Mar 21, Apr 18, May 2, May 9)",venue:"Lodge Kohler",loc:"Ashwaubenon",addr:"725 Eisenhower Dr, Green Bay, WI 54304",desc:"Full-day guided wine tour of Door County departing from Lodge Kohler! 10am-6:30pm. Book via concierge (920-327-4614). A luxurious way to explore Door County wineries.",url:"https://www.lodgekohler.com/",setting:"outdoor",walking:"lowWalking",goodFor:["seniors","couples"],highlight:true,free:false,recurring:true},
// === ASHWAUBENON CONCERTS ===
{id:3855,name:"Ashwaubenon Concert in the Parks (Wed Lunchtimes)",cat:"Event",sub:"Free Concert Series",date:"2026-06-11",dateTo:"2026-07-30",dateLabel:"Wednesdays 11:30am-2pm, Jun 11 - Jul 30",venue:"Ashwaubenon Parks",loc:"Ashwaubenon",addr:"Ashwaubenon, WI 54304",desc:"FREE Wednesday lunchtime concerts! Live music, concessions available. 8 weeks of summer music. Rain location: Ashwaubenon Community Center.",url:"https://ashwaubenon.gov/",setting:"outdoor",walking:"lowWalking",goodFor:["seniors"],highlight:true,free:true,recurring:true},
// === BELLEVUE FOOD TRUCK RALLY ===
{id:3856,name:"Bellevue Food Truck Rally",cat:"Event",sub:"Festival",date:"2026-05-31",dateLabel:"Sun May 31, 4-8pm",venue:"Josten Park, Bellevue",loc:"Bellevue",addr:"Josten Park, Bellevue, WI 54311",desc:"Food trucks, live local music, family activities, beverages! A fun Sunday evening kickoff to summer at Josten Park.",url:"https://www.villageofbellevuewi.gov/",setting:"outdoor",walking:"lowWalking",goodFor:["family","seniors","couples"],highlight:false,free:true,recurring:false},
// === WALKING TOURS ===
{id:3858,name:"Green Bay StoryMap Walking Tours (Self-Guided, FREE)",cat:"Activity",sub:"Walking Tour",date:"",dateLabel:"Anytime (self-paced from phone/tablet)",venue:"Downtown Green Bay (various districts)",loc:"Downtown Green Bay",addr:"Downtown Green Bay",desc:"FREE self-guided digital tours! Choose from: Downtown Historic District, Broadway-Dousman, Broadway-Walnut, Astor Historic District, Oakland-Dousman. Read on your phone and drive between key stops for low-walking!",url:"https://www.greenbaywi.gov/549/Walking-Tours",setting:"outdoor",walking:"someWalking",goodFor:["seniors","couples"],highlight:true,free:true,recurring:true},
// === NOTRE DAME AT LAMBEAU ===
{id:3860,name:"Notre Dame vs. Wisconsin — at LAMBEAU FIELD!",cat:"Event",sub:"Sports",date:"2026-09-05",dateLabel:"Sat Sep 5 (time TBA)",venue:"Lambeau Field",loc:"Ashwaubenon",addr:"1265 Lombardi Ave, Green Bay, WI 54304",desc:"College football at Lambeau! Notre Dame Fighting Irish vs Wisconsin Badgers at Lambeau Field. A rare chance to see college football in the most iconic stadium in America.",url:"https://www.packers.com/",setting:"outdoor",walking:"someWalking",goodFor:["seniors","family","couples"],highlight:true,free:false,recurring:false},
];

let newStr = '';
for (const e of entries) {
  const descEsc = e.desc.replace(/"/g, '\\"');
  const nameEsc = e.name.replace(/"/g, '\\"');
  let s = ',\n{id:' + e.id + ',name:"' + nameEsc + '",cat:"' + e.cat + '",sub:"' + e.sub + '"';
  s += ',price:"' + (e.free ? 'free' : '$$') + '",priceNum:' + (e.free ? 0 : 2);
  s += ',date:"' + (e.date||'') + '"';
  if (e.dateTo) s += ',dateTo:"' + e.dateTo + '"';
  s += ',dateLabel:"' + e.dateLabel + '"';
  s += ',venue:"' + e.venue + '"';
  s += ',desc:"' + descEsc + '"';
  s += ',url:"' + (e.url || '') + '"';
  s += ',setting:"' + e.setting + '",walking:"' + e.walking + '"';
  s += ',goodFor:' + JSON.stringify(e.goodFor);
  s += ',highlight:' + e.highlight;
  s += ',cuisine:"' + (e.cuisine || '') + '",established:""';
  s += ',free:' + e.free + ',recurring:' + (e.recurring || false) + '}';
  newStr += s;
}

const lastEntry = 'free:false,recurring:false}';
const idx = html.lastIndexOf(lastEntry);
if (idx === -1) { console.log('ERROR: insertion point not found'); process.exit(1); }
html = html.substring(0, idx + lastEntry.length) + newStr + html.substring(idx + lastEntry.length);

fs.writeFileSync(path, html, 'utf8');
console.log('Added ' + entries.length + ' entries (IDs ' + Math.min(...entries.map(e=>e.id)) + '-' + Math.max(...entries.map(e=>e.id)) + ')');
console.log('File size: ' + Buffer.byteLength(html, 'utf8'));
