const fs = require('fs');
const path = 'C:/Users/shawn/Downloads/Green Bay Explorer.html';
let html = fs.readFileSync(path, 'utf8');

const entries = [
// === FOOD TRUCKS ===
{id:4400,name:"Titletown Night Market — Food Trucks + Music!",cat:"Event",sub:"Food",date:"2026-06-11",dateTo:"2026-08-27",dateLabel:"Thursdays Jun 11-Aug 27, 4:30-8:30pm",venue:"Titletown (Hy-Vee Plaza)",loc:"Ashwaubenon",addr:"Titletown, Green Bay, WI 54304",desc:"Weekly food trucks, local food vendors, restaurant specials + LIVE MUSIC every Thursday all summer! Shotgun Jane, Michigan Shivers + more bands. At Titletown near Lambeau.",url:"https://www.titletown.com/events/titletown-night-market",setting:"outdoor",walking:"lowWalking",goodFor:["seniors","family","couples"],highlight:true,free:true,recurring:false},
{id:4401,name:"Food Truck Fridays Downtown (Free Lunch!)",cat:"Event",sub:"Food",date:"2026-07-10",dateTo:"2026-08-28",dateLabel:"Fridays Jul-Aug, 11:30am-1:30pm",venue:"Brown County Library Lot (515 Pine St)",loc:"Downtown Green Bay",addr:"515 Pine St, Green Bay, WI 54301",desc:"Lunchtime food truck rally right downtown! Multiple trucks every Friday all summer. Perfect midday outing. Check Downtown Green Bay Facebook for weekly lineup.",url:"https://downtowngreenbay.com/",setting:"outdoor",walking:"lowWalking",goodFor:["seniors","couples"],highlight:true,free:false,recurring:false},
{id:4402,name:"Pamperin Park Food Truck Nights (Mondays!)",cat:"Event",sub:"Food",date:"2026-06-01",dateTo:"2026-08-31",dateLabel:"Mondays 5-8:30pm (summer)",venue:"Pamperin Park",loc:"Howard",addr:"2477 Shawano Ave, Green Bay, WI 54303",desc:"Monday evening food truck rally at Pamperin Park! 5-8:30pm. Multiple trucks each week — BBQ, tacos, ice cream, egg rolls + more. Follow @greenbayareafoodtrucks on Instagram for lineup.",url:"https://greenbayfoodtrucks.com/",setting:"outdoor",walking:"lowWalking",goodFor:["seniors","family"],highlight:true,free:false,recurring:false},
{id:4403,name:"Steel Belly BBQ (Texas Oak-Smoked Food Truck!)",cat:"Restaurant",sub:"Food Truck",date:"",dateLabel:"Check steelbellybbq.com for schedule",venue:"Steel Belly BBQ (2 trucks)",loc:"Green Bay area (mobile)",addr:"Green Bay area (mobile)",desc:"Texas-style oak-smoked BBQ from TWO mobile trucks! Brisket, pulled pork, ribs, mac & cheese. Find them at rallies, breweries, and events across NE Wisconsin.",url:"https://steelbellybbq.com/",setting:"outdoor",walking:"lowWalking",goodFor:["seniors","family"],highlight:true,free:false,recurring:true,cuisine:"BBQ"},
{id:4404,name:"Captain Quesadilla (Food Truck!)",cat:"Restaurant",sub:"Food Truck",date:"",dateLabel:"Events & rallies (see Facebook)",venue:"Captain Quesadilla",loc:"Green Bay area (mobile)",addr:"Green Bay area (mobile)",desc:"Gourmet quesadillas from a food truck! Find Captain Quesadilla at Pamperin Park nights, Titletown market, farmers markets, and brewery events.",url:"",setting:"outdoor",walking:"lowWalking",goodFor:["seniors","family"],highlight:false,free:false,recurring:true,cuisine:"Mexican"},
{id:4405,name:"Big MO's Soul Food (Food Truck!)",cat:"Restaurant",sub:"Food Truck",date:"",dateLabel:"Events & rallies (see Facebook)",venue:"Big MO's Soul Food",loc:"Green Bay area (mobile)",addr:"Green Bay area (mobile)",desc:"Soul food from a food truck! Rib tips, turkey legs, smothered chops, sides, cobblers. Find at Green Bay area rallies and events.",url:"https://www.bigmossoulfoodchef.org/",setting:"outdoor",walking:"lowWalking",goodFor:["seniors","family"],highlight:false,free:false,recurring:true,cuisine:"Soul Food"},
// === CHURCHES / WORSHIP ===
{id:4410,name:"Cathedral of St. Francis Xavier (Mother Church!)",cat:"Activity",sub:"Church / Worship",date:"",dateLabel:"Sat 4pm, Sun 9am, Wed/Fri 8:30am",venue:"Cathedral of St. Francis Xavier",loc:"Downtown Green Bay",addr:"139 S Madison St, Green Bay, WI 54301",desc:"Mother church of the Diocese of Green Bay! Beautiful historic cathedral. Wed adoration, Sat confession, Sun 9am on Relevant Radio. Tours 2nd Sunday after Mass.",url:"",setting:"indoor",walking:"lowWalking",goodFor:["seniors"],highlight:true,free:true,recurring:true},
{id:4411,name:"Celebration Church (Large Nondenominational!)",cat:"Activity",sub:"Church / Worship",date:"",dateLabel:"Sundays 9:00 & 10:30am (live + online)",venue:"Celebration Church",loc:"East Green Bay",addr:"3475 Humboldt Rd, Green Bay, WI 54311",desc:"Large nondenominational church with contemporary worship. Two Sunday services, live stream available. Accessible campus with parking. (920) 468-1122.",url:"https://celebrationchurch.tv/",setting:"indoor",walking:"lowWalking",goodFor:["seniors"],highlight:false,free:true,recurring:true},
{id:4412,name:"Green Bay Community Church (Breakfast Between Services!)",cat:"Activity",sub:"Church / Worship",date:"",dateLabel:"Sundays 8:00 & 10:00am (9am breakfast!)",venue:"Green Bay Community Church",loc:"Howard",addr:"600 Cardinal Ln, Green Bay, WI 54313",desc:"Sundays 8 & 10am with FREE BREAKFAST at 9am between services! Accessible parking, Alpha newcomer course, live 10am stream. Welcoming community.",url:"https://gbcc.me/",setting:"indoor",walking:"lowWalking",goodFor:["seniors"],highlight:false,free:true,recurring:true},
{id:4413,name:"Bay City Baptist — Young at Heart (65+) Group!",cat:"Activity",sub:"Church / Worship",date:"",dateLabel:"Sun 9am Bible study, 10am worship, 6pm evening",venue:"Bay City Baptist Church",loc:"West Green Bay",addr:"1840 Bond St, Green Bay, WI 54304",desc:"Dedicated 'Young at Heart' group for ages 65+! Plus adult Bible fellowship, Deaf church at 9am. Sun evening 6pm, Wed prayer 6:30pm. (920) 499-5561.",url:"https://baycity.org/",setting:"indoor",walking:"lowWalking",goodFor:["seniors"],highlight:true,free:true,recurring:true},
{id:4414,name:"Congregation Cnesses Israel (Jewish Community!)",cat:"Activity",sub:"Church / Worship",date:"",dateLabel:"Erev Shabbat + Shabbat morning + High Holidays",venue:"Congregation Cnesses Israel",loc:"Downtown Green Bay",addr:"222 S Baird St, Green Bay, WI 54301",desc:"Green Bay's Conservative synagogue with a warm, welcoming congregation. Community classes, dinners, groups. Long history in Green Bay. (920) 437-4841.",url:"http://www.cnesses.org/",setting:"indoor",walking:"lowWalking",goodFor:["seniors"],highlight:false,free:true,recurring:true},
{id:4415,name:"Green Bay Zen Center (Meditation, All Welcome!)",cat:"Activity",sub:"Church / Worship",date:"",dateLabel:"Sun 8am & Thu 6pm zazen (alternating weeks, FREE)",venue:"Green Bay Zen Center",loc:"Downtown Green Bay",addr:"123 N Oakland Ave, 2nd Floor, Green Bay, WI 54303",desc:"Zazen meditation + dharma talks. Welcomes non-Buddhists! Free, no charge. Alternating weeks: even Sundays 8am, odd Thursdays 6pm. (920) 770-4088.",url:"https://greenbayzencenter.org/",setting:"indoor",walking:"lowWalking",goodFor:["seniors"],highlight:false,free:true,recurring:true},
// === BREAKFAST / BRUNCH SPOTS ===
{id:4420,name:"Village Grille — Sunday Breakfast Buffet 8am-1pm!",cat:"Restaurant",sub:"Breakfast",date:"",dateLabel:"Mon-Sat 6am-9pm, Sun 6am-2pm (buffet 8-1)",venue:"Village Grille",loc:"Green Bay",addr:"801 Hoffman Rd, Green Bay, WI 54301",desc:"Sunday breakfast buffet 8am-1pm PLUS full menu all week starting at 6am! Long-running Green Bay favorite. Also serves lunch and dinner Mon-Sat.",url:"https://villagegrillegreenbay.com/",setting:"indoor",walking:"lowWalking",goodFor:["seniors","family"],highlight:true,free:false,recurring:true,cuisine:"Breakfast"},
{id:4421,name:"River's Bend — Sunday Brunch Buffet!",cat:"Restaurant",sub:"Breakfast",date:"",dateLabel:"Sundays 10am-2pm (buffet stations)",venue:"River's Bend",loc:"Green Bay",addr:"792 Riverview Dr, Green Bay, WI",desc:"Brunch at The Bend! Omelette station, carving station, salads, desserts, Bloody Marys, mimosas. Reservations recommended. Great river views!",url:"https://riversbendgb.com/",setting:"indoor",walking:"lowWalking",goodFor:["seniors","couples"],highlight:true,free:false,recurring:true,cuisine:"Brunch"},
{id:4422,name:"Allouez Cafe (Homemade Bread & Pies!)",cat:"Restaurant",sub:"Breakfast",date:"",dateLabel:"Daily 7am-2pm",venue:"Allouez Cafe",loc:"Allouez",addr:"2020 S Webster Ave, Green Bay, WI 54301",desc:"All-day breakfast with HOMEMADE bread and pies! Classic diner atmosphere. Affordable prices. A neighborhood gem.",url:"",setting:"indoor",walking:"lowWalking",goodFor:["seniors"],highlight:false,free:false,recurring:true,cuisine:"Breakfast"},
{id:4423,name:"Toast & Co. (Upscale Toast + Benedicts!)",cat:"Restaurant",sub:"Breakfast",date:"",dateLabel:"Mon-Tue & Thu-Sun 7am-3pm (closed Wed)",venue:"Toast & Co.",loc:"De Pere",addr:"2200 Dickinson Rd #5, De Pere, WI 54115",desc:"Upscale toast creations, Benedicts, waffles, and more! Modern brunch spot in De Pere. Closed Wednesdays.",url:"",setting:"indoor",walking:"lowWalking",goodFor:["seniors","couples"],highlight:false,free:false,recurring:true,cuisine:"Breakfast"},
{id:4424,name:"Perkins (2 Locations — 55+ Menu!)",cat:"Restaurant",sub:"Breakfast",date:"",dateLabel:"Daily ~6am-late",venue:"Perkins Restaurant",loc:"Multiple Locations",addr:"100 N Military Ave, Green Bay, WI 54303",desc:"Two Green Bay Perkins! Ask for the 55+ senior menu for smaller portions and lower prices. Also at 2306 E Mason St. Famous bakery section. Open early to late.",url:"https://www.perkinsrestaurants.com/",setting:"indoor",walking:"lowWalking",goodFor:["seniors","family"],highlight:false,free:false,recurring:true,cuisine:"Breakfast"},
{id:4425,name:"Denny's (24hr, 55+ Menu Available!)",cat:"Restaurant",sub:"Breakfast",date:"",dateLabel:"Often 24 hours",venue:"Denny's",loc:"Ashwaubenon",addr:"2894 S Oneida St, Green Bay, WI 54304",desc:"Open 24 hours! Ask for the 55+ senior menu — smaller portions at lower prices. Grand Slam breakfasts anytime. Late night diner option.",url:"",setting:"indoor",walking:"lowWalking",goodFor:["seniors"],highlight:false,free:false,recurring:true,cuisine:"Breakfast"},
// === BARBERS / SALONS ===
{id:4430,name:"Great Clips De Pere — Senior Haircut $20 (65+)!",cat:"Service",sub:"Salon / Senior Discount",date:"",dateLabel:"Mon-Fri 9-7, Sat 8-5, Sun 10-3",venue:"Great Clips",loc:"De Pere",addr:"1301 Lawrence Dr, De Pere, WI 54115",desc:"Published senior (65+) haircut $20! Regular haircut $22. No appointment needed, walk-in. (920) 338-8300.",url:"https://www.greatclips.com/",setting:"indoor",walking:"lowWalking",goodFor:["seniors"],highlight:true,free:false,recurring:true},
{id:4431,name:"Shear Sports Cuts — Senior $20 (60+)!",cat:"Service",sub:"Barber / Senior Discount",date:"",dateLabel:"Mon-Thu 10-6, Fri 9-5, Sat 9-2",venue:"Shear Sports Cuts",loc:"Green Bay",addr:"511 S Military Ave, Green Bay, WI 54303",desc:"$20 haircuts for ages 60+! Fun sports-themed barbershop. Walk-ins welcome. (920) 884-6680.",url:"https://shearsportscuts.com/",setting:"indoor",walking:"lowWalking",goodFor:["seniors"],highlight:true,free:false,recurring:true},
{id:4432,name:"Kohler Waters Spa — 20% Off Wed Community Day!",cat:"Activity",sub:"Spa & Wellness",date:"",dateLabel:"Every Wednesday (20% off 50/80-min services)",venue:"Kohler Waters Spa at Lodge Kohler",loc:"Ashwaubenon",addr:"1950 S Ridge Rd, Green Bay, WI 54304",desc:"Every WEDNESDAY is Community Day — 20% off 50 and 80-minute spa services! Book with code 'community'. World-class spa right at Lambeau. (855) 395-7638.",url:"https://www.lodgekohler.com/",setting:"indoor",walking:"lowWalking",goodFor:["seniors","couples"],highlight:true,free:false,recurring:true},
{id:4433,name:"Golden Age Wellness (Mobile Senior Massage!)",cat:"Service",sub:"Spa & Wellness",date:"",dateLabel:"By appointment (in-home or senior communities)",venue:"Golden Age Wellness",loc:"Luxemburg (serves GB area)",addr:"Luxemburg, WI (serves Green Bay area)",desc:"Massage marketed TO seniors! In-home or at senior communities. Seated $15-25, table $30 (30 min) / $55 (60 min). Gentle, experienced. (920) 288-2317.",url:"https://goldenagemassage.com/",setting:"indoor",walking:"lowWalking",goodFor:["seniors"],highlight:true,free:false,recurring:true},
// === SWIMMING / POOLS ===
{id:4438,name:"Colburn Pool — Lap Swim & Water Walking!",cat:"Activity",sub:"Swimming",date:"",dateLabel:"Starts Jun 16 (lap: M-Th 10-11:30am & 5:30-7pm)",venue:"Colburn Pool",loc:"West Green Bay",addr:"1025 S Fisk St, Green Bay, WI 54304",desc:"City outdoor pool with dedicated LAP SWIM & WATER WALKING! Mon-Thu 10-11:30am & 5:30-7pm, Sat-Sun 8-11am. $5/visit or $30 season pass (covers 3 city pools!).",url:"https://greenbaywi.gov/",setting:"outdoor",walking:"lowWalking",goodFor:["seniors"],highlight:true,free:false,recurring:true},
{id:4439,name:"Ferguson YMCA — Warm Water Therapy Pool!",cat:"Activity",sub:"Swimming",date:"",dateLabel:"Check greenbayymca.org for schedule",venue:"Ferguson Family YMCA",loc:"Downtown Green Bay",addr:"235 N Jefferson St, Green Bay, WI 54301",desc:"WARM WATER THERAPY POOL plus aqua fitness classes! Perfect for seniors with arthritis or joint issues. SilverSneakers and Renew Active may cover membership. Senior rates ~$46/mo for 65+.",url:"https://www.greenbayymca.org/",setting:"indoor",walking:"lowWalking",goodFor:["seniors"],highlight:true,free:false,recurring:true},
// === PET FRIENDLY ===
{id:4441,name:"Whitney Dog Park (Downtown Fenced!)",cat:"Park",sub:"Dog Park",date:"",dateLabel:"Dawn to dusk",venue:"Whitney Dog Park",loc:"Downtown Green Bay",addr:"800 Main St, Green Bay, WI 54301",desc:"Fenced off-leash dog park right downtown! Dog water fountains. Convenient for a quick dog outing while exploring CityDeck area.",url:"https://downtowngreenbay.com/",setting:"outdoor",walking:"lowWalking",goodFor:["seniors"],highlight:false,free:true,recurring:true},
{id:4442,name:"Brown County Dog Park (Fenced, Small Dog Area!)",cat:"Park",sub:"Dog Park",date:"",dateLabel:"Dawn to dusk ($3/day or $25/year)",venue:"Brown County Dog Park",loc:"Hobart",addr:"1000 Pleasant Ln, Hobart, WI 54313",desc:"~4 acres fenced with separate SMALL DOG area! $3/day or $25/year permit. Also on-leash trails outside the fenced area. Tree-covered for shade.",url:"https://www.browncountywi.gov/",setting:"outdoor",walking:"someWalking",goodFor:["seniors"],highlight:false,free:false,recurring:true},
{id:4443,name:"White Dog (Dog-Friendly Patio Restaurant!)",cat:"Restaurant",sub:"Pet Friendly",date:"",dateLabel:"Check hours",venue:"White Dog",loc:"Downtown Green Bay",addr:"201 S Broadway, Green Bay, WI 54303",desc:"Dog-friendly outdoor patio! Bring your leashed pup while you enjoy food and drinks on Broadway. Summer live music nights too.",url:"https://www.whitedoggreenbay.com/",setting:"outdoor",walking:"lowWalking",goodFor:["seniors","couples"],highlight:false,free:false,recurring:true,cuisine:"American"},
// === MEDICAL ESSENTIALS ===
{id:4445,name:"Bellin Hospital Emergency (24/7)",cat:"Service",sub:"Medical",date:"",dateLabel:"ER: 24/7 | ED: (920) 445-7373",venue:"Bellin Hospital",loc:"Downtown Green Bay",addr:"744 S Webster Ave, Green Bay, WI 54301",desc:"24/7 emergency department. Main hospital (920) 433-3500. ED direct: (920) 445-7373 or toll-free (888) 758-7373.",url:"https://www.bellin.org/",setting:"indoor",walking:"lowWalking",goodFor:["seniors"],highlight:false,free:false,recurring:true},
{id:4446,name:"Aurora BayCare Medical Center (24/7 ER)",cat:"Service",sub:"Medical",date:"",dateLabel:"ER: 24/7 | (920) 288-8000",venue:"Aurora BayCare Medical Center",loc:"East Green Bay",addr:"2845 Greenbrier Rd, Green Bay, WI 54311",desc:"Level II trauma center, 24/7 emergency. Also urgent care on campus: (920) 288-4545, Mon-Fri 8am-7:30pm. Main: (920) 288-8000.",url:"https://www.aurorabaycare.com/",setting:"indoor",walking:"lowWalking",goodFor:["seniors"],highlight:false,free:false,recurring:true},
{id:4447,name:"Poison Control / Crisis Lines (Important Numbers!)",cat:"Service",sub:"Medical",date:"",dateLabel:"24/7 hotlines",venue:"Emergency Phone Lines",loc:"Nationwide",addr:"N/A",desc:"POISON: (800) 222-1222. CRISIS: 988. INFO: 211. MEDICARE: (800) 633-4227. ADRC Brown County: (920) 448-4300. Social Security: (800) 772-1213. Quit Line: (800) 784-8669.",url:"",setting:"indoor",walking:"lowWalking",goodFor:["seniors"],highlight:true,free:true,recurring:true},
// === WALKING TRAILS ===
{id:4449,name:"East River Trail (6+ Paved Miles!)",cat:"Park",sub:"Trail",date:"",dateLabel:"Open daily (paved, flat, easy)",venue:"East River Trail",loc:"Green Bay to De Pere",addr:"635 Main St, Green Bay, WI 54301",desc:"6+ miles of PAVED trail along the East River through Bellevue, Allouez, De Pere, Ledgeview. Easy, flat, scenic waterway views. Free!",url:"https://downtowngreenbay.com/",setting:"outdoor",walking:"someWalking",goodFor:["seniors","couples"],highlight:true,free:true,recurring:true},
{id:4450,name:"Baird Creek Trail (Paved, Wooded, 3+ Miles!)",cat:"Park",sub:"Trail",date:"",dateLabel:"Open daily (paved main trail, ~3.2 miles)",venue:"Baird Creek Greenway",loc:"East Green Bay",addr:"Baird Creek Greenway, Green Bay, WI",desc:"3.2-mile paved trail through wooded corridor on Green Bay's east side. Some gentle grade changes. Dogs allowed on leash (7 ft max). Benches along the way.",url:"https://bairdcreek.org/",setting:"outdoor",walking:"someWalking",goodFor:["seniors"],highlight:false,free:true,recurring:true},
{id:4451,name:"Titletown Walking Club (Social Walks!)",cat:"Activity",sub:"Walking",date:"",dateLabel:"Check titletown.com for schedule",venue:"Titletown District",loc:"Ashwaubenon",addr:"1065 Lombardi Ave, Green Bay, WI 54304",desc:"Social walking group at Titletown! Short paved loops (0.2-0.5 mi) through the modern park near Lambeau. Very easy, ADA accessible. Join the club!",url:"https://titletown.com/",setting:"outdoor",walking:"lowWalking",goodFor:["seniors"],highlight:false,free:true,recurring:true},
{id:4452,name:"Bellin Health Fitness — Indoor Walking Track!",cat:"Activity",sub:"Fitness",date:"",dateLabel:"Membership / day pass (SilverSneakers accepted!)",venue:"Bellin Health Fitness Center",loc:"Downtown Green Bay",addr:"744 S Webster Ave, Green Bay, WI 54301",desc:"Elevated INDOOR walking track! Climate-controlled year-round walking. SilverSneakers, Renew Active accepted. Day passes available. (920) 834-5585.",url:"https://bellin.org/",setting:"indoor",walking:"someWalking",goodFor:["seniors"],highlight:true,free:false,recurring:true},
// === APPLETON EXTRAS ===
{id:4455,name:"History Museum at the Castle (Houdini!)  — 30 min",cat:"Attraction",sub:"Day Trip",date:"",dateLabel:"Daily 10am-4pm (senior $12, adult $12)",venue:"History Museum at the Castle",loc:"Appleton (30 min)",addr:"330 E College Ave, Appleton, WI 54911",desc:"Harry Houdini's adopted hometown! Interactive 'AKA Houdini' experience, regional history in a 1923 Masonic temple. Daily 10-4. Museums for All $3/person with EBT.",url:"https://myhistorymuseum.org/",setting:"indoor",walking:"someWalking",goodFor:["seniors","family"],highlight:true,free:false,recurring:true},
{id:4456,name:"Building for Kids Museum — 30 min (Grandkids!)",cat:"Attraction",sub:"Day Trip",date:"",dateLabel:"Tue-Sun 9am-4pm, closed Mon ($11/person)",venue:"The Building for Kids",loc:"Appleton (30 min)",addr:"100 W College Ave, Appleton, WI 54911",desc:"30,000+ sq ft children's museum! Two floors of exhibits, Studio, Lab, daily activities. $11/person, infants under 1 free. Perfect grandparent outing! Full indoor day.",url:"https://www.buildingforkids.org/",setting:"indoor",walking:"someWalking",goodFor:["family"],highlight:true,free:false,recurring:true},
{id:4457,name:"Appleton Christmas Parade (FREE, 80,000 attend!)",cat:"Event",sub:"Holiday",date:"2026-11-24",dateLabel:"Tue Nov 24, 7pm (FREE!)",venue:"College Ave, Downtown Appleton",loc:"Appleton (30 min)",addr:"State St & College Ave, Appleton, WI 54911",desc:"Major holiday tradition! ~80,000 people line College Ave for this classic Christmas parade. FREE to watch. TV coverage. Starts State St, heads east to Drew St. 30 min from GB.",url:"https://www.appletonwi.gov/",setting:"outdoor",walking:"someWalking",goodFor:["seniors","family"],highlight:true,free:true,recurring:false},
// === GARDEN / NATURE ===
{id:4459,name:"Brown County Seed Library — FREE Seeds!",cat:"Activity",sub:"Garden",date:"2026-03-07",dateLabel:"Launch Party Mar 7 (year-round seed borrowing FREE)",venue:"Brown County Central Library",loc:"Downtown Green Bay",addr:"515 Pine St, Green Bay, WI 54301",desc:"FREE seed borrowing program year-round! Launch party Mar 7. Workshops, activities, partner organizations. Get FREE vegetable, herb, and flower seeds. Bring extras to share!",url:"https://www.browncountylibrary.org/seed-library/",setting:"indoor",walking:"lowWalking",goodFor:["seniors"],highlight:true,free:true,recurring:false},
{id:4460,name:"Brown County Community Gardens (386+ Plots!)",cat:"Activity",sub:"Garden",date:"",dateLabel:"Seasonal ($15-45/plot, 13+ garden sites)",venue:"Brown County Extension",loc:"Various Green Bay locations",addr:"Various locations countywide",desc:"386+ garden plots at 13+ community garden sites across Brown County! Rent a plot for $15-45. Contact Rachel Quintas: (920) 391-4660 or rachel.quintas@browncountywi.gov.",url:"https://www.browncountywi.gov/",setting:"outdoor",walking:"someWalking",goodFor:["seniors"],highlight:true,free:false,recurring:true},
// === BREWERIES ===
{id:4462,name:"Badger State Brewing — Friday Night Acoustics!",cat:"Bar/Nightlife",sub:"Brewery",date:"",dateLabel:"Fridays 7-10pm (live music!) + Dog-friendly",venue:"Badger State Brewing",loc:"Ashwaubenon",addr:"990 Tony Canadeo Run, Green Bay, WI 54304",desc:"Friday Night Acoustics live music 7-10pm! Dog-friendly beer garden. Pizza, snacks. Mon-Thu 3-10, Fri-Sat 12-12, Sun 12-8.",url:"https://badgerstatebrewing.com/",setting:"indoor",walking:"lowWalking",goodFor:["seniors","couples"],highlight:true,free:false,recurring:true},
{id:4463,name:"Titletown Brewing (Rooftop Sky Lounge!)",cat:"Bar/Nightlife",sub:"Brewery",date:"",dateLabel:"Daily ~11am-10pm (Thu trivia, rooftop bar!)",venue:"Titletown Brewing Co.",loc:"Downtown Green Bay",addr:"200 Dousman St, Green Bay, WI 54303",desc:"Historic brewery with ROOFTOP Sky Lounge overlooking the Fox River! Thursday trivia, live music, Puzzles & Pints, Cribbage League. Full pub menu. Tours available.",url:"https://www.titletownbrewing.com/",setting:"indoor",walking:"lowWalking",goodFor:["seniors","couples"],highlight:true,free:false,recurring:true},
{id:4464,name:"Hinterland — Outdoor Winter Beer Festival!",cat:"Event",sub:"Festival",date:"2026-03-21",dateLabel:"Sat Mar 21, 1-4pm ($ticketed)",venue:"Hinterland Brewery",loc:"Ashwaubenon (Titletown)",addr:"1001 Lombardi Ave, Green Bay, WI 54304",desc:"4th Annual Pour Another Round Outdoor Winter Beer Festival! Craft beers, food, fun at Titletown near Lambeau. Full restaurant + beer hall open daily.",url:"https://hinterlandbeer.com/",setting:"outdoor",walking:"lowWalking",goodFor:["seniors","couples"],highlight:true,free:false,recurring:false},
{id:4465,name:"Nicolet Ale Works (NEW! De Pere, Opening 2026!)",cat:"Bar/Nightlife",sub:"Brewery",date:"",dateLabel:"Opening fall 2026!",venue:"Nicolet Ale Works",loc:"De Pere",addr:"301 Main Ave, De Pere, WI 54115",desc:"Brand new full brewery + taproom + outdoor beer garden coming to downtown De Pere! Opening fall 2026. Watch for grand opening events.",url:"",setting:"indoor",walking:"lowWalking",goodFor:["seniors","couples"],highlight:true,free:false,recurring:true},
// === CREDIT UNIONS / BANKING ===
{id:4467,name:"Fox Communities Credit Union (Notary On-Site!)",cat:"Service",sub:"Banking",date:"",dateLabel:"Mon-Fri 9-5, Sat 9-12 (3 GB locations)",venue:"Fox Communities Credit Union",loc:"Multiple Locations",addr:"1820 Main St, Green Bay, WI 54302",desc:"3 Green Bay locations! Also on Ashland Ave and Steffens Ct. Notary services available for members. (920) 993-9000. Good local option for seniors.",url:"https://foxcu.org/",setting:"indoor",walking:"lowWalking",goodFor:["seniors"],highlight:false,free:false,recurring:true},
{id:4468,name:"Capital Credit Union (Many GB Branches!)",cat:"Service",sub:"Banking",date:"",dateLabel:"Mon-Fri 8:30-5:30, Sat 8:30-12",venue:"Capital Credit Union",loc:"Multiple Locations",addr:"825 Morris Ave, Green Bay, WI 54304",desc:"Multiple Green Bay area branches — Morris Ave, Allouez, Velp, Huron Rd, Lineville + more. Notary services. (920) 494-2828.",url:"https://www.capitalcu.com/",setting:"indoor",walking:"lowWalking",goodFor:["seniors"],highlight:false,free:false,recurring:true},
];

let newStr = '';
for (const e of entries) {
  const descEsc = e.desc.replace(/"/g, '\\"');
  const nameEsc = e.name.replace(/"/g, '\\"');
  let s = ',\n{id:' + e.id + ',name:"' + nameEsc + '",cat:"' + e.cat + '",sub:"' + e.sub + '"';
  s += ',price:"' + (e.free ? 'free' : '$$') + '",priceNum:' + (e.free ? 0 : 2);
  s += ',date:"' + (e.date||'') + '"';
  if (e.dateTo) s += ',dateTo:"' + e.dateTo + '"';
  s += ',dateLabel:"' + (e.dateLabel || '') + '"';
  s += ',venue:"' + e.venue + '"';
  s += ',desc:"' + descEsc + '"';
  s += ',url:"' + (e.url || '') + '"';
  s += ',setting:"' + e.setting + '",walking:"' + e.walking + '"';
  s += ',goodFor:' + JSON.stringify(e.goodFor);
  s += ',highlight:' + e.highlight;
  s += ',cuisine:"' + (e.cuisine || '') + '",established:""';
  s += ',free:' + e.free + ',recurring:' + (e.recurring || false) + '}';
  newStr += s;
}

const lastEntry = 'free:false,recurring:true}';
const idx = html.lastIndexOf(lastEntry);
if (idx === -1) { console.log('ERROR: insertion point not found'); process.exit(1); }
html = html.substring(0, idx + lastEntry.length) + newStr + html.substring(idx + lastEntry.length);

fs.writeFileSync(path, html, 'utf8');
console.log('Added ' + entries.length + ' entries (IDs ' + Math.min(...entries.map(e=>e.id)) + '-' + Math.max(...entries.map(e=>e.id)) + ')');
console.log('File size: ' + Buffer.byteLength(html, 'utf8'));
